.TH FIX.4.2 "" "" "Tag #100"
Tag
Field Name
Data Type
Description
Depr.
Valid values
100 (tag100.html)
ExDestination (tag100.html)
Exchange
.PP
Execution destination as defined by institution when order is
entered.
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=ExDestination)]
[Order - Single (body_495268.html?find=ExDestination)]
[Order Cancel/Replace Request (body_495571.html?find=ExDestination)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
