.TH FIX.4.2 "" "" "Tag #103"
Tag
Field Name
Data Type
Description
Depr.
Valid values
103 (tag103.html)
OrdRejReason (tag103.html)
int
.PP
Code to identify reason for order rejection.
0
=
.PP
Broker option
1
=
.PP
Unknown symbol
2
=
.PP
Exchange closed
3
=
.PP
Order exceeds limit
4
=
.PP
Too late to enter
5
=
.PP
Unknown Order
6
=
.PP
Duplicate Order (e.g. dupe ClOrdID)
7
=
.PP
Duplicate of a verbally communicated order
8
=
.PP
Stale Order
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=OrdRejReason)]
[List Status (body_505178.html?find=OrdRejReason)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
