.TH FIX.4.2 "" "" "Tag #104"
Tag
Field Name
Data Type
Description
Depr.
Valid values
104 (tag104.html)
IOIQualifier (tag104.html)
char
.PP
Code to qualify IOI use.
A
=
.PP
All or none
C
=
.PP
At the close
I
=
.PP
In touch with
L
=
.PP
Limit
M
=
.PP
More behind
O
=
.PP
At the open
P
=
.PP
Taking a position
Q
=
.PP
At the Market (previously called Current Quote)
R
=
.PP
Ready to trade
S
=
.PP
Portfolio show-n
T
=
.PP
Through the day
V
=
.PP
Versus
W
=
.PP
Indication - Working away
X
=
.PP
Crossing opportunity
Y
=
.PP
At the Midpoint
Z
=
.PP
Pre-open
.PP
   *   *   *   *   *
Used in messages:
[Indication of Interest (body_5554.html?find=IOIQualifier)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
