.TH FIX.4.2 "" "" "Tag #111"
Tag
Field Name
Data Type
Description
Depr.
Valid values
111 (tag111.html)
MaxFloor (tag111.html)
Qty
.PP
Maximum number of shares within an order to be shown on the
exchange floor at any given time.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=MaxFloor)]
[Order - List (body_495369.html?find=MaxFloor)]
[Order - Single (body_495268.html?find=MaxFloor)]
[Order Cancel/Replace Request (body_495571.html?find=MaxFloor)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
