.TH FIX.4.2 "" "" "Tag #119"
Tag
Field Name
Data Type
Description
Depr.
Valid values
119 (tag119.html)
SettlCurrAmt (tag119.html)
Amt
.PP
Total amount due expressed in settlement currency (includes the
effect of the forex transaction)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=SettlCurrAmt)]
[Execution Report (body_5756.html?find=SettlCurrAmt)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
