.TH FIX.4.2 "" "" "Tag #122"
Tag
Field Name
Data Type
Description
Depr.
Valid values
122 (tag122.html)
OrigSendingTime (tag122.html)
UTCTimestamp
.PP
Original time of message transmission (always expressed in UTC
(Universal Time Coordinated, also known as “GMT”) when transmitting
orders as the result of a resend request.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
