.TH FIX.4.2 "" "" "Tag #123"
Tag
Field Name
Data Type
Description
Depr.
Valid values
123 (tag123.html)
GapFillFlag (tag123.html)
Boolean
.PP
Indicates that the Sequence Reset message is replacing
administrative or application messages which will not be resent.
N
=
.PP
Sequence Reset, ignore MsgSeqNum
Y
=
.PP
Gap Fill message, MsgSeqNum field valid
.PP
   *   *   *   *   *
Used in messages:
[Sequence Reset (body_5352.html?find=GapFillFlag)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
