.TH FIX.4.2 "" "" "Tag #126"
Tag
Field Name
Data Type
Description
Depr.
Valid values
126 (tag126.html)
ExpireTime (tag126.html)
UTCTimestamp
.PP
Time/Date of order expiration (always expressed in UTC (Universal
Time Coordinated, also known as “GMT”)
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=ExpireTime)]
[Market Data-Incremental Refresh (body_514988.html?find=ExpireTime)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=ExpireTime)]
[Order - List (body_495369.html?find=ExpireTime)]
[Order - Single (body_495268.html?find=ExpireTime)]
[Order Cancel/Replace Request (body_495571.html?find=ExpireTime)]
[Quote Request (body_505482.html?find=ExpireTime)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
