.TH FIX.4.2 "" "" "Tag #135"
Tag
Field Name
Data Type
Description
Depr.
Valid values
135 (tag135.html)
OfferSize (tag135.html)
Qty
.PP
Quantity of offer
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=OfferSize)]
[Quote (body_505583.html?find=OfferSize)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
