.TH FIX.4.2 "" "" "Tag #159"
Tag
Field Name
Data Type
Description
Depr.
Valid values
159 (tag159.html)
AccruedInterestAmt (tag159.html)
Amt
.PP
Amount of Accrued Interest for convertible bonds and fixed income
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AccruedInterestAmt)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
