.TH FIX.4.2 "" "" "Tag #16"
Tag
Field Name
Data Type
Description
Depr.
Valid values
16 (tag16.html)
EndSeqNo (tag16.html)
int
.PP
Message sequence number of last message in range to be resent. If
request is for a single message BeginSeqNo = EndSeqNo. If request
is for all messages subsequent to a particular message, EndSeqNo =
“0” (representing infinity).
.PP
   *   *   *   *   *
Used in messages:
[Resend Request (body_5150.html?find=EndSeqNo)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
