.TH FIX.4.2 "" "" "Tag #165"
Tag
Field Name
Data Type
Description
Depr.
Valid values
165 (tag165.html)
SettlInstSource (tag165.html)
char
.PP
Indicates source of Settlement Instructions
1
=
.PP
Brokers Instructions
2
=
.PP
Institutions Instructions
.PP
   *   *   *   *   *
Used in messages:
[Settlement Instructions (body_505684.html?find=SettlInstSource)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
