.TH FIX.4.2 "" "" "Tag #167"
Tag
Field Name
Data Type
Description
Depr.
Valid values
167 (tag167.html)
SecurityType (tag167.html)
String
.PP
Indicates type of security (ISITC spec)
?
=
.PP
Wildcard entry (used on Security Definition Request message)
BA
=
.PP
Bankers Acceptance
CB
=
.PP
Convertible Bond (Note not part of ISITC spec)
CD
=
.PP
Certificate Of Deposit
CMO
=
.PP
Collateralize Mortgage Obligation
CORP
=
.PP
Corporate Bond
CP
=
.PP
Commercial Paper
CPP
=
.PP
Corporate Private Placement
CS
=
.PP
Common Stock
FHA
=
.PP
Federal Housing Authority
FHL
=
.PP
Federal Home Loan
FN
=
.PP
Federal National Mortgage Association
FOR
=
.PP
Foreign Exchange Contract
FUT
=
.PP
Future
GN
=
.PP
Government National Mortgage Association
GOVT
=
.PP
Treasuries + Agency Debenture
IET
=
.PP
Mortgage IOETTE
MF
=
.PP
Mutual Fund
MIO
=
.PP
Mortgage Interest Only
MPO
=
.PP
Mortgage Principal Only
MPP
=
.PP
Mortgage Private Placement
MPT
=
.PP
Miscellaneous Pass-Thru
MUNI
=
.PP
Municipal Bond
NONE
=
.PP
No ISITC Security Type
OPT
=
.PP
Option
PS
=
.PP
Preferred Stock
RP
=
.PP
Repurchase Agreement
RVRP
=
.PP
Reverse Repurchase Agreement
SL
=
.PP
Student Loan Marketing Association
TD
=
.PP
Time Deposit
USTB
=
.PP
US Treasury Bill
WAR
=
.PP
Warrant
ZOO
=
.PP
Cats, Tigers & Lions (a real code: US Treasury Receipts)
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=SecurityType)]
[Allocation (body_495774.html?find=SecurityType)]
[Don’t Know Trade (DK) (body_505381.html?find=SecurityType)]
[Email (body_495167.html?find=SecurityType)]
[Execution Report (body_5756.html?find=SecurityType)]
[Indication of Interest (body_5554.html?find=SecurityType)]
[List Strike Price (body_5254109.html?find=SecurityType)]
[Market Data Request (body_505786.html?find=SecurityType)]
[Market Data-Incremental Refresh (body_514988.html?find=SecurityType)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=SecurityType)]
[Mass Quote (body_5250105.html?find=SecurityType)]
[News (body_495066.html?find=SecurityType)]
[Order - List (body_495369.html?find=SecurityType)]
[Order - Single (body_495268.html?find=SecurityType)]
[Order Cancel Request (body_495470.html?find=SecurityType)]
[Order Cancel/Replace Request (body_495571.html?find=SecurityType)]
[Order Status Request (body_495672.html?find=SecurityType)]
[Quote (body_505583.html?find=SecurityType)]
[Quote Acknowledgement (body_515398.html?find=SecurityType)]
[Quote Cancel (body_515190.html?find=SecurityType)]
[Quote Request (body_505482.html?find=SecurityType)]
[Quote Status Request (body_515297.html?find=SecurityType)]
[Security Definition (body_5155100.html?find=SecurityType)]
[Security Definition Request (body_515499.html?find=SecurityType)]
[Security Status (body_5157102.html?find=SecurityType)]
[Security Status Request (body_5156101.html?find=SecurityType)]
[Settlement Instructions (body_505684.html?find=SecurityType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
