.TH FIX.4.2 "" "" "Tag #173"
Tag
Field Name
Data Type
Description
Depr.
Valid values
173 (tag173.html)
SettlDepositoryCode (tag173.html)
String
.PP
Broker’s account code at the depository (i.e. CEDEL ID for CEDEL,
FINS for DTC, or Euroclear ID for Euroclear) if SettlLocation is a
depository
.PP
   *   *   *   *   *
Used in messages:
[Settlement Instructions (body_505684.html?find=SettlDepositoryCode)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
