.TH FIX.4.2 "" "" "Tag #174"
Tag
Field Name
Data Type
Description
Depr.
Valid values
174 (tag174.html)
SettlBrkrCode (tag174.html)
String
.PP
BIC (Bank Identification Code—Swift managed) code of the broker
involved (i.e. for multi-company brokerage firms)
.PP
   *   *   *   *   *
Used in messages:
[Settlement Instructions (body_505684.html?find=SettlBrkrCode)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
