.TH FIX.4.2 "" "" "Tag #179"
Tag
Field Name
Data Type
Description
Depr.
Valid values
179 (tag179.html)
SecuritySettlAgentAcctName (tag179.html)
String
.PP
Name of SettlInstSource\[aq]s account at local agent bank if
SettlLocation is not a depository
.PP
   *   *   *   *   *
Used in messages:
[Settlement Instructions (body_505684.html?find=SecuritySettlAgentAcctName)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
