.TH FIX.4.2 "" "" "Tag #186"
Tag
Field Name
Data Type
Description
Depr.
Valid values
186 (tag186.html)
CashSettlAgentContactName (tag186.html)
String
.PP
Name of contact at local agent bank for SettlInstSource\[aq]s
account if SettlDeliveryType=Free
.PP
   *   *   *   *   *
Used in messages:
[Settlement Instructions (body_505684.html?find=CashSettlAgentContactName)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
