.TH FIX.4.2 "" "" "Tag #193"
Tag
Field Name
Data Type
Description
Depr.
Valid values
193 (tag193.html)
FutSettDate2 (tag193.html)
LocalMktDate
.PP
FutSettDate of the future part of a F/X swap order.
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=FutSettDate2)]
[Mass Quote (body_5250105.html?find=FutSettDate2)]
[Order - List (body_495369.html?find=FutSettDate2)]
[Order - Single (body_495268.html?find=FutSettDate2)]
[Order Cancel/Replace Request (body_495571.html?find=FutSettDate2)]
[Quote (body_505583.html?find=FutSettDate2)]
[Quote Request (body_505482.html?find=FutSettDate2)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
