.TH FIX.4.2 "" "" "Tag #197"
Tag
Field Name
Data Type
Description
Depr.
Valid values
197 (tag197.html)
AllocLinkType (tag197.html)
int
.PP
Identifies the type of Allocation linkage when AllocLinkID is used.
0
=
.PP
F/X Netting
1
=
.PP
F/X Swap
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AllocLinkType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
