.TH FIX.4.2 "" "" "Tag #200"
Tag
Field Name
Data Type
Description
Depr.
Valid values
200 (tag200.html)
MaturityMonthYear (tag200.html)
month-year
.PP
Month and Year of the maturity for SecurityType=FUT or
SecurityType=OPT. Required if MaturityDay is specified.
.PP
Format: YYYYMM
.PP
(i.e. 199903)
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=MaturityMonthYear)]
[Allocation (body_495774.html?find=MaturityMonthYear)]
[Don’t Know Trade (DK) (body_505381.html?find=MaturityMonthYear)]
[Email (body_495167.html?find=MaturityMonthYear)]
[Execution Report (body_5756.html?find=MaturityMonthYear)]
[Indication of Interest (body_5554.html?find=MaturityMonthYear)]
[List Strike Price (body_5254109.html?find=MaturityMonthYear)]
[Market Data Request (body_505786.html?find=MaturityMonthYear)]
[Market Data-Incremental Refresh (body_514988.html?find=MaturityMonthYear)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=MaturityMonthYear)]
[Mass Quote (body_5250105.html?find=MaturityMonthYear)]
[News (body_495066.html?find=MaturityMonthYear)]
[Order - List (body_495369.html?find=MaturityMonthYear)]
[Order - Single (body_495268.html?find=MaturityMonthYear)]
[Order Cancel Request (body_495470.html?find=MaturityMonthYear)]
[Order Cancel/Replace Request (body_495571.html?find=MaturityMonthYear)]
[Order Status Request (body_495672.html?find=MaturityMonthYear)]
[Quote (body_505583.html?find=MaturityMonthYear)]
[Quote Acknowledgement (body_515398.html?find=MaturityMonthYear)]
[Quote Cancel (body_515190.html?find=MaturityMonthYear)]
[Quote Request (body_505482.html?find=MaturityMonthYear)]
[Quote Status Request (body_515297.html?find=MaturityMonthYear)]
[Security Definition (body_5155100.html?find=MaturityMonthYear)]
[Security Definition Request (body_515499.html?find=MaturityMonthYear)]
[Security Status (body_5157102.html?find=MaturityMonthYear)]
[Security Status Request (body_5156101.html?find=MaturityMonthYear)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
