.TH FIX.4.2 "" "" "Tag #21"
Tag
Field Name
Data Type
Description
Depr.
Valid values
21 (tag21.html)
HandlInst (tag21.html)
char
.PP
Instructions for order handling on Broker trading floor
1
=
.PP
Automated execution order, private, no Broker intervention
2
=
.PP
Automated execution order, public, Broker intervention OK
3
=
.PP
Manual order, best execution
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=HandlInst)]
[Order - List (body_495369.html?find=HandlInst)]
[Order - Single (body_495268.html?find=HandlInst)]
[Order Cancel/Replace Request (body_495571.html?find=HandlInst)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
