.TH FIX.4.2 "" "" "Tag #222"
Tag
Field Name
Data Type
Description
Depr.
Valid values
222 (tag222.html)
Reserved/Allocated to the Fixed Income proposal (tag222.html)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
