.TH FIX.4.2 "" "" "Tag #231"
Tag
Field Name
Data Type
Description
Depr.
Valid values
231 (tag231.html)
ContractMultiplier (tag231.html)
float
.PP
Specifies the ratio or multiply factor to convert from contracts to
shares (e.g. 1.0, 100, 1000, etc). Applicable For Fixed Income,
Convertible Bonds, Derivatives, etc. Note: If used, quantities
should be expressed in the "nominal" (e.g. contracts vs. shares)
amount.
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=ContractMultiplier)]
[Allocation (body_495774.html?find=ContractMultiplier)]
[Don’t Know Trade (DK) (body_505381.html?find=ContractMultiplier)]
[Email (body_495167.html?find=ContractMultiplier)]
[Execution Report (body_5756.html?find=ContractMultiplier)]
[Indication of Interest (body_5554.html?find=ContractMultiplier)]
[List Strike Price (body_5254109.html?find=ContractMultiplier)]
[Market Data Request (body_505786.html?find=ContractMultiplier)]
[Market Data-Incremental Refresh (body_514988.html?find=ContractMultiplier)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=ContractMultiplier)]
[Mass Quote (body_5250105.html?find=ContractMultiplier)]
[News (body_495066.html?find=ContractMultiplier)]
[Order - List (body_495369.html?find=ContractMultiplier)]
[Order - Single (body_495268.html?find=ContractMultiplier)]
[Order Cancel Request (body_495470.html?find=ContractMultiplier)]
[Order Cancel/Replace Request (body_495571.html?find=ContractMultiplier)]
[Order Status Request (body_495672.html?find=ContractMultiplier)]
[Quote (body_505583.html?find=ContractMultiplier)]
[Quote Acknowledgement (body_515398.html?find=ContractMultiplier)]
[Quote Cancel (body_515190.html?find=ContractMultiplier)]
[Quote Request (body_505482.html?find=ContractMultiplier)]
[Quote Status Request (body_515297.html?find=ContractMultiplier)]
[Security Definition (body_5155100.html?find=ContractMultiplier)]
[Security Definition Request (body_515499.html?find=ContractMultiplier)]
[Security Status (body_5157102.html?find=ContractMultiplier)]
[Security Status Request (body_5156101.html?find=ContractMultiplier)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
