.TH FIX.4.2 "" "" "Tag #263"
Tag
Field Name
Data Type
Description
Depr.
Valid values
263 (tag263.html)
SubscriptionRequestType (tag263.html)
char
.PP
Subscription Request Type
0
=
.PP
Snapshot
1
=
.PP
Snapshot + Updates (Subscribe)
2
=
.PP
Disable previous Snapshot + Update Request (Unsubscribe)
.PP
   *   *   *   *   *
Used in messages:
[Market Data Request (body_505786.html?find=SubscriptionRequestType)]
[Security Status Request (body_5156101.html?find=SubscriptionRequestType)]
[Trading Session Status Request (body_5248103.html?find=SubscriptionRequestType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
