.TH FIX.4.2 "" "" "Tag #264"
Tag
Field Name
Data Type
Description
Depr.
Valid values
264 (tag264.html)
MarketDepth (tag264.html)
int
.PP
Depth of market for Book Snapshot
N>1
=
.PP
Report best N price tiers of data
0
=
.PP
Full Book
1
=
.PP
Top of Book
.PP
   *   *   *   *   *
Used in messages:
[Market Data Request (body_505786.html?find=MarketDepth)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
