.TH FIX.4.2 "" "" "Tag #265"
Tag
Field Name
Data Type
Description
Depr.
Valid values
265 (tag265.html)
MDUpdateType (tag265.html)
int
.PP
Specifies the type of Market Data update.
0
=
.PP
Full Refresh
1
=
.PP
Incremental Refresh
.PP
   *   *   *   *   *
Used in messages:
[Market Data Request (body_505786.html?find=MDUpdateType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
