.TH FIX.4.2 "" "" "Tag #271"
Tag
Field Name
Data Type
Description
Depr.
Valid values
271 (tag271.html)
MDEntrySize (tag271.html)
Qty
.PP
Number of shares represented by the Market Data Entry.
.PP
   *   *   *   *   *
Used in messages:
[Market Data-Incremental Refresh (body_514988.html?find=MDEntrySize)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=MDEntrySize)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
