.TH FIX.4.2 "" "" "Tag #272"
Tag
Field Name
Data Type
Description
Depr.
Valid values
272 (tag272.html)
MDEntryDate (tag272.html)
UTCDate
.PP
Date of Market Data Entry.
.PP
   *   *   *   *   *
Used in messages:
[Market Data-Incremental Refresh (body_514988.html?find=MDEntryDate)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=MDEntryDate)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
