.TH FIX.4.2 "" "" "Tag #276"
Tag
Field Name
Data Type
Description
Depr.
Valid values
276 (tag276.html)
QuoteCondition (tag276.html)
MultipleValueString
.PP
Space-delimited list of conditions describing a quote.
A
=
.PP
Open / Active
B
=
.PP
Closed / Inactive
C
=
.PP
Exchange Best
D
=
.PP
Consolidated Best
E
=
.PP
Locked
F
=
.PP
Crossed
G
=
.PP
Depth
H
=
.PP
Fast Trading
I
=
.PP
Non-Firm
.PP
   *   *   *   *   *
Used in messages:
[Market Data-Incremental Refresh (body_514988.html?find=QuoteCondition)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=QuoteCondition)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
