.TH FIX.4.2 "" "" "Tag #279"
Tag
Field Name
Data Type
Description
Depr.
Valid values
279 (tag279.html)
MDUpdateAction (tag279.html)
char
.PP
Type of Market Data update action.
0
=
.PP
New
1
=
.PP
Change
2
=
.PP
Delete
.PP
   *   *   *   *   *
Used in messages:
[Market Data-Incremental Refresh (body_514988.html?find=MDUpdateAction)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
