.TH FIX.4.2 "" "" "Tag #285"
Tag
Field Name
Data Type
Description
Depr.
Valid values
285 (tag285.html)
DeleteReason (tag285.html)
char
.PP
Reason for deletion.
0
=
.PP
Cancelation / Trade Bust
1
=
.PP
Error
.PP
   *   *   *   *   *
Used in messages:
[Market Data-Incremental Refresh (body_514988.html?find=DeleteReason)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
