.TH FIX.4.2 "" "" "Tag #291"
Tag
Field Name
Data Type
Description
Depr.
Valid values
291 (tag291.html)
FinancialStatus (tag291.html)
char
.PP
Identifies a firm’s financial status.
1
=
.PP
Bankrupt
.PP
   *   *   *   *   *
Used in messages:
[Market Data-Incremental Refresh (body_514988.html?find=FinancialStatus)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=FinancialStatus)]
[Security Status (body_5157102.html?find=FinancialStatus)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
