.TH FIX.4.2 "" "" "Tag #296"
Tag
Field Name
Data Type
Description
Depr.
Valid values
296 (tag296.html)
NoQuoteSets (tag296.html)
int
.PP
The number of sets of quotes in the message.
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=NoQuoteSets)]
[Quote Acknowledgement (body_515398.html?find=NoQuoteSets)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
