.TH FIX.4.2 "" "" "Tag #297"
Tag
Field Name
Data Type
Description
Depr.
Valid values
297 (tag297.html)
QuoteAckStatus (tag297.html)
int
.PP
Identifies the status of the quote acknowledgement.
0
=
.PP
Accepted
1
=
.PP
Canceled for Symbol(s)
2
=
.PP
Canceled for Security Type(s)
3
=
.PP
Canceled for Underlying
4
=
.PP
Canceled All
5
=
.PP
Rejected
.PP
   *   *   *   *   *
Used in messages:
[Quote Acknowledgement (body_515398.html?find=QuoteAckStatus)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
