.TH FIX.4.2 "" "" "Tag #298"
Tag
Field Name
Data Type
Description
Depr.
Valid values
298 (tag298.html)
QuoteCancelType (tag298.html)
int
.PP
Identifies the type of quote cancel.
1
=
.PP
Cancel for Symbol(s)
2
=
.PP
Cancel for Security Type(s)
3
=
.PP
Cancel for Underlying Symbol
4
=
.PP
Cancel for All Quotes
.PP
   *   *   *   *   *
Used in messages:
[Quote Cancel (body_515190.html?find=QuoteCancelType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
