.TH FIX.4.2 "" "" "Tag #299"
Tag
Field Name
Data Type
Description
Depr.
Valid values
299 (tag299.html)
QuoteEntryID (tag299.html)
String
.PP
Uniquely identifies the quote as part of a QuoteSet.
.PP
   *   *   *   *   *
Used in messages:
[Market Data-Incremental Refresh (body_514988.html?find=QuoteEntryID)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=QuoteEntryID)]
[Mass Quote (body_5250105.html?find=QuoteEntryID)]
[Quote Acknowledgement (body_515398.html?find=QuoteEntryID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
