.TH FIX.4.2 "" "" "Tag #304"
Tag
Field Name
Data Type
Description
Depr.
Valid values
304 (tag304.html)
TotQuoteEntries (tag304.html)
int
.PP
Total number of quotes for the quote set across all messages.
Should be the sum of all NoQuoteEntries in each message that has
repeating quotes that are part of the same quote set.
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=TotQuoteEntries)]
[Quote Acknowledgement (body_515398.html?find=TotQuoteEntries)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
