.TH FIX.4.2 "" "" "Tag #306"
Tag
Field Name
Data Type
Description
Depr.
Valid values
306 (tag306.html)
UnderlyingIssuer (tag306.html)
String
.PP
Underlying security’s Issuer.
.PP
See Issuer field for description
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=UnderlyingIssuer)]
[Quote Acknowledgement (body_515398.html?find=UnderlyingIssuer)]
[Security Definition (body_5155100.html?find=UnderlyingIssuer)]
[Security Definition Request (body_515499.html?find=UnderlyingIssuer)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
