.TH FIX.4.2 "" "" "Tag #308"
Tag
Field Name
Data Type
Description
Depr.
Valid values
308 (tag308.html)
UnderlyingSecurityExchange (tag308.html)
Exchange
.PP
Underlying security’s SecurityExchange. Can be used to identify the
underlying security.
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=UnderlyingSecurityExchange)]
[Quote Acknowledgement (body_515398.html?find=UnderlyingSecurityExchange)]
[Security Definition (body_5155100.html?find=UnderlyingSecurityExchange)]
[Security Definition Request (body_515499.html?find=UnderlyingSecurityExchange)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
