.TH FIX.4.2 "" "" "Tag #312"
Tag
Field Name
Data Type
Description
Depr.
Valid values
312 (tag312.html)
UnderlyingSymbolSfx (tag312.html)
String
.PP
Underlying security’s SymbolSfx.
.PP
See SymbolSfx field for description
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=UnderlyingSymbolSfx)]
[Quote Acknowledgement (body_515398.html?find=UnderlyingSymbolSfx)]
[Security Definition (body_5155100.html?find=UnderlyingSymbolSfx)]
[Security Definition Request (body_515499.html?find=UnderlyingSymbolSfx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
