.TH FIX.4.2 "" "" "Tag #314"
Tag
Field Name
Data Type
Description
Depr.
Valid values
314 (tag314.html)
UnderlyingMaturityDay (tag314.html)
day-of-month
.PP
Underlying security’s MaturityDay.
.PP
See MaturityDay field for description
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=UnderlyingMaturityDay)]
[Quote Acknowledgement (body_515398.html?find=UnderlyingMaturityDay)]
[Security Definition (body_5155100.html?find=UnderlyingMaturityDay)]
[Security Definition Request (body_515499.html?find=UnderlyingMaturityDay)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
