.TH FIX.4.2 "" "" "Tag #315"
Tag
Field Name
Data Type
Description
Depr.
Valid values
315 (tag315.html)
UnderlyingPutOrCall (tag315.html)
int
.PP
Underlying security’s PutOrCall.
.PP
See PutOrCall field for description
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=UnderlyingPutOrCall)]
[Quote Acknowledgement (body_515398.html?find=UnderlyingPutOrCall)]
[Security Definition (body_5155100.html?find=UnderlyingPutOrCall)]
[Security Definition Request (body_515499.html?find=UnderlyingPutOrCall)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
