.TH FIX.4.2 "" "" "Tag #318"
Tag
Field Name
Data Type
Description
Depr.
Valid values
318 (tag318.html)
Underlying Currency (tag318.html)
Currency
.PP
Underlying security’s Currency.
.PP
See Currency field for description and
.PP
   *   *   *   *   *
Used in messages:
[Security Definition (body_5155100.html?find=Underlying%20Currency)]
[Security Definition Request (body_515499.html?find=Underlying%20Currency)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
