.TH FIX.4.2 "" "" "Tag #335"
Tag
Field Name
Data Type
Description
Depr.
Valid values
335 (tag335.html)
TradSesReqID (tag335.html)
String
.PP
Unique ID of a Trading Session Status message.
.PP
   *   *   *   *   *
Used in messages:
[Trading Session Status (body_5249104.html?find=TradSesReqID)]
[Trading Session Status Request (body_5248103.html?find=TradSesReqID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
