.TH FIX.4.2 "" "" "Tag #336"
Tag
Field Name
Data Type
Description
Depr.
Valid values
336 (tag336.html)
TradingSessionID (tag336.html)
String
.PP
Identifier for Trading Session
.PP
Can be used to represent a specific market trading session (e.g.
“PRE-OPEN", "CROSS_2", "AFTER-HOURS", "TOSTNET1", "TOSTNET2", etc).
.PP
Values should be bi-laterally agreed to between counterparties.
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=TradingSessionID)]
[Allocation (body_495774.html?find=TradingSessionID)]
[Bid Request (body_5252107.html?find=TradingSessionID)]
[Bid Response (lowercase L) (body_5253108.html?find=TradingSessionID)]
[Execution Report (body_5756.html?find=TradingSessionID)]
[Market Data Request (body_505786.html?find=TradingSessionID)]
[Market Data-Incremental Refresh (body_514988.html?find=TradingSessionID)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=TradingSessionID)]
[Mass Quote (body_5250105.html?find=TradingSessionID)]
[Order - List (body_495369.html?find=TradingSessionID)]
[Order - Single (body_495268.html?find=TradingSessionID)]
[Order Cancel/Replace Request (body_495571.html?find=TradingSessionID)]
[Quote (body_505583.html?find=TradingSessionID)]
[Quote Acknowledgement (body_515398.html?find=TradingSessionID)]
[Quote Cancel (body_515190.html?find=TradingSessionID)]
[Quote Request (body_505482.html?find=TradingSessionID)]
[Quote Status Request (body_515297.html?find=TradingSessionID)]
[Security Definition (body_5155100.html?find=TradingSessionID)]
[Security Definition Request (body_515499.html?find=TradingSessionID)]
[Security Status (body_5157102.html?find=TradingSessionID)]
[Security Status Request (body_5156101.html?find=TradingSessionID)]
[Settlement Instructions (body_505684.html?find=TradingSessionID)]
[Trading Session Status (body_5249104.html?find=TradingSessionID)]
[Trading Session Status Request (body_5248103.html?find=TradingSessionID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
