.TH FIX.4.2 "" "" "Tag #347"
Tag
Field Name
Data Type
Description
Depr.
Valid values
347 (tag347.html)
MessageEncoding (tag347.html)
String
.PP
Type of message encoding (non-ASCII (non-English) characters) used
in a message’s “Encoded” fields.
EUC-JP
=
.PP
(for using EUC)
ISO-2022-JP
=
.PP
(for using JIS)
Shift_JIS
=
.PP
(for using SJIS)
UTF-8
=
.PP
(for using Unicode)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
