.TH FIX.4.2 "" "" "Tag #349"
Tag
Field Name
Data Type
Description
Depr.
Valid values
349 (tag349.html)
EncodedIssuer (tag349.html)
data
.PP
Encoded (non-ASCII characters) representation of the Issuer field
in the encoded format specified via the MessageEncoding field. If
used, the ASCII (English) representation should also be specified
in the Issuer field.
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=EncodedIssuer)]
[Allocation (body_495774.html?find=EncodedIssuer)]
[Don’t Know Trade (DK) (body_505381.html?find=EncodedIssuer)]
[Email (body_495167.html?find=EncodedIssuer)]
[Execution Report (body_5756.html?find=EncodedIssuer)]
[Indication of Interest (body_5554.html?find=EncodedIssuer)]
[List Strike Price (body_5254109.html?find=EncodedIssuer)]
[Market Data Request (body_505786.html?find=EncodedIssuer)]
[Market Data-Incremental Refresh (body_514988.html?find=EncodedIssuer)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=EncodedIssuer)]
[Mass Quote (body_5250105.html?find=EncodedIssuer)]
[News (body_495066.html?find=EncodedIssuer)]
[Order - List (body_495369.html?find=EncodedIssuer)]
[Order - Single (body_495268.html?find=EncodedIssuer)]
[Order Cancel Request (body_495470.html?find=EncodedIssuer)]
[Order Cancel/Replace Request (body_495571.html?find=EncodedIssuer)]
[Order Status Request (body_495672.html?find=EncodedIssuer)]
[Quote (body_505583.html?find=EncodedIssuer)]
[Quote Acknowledgement (body_515398.html?find=EncodedIssuer)]
[Quote Cancel (body_515190.html?find=EncodedIssuer)]
[Quote Request (body_505482.html?find=EncodedIssuer)]
[Quote Status Request (body_515297.html?find=EncodedIssuer)]
[Security Definition (body_5155100.html?find=EncodedIssuer)]
[Security Definition Request (body_515499.html?find=EncodedIssuer)]
[Security Status (body_5157102.html?find=EncodedIssuer)]
[Security Status Request (body_5156101.html?find=EncodedIssuer)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
