.TH FIX.4.2 "" "" "Tag #35"
Tag
Field Name
Data Type
Description
Depr.
Valid values
35 (tag35.html)
MsgType (tag35.html)
String
.PP
Defines message type. ALWAYS THIRD FIELD IN MESSAGE. (Always
unencrypted)
.PP
Note: A "U" as the first character in the MsgType field (i.e. U1,
U2, etc) indicates that the message format is privately defined
between the sender and receiver.
0
=
.PP
Heartbeat
1
=
.PP
Test Request
2
=
.PP
Resend Request
3
=
.PP
Reject
4
=
.PP
Sequence Reset
5
=
.PP
Logout
6
=
.PP
Indication of Interest
7
=
.PP
Advertisement
8
=
.PP
Execution Report
9
=
.PP
Order Cancel Reject
a
=
.PP
Quote Status Request
A
=
.PP
Logon
B
=
.PP
News
b
=
.PP
Quote Acknowledgement
C
=
.PP
Email
c
=
.PP
Security Definition Request
D
=
.PP
Order Single
d
=
.PP
Security Definition
E
=
.PP
Order List
e
=
.PP
Security Status Request
f
=
.PP
Security Status
F
=
.PP
Order Cancel Request
G
=
.PP
Order Cancel/Replace Request
g
=
.PP
Trading Session Status Request
H
=
.PP
Order Status Request
h
=
.PP
Trading Session Status
i
=
.PP
Mass Quote
j
=
.PP
Business Message Reject
J
=
.PP
Allocation
K
=
.PP
List Cancel Request
k
=
.PP
Bid Request
l
=
.PP
Bid Response (lowercase L)
L
=
.PP
List Execute
m
=
.PP
List Strike Price
M
=
.PP
List Status Request
N
=
.PP
List Status
P
=
.PP
Allocation ACK
Q
=
.PP
Dont Know Trade (DK)
R
=
.PP
Quote Request
S
=
.PP
Quote
T
=
.PP
Settlement Instructions
V
=
.PP
Market Data Request
W
=
.PP
Market Data-Snapshot/Full Refresh
X
=
.PP
Market Data-Incremental Refresh
Y
=
.PP
Market Data Request Reject
Z
=
.PP
Quote Cancel
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
