.TH FIX.4.2 "" "" "Tag #354"
Tag
Field Name
Data Type
Description
Depr.
Valid values
354 (tag354.html)
EncodedTextLen (tag354.html)
Length
.PP
Byte length of encoded (non-ASCII characters) EncodedText field.
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=EncodedTextLen)]
[Allocation (body_495774.html?find=EncodedTextLen)]
[Allocation ACK (body_505280.html?find=EncodedTextLen)]
[Bid Request (body_5252107.html?find=EncodedTextLen)]
[Bid Response (lowercase L) (body_5253108.html?find=EncodedTextLen)]
[Business Message Reject (body_5251106.html?find=EncodedTextLen)]
[Don’t Know Trade (DK) (body_505381.html?find=EncodedTextLen)]
[Email (body_495167.html?find=EncodedTextLen)]
[Execution Report (body_5756.html?find=EncodedTextLen)]
[Indication of Interest (body_5554.html?find=EncodedTextLen)]
[List Cancel Request (body_504875.html?find=EncodedTextLen)]
[List Execute (body_504976.html?find=EncodedTextLen)]
[List Status (body_505178.html?find=EncodedTextLen)]
[List Status Request (body_505077.html?find=EncodedTextLen)]
[List Strike Price (body_5254109.html?find=EncodedTextLen)]
[Logout (body_5453.html?find=EncodedTextLen)]
[Market Data Request Reject (body_515089.html?find=EncodedTextLen)]
[Market Data-Incremental Refresh (body_514988.html?find=EncodedTextLen)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=EncodedTextLen)]
[News (body_495066.html?find=EncodedTextLen)]
[Order - List (body_495369.html?find=EncodedTextLen)]
[Order - Single (body_495268.html?find=EncodedTextLen)]
[Order Cancel Reject (body_494857.html?find=EncodedTextLen)]
[Order Cancel Request (body_495470.html?find=EncodedTextLen)]
[Order Cancel/Replace Request (body_495571.html?find=EncodedTextLen)]
[Reject (body_5251.html?find=EncodedTextLen)]
[Security Definition (body_5155100.html?find=EncodedTextLen)]
[Security Definition Request (body_515499.html?find=EncodedTextLen)]
[Trading Session Status (body_5249104.html?find=EncodedTextLen)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
