.TH FIX.4.2 "" "" "Tag #367"
Tag
Field Name
Data Type
Description
Depr.
Valid values
367 (tag367.html)
QuoteSetValidUntilTime (tag367.html)
UTCTimestamp
.PP
Indicates expiration time of this particular QuoteSet (always
expressed in UTC (Universal Time Coordinated, also known as “GMT”)
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=QuoteSetValidUntilTime)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
