.TH FIX.4.2 "" "" "Tag #370"
Tag
Field Name
Data Type
Description
Depr.
Valid values
370 (tag370.html)
OnBehalfOfSendingTime (tag370.html)
UTCTimestamp
.PP
Used when a message is sent via a “hub” or “service bureau”. If A
sends to Q (the hub) who then sends to B via a separate FIX
session, then when Q sends to B the value of this field should
represent the SendingTime on the message A sent to Q. (always
expressed in UTC (Universal Time Coordinated, also known as “GMT”)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
