.TH FIX.4.2 "" "" "Tag #371"
Tag
Field Name
Data Type
Description
Depr.
Valid values
371 (tag371.html)
RefTagID (tag371.html)
int
.PP
The tag number of the FIX field being referenced.
.PP
   *   *   *   *   *
Used in messages:
[Reject (body_5251.html?find=RefTagID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
