.TH FIX.4.2 "" "" "Tag #373"
Tag
Field Name
Data Type
Description
Depr.
Valid values
373 (tag373.html)
SessionRejectReason (tag373.html)
int
.PP
Code to identify reason for a session-level Reject message.
0
=
.PP
Invalid tag number
1
=
.PP
Required tag missing
2
=
.PP
Tag not defined for this message type
3
=
.PP
Undefined Tag
4
=
.PP
Tag specified without a value
5
=
.PP
Value is incorrect (out of range) for this tag
6
=
.PP
Incorrect data format for value
7
=
.PP
Decryption problem
8
=
.PP
Signature problem
9
=
.PP
CompID problem
10
=
.PP
SendingTime accuracy problem
11
=
.PP
Invalid MsgType
.PP
   *   *   *   *   *
Used in messages:
[Reject (body_5251.html?find=SessionRejectReason)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
