.TH FIX.4.2 "" "" "Tag #376"
Tag
Field Name
Data Type
Description
Depr.
Valid values
376 (tag376.html)
ComplianceID (tag376.html)
String
.PP
ID used to represent this transaction for compliance purposes (e.g.
OATS reporting).
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=ComplianceID)]
[Order - List (body_495369.html?find=ComplianceID)]
[Order - Single (body_495268.html?find=ComplianceID)]
[Order Cancel Request (body_495470.html?find=ComplianceID)]
[Order Cancel/Replace Request (body_495571.html?find=ComplianceID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
