.TH FIX.4.2 "" "" "Tag #381"
Tag
Field Name
Data Type
Description
Depr.
Valid values
381 (tag381.html)
GrossTradeAmt (tag381.html)
Amt
.PP
Total amount traded (e.g. CumQty * AvgPx) expressed in units of
currency.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=GrossTradeAmt)]
[Execution Report (body_5756.html?find=GrossTradeAmt)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
