.TH FIX.4.2 "" "" "Tag #386"
Tag
Field Name
Data Type
Description
Depr.
Valid values
386 (tag386.html)
NoTradingSessions (tag386.html)
int
.PP
Number of TradingSessionIDs in repeating group.
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=NoTradingSessions)]
[Order - Single (body_495268.html?find=NoTradingSessions)]
[Order Cancel/Replace Request (body_495571.html?find=NoTradingSessions)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
