.TH FIX.4.2 "" "" "Tag #388"
Tag
Field Name
Data Type
Description
Depr.
Valid values
388 (tag388.html)
DiscretionInst (tag388.html)
char
.PP
Code to identify the price a DiscretionOffset is related to and
should be mathematically added to.
0
=
.PP
Related to displayed price
1
=
.PP
Related to market price
2
=
.PP
Related to primary price
3
=
.PP
Related to local primary price
4
=
.PP
Related to midpoint price
5
=
.PP
Related to last trade price
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=DiscretionInst)]
[Order - List (body_495369.html?find=DiscretionInst)]
[Order - Single (body_495268.html?find=DiscretionInst)]
[Order Cancel/Replace Request (body_495571.html?find=DiscretionInst)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
