.TH FIX.4.2 "" "" "Tag #40"
Tag
Field Name
Data Type
Description
Depr.
Valid values
40 (tag40.html)
OrdType (tag40.html)
char
.PP
Order type.
1
=
.PP
Market
2
=
.PP
Limit
3
=
.PP
Stop
4
=
.PP
Stop limit
5
=
.PP
Market on close
6
=
.PP
With or without
7
=
.PP
Limit or better
8
=
.PP
Limit with or without
9
=
.PP
On basis
A
=
.PP
On close
B
=
.PP
Limit on close
C
=
.PP
Forex - Market
D
=
.PP
Previously quoted
E
=
.PP
Previously indicated
F
=
.PP
Forex - Limit
G
=
.PP
Forex - Swap
H
=
.PP
Forex - Previously Quoted
I
=
.PP
Funari (Limit Day Order with unexecuted portion handled as Market
On Close. e.g. Japan)
P
=
.PP
Pegged
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=OrdType)]
[Mass Quote (body_5250105.html?find=OrdType)]
[Order - List (body_495369.html?find=OrdType)]
[Order - Single (body_495268.html?find=OrdType)]
[Order Cancel/Replace Request (body_495571.html?find=OrdType)]
[Quote (body_505583.html?find=OrdType)]
[Quote Request (body_505482.html?find=OrdType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
