.TH FIX.4.2 "" "" "Tag #401"
Tag
Field Name
Data Type
Description
Depr.
Valid values
401 (tag401.html)
SideValueInd (tag401.html)
int
.PP
Code to identify which "SideValue" the value refers to. SideValue1
and SideValue2 are used as opposed to Buy or Sell so that the
basket can be quoted either way as Buy or Sell.
.PP
   *   *   *   *   *
Used in messages:
[Bid Request (body_5252107.html?find=SideValueInd)]
[Order - List (body_495369.html?find=SideValueInd)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
