.TH FIX.4.2 "" "" "Tag #423"
Tag
Field Name
Data Type
Description
Depr.
Valid values
423 (tag423.html)
PriceType (tag423.html)
int
.PP
Code to represent the price type.
1
=
.PP
Percentage
2
=
.PP
per share (e.g. cents per share)
3
=
.PP
Fixed Amount (absolute value)
.PP
   *   *   *   *   *
Used in messages:
[Bid Response (lowercase L) (body_5253108.html?find=PriceType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
