.TH FIX.4.2 "" "" "Tag #424"
Tag
Field Name
Data Type
Description
Depr.
Valid values
424 (tag424.html)
DayOrderQty (tag424.html)
Qty
.PP
For GT orders, the OrderQty less all shares (adjusted for stock
splits) that traded on previous days. DayOrderQty = OrderQty –
(CumQty - DayCumQty)
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=DayOrderQty)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
