.TH FIX.4.2 "" "" "Tag #425"
Tag
Field Name
Data Type
Description
Depr.
Valid values
425 (tag425.html)
DayCumQty (tag425.html)
Qty
.PP
The number of shares on a GT order that have traded today.
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=DayCumQty)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
