.TH FIX.4.2 "" "" "Tag #426"
Tag
Field Name
Data Type
Description
Depr.
Valid values
426 (tag426.html)
DayAvgPx (tag426.html)
Price
.PP
The average price of shares on a GT order that have traded today.
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=DayAvgPx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
