.TH FIX.4.2 "" "" "Tag #427"
Tag
Field Name
Data Type
Description
Depr.
Valid values
427 (tag427.html)
GTBookingInst (tag427.html)
int
.PP
Code to identify whether to book out executions on a part-filled GT
order on the day of execution or to accumulate.
0
=
.PP
book out all trades on day of execution
1
=
.PP
accumulate executions until order is filled or expires
2
=
.PP
accumulate until verbally notified otherwise
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=GTBookingInst)]
[Order - List (body_495369.html?find=GTBookingInst)]
[Order - Single (body_495268.html?find=GTBookingInst)]
[Order Cancel/Replace Request (body_495571.html?find=GTBookingInst)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
