.TH FIX.4.2 "" "" "Tag #428"
Tag
Field Name
Data Type
Description
Depr.
Valid values
428 (tag428.html)
NoStrikes (tag428.html)
int
.PP
Number of list strike price entries.
.PP
   *   *   *   *   *
Used in messages:
[List Strike Price (body_5254109.html?find=NoStrikes)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
