.TH FIX.4.2 "" "" "Tag #431"
Tag
Field Name
Data Type
Description
Depr.
Valid values
431 (tag431.html)
ListOrderStatus (tag431.html)
int
.PP
Code to represent the status of a list order.
.PP
   *   *   *   *   *
Used in messages:
[List Status (body_505178.html?find=ListOrderStatus)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
