.TH FIX.4.2 "" "" "Tag #433"
Tag
Field Name
Data Type
Description
Depr.
Valid values
433 (tag433.html)
ListExecInstType (tag433.html)
char
.PP
Identifies the type of ListExecInst.
1
=
.PP
Immediate
2
=
.PP
Wait for Execute Instruction (e.g. a List Execute message or phone
call before proceeding with execution of the list)
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=ListExecInstType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
