.TH FIX.4.2 "" "" "Tag #434"
Tag
Field Name
Data Type
Description
Depr.
Valid values
434 (tag434.html)
CxlRejResponseTo (tag434.html)
char
.PP
Identifies the type of request that a Cancel Reject is in response
to.
1
=
.PP
Order Cancel Request
2
=
.PP
Order Cancel/Replace Request
.PP
   *   *   *   *   *
Used in messages:
[Order Cancel Reject (body_494857.html?find=CxlRejResponseTo)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
