.TH FIX.4.2 "" "" "Tag #435"
Tag
Field Name
Data Type
Description
Depr.
Valid values
435 (tag435.html)
UnderlyingCouponRate (tag435.html)
float
.PP
Underlying security’s CouponRate.
.PP
See CouponRate field for description
.PP
   *   *   *   *   *
Used in messages:
[Mass Quote (body_5250105.html?find=UnderlyingCouponRate)]
[Quote Acknowledgement (body_515398.html?find=UnderlyingCouponRate)]
[Security Definition (body_5155100.html?find=UnderlyingCouponRate)]
[Security Definition Request (body_515499.html?find=UnderlyingCouponRate)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
