.TH FIX.4.2 "" "" "Tag #44"
Tag
Field Name
Data Type
Description
Depr.
Valid values
44 (tag44.html)
Price (tag44.html)
Price
.PP
Price per share
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=Price)]
[Bid Response (lowercase L) (body_5253108.html?find=Price)]
[Execution Report (body_5756.html?find=Price)]
[Indication of Interest (body_5554.html?find=Price)]
[List Strike Price (body_5254109.html?find=Price)]
[Order - List (body_495369.html?find=Price)]
[Order - Single (body_495268.html?find=Price)]
[Order Cancel/Replace Request (body_495571.html?find=Price)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
