.TH FIX.4.2 "" "" "Tag #440"
Tag
Field Name
Data Type
Description
Depr.
Valid values
440 (tag440.html)
ClearingAccount (tag440.html)
String
.PP
Supplemental accounting information forwared to clearing
house/firm.
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=ClearingAccount)]
[Order - List (body_495369.html?find=ClearingAccount)]
[Order - Single (body_495268.html?find=ClearingAccount)]
[Order Cancel/Replace Request (body_495571.html?find=ClearingAccount)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
