.TH FIX.4.2 "" "" "Tag #446"
Tag
Field Name
Data Type
Description
Depr.
Valid values
446 (tag446.html)
EncodedListStatusText (tag446.html)
data
.PP
Encoded (non-ASCII characters) representation of the ListStatusText
field in the encoded format specified via the MessageEncoding
field. If used, the ASCII (English) representation should also be
specified in the ListStatusText field.
.PP
   *   *   *   *   *
Used in messages:
[List Status (body_505178.html?find=EncodedListStatusText)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
