.TH FIX.4.2 "" "" "Tag #5"
Tag
Field Name
Data Type
Description
Depr.
Valid values
5 (tag5.html)
AdvTransType (tag5.html)
String
.PP
Identifies advertisement message transaction type
C
=
.PP
Cancel
N
=
.PP
New
R
=
.PP
Replace
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=AdvTransType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
