.TH FIX.4.2 "" "" "Tag #54"
Tag
Field Name
Data Type
Description
Depr.
Valid values
54 (tag54.html)
Side (tag54.html)
char
.PP
Side of order
1
=
.PP
Buy
2
=
.PP
Sell
3
=
.PP
Buy minus
4
=
.PP
Sell plus
5
=
.PP
Sell short
6
=
.PP
Sell short exempt
7
=
.PP
Undisclosed (valid for IOI and List Order messages only)
8
=
.PP
Cross (orders where counterparty is an exchange, valid for all
messages except IOIs)
9
=
.PP
Cross short
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=Side)]
[Bid Request (body_5252107.html?find=Side)]
[Bid Response (lowercase L) (body_5253108.html?find=Side)]
[Don’t Know Trade (DK) (body_505381.html?find=Side)]
[Execution Report (body_5756.html?find=Side)]
[Indication of Interest (body_5554.html?find=Side)]
[List Strike Price (body_5254109.html?find=Side)]
[Order - List (body_495369.html?find=Side)]
[Order - Single (body_495268.html?find=Side)]
[Order Cancel Request (body_495470.html?find=Side)]
[Order Cancel/Replace Request (body_495571.html?find=Side)]
[Order Status Request (body_495672.html?find=Side)]
[Quote Request (body_505482.html?find=Side)]
[Quote Status Request (body_515297.html?find=Side)]
[Security Definition (body_5155100.html?find=Side)]
[Security Definition Request (body_515499.html?find=Side)]
[Settlement Instructions (body_505684.html?find=Side)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
