.TH FIX.4.2 "" "" "Tag #59"
Tag
Field Name
Data Type
Description
Depr.
Valid values
59 (tag59.html)
TimeInForce (tag59.html)
char
.PP
Specifies how long the order remains in effect. Absence of this
field is interpreted as DAY.
0
=
.PP
Day
1
=
.PP
Good Till Cancel (GTC)
2
=
.PP
At the Opening (OPG)
3
=
.PP
Immediate or Cancel (IOC)
4
=
.PP
Fill or Kill (FOK)
5
=
.PP
Good Till Crossing (GTX)
6
=
.PP
Good Till Date
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=TimeInForce)]
[Market Data-Incremental Refresh (body_514988.html?find=TimeInForce)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=TimeInForce)]
[Order - List (body_495369.html?find=TimeInForce)]
[Order - Single (body_495268.html?find=TimeInForce)]
[Order Cancel/Replace Request (body_495571.html?find=TimeInForce)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
