.TH FIX.4.2 "" "" "Tag #60"
Tag
Field Name
Data Type
Description
Depr.
Valid values
60 (tag60.html)
TransactTime (tag60.html)
UTCTimestamp
.PP
Time of execution/order creation (expressed in UTC (Universal Time
Coordinated, also known as “GMT”)
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=TransactTime)]
[Allocation (body_495774.html?find=TransactTime)]
[Allocation ACK (body_505280.html?find=TransactTime)]
[Execution Report (body_5756.html?find=TransactTime)]
[Indication of Interest (body_5554.html?find=TransactTime)]
[List Cancel Request (body_504875.html?find=TransactTime)]
[List Execute (body_504976.html?find=TransactTime)]
[List Status (body_505178.html?find=TransactTime)]
[Mass Quote (body_5250105.html?find=TransactTime)]
[Order - List (body_495369.html?find=TransactTime)]
[Order - Single (body_495268.html?find=TransactTime)]
[Order Cancel Reject (body_494857.html?find=TransactTime)]
[Order Cancel Request (body_495470.html?find=TransactTime)]
[Order Cancel/Replace Request (body_495571.html?find=TransactTime)]
[Quote (body_505583.html?find=TransactTime)]
[Quote Request (body_505482.html?find=TransactTime)]
[Security Status (body_5157102.html?find=TransactTime)]
[Settlement Instructions (body_505684.html?find=TransactTime)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
