.TH FIX.4.2 "" "" "Tag #61"
Tag
Field Name
Data Type
Description
Depr.
Valid values
61 (tag61.html)
Urgency (tag61.html)
char
.PP
Urgency flag
0
=
.PP
Normal
1
=
.PP
Flash
2
=
.PP
Background
.PP
   *   *   *   *   *
Used in messages:
[News (body_495066.html?find=Urgency)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
