.TH FIX.4.2 "" "" "Tag #64"
Tag
Field Name
Data Type
Description
Depr.
Valid values
64 (tag64.html)
FutSettDate (tag64.html)
LocalMktDate
.PP
Specific date of trade settlement (SettlementDate) in YYYYMMDD
format. Required when SettlmntTyp = 6 (Future) or SettlmntTyp = 8
(Sellers Option). (expressed in local time at place of settlement)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=FutSettDate)]
[Bid Request (body_5252107.html?find=FutSettDate)]
[Bid Response (lowercase L) (body_5253108.html?find=FutSettDate)]
[Execution Report (body_5756.html?find=FutSettDate)]
[Mass Quote (body_5250105.html?find=FutSettDate)]
[Order - List (body_495369.html?find=FutSettDate)]
[Order - Single (body_495268.html?find=FutSettDate)]
[Order Cancel/Replace Request (body_495571.html?find=FutSettDate)]
[Quote (body_505583.html?find=FutSettDate)]
[Quote Request (body_505482.html?find=FutSettDate)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
