.TH FIX.4.2 "" "" "Tag #65"
Tag
Field Name
Data Type
Description
Depr.
Valid values
65 (tag65.html)
SymbolSfx (tag65.html)
String
.PP
Additional information about the security (e.g. preferred,
warrants, etc.). Note also see SecurityType.
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=SymbolSfx)]
[Allocation (body_495774.html?find=SymbolSfx)]
[Don’t Know Trade (DK) (body_505381.html?find=SymbolSfx)]
[Email (body_495167.html?find=SymbolSfx)]
[Execution Report (body_5756.html?find=SymbolSfx)]
[Indication of Interest (body_5554.html?find=SymbolSfx)]
[List Strike Price (body_5254109.html?find=SymbolSfx)]
[Market Data Request (body_505786.html?find=SymbolSfx)]
[Market Data-Incremental Refresh (body_514988.html?find=SymbolSfx)]
[Market Data-Snapshot/Full Refresh (body_514887.html?find=SymbolSfx)]
[Mass Quote (body_5250105.html?find=SymbolSfx)]
[News (body_495066.html?find=SymbolSfx)]
[Order - List (body_495369.html?find=SymbolSfx)]
[Order - Single (body_495268.html?find=SymbolSfx)]
[Order Cancel Request (body_495470.html?find=SymbolSfx)]
[Order Cancel/Replace Request (body_495571.html?find=SymbolSfx)]
[Order Status Request (body_495672.html?find=SymbolSfx)]
[Quote (body_505583.html?find=SymbolSfx)]
[Quote Acknowledgement (body_515398.html?find=SymbolSfx)]
[Quote Cancel (body_515190.html?find=SymbolSfx)]
[Quote Request (body_505482.html?find=SymbolSfx)]
[Quote Status Request (body_515297.html?find=SymbolSfx)]
[Security Definition (body_5155100.html?find=SymbolSfx)]
[Security Definition Request (body_515499.html?find=SymbolSfx)]
[Security Status (body_5157102.html?find=SymbolSfx)]
[Security Status Request (body_5156101.html?find=SymbolSfx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
