.TH FIX.4.2 "" "" "Tag #66"
Tag
Field Name
Data Type
Description
Depr.
Valid values
66 (tag66.html)
ListID (tag66.html)
String
.PP
Unique identifier for list as assigned by institution, used to
associate multiple individual orders. Uniqueness must be guaranteed
within a single trading day. Firms which generate multi-day orders
should consider embedding a date within the ListID field to assure
uniqueness across days.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=ListID)]
[Bid Request (body_5252107.html?find=ListID)]
[Bid Response (lowercase L) (body_5253108.html?find=ListID)]
[Execution Report (body_5756.html?find=ListID)]
[List Cancel Request (body_504875.html?find=ListID)]
[List Execute (body_504976.html?find=ListID)]
[List Status (body_505178.html?find=ListID)]
[List Status Request (body_505077.html?find=ListID)]
[List Strike Price (body_5254109.html?find=ListID)]
[Order - List (body_495369.html?find=ListID)]
[Order Cancel Reject (body_494857.html?find=ListID)]
[Order Cancel Request (body_495470.html?find=ListID)]
[Order Cancel/Replace Request (body_495571.html?find=ListID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
