.TH FIX.4.2 "" "" "Tag #67"
Tag
Field Name
Data Type
Description
Depr.
Valid values
67 (tag67.html)
ListSeqNo (tag67.html)
int
.PP
Sequence of individual order within list (i.e. ListSeqNo of
ListNoOrds, 2 of 25, 3 of 25, \&.
\&.
\&.
)
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=ListSeqNo)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
