.TH FIX.4.2 "" "" "Tag #75"
Tag
Field Name
Data Type
Description
Depr.
Valid values
75 (tag75.html)
TradeDate (tag75.html)
LocalMktDate
.PP
Indicates date of trade referenced in this message in YYYYMMDD
format. Absence of this field indicates current day (expressed in
local time at place of trade).
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=TradeDate)]
[Allocation (body_495774.html?find=TradeDate)]
[Allocation ACK (body_505280.html?find=TradeDate)]
[Bid Request (body_5252107.html?find=TradeDate)]
[Execution Report (body_5756.html?find=TradeDate)]
[Settlement Instructions (body_505684.html?find=TradeDate)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
