.TH FIX.4.2 "" "" "Tag #78"
Tag
Field Name
Data Type
Description
Depr.
Valid values
78 (tag78.html)
NoAllocs (tag78.html)
int
.PP
Number of repeating AllocAccount/AllocPrice entries.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=NoAllocs)]
[Order - List (body_495369.html?find=NoAllocs)]
[Order - Single (body_495268.html?find=NoAllocs)]
[Order Cancel/Replace Request (body_495571.html?find=NoAllocs)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
