.TH FIX.4.2 "" "" "Tag #81"
Tag
Field Name
Data Type
Description
Depr.
Valid values
81 (tag81.html)
ProcessCode (tag81.html)
char
.PP
Processing code for sub-account. Absence of this field in
AllocAccount / AllocPrice/AllocShares / ProcessCode instance
indicates regular trade.
0
=
.PP
regular
1
=
.PP
soft dollar
2
=
.PP
step-in
3
=
.PP
step-out
4
=
.PP
soft-dollar step-in
5
=
.PP
soft-dollar step-out
6
=
.PP
plan sponsor
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=ProcessCode)]
[Order - List (body_495369.html?find=ProcessCode)]
[Order - Single (body_495268.html?find=ProcessCode)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
