.TH FIX.4.2 "" "" "Tag #94"
Tag
Field Name
Data Type
Description
Depr.
Valid values
94 (tag94.html)
EmailType (tag94.html)
char
.PP
Email message type.
0
=
.PP
New
1
=
.PP
Reply
2
=
.PP
Admin Reply
.PP
   *   *   *   *   *
Used in messages:
[Email (body_495167.html?find=EmailType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
