.TH FIX.5.0 "" "" "Tag #100"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
100 (tag100.html)
ExDestination (tag100.html)
\@ExDest
Exchange
.PP
Execution destination as defined by institution when order is
entered.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=ExDestination)]
[MultilegOrderCancelReplace (body_54506567.html?find=ExDestination)]
[NewOrderCross (body_5350115.html?find=ExDestination)]
[NewOrderMultileg (body_54496566.html?find=ExDestination)]
[NewOrderSingle (body_495268.html?find=ExDestination)]
[OrderCancelReplaceRequest (body_495571.html?find=ExDestination)]
[Quote (body_505583.html?find=ExDestination)]
[QuoteResponse (body_54576574.html?find=ExDestination)]
[QuoteStatusReport (body_54566573.html?find=ExDestination)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=ExDestination)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
