.TH FIX.5.0 "" "" "Tag #1001"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1001 (tag1001.html)
LegTimeUnit (tag1001.html)
\@TmUnit
String
.PP
Same as TimeUnit.
H
=
.PP
Hour
Min
=
.PP
Minute
S
=
.PP
Second
D
=
.PP
Day
Wk
=
.PP
Week
Mo
=
.PP
Month
Yr
=
.PP
Year
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegTimeUnit)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
