.TH FIX.5.0 "" "" "Tag #1002"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1002 (tag1002.html)
AllocMethod (tag1002.html)
\@Meth
int
.PP
Specifies the method under which a trade quantity was allocated.
1
=
.PP
Automatic
2
=
.PP
Guarantor
3
=
.PP
Manual
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=AllocMethod)]
[TrdAllocGrp (body_50485448.html?find=AllocMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
