.TH FIX.5.0 "" "" "Tag #1008"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1008 (tag1008.html)
SideTrdSubTyp (tag1008.html)
\@TrdSubTyp
int
.PP
Used on a multi-sided trade to specify the type of trade for a
given side
0
=
.PP
CMTA
1
=
.PP
Internal Transfer
2
=
.PP
External Transfer
3
=
.PP
Reject for Submitting Trade
4
=
.PP
Advisory for Contra Side
5
=
.PP
Offset due to an allocation
6
=
.PP
Onset due to an allocation
7
=
.PP
Differential Spread
8
=
.PP
Implied Spread leg executed against an outright
9
=
.PP
Transaction from Exercise
10
=
.PP
Transaction from Assignment
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=SideTrdSubTyp)]
[TrdCapRptSideGrp (body_50485449.html?find=SideTrdSubTyp)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
