.TH FIX.5.0 "" "" "Tag #1009"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1009 (tag1009.html)
SideQty (tag1009.html)
\@SideQty
int
.PP
Used to indicate the quantity on one of a multi-sided Trade Capture
Report
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=SideQty)]
[TrdCapRptSideGrp (body_50485449.html?find=SideQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
