.TH FIX.5.0 "" "" "Tag #1011"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1011 (tag1011.html)
MessageEventSource (tag1011.html)
\@MsgEvtSrc
String
.PP
Used to identify the event or source which gave rise to a message.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=MessageEventSource)]
[AllocationInstructionAlert (body_57566677.html?find=MessageEventSource)]
[AllocationReport (body_55566583.html?find=MessageEventSource)]
[PositionReport (body_55536580.html?find=MessageEventSource)]
[TradeCaptureReport (body_54526569.html?find=MessageEventSource)]
[TradeCaptureReportAck (body_55556582.html?find=MessageEventSource)]
[TradeCaptureReportRequest (body_54516568.html?find=MessageEventSource)]
[TradeCaptureReportRequestAck (body_55546581.html?find=MessageEventSource)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
