.TH FIX.5.0 "" "" "Tag #1014"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1014 (tag1014.html)
SideTrdRegTimestampSrc (tag1014.html)
\@Src
String
.PP
Same as TrdRegTimestampOrigin
.PP
Text which identifies the origin i.e. system which was used to
generate the time stamp for the Traded Regulatory timestamp value
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SideTrdRegTS (body_49485056.html?find=SideTrdRegTimestampSrc)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
