.TH FIX.5.0 "" "" "Tag #1021"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1021 (tag1021.html)
MDBookType (tag1021.html)
\@MDBkTyp
int
.PP
Describes the type of book for which the feed is intended. Used
when multiple feeds are provided over the same connection
1
=
.PP
Top of Book
2
=
.PP
Price Depth
3
=
.PP
Order Depth
.PP
   *   *   *   *   *
Used in messages:
[MarketDataIncrementalRefresh (body_514988.html?find=MDBookType)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=MDBookType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
