.TH FIX.5.0 "" "" "Tag #1023"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1023 (tag1023.html)
MDPriceLevel (tag1023.html)
\@MDPxLvl
int
.PP
Integer to convey the level of a bid or offer at a given price
level. This is in contrast to MDEntryPositionNo which is used to
convey the position of an order within a Price level
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=MDPriceLevel)]
[MDIncGrp (body_50485150.html?find=MDPriceLevel)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
