.TH FIX.5.0 "" "" "Tag #1025"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1025 (tag1025.html)
FirstPx (tag1025.html)
\@FirstPx
Price
.PP
Indicates the first trade price of the day/session
.PP
   *   *   *   *   *
Used in messages:
[SecurityStatus (body_5157102.html?find=FirstPx)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
