.TH FIX.5.0 "" "" "Tag #1027"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1027 (tag1027.html)
MDEntryForwardPoints (tag1027.html)
\@MDEntryFwdPnts
PriceOffset
.PP
Used for an F/X entry. The forward points to be added to or
subtracted from the spot rate to get the "all-in" rate in
MDEntryPx. Expressed in decimal form. For example, 61.99 points is
expressed and sent as 0.006199
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=MDEntryForwardPoints)]
[MDIncGrp (body_50485150.html?find=MDEntryForwardPoints)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
