.TH FIX.5.0 "" "" "Tag #1028"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1028 (tag1028.html)
ManualOrderIndicator (tag1028.html)
\@ManOrdInd
Boolean
.PP
Indicates if the order was initially received manually (as opposed
to electronically)
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ManualOrderIndicator)]
[NewOrderSingle (body_495268.html?find=ManualOrderIndicator)]
[OrderCancelReplaceRequest (body_495571.html?find=ManualOrderIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
