.TH FIX.5.0 "" "" "Tag #1040"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1040 (tag1040.html)
SecondaryTradeID (tag1040.html)
\@TrdID2
String
.PP
Used to carry an internal trade entity ID which may or may not be
reported to the firm
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=SecondaryTradeID)]
[TradeCaptureReportAck (body_55556582.html?find=SecondaryTradeID)]
[TradeCaptureReportRequest (body_54516568.html?find=SecondaryTradeID)]
[TradeCaptureReportRequestAck (body_55546581.html?find=SecondaryTradeID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
