.TH FIX.5.0 "" "" "Tag #1042"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1042 (tag1042.html)
SecondaryFirmTradeID (tag1042.html)
\@FirmTrdID2
String
.PP
Used to carry an internal firm assigned ID which may or may not be
reported to the exchange or central counterpary
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=SecondaryFirmTradeID)]
[TradeCaptureReportAck (body_55556582.html?find=SecondaryFirmTradeID)]
[TradeCaptureReportRequest (body_54516568.html?find=SecondaryFirmTradeID)]
[TradeCaptureReportRequestAck (body_55546581.html?find=SecondaryFirmTradeID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
