.TH FIX.5.0 "" "" "Tag #1058"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1058 (tag1058.html)
NoUndlyInstrumentParties (tag1058.html)
NumInGroup
.PP
Identifies the number of parties identified with an underlying
instrument
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UndlyInstrumentParties (body_49485151.html?find=NoUndlyInstrumentParties)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
