.TH FIX.5.0 "" "" "Tag #1059"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1059 (tag1059.html)
UndlyInstrumentPartyID (tag1059.html)
\@ID
String
.PP
PartyID value within an underlying instrument party repeating
group.
.PP
Same values as PartyID (448)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UndlyInstrumentParties (body_49485151.html?find=UndlyInstrumentPartyID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
