.TH FIX.5.0 "" "" "Tag #1063"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1063 (tag1063.html)
UndlyInstrumentPartySubID (tag1063.html)
\@ID
String
.PP
PartySubID value within an underlying instrument party repeating
group.
.PP
Same values as PartySubID (523)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UndlyInstrumentPtysSubGrp (body_50485754.html?find=UndlyInstrumentPartySubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
