.TH FIX.5.0 "" "" "Tag #1070"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1070 (tag1070.html)
MDQuoteType (tag1070.html)
\@MDQteTyp
int
.PP
Identifies market data quote type.
0
=
.PP
Indicative
1
=
.PP
Tradeable
2
=
.PP
Restricted Tradeable
3
=
.PP
Counter
4
=
.PP
Indicative and Tradeable
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequest (body_505786.html?find=MDQuoteType)]
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=MDQuoteType)]
[MDIncGrp (body_50485150.html?find=MDQuoteType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
