.TH FIX.5.0 "" "" "Tag #1075"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1075 (tag1075.html)
LegGrossTradeAmt (tag1075.html)
\@LegGrossTrdAmt
Amt
.PP
The gross trade amount of the leg. For FX Futures this is used to
express the notional value of a fill when LegLastQty and other
quantity fields are express in terms of contract size.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegGrossTradeAmt)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegGrossTradeAmt)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
