.TH FIX.5.0 "" "" "Tag #1080"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1080 (tag1080.html)
RefOrderID (tag1080.html)
\@RefOrdID
String
.PP
The ID reference to the order being hit or taken
.PP
   *   *   *   *   *
Used in messages:
[NewOrderMultileg (body_54496566.html?find=RefOrderID)]
[NewOrderSingle (body_495268.html?find=RefOrderID)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=RefOrderID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
