.TH FIX.5.0 "" "" "Tag #1085"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1085 (tag1085.html)
DisplayLowQty (tag1085.html)
\@DsplLwQty
Qty
.PP
Defines the lower quantity limit to a randomized refresh of
DisplayQty.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DisplayInstruction (body_49485057.html?find=DisplayLowQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
