.TH FIX.5.0 "" "" "Tag #110"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
110 (tag110.html)
MinQty (tag110.html)
\@MinQty
Qty
.PP
Minimum quantity of an order to be executed.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=MinQty)]
[ExecutionReport (body_5756.html?find=MinQty)]
[MultilegOrderCancelReplace (body_54506567.html?find=MinQty)]
[NewOrderCross (body_5350115.html?find=MinQty)]
[NewOrderMultileg (body_54496566.html?find=MinQty)]
[NewOrderSingle (body_495268.html?find=MinQty)]
[OrderCancelReplaceRequest (body_495571.html?find=MinQty)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=MinQty)]
[MDFullGrp (body_50485149.html?find=MinQty)]
[MDIncGrp (body_50485150.html?find=MinQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
