.TH FIX.5.0 "" "" "Tag #1104"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1104 (tag1104.html)
TriggerSecurityID (tag1104.html)
\@TrgrSecID
String
.PP
Defines the identity of the security whose prices will be tracked
by the trigger logic.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerSecurityID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
