.TH FIX.5.0 "" "" "Tag #1107"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1107 (tag1107.html)
TriggerPriceType (tag1107.html)
\@TrgrPxTyp
char
.PP
The type of price that the trigger is compared to.
1
=
.PP
Best Offer
2
=
.PP
Last Trade
3
=
.PP
Best Bid
4
=
.PP
Best Bid or Last Trade
5
=
.PP
Best Offer or Last Trade
6
=
.PP
Best Mid
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerPriceType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
