.TH FIX.5.0 "" "" "Tag #111"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
111 (tag111.html)
MaxFloor (tag111.html)
\@MaxFloor
Qty
.PP
The quantity to be displayed \&.
Required for reserve orders. On orders specifies the qty to be
displayed, on execution reports the currently displayed quantity.
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=MaxFloor)]
[ExecutionReport (body_5756.html?find=MaxFloor)]
[MultilegOrderCancelReplace (body_54506567.html?find=MaxFloor)]
[NewOrderCross (body_5350115.html?find=MaxFloor)]
[NewOrderMultileg (body_54496566.html?find=MaxFloor)]
[NewOrderSingle (body_495268.html?find=MaxFloor)]
[OrderCancelReplaceRequest (body_495571.html?find=MaxFloor)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=MaxFloor)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
