.TH FIX.5.0 "" "" "Tag #1110"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1110 (tag1110.html)
TriggerNewPrice (tag1110.html)
\@TrgrNewPx
Price
.PP
The Price that the order should have after the trigger has hit.
Could be applicable for any trigger type, but must be specified for
Trigger Type 1.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerNewPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
