.TH FIX.5.0 "" "" "Tag #1113"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1113 (tag1113.html)
TriggerTradingSessionID (tag1113.html)
\@TrgrTrdSessID
String
.PP
Defines the trading session at which the order will be activated.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerTradingSessionID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
