.TH FIX.5.0 "" "" "Tag #1115"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1115 (tag1115.html)
OrderCategory (tag1115.html)
\@OrdCat
char
.PP
Defines the type of interest behind a trade (fill or partial fill).
1
=
.PP
Order
2
=
.PP
Quote
3
=
.PP
Privately Negotiated Trade
4
=
.PP
Multileg order
5
=
.PP
Linked order
6
=
.PP
Quote Request
7
=
.PP
Implied Order
8
=
.PP
Cross Order
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=OrderCategory)]
[TradeCaptureReport (body_54526569.html?find=OrderCategory)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
