.TH FIX.5.0 "" "" "Tag #112"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
112 (tag112.html)
TestReqID (tag112.html)
String
.PP
Identifier included in Test Request message to be returned in
resulting Heartbeat
.PP
   *   *   *   *   *
Used in messages:
[Heartbeat (body_4948.html?find=TestReqID)]
[TestRequest (body_5049.html?find=TestReqID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
