.TH FIX.5.0 "" "" "Tag #1129"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1129 (tag1129.html)
CstmApplVerID (tag1129.html)
\@CstmApplVerID
String
.PP
Specifies a custom extension to a message being applied at the
message level. Enumerated field
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=CstmApplVerID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
