.TH FIX.5.0 "" "" "Tag #1132"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1132 (tag1132.html)
TZTransactTime (tag1132.html)
\@TZTransactTime
TZTimestamp
.PP
Transact time in the local date-time stamp with a TZ offset to UTC
identified
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TZTransactTime)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
