.TH FIX.5.0 "" "" "Tag #1139"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1139 (tag1139.html)
ExchangeSpecialInstructions (tag1139.html)
\@ExchSpeclInstr
String
.PP
Free format test string related to exchange.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptSideGrp (body_50485449.html?find=ExchangeSpecialInstructions)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
