.TH FIX.5.0 "" "" "Tag #118"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
118 (tag118.html)
NetMoney (tag118.html)
\@NetMny
Amt
.PP
Total amount due as the result of the transaction (e.g. for Buy
order - principal + commission + fees) reported in currency of
execution.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=NetMoney)]
[AllocationInstructionAlert (body_57566677.html?find=NetMoney)]
[AllocationReport (body_55566583.html?find=NetMoney)]
[Confirmation (body_55486575.html?find=NetMoney)]
[ExecutionReport (body_5756.html?find=NetMoney)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=NetMoney)]
[TrdCapRptSideGrp (body_50485449.html?find=NetMoney)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
