.TH FIX.5.0 "" "" "Tag #12"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
12 (tag12.html)
Commission (tag12.html)
\@Comm
Amt
.PP
Commission. Note if CommType (13) is percentage, Commission of 5%
should be represented as .05.
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=Commission)]
[QuoteResponse (body_54576574.html?find=Commission)]
[QuoteStatusReport (body_54566573.html?find=Commission)]
.PP
   *   *   *   *   *
Used in components:
[CommissionData (body_49484848.html?find=Commission)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
