.TH FIX.5.0 "" "" "Tag #121"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
121 (tag121.html)
ForexReq (tag121.html)
\@ForexReq
Boolean
.PP
Indicates request for forex accommodation trade to be executed
along with security transaction.
N
=
.PP
Do Not Execute Forex After Security Trade
Y
=
.PP
Execute Forex After Security Trade
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=ForexReq)]
[MultilegOrderCancelReplace (body_54506567.html?find=ForexReq)]
[NewOrderMultileg (body_54496566.html?find=ForexReq)]
[NewOrderSingle (body_495268.html?find=ForexReq)]
[OrderCancelReplaceRequest (body_495571.html?find=ForexReq)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=ForexReq)]
[SideCrossOrdModGrp (body_50485357.html?find=ForexReq)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
