.TH FIX.5.0 "" "" "Tag #135"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
135 (tag135.html)
OfferSize (tag135.html)
\@OfrSz
Qty
.PP
Quantity of offer
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=OfferSize)]
[QuoteResponse (body_54576574.html?find=OfferSize)]
[QuoteStatusReport (body_54566573.html?find=OfferSize)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=OfferSize)]
[QuotEntryGrp (body_50485251.html?find=OfferSize)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
