.TH FIX.5.0 "" "" "Tag #14"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
14 (tag14.html)
CumQty (tag14.html)
\@CumQty
Qty
.PP
Total quantity (e.g. number of shares) filled.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[ExecutionAcknowledgement (body_57576678.html?find=CumQty)]
[ExecutionReport (body_5756.html?find=CumQty)]
.PP
   *   *   *   *   *
Used in components:
[OrdListStatGrp (body_50485155.html?find=CumQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
