.TH FIX.5.0 "" "" "Tag #140"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
140 (tag140.html)
PrevClosePx (tag140.html)
\@PrevClsPx
Price
.PP
Previous closing price of security.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=PrevClosePx)]
[MultilegOrderCancelReplace (body_54506567.html?find=PrevClosePx)]
[NewOrderCross (body_5350115.html?find=PrevClosePx)]
[NewOrderMultileg (body_54496566.html?find=PrevClosePx)]
[NewOrderSingle (body_495268.html?find=PrevClosePx)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=PrevClosePx)]
[QuotReqGrp (body_50485253.html?find=PrevClosePx)]
[QuotReqRjctGrp (body_50485255.html?find=PrevClosePx)]
[RFQReqGrp (body_50485349.html?find=PrevClosePx)]
[UndInstrmtStrkPxGrp (body_50485455.html?find=PrevClosePx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
