.TH FIX.5.0 "" "" "Tag #158"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
158 (tag158.html)
AccruedInterestRate (tag158.html)
\@AcrdIntRt
Percentage
.PP
The amount the buyer compensates the seller for the portion of the
next coupon interest payment the seller has earned but will not
receive from the issuer because the issuer will send the next
coupon payment to the buyer. Accrued Interest Rate is the
annualized Accrued Interest amount divided by the purchase price of
the bond.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=AccruedInterestRate)]
[AllocationInstructionAlert (body_57566677.html?find=AccruedInterestRate)]
[AllocationReport (body_55566583.html?find=AccruedInterestRate)]
[Confirmation (body_55486575.html?find=AccruedInterestRate)]
[ExecutionReport (body_5756.html?find=AccruedInterestRate)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=AccruedInterestRate)]
[TrdCapRptSideGrp (body_50485449.html?find=AccruedInterestRate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
