.TH FIX.5.0 "" "" "Tag #165"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
165 (tag165.html)
SettlInstSource (tag165.html)
\@InstSrc
char
.PP
Indicates source of Settlement Instructions
1
=
.PP
Broker\[aq]s Instructions
2
=
.PP
Institution\[aq]s Instructions
3
=
.PP
Investor (e.g. CIV use)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DlvyInstGrp (body_50485553.html?find=SettlInstSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
