.TH FIX.5.0 "" "" "Tag #169"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
169 (tag169.html)
StandInstDbType (tag169.html)
\@StandInstDbTyp
int
.PP
Identifies the Standing Instruction database used
0
=
.PP
Other
1
=
.PP
DTC SID
2
=
.PP
Thomson ALERT
3
=
.PP
A Global Custodian (StandInstDBName (70) must be provided)
4
=
.PP
AccountNet
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructionRequest (body_56496586.html?find=StandInstDbType)]
.PP
   *   *   *   *   *
Used in components:
[SettlInstructionsData (body_49484954.html?find=StandInstDbType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
