.TH FIX.5.0 "" "" "Tag #18"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
18 (tag18.html)
ExecInst (tag18.html)
\@ExecInst
MultipleCharValue
.PP
Instructions for order handling on exchange trading floor. If more
than one instruction is applicable to an order, this field can
contain multiple instructions separated by space. *** SOME VALUES
HAVE BEEN REPLACED - See "Replaced Features and Supported Approach"
*** (see Volume : "Glossary" for value definitions)
0
=
.PP
Stay on offer side
1
=
.PP
Not held
2
=
.PP
Work
3
=
.PP
Go along
4
=
.PP
Over the day
5
=
.PP
Held
6
=
.PP
Participant don\[aq]t initiate
7
=
.PP
Strict scale
8
=
.PP
Try to scale
9
=
.PP
Stay on bid side
A
=
.PP
No cross (cross is forbidden)
B
=
.PP
OK to cross
C
=
.PP
Call first
D
=
.PP
Percent of volume (indicates that the sender does not want to be
all of the volume on the floor vs. a specific percentage)
E
=
.PP
Do not increase - DNI
F
=
.PP
Do not reduce - DNR
G
=
.PP
All or none - AON
H
=
.PP
Reinstate on system failue (mutually exclusive with Q)
I
=
.PP
Institutions only
J
=
.PP
Reinstate on Trading Halt (mutually exclusive with K)
K
=
.PP
Cancel on Trading Halt (mutually exclusive with J)
L
=
.PP
Last peg (last sale)
M
=
.PP
Mid-price peg (midprice of inside quote)
N
=
.PP
Non-negotiable
O
=
.PP
Opening peg
P
=
.PP
Market peg
Q
=
.PP
Cancel on system failure (mutually exclusive with H)
R
=
.PP
Primary peg (primary market - buy at bid/sell at offer)
S
=
.PP
Suspend
T
=
.PP
Fixed Peg to Local best bid or offer at time of order
U
=
.PP
Customer Display Instruction (Rule 11Ac1-1/4)
V
=
.PP
Netting (for Forex)
W
=
.PP
Peg to VWAP
X
=
.PP
Trade Along
Y
=
.PP
Try To Stop
Z
=
.PP
Cancel if not best
a
=
.PP
Trailing Stop Peg
b
=
.PP
Strict Limit (No price improvement)
c
=
.PP
Ignore Price Validity Checks
d
=
.PP
Peg to Limit Price
e
=
.PP
Work to Target Strategy
f
=
.PP
Intermarket Sweep
g
=
.PP
External Routing Allowed
h
=
.PP
External Routing Not Allowed
i
=
.PP
Imbalance Only
j
=
.PP
Single execution requested for block trade
k
=
.PP
Best Execution
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=ExecInst)]
[ExecutionReport (body_5756.html?find=ExecInst)]
[MultilegOrderCancelReplace (body_54506567.html?find=ExecInst)]
[NewOrderCross (body_5350115.html?find=ExecInst)]
[NewOrderMultileg (body_54496566.html?find=ExecInst)]
[NewOrderSingle (body_495268.html?find=ExecInst)]
[OrderCancelReplaceRequest (body_495571.html?find=ExecInst)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=ExecInst)]
[MDFullGrp (body_50485149.html?find=ExecInst)]
[MDIncGrp (body_50485150.html?find=ExecInst)]
[TrdCapRptAckSideGrp (body_50485752.html?find=ExecInst)]
[TrdCapRptSideGrp (body_50485449.html?find=ExecInst)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
