.TH FIX.5.0 "" "" "Tag #193"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
193 (tag193.html)
SettlDate2 (tag193.html)
\@SettlDt2
LocalMktDate
.PP
SettDate (64) of the future part of a F/X swap order.
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=SettlDate2)]
[NewOrderSingle (body_495268.html?find=SettlDate2)]
[OrderCancelReplaceRequest (body_495571.html?find=SettlDate2)]
[Quote (body_505583.html?find=SettlDate2)]
[QuoteResponse (body_54576574.html?find=SettlDate2)]
[QuoteStatusReport (body_54566573.html?find=SettlDate2)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=SettlDate2)]
[QuotEntryAckGrp (body_50485250.html?find=SettlDate2)]
[QuotEntryGrp (body_50485251.html?find=SettlDate2)]
[QuotReqGrp (body_50485253.html?find=SettlDate2)]
[QuotReqRjctGrp (body_50485255.html?find=SettlDate2)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
