.TH FIX.5.0 "" "" "Tag #198"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
198 (tag198.html)
SecondaryOrderID (tag198.html)
\@OrdID2
String
.PP
Assigned by the party which accepts the order. Can be used to
provide the OrderID (37) used by an exchange or executing system.
.PP
   *   *   *   *   *
Used in messages:
[CollateralAssignment (body_56526589.html?find=SecondaryOrderID)]
[CollateralInquiry (body_56556666.html?find=SecondaryOrderID)]
[CollateralInquiryAck (body_57506671.html?find=SecondaryOrderID)]
[CollateralReport (body_56546665.html?find=SecondaryOrderID)]
[CollateralRequest (body_56516588.html?find=SecondaryOrderID)]
[CollateralResponse (body_56536590.html?find=SecondaryOrderID)]
[DontKnowTradeDK (body_505381.html?find=SecondaryOrderID)]
[ExecutionAcknowledgement (body_57576678.html?find=SecondaryOrderID)]
[ExecutionReport (body_5756.html?find=SecondaryOrderID)]
[OrderCancelReject (body_494857.html?find=SecondaryOrderID)]
[OrderMassCancelReport (body_5349114.html?find=SecondaryOrderID)]
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=SecondaryOrderID)]
[MDIncGrp (body_50485150.html?find=SecondaryOrderID)]
[OrdAllocGrp (body_50485154.html?find=SecondaryOrderID)]
[TrdCapRptAckSideGrp (body_50485752.html?find=SecondaryOrderID)]
[TrdCapRptSideGrp (body_50485449.html?find=SecondaryOrderID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
