.TH FIX.5.0 "" "" "Tag #210"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
210 (tag210.html)
MaxShow (tag210.html)
\@MaxShow
Qty
.PP
Maximum quantity (e.g. number of shares) within an order to be
shown to other customers (i.e. sent via an IOI).
.PP
(Prior to FIX 4.2 this field was of type int)
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=MaxShow)]
[ExecutionReport (body_5756.html?find=MaxShow)]
[MultilegOrderCancelReplace (body_54506567.html?find=MaxShow)]
[NewOrderCross (body_5350115.html?find=MaxShow)]
[NewOrderMultileg (body_54496566.html?find=MaxShow)]
[NewOrderSingle (body_495268.html?find=MaxShow)]
[OrderCancelReplaceRequest (body_495571.html?find=MaxShow)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=MaxShow)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
