.TH FIX.5.0 "" "" "Tag #216"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
216 (tag216.html)
RoutingType (tag216.html)
\@RtgTyp
int
.PP
Indicates the type of RoutingID (217) specified.
1
=
.PP
Target Firm
2
=
.PP
Target List
3
=
.PP
Block Firm
4
=
.PP
Block List
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RoutingGrp (body_50485352.html?find=RoutingType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
