.TH FIX.5.0 "" "" "Tag #219"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
219 (tag219.html)
Benchmark (tag219.html)
char
.PP
For Fixed Income. Identifies the benchmark (e.g. used in
conjunction with the Spread field).
FIX.4.2
1
=
.PP
CURVE
2
=
.PP
5YR
3
=
.PP
OLD5
4
=
.PP
10YR
5
=
.PP
OLD10
6
=
.PP
30YR
7
=
.PP
OLD30
8
=
.PP
3MOLIBOR
9
=
.PP
6MOLIBOR
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
