.TH FIX.5.0 "" "" "Tag #220"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
220 (tag220.html)
BenchmarkCurveCurrency (tag220.html)
\@Ccy
Currency
.PP
Identifies currency used for benchmark curve. See "Appendix 6-A:
Valid Currency Codes" for information on obtaining
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SpreadOrBenchmarkCurveData (body_49484956.html?find=BenchmarkCurveCurrency)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
