.TH FIX.5.0 "" "" "Tag #229"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
229 (tag229.html)
TradeOriginationDate (tag229.html)
\@OrignDt
LocalMktDate
.PP
Used with Fixed Income for Muncipal New Issue Market. Agreement in
principal between counter-parties prior to actual trade date.
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
(prior to FIX 4.4 field was of type UTCDate)
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=TradeOriginationDate)]
[AllocationInstructionAlert (body_57566677.html?find=TradeOriginationDate)]
[AllocationReport (body_55566583.html?find=TradeOriginationDate)]
[ExecutionReport (body_5756.html?find=TradeOriginationDate)]
[ListCancelRequest (body_504875.html?find=TradeOriginationDate)]
[MultilegOrderCancelReplace (body_54506567.html?find=TradeOriginationDate)]
[NewOrderMultileg (body_54496566.html?find=TradeOriginationDate)]
[NewOrderSingle (body_495268.html?find=TradeOriginationDate)]
[OrderCancelReject (body_494857.html?find=TradeOriginationDate)]
[OrderCancelReplaceRequest (body_495571.html?find=TradeOriginationDate)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=TradeOriginationDate)]
[QuotReqGrp (body_50485253.html?find=TradeOriginationDate)]
[QuotReqRjctGrp (body_50485255.html?find=TradeOriginationDate)]
[SideCrossOrdCxlGrp (body_50485356.html?find=TradeOriginationDate)]
[SideCrossOrdModGrp (body_50485357.html?find=TradeOriginationDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
