.TH FIX.5.0 "" "" "Tag #235"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
235 (tag235.html)
YieldType (tag235.html)
\@Typ
String
.PP
Type of yield. (Note tag # was reserved in FIX 4.1, added in FIX
4.3)
AFTERTAX
=
.PP
After Tax Yield (Municipals)
ANNUAL
=
.PP
Annual Yield
ATISSUE
=
.PP
Yield At Issue (Municipals)
AVGMATURITY
=
.PP
Yield To Avg Maturity
BOOK
=
.PP
Book Yield
CALL
=
.PP
Yield to Next Call
CHANGE
=
.PP
Yield Change Since Close
CLOSE
=
.PP
Closing Yield
COMPOUND
=
.PP
Compound Yield
CURRENT
=
.PP
Current Yield
GOVTEQUIV
=
.PP
Gvnt Equivalent Yield
GROSS
=
.PP
True Gross Yield
INFLATION
=
.PP
Yield with Inflation Assumption
INVERSEFLOATER
=
.PP
Inverse Floater Bond Yield
LASTCLOSE
=
.PP
Most Recent Closing Yield
LASTMONTH
=
.PP
Closing Yield Most Recent Month
LASTQUARTER
=
.PP
Closing Yield Most Recent Quarter
LASTYEAR
=
.PP
Closing Yield Most Recent Year
LONGAVGLIFE
=
.PP
Yield to Longest Average Life
MARK
=
.PP
Mark to Market Yield
MATURITY
=
.PP
Yield to Maturity
NEXTREFUND
=
.PP
Yield to Next Refund (Sinking Fund Bonds)
OPENAVG
=
.PP
Open Average Yield
PREVCLOSE
=
.PP
Previous Close Yield
PROCEEDS
=
.PP
Proceeds Yield
PUT
=
.PP
Yield to Next Put
SEMIANNUAL
=
.PP
Semi-annual Yield
SHORTAVGLIFE
=
.PP
Yield to Shortest Average Life
SIMPLE
=
.PP
Simple Yield
TAXEQUIV
=
.PP
Tax Equivalent Yield
TENDER
=
.PP
Yield to Tender Date
TRUE
=
.PP
True Yield
VALUE1_32
=
.PP
Yield Value Of 1/32
WORST
=
.PP
Yield To Worst
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[YieldData (body_49485050.html?find=YieldType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
