.TH FIX.5.0 "" "" "Tag #243"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
243 (tag243.html)
UnderlyingRepoCollateralSecurityType (tag243.html)
\@RepoCollSecTyp
int
.PP
Underlying security\[aq]s RepoCollateralSecurityType. See
RepoCollateralSecurityType (239) field for description.(Note tag #
was reserved in FIX 4.1, added in FIX 4.3)
FIX.4.4
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingRepoCollateralSecurityType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
