.TH FIX.5.0 "" "" "Tag #268"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
268 (tag268.html)
NoMDEntries (tag268.html)
NumInGroup
.PP
Number of entries in Market Data message.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=NoMDEntries)]
[MDIncGrp (body_50485150.html?find=NoMDEntries)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
