.TH FIX.5.0 "" "" "Tag #277"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
277 (tag277.html)
TradeCondition (tag277.html)
\@TrdCond
MultipleStringValue
.PP
Space-delimited list of conditions describing a trade
A
=
.PP
Cash (only) Market
B
=
.PP
Average Price Trade
C
=
.PP
Cash Trade (same day clearing)
D
=
.PP
Next Day (only)Market
E
=
.PP
Opening/Reopening Trade Detail
F
=
.PP
Intraday Trade Detail
G
=
.PP
Rule 127 Trade (NYSE)
H
=
.PP
Rule 155 Trade (AMEX)
I
=
.PP
Sold Last (late reporting)
J
=
.PP
Next Day Trade (next day clearing)
K
=
.PP
Opened (late report of opened trade)
L
=
.PP
Seller
M
=
.PP
Sold (out of sequence)
N
=
.PP
Stopped Stock (guarantee of price but does not execute the order)
P
=
.PP
Imbalance More Buyers (cannot be used in combination with Q)
Q
=
.PP
Imbalance More Sellers (cannot be used in combination with P)
R
=
.PP
Opening Price
S
=
.PP
Bargain Condition (LSE)
T
=
.PP
Converted Price Indicator
U
=
.PP
Exchange Last
V
=
.PP
Final Price of Session
W
=
.PP
Ex-pit
X
=
.PP
Crossed
Y
=
.PP
Trades resulting from manual/slow quote
Z
=
.PP
Trades resulting from intermarket sweep
a
=
.PP
Volume Only
b
=
.PP
Direct Plus
c
=
.PP
Acquisition
d
=
.PP
Bunched
e
=
.PP
Distribution
f
=
.PP
Bunched Sale
g
=
.PP
Split Trade
h
=
.PP
Cancel Stopped
i
=
.PP
Cancel ETH
j
=
.PP
Cancel Stopped ETH
k
=
.PP
Out of Sequence ETH
l
=
.PP
Cancel Last ETH
m
=
.PP
Sold Last Sale ETH
n
=
.PP
Cancel Last
o
=
.PP
Sold Last Sale
p
=
.PP
Cancel Open
q
=
.PP
Cancel Open ETH
r
=
.PP
Opened Sale ETH
s
=
.PP
Cancel Only
t
=
.PP
Cancel Only ETH
u
=
.PP
Late Open ETH
v
=
.PP
Auto Execution ETH
w
=
.PP
Reopen
x
=
.PP
Reopen ETH
y
=
.PP
Adjusted
z
=
.PP
Adjusted ETH
AA
=
.PP
Spread
AB
=
.PP
Spread ETH
AC
=
.PP
Straddle
AD
=
.PP
Straddle ETH
AE
=
.PP
Stopped
AF
=
.PP
Stopped ETH
AG
=
.PP
Regular ETH
AH
=
.PP
Combo
AI
=
.PP
Combo ETH
AJ
=
.PP
Official Closing Price
AK
=
.PP
Prior Reference Price
0
=
.PP
Cancel
AL
=
.PP
Stopped Sold Last
AM
=
.PP
Stopped Out of Sequence
AN
=
.PP
Offical Closing Price
AO
=
.PP
Crossed
AP
=
.PP
Fast Market
AQ
=
.PP
Automatic Execution
AR
=
.PP
Form T
AS
=
.PP
Basket Index
AT
=
.PP
Burst Basket
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=TradeCondition)]
[MDIncGrp (body_50485150.html?find=TradeCondition)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
