.TH FIX.5.0 "" "" "Tag #280"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
280 (tag280.html)
MDEntryRefID (tag280.html)
\@RefID
String
.PP
Refers to a previous MDEntryID (278).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDIncGrp (body_50485150.html?find=MDEntryRefID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
