.TH FIX.5.0 "" "" "Tag #281"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
281 (tag281.html)
MDReqRejReason (tag281.html)
\@ReqRejResn
char
.PP
Reason for the rejection of a Market Data request.
0
=
.PP
Unknown symbol
1
=
.PP
Duplicate MDReqID
2
=
.PP
Insufficient Bandwidth
3
=
.PP
Insufficient Permissions
4
=
.PP
Unsupported SubscriptionRequestType
5
=
.PP
Unsupported MarketDepth
6
=
.PP
Unsupported MDUpdateType
7
=
.PP
Unsupported AggregatedBook
8
=
.PP
Unsupported MDEntryType
9
=
.PP
Unsupported TradingSessionID
A
=
.PP
Unsupported Scope
B
=
.PP
Unsupported OpenCloseSettleFlag
C
=
.PP
Unsupported MDImplicitDelete
D
=
.PP
Insufficient credit
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequestReject (body_515089.html?find=MDReqRejReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
