.TH FIX.5.0 "" "" "Tag #284"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
284 (tag284.html)
DeskID (tag284.html)
\@DeskID
String
.PP
Identification of a Market Maker’s desk
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CompIDReqGrp (body_50484857.html?find=DeskID)]
[CompIDStatGrp (body_50484948.html?find=DeskID)]
[MDFullGrp (body_50485149.html?find=DeskID)]
[MDIncGrp (body_50485150.html?find=DeskID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
