.TH FIX.5.0 "" "" "Tag #292"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
292 (tag292.html)
CorporateAction (tag292.html)
\@CorpActn
MultipleCharValue
.PP
Identifies the type of Corporate Action.
A
=
.PP
Ex-Dividend
B
=
.PP
Ex-Distribution
C
=
.PP
Ex-Rights
D
=
.PP
New
E
=
.PP
Ex-Interest
F
=
.PP
Cash Dividend
G
=
.PP
Stock Dividend
H
=
.PP
Non-Integer Stock Split
I
=
.PP
Reverse Stock Split
J
=
.PP
Standard-Integer Stock Split
K
=
.PP
Position Consolidation
L
=
.PP
Liquidation Reorganization
M
=
.PP
Merger Reorganization
N
=
.PP
Rights Offering
O
=
.PP
Shareholder Meeting
P
=
.PP
Spinoff
Q
=
.PP
Tender Offer
R
=
.PP
Warrant
S
=
.PP
Special Action
T
=
.PP
Symbol Conversion
U
=
.PP
CUSIP / Name Change
V
=
.PP
Leap Rollover
.PP
   *   *   *   *   *
Used in messages:
[MarketDataSnapshotFullRefresh (body_514887.html?find=CorporateAction)]
[SecurityDefinitionUpdateReport (body_57536680.html?find=CorporateAction)]
[SecurityListUpdateReport (body_57546675.html?find=CorporateAction)]
[SecurityStatus (body_5157102.html?find=CorporateAction)]
.PP
   *   *   *   *   *
Used in components:
[MDIncGrp (body_50485150.html?find=CorporateAction)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
