.TH FIX.5.0 "" "" "Tag #297"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
297 (tag297.html)
QuoteStatus (tag297.html)
\@Stat
int
.PP
Identifies the status of the quote acknowledgement.
0
=
.PP
Accepted
1
=
.PP
Cancel for Symbol(s)
2
=
.PP
Canceled for Security Type(s)
3
=
.PP
Canceled for Underlying
4
=
.PP
Canceled All
5
=
.PP
Rejected
6
=
.PP
Removed from Market
7
=
.PP
Expired
8
=
.PP
Query
9
=
.PP
Quote Not Found
10
=
.PP
Pending
11
=
.PP
Pass
12
=
.PP
Locked Market Warning
13
=
.PP
Cross Market Warning
14
=
.PP
Canceled Due To Lock Market
15
=
.PP
Canceled Due To Cross Market
.PP
   *   *   *   *   *
Used in messages:
[MassQuoteAcknowledgement (body_515398.html?find=QuoteStatus)]
[QuoteStatusReport (body_54566573.html?find=QuoteStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
