.TH FIX.5.0 "" "" "Tag #30"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
30 (tag30.html)
LastMkt (tag30.html)
\@LastMkt
Exchange
.PP
Market of execution for last fill, or an indication of the market
where an order was routed
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=LastMkt)]
[AllocationInstruction (body_495774.html?find=LastMkt)]
[AllocationInstructionAlert (body_57566677.html?find=LastMkt)]
[AllocationReport (body_55566583.html?find=LastMkt)]
[Confirmation (body_55486575.html?find=LastMkt)]
[ExecutionReport (body_5756.html?find=LastMkt)]
[TradeCaptureReport (body_54526569.html?find=LastMkt)]
[TradeCaptureReportAck (body_55556582.html?find=LastMkt)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
