.TH FIX.5.0 "" "" "Tag #300"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
300 (tag300.html)
QuoteRejectReason (tag300.html)
\@RejRsn
int
.PP
Reason Quote was rejected:
1
=
.PP
Unknown Symbol (security)
2
=
.PP
Exchange (Security) closed
3
=
.PP
Quote Request exceeds limit
4
=
.PP
Too late to enter
5
=
.PP
Unknown Quote
6
=
.PP
Duplicate Quote
7
=
.PP
Invalid bid/ask spread
8
=
.PP
Invalid price
9
=
.PP
Not authorized to quote security
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[MassQuoteAcknowledgement (body_515398.html?find=QuoteRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
