.TH FIX.5.0 "" "" "Tag #311"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
311 (tag311.html)
UnderlyingSymbol (tag311.html)
\@Sym
String
.PP
Underlying security’s Symbol.
.PP
See Symbol (55) field for description
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingSymbol)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
