.TH FIX.5.0 "" "" "Tag #316"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
316 (tag316.html)
UnderlyingStrikePrice (tag316.html)
\@StrkPx
Price
.PP
Underlying security’s StrikePrice.
.PP
See StrikePrice (202) field for description
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingStrikePrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
