.TH FIX.5.0 "" "" "Tag #32"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
32 (tag32.html)
LastQty (tag32.html)
\@LastQty
Qty
.PP
Quantity (e.g. shares) bought/sold on this (last) fill.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[DontKnowTradeDK (body_505381.html?find=LastQty)]
[ExecutionAcknowledgement (body_57576678.html?find=LastQty)]
[ExecutionReport (body_5756.html?find=LastQty)]
[TradeCaptureReport (body_54526569.html?find=LastQty)]
[TradeCaptureReportAck (body_55556582.html?find=LastQty)]
.PP
   *   *   *   *   *
Used in components:
[ExecAllocGrp (body_50484952.html?find=LastQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
