.TH FIX.5.0 "" "" "Tag #341"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
341 (tag341.html)
TradSesStartTime (tag341.html)
\@StartTm
UTCTimestamp
.PP
Starting time of the trading session
.PP
   *   *   *   *   *
Used in messages:
[TradingSessionStatus (body_5249104.html?find=TradSesStartTime)]
.PP
   *   *   *   *   *
Used in components:
[TrdSessLstGrp (body_50485757.html?find=TradSesStartTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
