.TH FIX.5.0 "" "" "Tag #347"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
347 (tag347.html)
MessageEncoding (tag347.html)
\@MsgEncd
String
.PP
Type of message encoding (non-ASCII (non-English) characters) used
in a message’s "Encoded" fields.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=MessageEncoding)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
