.TH FIX.5.0 "" "" "Tag #348"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
348 (tag348.html)
EncodedIssuerLen (tag348.html)
\@EncIssrLen
Length
.PP
Byte length of encoded (non-ASCII characters) EncodedIssuer (349)
field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=EncodedIssuerLen)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
