.TH FIX.5.0 "" "" "Tag #35"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
35 (tag35.html)
MsgType (tag35.html)
\@MsgTyp
String
.PP
Defines message type ALWAYS THIRD FIELD IN MESSAGE. (Always
unencrypted)
.PP
Note: A "U" as the first character in the MsgType field (i.e. U,
U2, etc) indicates that the message format is privately defined
between the sender and receiver.
.PP
*** Note the use of lower case letters ***
0
=
.PP
Heartbeat
1
=
.PP
Test Request
2
=
.PP
Resend Request
3
=
.PP
Reject
4
=
.PP
Sequence Reset
5
=
.PP
Logout
6
=
.PP
Indication of Interest
7
=
.PP
Advertisement
8
=
.PP
Execution Report
9
=
.PP
Order Cancel Reject
A
=
.PP
Logon
B
=
.PP
News
C
=
.PP
Email
D
=
.PP
New Order - Single
E
=
.PP
New Order - List
F
=
.PP
Order Cancel Request
G
=
.PP
Order Cancel/Replace Request (a.k.a. Order Modification Request)
H
=
.PP
Order Status Request
J
=
.PP
Allocation Instruction
K
=
.PP
List Cancel Request
L
=
.PP
List Execute
M
=
.PP
List Status Request
N
=
.PP
List Status
P
=
.PP
Allocation Instruction Ack
Q
=
.PP
Don\[aq]t Know Trade (DK)
R
=
.PP
Quote Request
S
=
.PP
Quote
T
=
.PP
Settlement Instructions
V
=
.PP
Market Data Request
W
=
.PP
Market Data - Snapshot/Full Refresh
X
=
.PP
Market Data - Incremental Refresh
Y
=
.PP
Market Data Request Reject
Z
=
.PP
Quote Cancel
a
=
.PP
Quote Status Request
b
=
.PP
Mass Quote Acknowledgement
c
=
.PP
Security Definition Request
d
=
.PP
Security Definition
e
=
.PP
Security Status Request
f
=
.PP
Security Status
g
=
.PP
Trading Session Status Request
h
=
.PP
Trading Session Status
i
=
.PP
Mass Quote
j
=
.PP
Business Message Reject
k
=
.PP
Bid Request
l
=
.PP
Bid Response (lowercase L)
m
=
.PP
List Strike Price
n
=
.PP
XML message (e.g. non FIX Msg Type)
o
=
.PP
Registration Instructions
p
=
.PP
Registration Instructions Response
q
=
.PP
Order Mass Cancel Request
r
=
.PP
Order Mass Cancel Report
s
=
.PP
New Order - Cross
t
=
.PP
Cross Order Cancel/Replace Request (a.k.a. Cross Order Modification
Request)
u
=
.PP
Cross Order Cancel Request
v
=
.PP
Security Type Request
w
=
.PP
Security Types
x
=
.PP
Security List Request
y
=
.PP
Security List
z
=
.PP
Derivative Security List Request
AA
=
.PP
Derivative Security List
AB
=
.PP
New Order - Multileg
AC
=
.PP
Multileg Order Cancel/Replace (a.k.a. Multileg Order Modification
Request)
AD
=
.PP
Trade Capture Report Request
AE
=
.PP
Trade Capture Report
AF
=
.PP
Order Mass Status Request
AG
=
.PP
Quote Request Reject
AH
=
.PP
RFQ Request
AI
=
.PP
Quote Status Report
AJ
=
.PP
Quote Response
AK
=
.PP
Confirmation
AL
=
.PP
Position Maintenance Request
AM
=
.PP
Position Maintenance Report
AN
=
.PP
Request For Positions
AO
=
.PP
Request For Positions Ack
AP
=
.PP
Position Report
AQ
=
.PP
Trade Capture Report Request Ack
AR
=
.PP
Trade Capture Report Ack
AS
=
.PP
Allocation Report (a.k.a. Allocation Claim)
AT
=
.PP
Allocation Report Ack (a.k.a. Allocation Claim Ack)
AU
=
.PP
Confirmation Ack (a.k.a. Affirmation)
AV
=
.PP
Settlement Instruction Request
AW
=
.PP
Assignment Report
AX
=
.PP
Collateral Request
AY
=
.PP
Collateral Assignment
AZ
=
.PP
Collateral Response
BA
=
.PP
Collateral Report
BB
=
.PP
Collateral Inquiry
BC
=
.PP
Network Counterparty System Status Request
BD
=
.PP
Network Counterparty System Status Response
BE
=
.PP
User Request
BF
=
.PP
User Response
BG
=
.PP
Collateral Inquiry Ack
BH
=
.PP
Confirmation Request
BI
=
.PP
Trading Session List Request
BJ
=
.PP
Trading Session List
BK
=
.PP
Security List Update Report
BL
=
.PP
Adjusted Position Report
BM
=
.PP
Allocation Instruction Alert
BN
=
.PP
Execution Acknowledgement
BO
=
.PP
Contrary Intention Report
BP
=
.PP
Security Definition Update Report
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=MsgType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
