.TH FIX.5.0 "" "" "Tag #370"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
370 (tag370.html)
OnBehalfOfSendingTime (tag370.html)
UTCTimestamp
.PP
Used when a message is sent via a \[aq]hub\[aq] or \[aq]service
bureau\[aq]. If A sends to Q (the hub) who then sends to B via a
separate FIX session, then when Q sends to B the value of this
field should represent the SendingTime on the message A sent to Q.
(always expressed in UTC (Universal Time Coordinated, also known as
\[aq]GMT\[aq])
FIX.4.3
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
