.TH FIX.5.0 "" "" "Tag #373"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
373 (tag373.html)
SessionRejectReason (tag373.html)
int
.PP
Code to identify reason for a session-level Reject message.
0
=
.PP
Invalid Tag Number
1
=
.PP
Required Tag Missing
2
=
.PP
Tag not defined for this message type
3
=
.PP
Undefined tag
4
=
.PP
Tag specified without a value
5
=
.PP
Value is incorrect (out of range) for this tag
6
=
.PP
Incorrect data format for value
7
=
.PP
Decryption problem
8
=
.PP
Signature problem
9
=
.PP
CompID problem
10
=
.PP
SendingTime Accuracy Problem
11
=
.PP
Invalid MsgType
12
=
.PP
XML Validation Error
13
=
.PP
Tag appears more than once
14
=
.PP
Tag specified out of required order
15
=
.PP
Repeating group fields out of order
16
=
.PP
Incorrect NumInGroup count for repeating group
17
=
.PP
Non "Data" value includes field delimiter (<SOH> character)
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[Reject (body_5251.html?find=SessionRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
