.TH FIX.5.0 "" "" "Tag #379"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
379 (tag379.html)
BusinessRejectRefID (tag379.html)
\@BizRejRefID
String
.PP
The value of the business-level "ID" field on the message being
referenced.
.PP
   *   *   *   *   *
Used in messages:
[BusinessMessageReject (body_5251106.html?find=BusinessRejectRefID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
