.TH FIX.5.0 "" "" "Tag #389"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
389 (tag389.html)
DiscretionOffsetValue (tag389.html)
\@OfstValu
float
.PP
Amount (signed) added to the "related to" price specified via
DiscretionInst (388), in the context of DiscretionOffsetType (842)
.PP
(Prior to FIX 4.4 this field was of type PriceOffset)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DiscretionInstructions (body_49484849.html?find=DiscretionOffsetValue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
