.TH FIX.5.0 "" "" "Tag #39"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
39 (tag39.html)
OrdStatus (tag39.html)
\@OrdStat
char
.PP
Identifies current status of order. *** SOME VALUES HAVE BEEN
REPLACED - See "Replaced Features and Supported Approach" *** (see
Volume : "Glossary" for value definitions)
0
=
.PP
New
1
=
.PP
Partially filled
2
=
.PP
Filled
3
=
.PP
Done for day
4
=
.PP
Canceled
5
=
.PP
Replaced (No longer used)
6
=
.PP
Pending Cancel (i.e. result of Order Cancel Request)
7
=
.PP
Stopped
8
=
.PP
Rejected
9
=
.PP
Suspended
A
=
.PP
Pending New
B
=
.PP
Calculated
C
=
.PP
Expired
D
=
.PP
Accepted for Bidding
E
=
.PP
Pending Replace (i.e. result of Order Cancel/Replace Request)
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=OrdStatus)]
[OrderCancelReject (body_494857.html?find=OrdStatus)]
[TradeCaptureReport (body_54526569.html?find=OrdStatus)]
[TradeCaptureReportAck (body_55556582.html?find=OrdStatus)]
.PP
   *   *   *   *   *
Used in components:
[OrdListStatGrp (body_50485155.html?find=OrdStatus)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
