.TH FIX.5.0 "" "" "Tag #392"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
392 (tag392.html)
ListName (tag392.html)
\@ListName
String
.PP
Descriptive name for list order.
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=ListName)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
