.TH FIX.5.0 "" "" "Tag #396"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
396 (tag396.html)
SideValue1 (tag396.html)
\@SideValu1
Amt
.PP
Amounts in currency
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=SideValue1)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
