.TH FIX.5.0 "" "" "Tag #401"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
401 (tag401.html)
SideValueInd (tag401.html)
\@SideValuInd
int
.PP
Code to identify which "SideValue" the value refers to. SideValue1
and SideValue2 are used as opposed to Buy or Sell so that the
basket can be quoted either way as Buy or Sell.
1
=
.PP
Side Value 1
2
=
.PP
Side Value 2
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[BidDescReqGrp (body_50484854.html?find=SideValueInd)]
[ListOrdGrp (body_50485148.html?find=SideValueInd)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
