.TH FIX.5.0 "" "" "Tag #409"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
409 (tag409.html)
LiquidityIndType (tag409.html)
\@LqdtyIndTyp
int
.PP
Code to identify the type of liquidity indicator.
1
=
.PP
5-day moving average
2
=
.PP
20-day moving average
3
=
.PP
Normal market size
4
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=LiquidityIndType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
