.TH FIX.5.0 "" "" "Tag #420"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
420 (tag420.html)
NoBidComponents (tag420.html)
NumInGroup
.PP
Indicates the number of list entries.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[BidCompReqGrp (body_50484852.html?find=NoBidComponents)]
[BidCompRspGrp (body_50484853.html?find=NoBidComponents)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
