.TH FIX.5.0 "" "" "Tag #422"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
422 (tag422.html)
TotNoStrikes (tag422.html)
\@TotNoStrks
int
.PP
Total number of strike price entries across all messages. Should be
the sum of all NoStrikes (428) in each message that has repeating
strike price entries related to the same ListID (66). Used to
support fragmentation.
.PP
   *   *   *   *   *
Used in messages:
[ListStrikePrice (body_5254109.html?find=TotNoStrikes)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
