.TH FIX.5.0 "" "" "Tag #423"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
423 (tag423.html)
PriceType (tag423.html)
\@PxTyp
int
.PP
Code to represent the price type.
.PP
(For Financing transactions PriceType implies the "repo type" –
Fixed or Floating – 9 (Yield) or 6 (Spread) respectively - and
Price (44) gives the corresponding "repo rate".
.PP
See Volume : "Glossary" for further value definitions)
1
=
.PP
Percentage (i.e. percent of par) (often called "dollar price" for
fixed income)
2
=
.PP
Per unit (i.e. per share or contract)
3
=
.PP
Fixed amount (absolute value)
4
=
.PP
Discount - percentage points below par
5
=
.PP
Premium - percentage points over par
6
=
.PP
Spread (basis points spread)
7
=
.PP
TED Price
8
=
.PP
TED Yield
9
=
.PP
Yield
10
=
.PP
Fixed cabinet trade price (primarily for listed futures and
options)
11
=
.PP
Variable cabinet trade price (primarily for listed futures and
options)
13
=
.PP
Product ticks in halfs
14
=
.PP
Product ticks in fourths
15
=
.PP
Product ticks in eights
16
=
.PP
Product ticks in sixteenths
17
=
.PP
Product ticks in thirty-seconds
18
=
.PP
Product ticks in sixty-forths
19
=
.PP
Product ticks in one-twenty-eights
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=PriceType)]
[AllocationInstructionAlert (body_57566677.html?find=PriceType)]
[AllocationReport (body_55566583.html?find=PriceType)]
[CollateralAssignment (body_56526589.html?find=PriceType)]
[CollateralInquiry (body_56556666.html?find=PriceType)]
[CollateralReport (body_56546665.html?find=PriceType)]
[CollateralRequest (body_56516588.html?find=PriceType)]
[CollateralResponse (body_56536590.html?find=PriceType)]
[Confirmation (body_55486575.html?find=PriceType)]
[CrossOrderCancelReplaceRequest (body_5351116.html?find=PriceType)]
[ExecutionAcknowledgement (body_57576678.html?find=PriceType)]
[ExecutionReport (body_5756.html?find=PriceType)]
[IOI (body_5554.html?find=PriceType)]
[MultilegOrderCancelReplace (body_54506567.html?find=PriceType)]
[NewOrderCross (body_5350115.html?find=PriceType)]
[NewOrderMultileg (body_54496566.html?find=PriceType)]
[NewOrderSingle (body_495268.html?find=PriceType)]
[OrderCancelReplaceRequest (body_495571.html?find=PriceType)]
[PositionReport (body_55536580.html?find=PriceType)]
[Quote (body_505583.html?find=PriceType)]
[QuoteResponse (body_54576574.html?find=PriceType)]
[QuoteStatusReport (body_54566573.html?find=PriceType)]
[TradeCaptureReport (body_54526569.html?find=PriceType)]
[TradeCaptureReportAck (body_55556582.html?find=PriceType)]
.PP
   *   *   *   *   *
Used in components:
[BidCompRspGrp (body_50484853.html?find=PriceType)]
[ListOrdGrp (body_50485148.html?find=PriceType)]
[QuotReqGrp (body_50485253.html?find=PriceType)]
[QuotReqRjctGrp (body_50485255.html?find=PriceType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
