.TH FIX.5.0 "" "" "Tag #43"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
43 (tag43.html)
PossDupFlag (tag43.html)
\@PosDup
Boolean
.PP
Indicates possible retransmission of message with this sequence
number
N
=
.PP
Original transmission
Y
=
.PP
Possible duplicate
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=PossDupFlag)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
