.TH FIX.5.0 "" "" "Tag #433"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
433 (tag433.html)
ListExecInstType (tag433.html)
\@ListExecInstTyp
char
.PP
Identifies the type of ListExecInst (69).
1
=
.PP
Immediate
2
=
.PP
Wait for Execut Instruction (i.e. a List Execut message or phone
call before proceeding with execution of the list)
3
=
.PP
Exchange/switch CIV order - Sell driven
4
=
.PP
Exchange/switch CIV order - Buy driven, cash top-up (i.e.
additional cash will be provided to fulfill the order)
5
=
.PP
Exchange/switch CIV order - Buy driven, cash withdraw (i.e.
additional cash will not be provided to fulfill the order)
.PP
   *   *   *   *   *
Used in messages:
[NewOrderList (body_495369.html?find=ListExecInstType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
