.TH FIX.5.0 "" "" "Tag #445"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
445 (tag445.html)
EncodedListStatusTextLen (tag445.html)
\@EncListStatTextLen
Length
.PP
Byte length of encoded (non-ASCII characters) EncodedListStatusText
(446) field.
.PP
   *   *   *   *   *
Used in messages:
[ListStatus (body_505178.html?find=EncodedListStatusTextLen)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
