.TH FIX.5.0 "" "" "Tag #451"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
451 (tag451.html)
NetChgPrevDay (tag451.html)
\@NetChgPrevDay
PriceOffset
.PP
Net change from previous day’s closing price vs. last traded price.
.PP
   *   *   *   *   *
Used in messages:
[MarketDataSnapshotFullRefresh (body_514887.html?find=NetChgPrevDay)]
.PP
   *   *   *   *   *
Used in components:
[MDIncGrp (body_50485150.html?find=NetChgPrevDay)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
