.TH FIX.5.0 "" "" "Tag #452"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
452 (tag452.html)
PartyRole (tag452.html)
\@R
int
.PP
Identifies the type or role of the PartyID (448) specified.
.PP
See "Appendix 6-G – Use of <Parties> Component Block"
.PP
(see Volume : "Glossary" for value definitions)
1
=
.PP
Executing Firm (formerly FIX 4.2 ExecBroker)
2
=
.PP
Broker of Credit (formerly FIX 4.2 BrokerOfCredit)
3
=
.PP
Client ID (formerly FIX 4.2 ClientID)
4
=
.PP
Clearing Firm (formerly FIX 4.2 ClearingFirm)
5
=
.PP
Investor ID
6
=
.PP
Introducing Firm
7
=
.PP
Entering Firm
8
=
.PP
Locate / Lending Firm (for short-sales)
9
=
.PP
Fund Manager Client ID (for CIV)
10
=
.PP
Settlement Location (formerly FIX 4.2 SettlLocation)
11
=
.PP
Order Origination Trader (associated with Order Origination Firm -
i.e. trader who initiates/submits the order)
12
=
.PP
Executing Trader (associated with Executing Firm - actually
executes)
13
=
.PP
Order Origination Firm (e.g. buy-side firm)
14
=
.PP
Giveup Clearing Firm (firm to which trade is given up)
15
=
.PP
Correspondant Clearing Firm
16
=
.PP
Executing System
17
=
.PP
Contra Firm
18
=
.PP
Contra Clearing Firm
19
=
.PP
Sponsoring Firm
20
=
.PP
Underlying Contra Firm
21
=
.PP
Clearing Organization
22
=
.PP
Exchange
24
=
.PP
Customer Account
25
=
.PP
Correspondent Clearing Organization
26
=
.PP
Correspondent Broker
27
=
.PP
Buyer/Seller (Receiver/Deliverer)
28
=
.PP
Custodian
29
=
.PP
Intermediary
30
=
.PP
Agent
31
=
.PP
Sub-custodian
32
=
.PP
Beneficiary
33
=
.PP
Interested party
34
=
.PP
Regulatory body
35
=
.PP
Liquidity provider
36
=
.PP
Entering trader
37
=
.PP
Contra trader
38
=
.PP
Position account
39
=
.PP
Contra Investor ID
40
=
.PP
Transfer to Firm
41
=
.PP
Contra Position Account
42
=
.PP
Contra Exchange
43
=
.PP
Internal Carry Account
44
=
.PP
Order Entry Operator ID
45
=
.PP
Secondary Account Number
46
=
.PP
Foriegn Firm
47
=
.PP
Third Party Allocation Firm
48
=
.PP
Claiming Account
49
=
.PP
Asset Manager
50
=
.PP
Pledgor Account
51
=
.PP
Pledgee Account
52
=
.PP
Large Trader Reportable Account
53
=
.PP
Trader mnemonic
54
=
.PP
Sender Location
55
=
.PP
Session ID
56
=
.PP
Acceptable Counterparty
57
=
.PP
Unacceptable Counterparty
58
=
.PP
Entering Unit
59
=
.PP
Executing Unit
60
=
.PP
Introducing Broker
61
=
.PP
Quote originator
62
=
.PP
Report originator
63
=
.PP
Systematic internaliser (SI)
64
=
.PP
Multilateral Trading Facility (MTF)
65
=
.PP
Regulated Market (RM)
66
=
.PP
Market Maker
67
=
.PP
Investment Firm
68
=
.PP
Host Competent Authority (Host CA)
69
=
.PP
Home Competent Authority (Home CA)
70
=
.PP
Competent Authority of the most relevant market in terms of
liquidity (CAL)
71
=
.PP
Competent Authority of the Transaction (Execution) Venue (CATV)
72
=
.PP
Reporting intermediary (medium/vendor via which report has been
published)
73
=
.PP
Execution Venue
74
=
.PP
Market data entry originator
75
=
.PP
Location ID
76
=
.PP
Desk ID
77
=
.PP
Market data market
78
=
.PP
Allocation Entity
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Parties (body_49484950.html?find=PartyRole)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
