.TH FIX.5.0 "" "" "Tag #457"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
457 (tag457.html)
NoUnderlyingSecurityAltID (tag457.html)
NumInGroup
.PP
Number of UnderlyingSecurityAltID (458) entries.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UndSecAltIDGrp (body_50485551.html?find=NoUnderlyingSecurityAltID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
