.TH FIX.5.0 "" "" "Tag #458"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
458 (tag458.html)
UnderlyingSecurityAltID (tag458.html)
\@AltID
String
.PP
Alternate Security identifier value for this underlying security of
UnderlyingSecurityAltIDSource (459) type (e.g. CUSIP, SEDOL, ISIN,
etc). Requires UnderlyingSecurityAltIDSource.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UndSecAltIDGrp (body_50485551.html?find=UnderlyingSecurityAltID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
