.TH FIX.5.0 "" "" "Tag #469"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
469 (tag469.html)
RoundingModulus (tag469.html)
\@RndMod
float
.PP
For CIV - a float value indicating the value to which rounding is
required.
.PP
i.e. 0 means round to a multiple of 0 units/shares; 0.5 means round
to a multiple of 0.5 units/shares.
.PP
The default, if RoundingDirection (468) is specified without
RoundingModulus, is to round to a whole unit/share.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[OrderQtyData (body_49484949.html?find=RoundingModulus)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
