.TH FIX.5.0 "" "" "Tag #470"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
470 (tag470.html)
CountryOfIssue (tag470.html)
\@IssuCtry
Country
.PP
ISO Country code of instrument issue (e.g. the country portion
typically used in ISIN). Can be used in conjunction with non-ISIN
SecurityID (48) (e.g. CUSIP for Municipal Bonds without ISIN) to
provide uniqueness.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=CountryOfIssue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
