.TH FIX.5.0 "" "" "Tag #476"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
476 (tag476.html)
PaymentRef (tag476.html)
\@PmtRef
String
.PP
"Settlement Payment Reference" – A free format Payment reference to
assist with reconciliation, e.g. a Client and/or Order ID number.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlInstGrp (body_50485355.html?find=PaymentRef)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
