.TH FIX.5.0 "" "" "Tag #478"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
478 (tag478.html)
CashDistribCurr (tag478.html)
\@CshDistribCurr
Currency
.PP
Specifies currency to be use for Cash Distributions– see "Appendix
6-A; Valid Currency Codes".
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RgstDistInstGrp (body_50485350.html?find=CashDistribCurr)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
