.TH FIX.5.0 "" "" "Tag #479"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
479 (tag479.html)
CommCurrency (tag479.html)
\@Ccy
Currency
.PP
Specifies currency to be use for Commission (12) if the Commission
currency is different from the Deal Currency - see "Appendix 6-A;
Valid Currency Codes".
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CommissionData (body_49484848.html?find=CommCurrency)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
