.TH FIX.5.0 "" "" "Tag #483"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
483 (tag483.html)
TransBkdTime (tag483.html)
\@TransBkdTm
UTCTimestamp
.PP
For CIV A date and time stamp to indicate the time a CIV order was
booked by the fund manager.
.PP
For derivatives a date and time stamp to indicate when this order
was booked with the agent prior to submission to the VMU. Indicates
the time at which the order was finalized between the buyer and
seller prior to submission.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=TransBkdTime)]
[ExecutionReport (body_5756.html?find=TransBkdTime)]
[NewOrderCross (body_5350115.html?find=TransBkdTime)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=TransBkdTime)]
[TrdCapRptSideGrp (body_50485449.html?find=TransBkdTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
