.TH FIX.5.0 "" "" "Tag #487"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
487 (tag487.html)
TradeReportTransType (tag487.html)
\@TransTyp
int
.PP
Identifies Trade Report message transaction type
.PP
(Prior to FIX 4.4 this field was of type char)
0
=
.PP
New
1
=
.PP
Cancel
2
=
.PP
Replace
3
=
.PP
Release
4
=
.PP
Reverse
5
=
.PP
Cancel Due To Back Out of Trade
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TradeReportTransType)]
[TradeCaptureReportAck (body_55556582.html?find=TradeReportTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
