.TH FIX.5.0 "" "" "Tag #491"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
491 (tag491.html)
CardIssNum (tag491.html)
\@CardIssNum
String
.PP
The issue number of the payment card as specified on the card being
used for payment. This is only applicable to certain types of card.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlInstGrp (body_50485355.html?find=CardIssNum)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
