.TH FIX.5.0 "" "" "Tag #494"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
494 (tag494.html)
Designation (tag494.html)
\@Designation
String
.PP
Free format text defining the designation to be associated with a
holding on the register. Used to identify assets of a specific
underlying investor using a common registration, e.g. a broker’s
nominee or street name.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=Designation)]
[ExecutionReport (body_5756.html?find=Designation)]
[MultilegOrderCancelReplace (body_54506567.html?find=Designation)]
[NewOrderCross (body_5350115.html?find=Designation)]
[NewOrderMultileg (body_54496566.html?find=Designation)]
[NewOrderSingle (body_495268.html?find=Designation)]
[OrderCancelReplaceRequest (body_495571.html?find=Designation)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=Designation)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
