.TH FIX.5.0 "" "" "Tag #496"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
496 (tag496.html)
RegistRejReasonText (tag496.html)
\@RejRsnTxt
String
.PP
Text indicating reason(s) why a Registration Instruction has been
rejected.
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructionsResponse (body_5257112.html?find=RegistRejReasonText)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
