.TH FIX.5.0 "" "" "Tag #5"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
5 (tag5.html)
AdvTransType (tag5.html)
\@AdvTransTyp
String
.PP
Identifies advertisement message transaction type
N
=
.PP
New
C
=
.PP
Cancel
R
=
.PP
Replace
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=AdvTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
