.TH FIX.5.0 "" "" "Tag #504"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
504 (tag504.html)
PaymentDate (tag504.html)
\@PmtDt
LocalMktDate
.PP
The date written on a cheque or date payment should be submitted to
the relevant clearing system.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlInstGrp (body_50485355.html?find=PaymentDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
