.TH FIX.5.0 "" "" "Tag #506"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
506 (tag506.html)
RegistStatus (tag506.html)
\@RegStat
char
.PP
Registration status as returned by the broker or (for CIV) the fund
manager:
A
=
.PP
Accepted
R
=
.PP
Rejected
H
=
.PP
Held
N
=
.PP
Reminder - i.e. Registration Instructions are still outstanding
.PP
   *   *   *   *   *
Used in messages:
[PositionReport (body_55536580.html?find=RegistStatus)]
[RegistrationInstructionsResponse (body_5257112.html?find=RegistStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
