.TH FIX.5.0 "" "" "Tag #509"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
509 (tag509.html)
RegistDtls (tag509.html)
\@Dtls
String
.PP
Set of Registration name and address details, possibly including
phone, fax etc.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RgstDtlsGrp (body_50485351.html?find=RegistDtls)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
