.TH FIX.5.0 "" "" "Tag #514"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
514 (tag514.html)
RegistTransType (tag514.html)
\@TransTyp
char
.PP
Identifies Registration Instructions transaction type
0
=
.PP
New
2
=
.PP
Cancel
1
=
.PP
Replace
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=RegistTransType)]
[RegistrationInstructionsResponse (body_5257112.html?find=RegistTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
