.TH FIX.5.0 "" "" "Tag #519"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
519 (tag519.html)
ContAmtType (tag519.html)
\@ContAmtTyp
int
.PP
Type of ContAmtValue (520).
.PP
NOTE That Commission Amount / % in Contract Amounts is the
commission actually charged, rather than the commission
instructions given in Fields 2/3.
.PP
For UK
1
=
.PP
Commission amount (actual)
2
=
.PP
Commission percent (actual)
3
=
.PP
Initial Charge Amount
4
=
.PP
Initial Charge Percent
5
=
.PP
Discount Amount
6
=
.PP
Discount Percent
7
=
.PP
Dilution Levy Amount
8
=
.PP
Dilution Levy Percent
9
=
.PP
Exit Charge Amount
10
=
.PP
Exit Charge Percent
11
=
.PP
Fund-Based Renewal Commission Percent (a.k.a. Trail commission)
12
=
.PP
Projected Fund Value (i.e. for investments intended to realise or
exceed a specific future value)
13
=
.PP
Fund-Based Renewal Commission Amount (based on Order value)
14
=
.PP
Fund-Based Renewal Commission Amount (based on Projected Fund
value)
15
=
.PP
Net Settlement Amount
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ContAmtGrp (body_50484949.html?find=ContAmtType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
