.TH FIX.5.0 "" "" "Tag #523"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
523 (tag523.html)
PartySubID (tag523.html)
\@ID
String
.PP
Sub-identifier (e.g. Clearing Account for PartyRole (452)=Clearing
Firm, Locate ID # for PartyRole=Locate/Lending Firm, etc). Not
required when using PartyID (448), PartyIDSource (447), and
PartyRole.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PtysSubGrp (body_50485555.html?find=PartySubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
