.TH FIX.5.0 "" "" "Tag #526"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
526 (tag526.html)
SecondaryClOrdID (tag526.html)
\@ClOrdID2
String
.PP
Assigned by the party which originates the order. Can be used to
provide the ClOrdID (11) used by an exchange or executing system.
.PP
   *   *   *   *   *
Used in messages:
[CollateralAssignment (body_56526589.html?find=SecondaryClOrdID)]
[CollateralInquiry (body_56556666.html?find=SecondaryClOrdID)]
[CollateralInquiryAck (body_57506671.html?find=SecondaryClOrdID)]
[CollateralReport (body_56546665.html?find=SecondaryClOrdID)]
[CollateralRequest (body_56516588.html?find=SecondaryClOrdID)]
[CollateralResponse (body_56536590.html?find=SecondaryClOrdID)]
[ExecutionReport (body_5756.html?find=SecondaryClOrdID)]
[MultilegOrderCancelReplace (body_54506567.html?find=SecondaryClOrdID)]
[NewOrderMultileg (body_54496566.html?find=SecondaryClOrdID)]
[NewOrderSingle (body_495268.html?find=SecondaryClOrdID)]
[OrderCancelReject (body_494857.html?find=SecondaryClOrdID)]
[OrderCancelReplaceRequest (body_495571.html?find=SecondaryClOrdID)]
[OrderCancelRequest (body_495470.html?find=SecondaryClOrdID)]
[OrderMassCancelReport (body_5349114.html?find=SecondaryClOrdID)]
[OrderMassCancelRequest (body_5348113.html?find=SecondaryClOrdID)]
[OrderStatusRequest (body_495672.html?find=SecondaryClOrdID)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=SecondaryClOrdID)]
[OrdAllocGrp (body_50485154.html?find=SecondaryClOrdID)]
[OrdListStatGrp (body_50485155.html?find=SecondaryClOrdID)]
[SideCrossOrdCxlGrp (body_50485356.html?find=SecondaryClOrdID)]
[SideCrossOrdModGrp (body_50485357.html?find=SecondaryClOrdID)]
[TrdCapRptAckSideGrp (body_50485752.html?find=SecondaryClOrdID)]
[TrdCapRptSideGrp (body_50485449.html?find=SecondaryClOrdID)]
[UndInstrmtStrkPxGrp (body_50485455.html?find=SecondaryClOrdID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
