.TH FIX.5.0 "" "" "Tag #531"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
531 (tag531.html)
MassCancelResponse (tag531.html)
\@MassCxlRsp
char
.PP
Specifies the action taken by counterparty order handling system as
a result of the Order Mass Cancel Request
0
=
.PP
Cancel Request Rejected - See MassCancelRejectReason (532)
1
=
.PP
Cancel orders for a security
2
=
.PP
Cancel orders for an Underlying Security
3
=
.PP
Cancel orders for a Product
4
=
.PP
Cancel orders for a CFICode
5
=
.PP
Cancel orders for a SecurityType
6
=
.PP
Cancel orders for a trading session
7
=
.PP
Cancel All Orders
.PP
   *   *   *   *   *
Used in messages:
[OrderMassCancelReport (body_5349114.html?find=MassCancelResponse)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
