.TH FIX.5.0 "" "" "Tag #532"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
532 (tag532.html)
MassCancelRejectReason (tag532.html)
\@MassCxlRejRsn
int
.PP
Reason Order Mass Cancel Request was rejected
0
=
.PP
Mass Cancel Not Supported
1
=
.PP
Invalid or Unknown Security
2
=
.PP
Invalid or Unkown Underlying security
3
=
.PP
Invalid or Unknown Product
4
=
.PP
Invalid or Unknown CFICode
5
=
.PP
Invalid or Unknown SecurityType
6
=
.PP
Invalid or Unknown Trading Session
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[OrderMassCancelReport (body_5349114.html?find=MassCancelRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
