.TH FIX.5.0 "" "" "Tag #533"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
533 (tag533.html)
TotalAffectedOrders (tag533.html)
\@TotAffctdOrds
int
.PP
Total number of orders affected by mass cancel request.
.PP
   *   *   *   *   *
Used in messages:
[OrderMassCancelReport (body_5349114.html?find=TotalAffectedOrders)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
