.TH FIX.5.0 "" "" "Tag #546"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
546 (tag546.html)
Scope (tag546.html)
\@Scope
MultipleCharValue
.PP
Specifies the market scope of the a market data.
1
=
.PP
Local Market (Exchange, ECN, ATS)
2
=
.PP
National
3
=
.PP
Global
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequest (body_505786.html?find=Scope)]
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=Scope)]
[MDIncGrp (body_50485150.html?find=Scope)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
