.TH FIX.5.0 "" "" "Tag #55"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
55 (tag55.html)
Symbol (tag55.html)
\@Sym
String
.PP
Ticker symbol. Common, "human understood" representation of the
security. SecurityID (48) value can be specified if no symbol
exists (e.g. non-exchange traded Collective Investment Vehicles)
.PP
Use "[N/A]" for products which do not have a symbol.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=Symbol)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
