.TH FIX.5.0 "" "" "Tag #551"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
551 (tag551.html)
OrigCrossID (tag551.html)
\@OrigCrssID
String
.PP
CrossID of the previous cross order (NOT the initial cross order of
the day) as assigned by the institution, used to identify the
previous cross order in Cross Cancel and Cross Cancel/Replace
Requests.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=OrigCrossID)]
[CrossOrderCancelRequest (body_5352117.html?find=OrigCrossID)]
[ExecutionReport (body_5756.html?find=OrigCrossID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
