.TH FIX.5.0 "" "" "Tag #552"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
552 (tag552.html)
NoSides (tag552.html)
NumInGroup
.PP
Number of Side repeating group instances.
1
=
.PP
One Side
2
=
.PP
Both Sides
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SideCrossOrdCxlGrp (body_50485356.html?find=NoSides)]
[SideCrossOrdModGrp (body_50485357.html?find=NoSides)]
[TrdCapRptAckSideGrp (body_50485752.html?find=NoSides)]
[TrdCapRptSideGrp (body_50485449.html?find=NoSides)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
