.TH FIX.5.0 "" "" "Tag #562"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
562 (tag562.html)
MinTradeVol (tag562.html)
\@MinTrdVol
Qty
.PP
The minimum trading volume for a security
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinition (body_5155100.html?find=MinTradeVol)]
[SecurityDefinitionUpdateReport (body_57536680.html?find=MinTradeVol)]
.PP
   *   *   *   *   *
Used in components:
[SecListGrp (body_50485353.html?find=MinTradeVol)]
[SecLstUpdRelSymGrp (body_50485655.html?find=MinTradeVol)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
