.TH FIX.5.0 "" "" "Tag #564"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
564 (tag564.html)
LegPositionEffect (tag564.html)
\@PosEfct
char
.PP
PositionEffect for leg of a multileg
.PP
See PositionEffect (77) field for description
C
=
.PP
Close
F
=
.PP
FIFO
O
=
.PP
Open
R
=
.PP
Rolled
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegPositionEffect)]
[LegOrdGrp (body_50485053.html?find=LegPositionEffect)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegPositionEffect)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
