.TH FIX.5.0 "" "" "Tag #567"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
567 (tag567.html)
TradSesStatusRejReason (tag567.html)
\@StatRejRsn
int
.PP
Indicates the reason a Trading Session Status Request was rejected.
1
=
.PP
Unknown or invalid TradingSessionID
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[TradingSessionStatus (body_5249104.html?find=TradSesStatusRejReason)]
.PP
   *   *   *   *   *
Used in components:
[TrdSessLstGrp (body_50485757.html?find=TradSesStatusRejReason)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
