.TH FIX.5.0 "" "" "Tag #571"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
571 (tag571.html)
TradeReportID (tag571.html)
\@RptID
String
.PP
Unique identifier of trade capture report
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TradeReportID)]
[TradeCaptureReportAck (body_55556582.html?find=TradeReportID)]
[TradeCaptureReportRequest (body_54516568.html?find=TradeReportID)]
.PP
   *   *   *   *   *
Used in components:
[TrdCollGrp (body_50485450.html?find=TradeReportID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
