.TH FIX.5.0 "" "" "Tag #575"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
575 (tag575.html)
OddLot (tag575.html)
\@OddLot
Boolean
.PP
This trade is to be treated as an odd lot
.PP
If this field is not specified, the default will be "N"
FIX.5.0
N
=
.PP
Treat as round lot (default)
Y
=
.PP
Treat as odd lot
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=OddLot)]
[TrdCapRptSideGrp (body_50485449.html?find=OddLot)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
