.TH FIX.5.0 "" "" "Tag #581"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
581 (tag581.html)
AccountType (tag581.html)
\@AcctTyp
int
.PP
Type of account associated with an order
1
=
.PP
Account is carried on customer side of the books
2
=
.PP
Account is carried on non-customer side of books
3
=
.PP
House Trader
4
=
.PP
Floor Trader
6
=
.PP
Account is carried on non-customer side of books and is cross
margined
7
=
.PP
Account is house trader and is cross margined
8
=
.PP
Joint back office account (JBO)
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=AccountType)]
[CollateralAssignment (body_56526589.html?find=AccountType)]
[CollateralInquiry (body_56556666.html?find=AccountType)]
[CollateralInquiryAck (body_57506671.html?find=AccountType)]
[CollateralReport (body_56546665.html?find=AccountType)]
[CollateralRequest (body_56516588.html?find=AccountType)]
[CollateralResponse (body_56536590.html?find=AccountType)]
[ExecutionReport (body_5756.html?find=AccountType)]
[MassQuote (body_5250105.html?find=AccountType)]
[MassQuoteAcknowledgement (body_515398.html?find=AccountType)]
[MultilegOrderCancelReplace (body_54506567.html?find=AccountType)]
[NewOrderMultileg (body_54496566.html?find=AccountType)]
[NewOrderSingle (body_495268.html?find=AccountType)]
[OrderCancelReject (body_494857.html?find=AccountType)]
[OrderCancelReplaceRequest (body_495571.html?find=AccountType)]
[OrderCancelRequest (body_495470.html?find=AccountType)]
[PositionMaintenanceReport (body_55506577.html?find=AccountType)]
[PositionMaintenanceRequest (body_55496576.html?find=AccountType)]
[PositionReport (body_55536580.html?find=AccountType)]
[Quote (body_505583.html?find=AccountType)]
[QuoteCancel (body_515190.html?find=AccountType)]
[QuoteResponse (body_54576574.html?find=AccountType)]
[QuoteStatusReport (body_54566573.html?find=AccountType)]
[QuoteStatusRequest (body_515297.html?find=AccountType)]
[RequestForPositions (body_55516578.html?find=AccountType)]
[RequestForPositionsAck (body_55526579.html?find=AccountType)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=AccountType)]
[QuotReqGrp (body_50485253.html?find=AccountType)]
[QuotReqRjctGrp (body_50485255.html?find=AccountType)]
[SideCrossOrdModGrp (body_50485357.html?find=AccountType)]
[TrdCapRptAckSideGrp (body_50485752.html?find=AccountType)]
[TrdCapRptSideGrp (body_50485449.html?find=AccountType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
