.TH FIX.5.0 "" "" "Tag #598"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
598 (tag598.html)
LegLocaleOfIssue (tag598.html)
\@Lcl
String
.PP
Multileg instrument\[aq]s individual leg security’s LocaleOfIssue.
.PP
See LocaleOfIssue (472) field for description
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegLocaleOfIssue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
