.TH FIX.5.0 "" "" "Tag #607"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
607 (tag607.html)
LegProduct (tag607.html)
\@Prod
int
.PP
Multileg instrument\[aq]s individual security’s Product.
.PP
See Product (460) field for description
1
=
.PP
AGENCY
2
=
.PP
COMMODITY
3
=
.PP
CORPORATE
4
=
.PP
CURRENCY
5
=
.PP
EQUITY
6
=
.PP
GOVERNMENT
7
=
.PP
INDEX
8
=
.PP
LOAN
9
=
.PP
MONEYMARKET
10
=
.PP
MORTGAGE
11
=
.PP
MUNICIPAL
12
=
.PP
OTHER
13
=
.PP
FINANCING
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegProduct)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
