.TH FIX.5.0 "" "" "Tag #624"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
624 (tag624.html)
LegSide (tag624.html)
\@Side
char
.PP
The side of this individual leg (multileg security).
.PP
See Side (54) field for description and values
1
=
.PP
Buy
2
=
.PP
Sell
3
=
.PP
Buy minus
4
=
.PP
Sell plus
5
=
.PP
Sell short
6
=
.PP
Sell short exempt
7
=
.PP
Undisclosed (valid for IOI and List Order messages only)
8
=
.PP
Cross (orders where counterparty is an exchange, valid for all
messages except IOIs)
9
=
.PP
Cross short
A
=
.PP
Cross short exxmpt
B
=
.PP
"As Defined" (for use with multileg instruments)
C
=
.PP
"Opposite" (for use with multileg instruments)
D
=
.PP
Subscribe (e.g. CIV)
E
=
.PP
Redeem (e.g. CIV)
F
=
.PP
Lend (FINANCING - identifies direction of collateral)
G
=
.PP
Borrow (FINANCING - identifies direction of collateral)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegSide)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
