.TH FIX.5.0 "" "" "Tag #625"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
625 (tag625.html)
TradingSessionSubID (tag625.html)
\@SesSub
String
.PP
Optional market assigned sub identifier for a trading session.
Usage is determined by market or counterparties.
.PP
Used by US based futures markets to identify exchange specific
execution time bracket codes as required by US market regulations.
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=TradingSessionSubID)]
[AllocationInstruction (body_495774.html?find=TradingSessionSubID)]
[AllocationInstructionAlert (body_57566677.html?find=TradingSessionSubID)]
[AllocationReport (body_55566583.html?find=TradingSessionSubID)]
[CollateralAssignment (body_56526589.html?find=TradingSessionSubID)]
[CollateralInquiry (body_56556666.html?find=TradingSessionSubID)]
[CollateralInquiryAck (body_57506671.html?find=TradingSessionSubID)]
[CollateralReport (body_56546665.html?find=TradingSessionSubID)]
[CollateralRequest (body_56516588.html?find=TradingSessionSubID)]
[DerivativeSecurityListRequest (body_5357122.html?find=TradingSessionSubID)]
[ExecutionReport (body_5756.html?find=TradingSessionSubID)]
[OrderMassCancelReport (body_5349114.html?find=TradingSessionSubID)]
[OrderMassCancelRequest (body_5348113.html?find=TradingSessionSubID)]
[OrderMassStatusRequest (body_54536570.html?find=TradingSessionSubID)]
[Quote (body_505583.html?find=TradingSessionSubID)]
[QuoteCancel (body_515190.html?find=TradingSessionSubID)]
[QuoteResponse (body_54576574.html?find=TradingSessionSubID)]
[QuoteStatusReport (body_54566573.html?find=TradingSessionSubID)]
[QuoteStatusRequest (body_515297.html?find=TradingSessionSubID)]
[SecurityDefinition (body_5155100.html?find=TradingSessionSubID)]
[SecurityDefinitionRequest (body_515499.html?find=TradingSessionSubID)]
[SecurityDefinitionUpdateReport (body_57536680.html?find=TradingSessionSubID)]
[SecurityListRequest (body_5355120.html?find=TradingSessionSubID)]
[SecurityStatus (body_5157102.html?find=TradingSessionSubID)]
[SecurityStatusRequest (body_5156101.html?find=TradingSessionSubID)]
[SecurityTypeRequest (body_5353118.html?find=TradingSessionSubID)]
[SecurityTypes (body_5354119.html?find=TradingSessionSubID)]
[TradeCaptureReportRequest (body_54516568.html?find=TradingSessionSubID)]
[TradingSessionListRequest (body_4948496673.html?find=TradingSessionSubID)]
[TradingSessionStatus (body_5249104.html?find=TradingSessionSubID)]
[TradingSessionStatusRequest (body_5248103.html?find=TradingSessionSubID)]
.PP
   *   *   *   *   *
Used in components:
[BidCompReqGrp (body_50484852.html?find=TradingSessionSubID)]
[BidCompRspGrp (body_50484853.html?find=TradingSessionSubID)]
[MDFullGrp (body_50485149.html?find=TradingSessionSubID)]
[MDIncGrp (body_50485150.html?find=TradingSessionSubID)]
[QuotEntryAckGrp (body_50485250.html?find=TradingSessionSubID)]
[QuotEntryGrp (body_50485251.html?find=TradingSessionSubID)]
[QuotReqGrp (body_50485253.html?find=TradingSessionSubID)]
[QuotReqRjctGrp (body_50485255.html?find=TradingSessionSubID)]
[RFQReqGrp (body_50485349.html?find=TradingSessionSubID)]
[RelSymDerivSecGrp (body_50485348.html?find=TradingSessionSubID)]
[SecListGrp (body_50485353.html?find=TradingSessionSubID)]
[SecLstUpdRelSymGrp (body_50485655.html?find=TradingSessionSubID)]
[TrdCapRptAckSideGrp (body_50485752.html?find=TradingSessionSubID)]
[TrdCapRptSideGrp (body_50485449.html?find=TradingSessionSubID)]
[TrdSessLstGrp (body_50485757.html?find=TradingSessionSubID)]
[TrdgSesGrp (body_50485452.html?find=TradingSessionSubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
