.TH FIX.5.0 "" "" "Tag #631"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
631 (tag631.html)
MidPx (tag631.html)
\@MidPx
Price
.PP
Mid price/rate
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=MidPx)]
[QuoteResponse (body_54576574.html?find=MidPx)]
[QuoteStatusReport (body_54566573.html?find=MidPx)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=MidPx)]
[QuotEntryGrp (body_50485251.html?find=MidPx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
