.TH FIX.5.0 "" "" "Tag #638"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
638 (tag638.html)
PriorityIndicator (tag638.html)
\@PriInd
int
.PP
Indicates if a Cancel/Replace has caused an order to lose book
priority.
0
=
.PP
Priority unchanged
1
=
.PP
Lost Priority as result of order change
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=PriorityIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
