.TH FIX.5.0 "" "" "Tag #640"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
640 (tag640.html)
Price2 (tag640.html)
\@Px2
Price
.PP
Price of the future part of a F/X swap order.
.PP
See Price (44) for description.
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[NewOrderSingle (body_495268.html?find=Price2)]
[OrderCancelReplaceRequest (body_495571.html?find=Price2)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=Price2)]
[QuotReqGrp (body_50485253.html?find=Price2)]
[QuotReqRjctGrp (body_50485255.html?find=Price2)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
