.TH FIX.5.0 "" "" "Tag #643"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
643 (tag643.html)
OfferForwardPoints2 (tag643.html)
\@OfrFwdPnts2
PriceOffset
.PP
Offer F/X forward points of the future portion of a F/X swap quote
added to spot rate. May be a negative value.
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=OfferForwardPoints2)]
[QuoteResponse (body_54576574.html?find=OfferForwardPoints2)]
[QuoteStatusReport (body_54566573.html?find=OfferForwardPoints2)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=OfferForwardPoints2)]
[QuotEntryGrp (body_50485251.html?find=OfferForwardPoints2)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
