.TH FIX.5.0 "" "" "Tag #650"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
650 (tag650.html)
LegalConfirm (tag650.html)
\@LegalCnfm
Boolean
.PP
Indicates that this message is to serve as the final and legal
confirmation.
N
=
.PP
Does not consitute a Legal Confirm
Y
=
.PP
Legal Confirm
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=LegalConfirm)]
[AllocationInstructionAlert (body_57566677.html?find=LegalConfirm)]
[AllocationReport (body_55566583.html?find=LegalConfirm)]
[Confirmation (body_55486575.html?find=LegalConfirm)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
