.TH FIX.5.0 "" "" "Tag #653"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
653 (tag653.html)
SecDefStatus (tag653.html)
int
.PP
State of a security definition request made to a market. Useful for
markets, such as derivatives markets, where market participants are
permitted to define instruments for subsequent trading
FIX.4.2
0
=
.PP
Pending Approval
1
=
.PP
Approved (Accepted)
2
=
.PP
Rejected
3
=
.PP
Unauthorized Request
4
=
.PP
Invalid Definition Request
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
