.TH FIX.5.0 "" "" "Tag #654"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
654 (tag654.html)
LegRefID (tag654.html)
\@RefID
String
.PP
Unique indicator for a specific leg.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegRefID)]
[LegOrdGrp (body_50485053.html?find=LegRefID)]
[LegQuotGrp (body_50485055.html?find=LegRefID)]
[QuotReqLegsGrp (body_50485254.html?find=LegRefID)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegRefID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
