.TH FIX.5.0 "" "" "Tag #657"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
657 (tag657.html)
SettlCurrOfferFxRate (tag657.html)
\@SettlCurrOfrFxRt
float
.PP
Foreign exchange rate used to compute the offer "SettlCurrAmt"
(119) from Currency (15) to SettlCurrency (120)
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=SettlCurrOfferFxRate)]
[QuoteResponse (body_54576574.html?find=SettlCurrOfferFxRate)]
[QuoteStatusReport (body_54566573.html?find=SettlCurrOfferFxRate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
