.TH FIX.5.0 "" "" "Tag #658"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
658 (tag658.html)
QuoteRequestRejectReason (tag658.html)
\@ReqRejRsn
int
.PP
Reason Quote was rejected:
1
=
.PP
Unknown Symbol (Security)
2
=
.PP
Exchange (Security) Closed
3
=
.PP
Quote Request Exceeds Limit
4
=
.PP
Too Late to enter
5
=
.PP
Invalid Price
6
=
.PP
Not Authorized To Request Quote
7
=
.PP
No Match For Inquiry
8
=
.PP
No Market For Instrument
9
=
.PP
No Inventory
10
=
.PP
Pass
11
=
.PP
Insufficient credit
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[QuoteRequestReject (body_54546571.html?find=QuoteRequestRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
