.TH FIX.5.0 "" "" "Tag #665"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
665 (tag665.html)
ConfirmStatus (tag665.html)
\@CnfmStat
int
.PP
Identifies the status of the Confirmation.
1
=
.PP
Received
2
=
.PP
Mismatched Account
3
=
.PP
Missing Settlement Instructions
4
=
.PP
Confirmed
5
=
.PP
Request Rejected
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=ConfirmStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
