.TH FIX.5.0 "" "" "Tag #675"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
675 (tag675.html)
LegSettlCurrency (tag675.html)
\@SettlCcy
Currency
.PP
Identifies settlement currency for the Leg.
.PP
See SettlCurrency (20) for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegSettlCurrency)]
[LegPreAllocGrp (body_50485054.html?find=LegSettlCurrency)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegSettlCurrency)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
