.TH FIX.5.0 "" "" "Tag #690"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
690 (tag690.html)
LegSwapType (tag690.html)
\@SwapTyp
int
.PP
For Fixed Income, used instead of LegQty (687) or LegOrderQty (685)
to requests the respondent to calculate the quantity based on the
quantity on the opposite side of the swap.
1
=
.PP
Par For Par
2
=
.PP
Modified Duration
4
=
.PP
Risk
5
=
.PP
Proceeds
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegSwapType)]
[InstrmtLegSecListGrp (body_50485049.html?find=LegSwapType)]
[LegOrdGrp (body_50485053.html?find=LegSwapType)]
[LegQuotGrp (body_50485055.html?find=LegSwapType)]
[LegQuotStatGrp (body_50485056.html?find=LegSwapType)]
[QuotReqLegsGrp (body_50485254.html?find=LegSwapType)]
[SecLstUpdRelSymsLegGrp (body_50485656.html?find=LegSwapType)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegSwapType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
