.TH FIX.5.0 "" "" "Tag #692"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
692 (tag692.html)
QuotePriceType (tag692.html)
\@QuotPxTyp
int
.PP
Code to represent price type requested in Quote.
.PP
If the Quote Request is for a Swap values 1-8 apply to all legs.
1
=
.PP
Percent (percent of par)
2
=
.PP
Per Share (e.g. cents per share)
3
=
.PP
Fixed Amount (absolute value)
4
=
.PP
Discount - percentage points below par
5
=
.PP
Premium - percentage points over par
6
=
.PP
Spread - basis points relative to benchmark
7
=
.PP
TED Price
8
=
.PP
TED Yield
9
=
.PP
Yield Spread (swaps)
10
=
.PP
Yield
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[QuotReqGrp (body_50485253.html?find=QuotePriceType)]
[QuotReqRjctGrp (body_50485255.html?find=QuotePriceType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
