.TH FIX.5.0 "" "" "Tag #694"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
694 (tag694.html)
QuoteRespType (tag694.html)
\@RspTyp
int
.PP
Identifies the type of Quote Response.
1
=
.PP
Hit/Lift
2
=
.PP
Counter
3
=
.PP
Expired
4
=
.PP
Cover
5
=
.PP
Done Away
6
=
.PP
Pass
.PP
   *   *   *   *   *
Used in messages:
[QuoteResponse (body_54576574.html?find=QuoteRespType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
