.TH FIX.5.0 "" "" "Tag #696"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
696 (tag696.html)
YieldRedemptionDate (tag696.html)
\@RedDt
LocalMktDate
.PP
Date to which the yield has been calculated (i.e. maturity, par
call or current call, pre-refunded date).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[YieldData (body_49485050.html?find=YieldRedemptionDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
