.TH FIX.5.0 "" "" "Tag #700"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
700 (tag700.html)
ReversalIndicator (tag700.html)
\@ReversalInd
Boolean
.PP
Indicates a trade that reverses a previous trade.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=ReversalIndicator)]
[AllocationInstructionAlert (body_57566677.html?find=ReversalIndicator)]
[AllocationReport (body_55566583.html?find=ReversalIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
