.TH FIX.5.0 "" "" "Tag #703"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
703 (tag703.html)
PosType (tag703.html)
\@Typ
String
.PP
Used to identify the type of quantity that is being returned.
ALC
=
.PP
Allocation Trade Qty
AS
=
.PP
Option Assignment
ASF
=
.PP
As-of Trade Qty
DLV
=
.PP
Delivery Qty
ETR
=
.PP
Electronic Trade Qty
EX
=
.PP
Option Exercise Qty
FIN
=
.PP
End-of-Day Qty
IAS
=
.PP
Intra-spread Qty
IES
=
.PP
Inter-spread Qty
PA
=
.PP
Adjustment Qty
PIT
=
.PP
Pit Trade Qty
SOD
=
.PP
Start-of-Day Qty
SPL
=
.PP
Integral Split
TA
=
.PP
Transaction from Assignment
TOT
=
.PP
Total Transaction Qty
TQ
=
.PP
Transaction Quantity
TRF
=
.PP
Transfer Trade Qty
TX
=
.PP
Transaction from Exercise
XM
=
.PP
Cross Margin Qty
RCV
=
.PP
Receive Quantity
CAA
=
.PP
Corporate Action Adjustment
DN
=
.PP
Delivery Notice Qty
EP
=
.PP
Exchange for Physical Qty
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PositionQty (body_49484953.html?find=PosType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
