.TH FIX.5.0 "" "" "Tag #707"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
707 (tag707.html)
PosAmtType (tag707.html)
\@Typ
String
.PP
Type of Position amount
CASH
=
.PP
Cash Amount (Corporate Event)
CRES
=
.PP
Cash Residual Amount
FMTM
=
.PP
Final Mark-to-Market Amount
IMTM
=
.PP
Incremental Mark-to-Market Amount
PREM
=
.PP
Premium Amount
SMTM
=
.PP
Start-of-Day Mark-to-Market Amount
TVAR
=
.PP
Trade Variation Amount
VADJ
=
.PP
Value Adjusted Amount
SETL
=
.PP
Settlement Value
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PositionAmountData (body_49484952.html?find=PosAmtType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
