.TH FIX.5.0 "" "" "Tag #710"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
710 (tag710.html)
PosReqID (tag710.html)
\@ReqID
String
.PP
Unique identifier for the position maintenance request as assigned
by the submitter
.PP
   *   *   *   *   *
Used in messages:
[PositionMaintenanceReport (body_55506577.html?find=PosReqID)]
[PositionMaintenanceRequest (body_55496576.html?find=PosReqID)]
[PositionReport (body_55536580.html?find=PosReqID)]
[RequestForPositions (body_55516578.html?find=PosReqID)]
[RequestForPositionsAck (body_55526579.html?find=PosReqID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
