.TH FIX.5.0 "" "" "Tag #717"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
717 (tag717.html)
SettlSessSubID (tag717.html)
\@SetSubID
String
.PP
SubID value associated with SettlSessID (716)
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=SettlSessSubID)]
[CollateralAssignment (body_56526589.html?find=SettlSessSubID)]
[CollateralInquiry (body_56556666.html?find=SettlSessSubID)]
[CollateralInquiryAck (body_57506671.html?find=SettlSessSubID)]
[CollateralReport (body_56546665.html?find=SettlSessSubID)]
[CollateralRequest (body_56516588.html?find=SettlSessSubID)]
[PositionMaintenanceReport (body_55506577.html?find=SettlSessSubID)]
[PositionMaintenanceRequest (body_55496576.html?find=SettlSessSubID)]
[PositionReport (body_55536580.html?find=SettlSessSubID)]
[RequestForPositions (body_55516578.html?find=SettlSessSubID)]
[RequestForPositionsAck (body_55526579.html?find=SettlSessSubID)]
[TradeCaptureReport (body_54526569.html?find=SettlSessSubID)]
[TradeCaptureReportAck (body_55556582.html?find=SettlSessSubID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
