.TH FIX.5.0 "" "" "Tag #723"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
723 (tag723.html)
PosMaintResult (tag723.html)
\@Rslt
int
.PP
Result of Position Maintenance Request.
.PP
4000+ Reserved and available for bi-laterally agreed upon
user-defined values
0
=
.PP
Successful Completion - no warnings or errors
1
=
.PP
Rejected
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[PositionMaintenanceReport (body_55506577.html?find=PosMaintResult)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
