.TH FIX.5.0 "" "" "Tag #732"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
732 (tag732.html)
UnderlyingSettlPrice (tag732.html)
\@UndSetPx
Price
.PP
Underlying security’s SettlPrice.
.PP
See SettlPrice (730) field for description
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=UnderlyingSettlPrice)]
.PP
   *   *   *   *   *
Used in components:
[PosUndInstrmtGrp (body_50485156.html?find=UnderlyingSettlPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
