.TH FIX.5.0 "" "" "Tag #736"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
736 (tag736.html)
AllocSettlCurrency (tag736.html)
\@AllocSettlCcy
Currency
.PP
Currency code of settlement denomination for a specific
AllocAccount (79).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=AllocSettlCurrency)]
[PreAllocGrp (body_50485157.html?find=AllocSettlCurrency)]
[PreAllocMlegGrp (body_50485248.html?find=AllocSettlCurrency)]
[TrdAllocGrp (body_50485448.html?find=AllocSettlCurrency)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
