.TH FIX.5.0 "" "" "Tag #738"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
738 (tag738.html)
InterestAtMaturity (tag738.html)
\@IntAtMat
Amt
.PP
Amount of interest (i.e. lump-sum) at maturity.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=InterestAtMaturity)]
[AllocationInstructionAlert (body_57566677.html?find=InterestAtMaturity)]
[AllocationReport (body_55566583.html?find=InterestAtMaturity)]
[Confirmation (body_55486575.html?find=InterestAtMaturity)]
[ExecutionReport (body_5756.html?find=InterestAtMaturity)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=InterestAtMaturity)]
[TrdCapRptSideGrp (body_50485449.html?find=InterestAtMaturity)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
