.TH FIX.5.0 "" "" "Tag #747"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
747 (tag747.html)
ExerciseMethod (tag747.html)
\@ExrMethod
char
.PP
Exercise Method used to in performing assignment.
A
=
.PP
Automatic
M
=
.PP
Manual
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=ExerciseMethod)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
