.TH FIX.5.0 "" "" "Tag #752"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
752 (tag752.html)
SideMultiLegReportingType (tag752.html)
\@MLegRptTyp
int
.PP
Used to indicate if the side being reported on Trade Capture Report
represents a leg of a multileg instrument or a single security.
1
=
.PP
Single Security (default if not specified)
2
=
.PP
Individual leg of a multileg security
3
=
.PP
Multileg Security
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=SideMultiLegReportingType)]
[TrdCapRptSideGrp (body_50485449.html?find=SideMultiLegReportingType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
