.TH FIX.5.0 "" "" "Tag #757"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
757 (tag757.html)
Nested2PartyID (tag757.html)
\@ID
String
.PP
PartyID value within a "second instance" Nested repeating group.
.PP
Same values as PartyID (448)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NestedParties2 (body_49484857.html?find=Nested2PartyID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
