.TH FIX.5.0 "" "" "Tag #77"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
77 (tag77.html)
PositionEffect (tag77.html)
\@PosEfct
char
.PP
Indicates whether the resulting position after a trade should be an
opening position or closing position. Used for omnibus accounting -
where accounts are held on a gross basis instead of being netted
together.
C
=
.PP
Close
F
=
.PP
FIFO
O
=
.PP
Open
R
=
.PP
Rolled
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=PositionEffect)]
[AllocationInstructionAlert (body_57566677.html?find=PositionEffect)]
[AllocationReport (body_55566583.html?find=PositionEffect)]
[ExecutionReport (body_5756.html?find=PositionEffect)]
[MultilegOrderCancelReplace (body_54506567.html?find=PositionEffect)]
[NewOrderMultileg (body_54496566.html?find=PositionEffect)]
[NewOrderSingle (body_495268.html?find=PositionEffect)]
[OrderCancelReplaceRequest (body_495571.html?find=PositionEffect)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=PositionEffect)]
[SideCrossOrdModGrp (body_50485357.html?find=PositionEffect)]
[TrdCapRptAckSideGrp (body_50485752.html?find=PositionEffect)]
[TrdCapRptSideGrp (body_50485449.html?find=PositionEffect)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
