.TH FIX.5.0 "" "" "Tag #780"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
780 (tag780.html)
AllocSettlInstType (tag780.html)
\@SettlInstTyp
int
.PP
Used to indicate whether settlement instructions are provided on an
allocation instruction message, and if not, how they are to be
derived.
0
=
.PP
Use default instructions
1
=
.PP
Derive from parameters provided
2
=
.PP
Full details provided
3
=
.PP
SSI DB IDs provided
4
=
.PP
Phone for instructions
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=AllocSettlInstType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
