.TH FIX.5.0 "" "" "Tag #788"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
788 (tag788.html)
TerminationType (tag788.html)
\@TrmTyp
int
.PP
Type of financing termination.
1
=
.PP
Overnight
2
=
.PP
Term
3
=
.PP
Flexible
4
=
.PP
Open
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[FinancingDetails (body_49484850.html?find=TerminationType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
