.TH FIX.5.0 "" "" "Tag #794"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
794 (tag794.html)
AllocReportType (tag794.html)
\@RptTyp
int
.PP
Describes the specific type or purpose of an Allocation Report
message
2
=
.PP
Preliminary Request to Intermediary
3
=
.PP
Sellside Calculated Using Preliminary (includes MiscFees and
NetMoney)
4
=
.PP
Sellside Calculated Without Preliminary (sent unsolicited by
sellside, includes MiscFees and NetMoney)
5
=
.PP
Warehouse Recap
8
=
.PP
Request to Intermediary
9
=
.PP
Accept
10
=
.PP
Reject
11
=
.PP
Accept Pending
12
=
.PP
Complete
14
=
.PP
Reverse Pending
.PP
   *   *   *   *   *
Used in messages:
[AllocationReport (body_55566583.html?find=AllocReportType)]
[AllocationReportAck (body_55576584.html?find=AllocReportType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
