.TH FIX.5.0 "" "" "Tag #795"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
795 (tag795.html)
AllocReportRefID (tag795.html)
\@RptRefID
String
.PP
Reference identifier to be used with AllocTransType (7) = Replace
or Cancel
.PP
   *   *   *   *   *
Used in messages:
[AllocationReport (body_55566583.html?find=AllocReportRefID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
