.TH FIX.5.0 "" "" "Tag #798"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
798 (tag798.html)
AllocAccountType (tag798.html)
\@AcctTyp
int
.PP
Type of account associated with a confirmation or other trade-level
message
1
=
.PP
Account is carried pn customer side of books
2
=
.PP
Account is carried on non-customer side of books
3
=
.PP
House trader
4
=
.PP
Floor trader
6
=
.PP
Account is carried on non-customer side of books and is cross
margined
7
=
.PP
Account is house trader and is cross margined
8
=
.PP
Joint back office account (JBO)
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=AllocAccountType)]
[ConfirmationRequest (body_57516672.html?find=AllocAccountType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
