.TH FIX.5.0 "" "" "Tag #799"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
799 (tag799.html)
OrderAvgPx (tag799.html)
\@AvgPx
Price
.PP
Average price for a specific order
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[OrdAllocGrp (body_50485154.html?find=OrderAvgPx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
