.TH FIX.5.0 "" "" "Tag #80"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
80 (tag80.html)
AllocQty (tag80.html)
\@Qty
Qty
.PP
Quantity to be allocated to specific sub-account
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=AllocQty)]
.PP
   *   *   *   *   *
Used in components:
[AllocAckGrp (body_50484850.html?find=AllocQty)]
[AllocGrp (body_50484851.html?find=AllocQty)]
[PreAllocGrp (body_50485157.html?find=AllocQty)]
[PreAllocMlegGrp (body_50485248.html?find=AllocQty)]
[TrdAllocGrp (body_50485448.html?find=AllocQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
