.TH FIX.5.0 "" "" "Tag #818"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
818 (tag818.html)
SecondaryTradeReportID (tag818.html)
\@TrdRptID2
String
.PP
Secondary trade report identifier - can be used to associate an
additional identifier with a trade.
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=SecondaryTradeReportID)]
[TradeCaptureReportAck (body_55556582.html?find=SecondaryTradeReportID)]
[TradeCaptureReportRequest (body_54516568.html?find=SecondaryTradeReportID)]
.PP
   *   *   *   *   *
Used in components:
[TrdCollGrp (body_50485450.html?find=SecondaryTradeReportID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
