.TH FIX.5.0 "" "" "Tag #822"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
822 (tag822.html)
UnderlyingTradingSessionID (tag822.html)
\@UndSesID
String
.PP
Trading Session in which the underlying instrument trades
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=UnderlyingTradingSessionID)]
[TradeCaptureReportAck (body_55556582.html?find=UnderlyingTradingSessionID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
