.TH FIX.5.0 "" "" "Tag #823"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
823 (tag823.html)
UnderlyingTradingSessionSubID (tag823.html)
\@UndSesSub
String
.PP
Trading Session sub identifier in which the underlying instrument
trades
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=UnderlyingTradingSessionSubID)]
[TradeCaptureReportAck (body_55556582.html?find=UnderlyingTradingSessionSubID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
