.TH FIX.5.0 "" "" "Tag #824"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
824 (tag824.html)
TradeLegRefID (tag824.html)
\@TrdLegRefID
String
.PP
Reference to the leg of a multileg instrument to which this trade
refers
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TradeLegRefID)]
[TradeCaptureReportAck (body_55556582.html?find=TradeLegRefID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
