.TH FIX.5.0 "" "" "Tag #826"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
826 (tag826.html)
TradeAllocIndicator (tag826.html)
\@AllocInd
int
.PP
Identifies how the trade is to be allocated
0
=
.PP
Allocation not required
1
=
.PP
Allocation required (give-up trade) allocation information not
provided (incomplete)
2
=
.PP
Use allocation provided with the trade
3
=
.PP
Allocation give-up executor
4
=
.PP
Allocation from executor
5
=
.PP
Allocation to claim account
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=TradeAllocIndicator)]
[TrdCapRptSideGrp (body_50485449.html?find=TradeAllocIndicator)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
