.TH FIX.5.0 "" "" "Tag #828"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
828 (tag828.html)
TrdType (tag828.html)
\@TrdTyp
int
.PP
Type of Trade:
0
=
.PP
Regular Trade
1
=
.PP
Block Trade
2
=
.PP
EFP (Exchange for physical)
3
=
.PP
Transfer
4
=
.PP
Late Trade
5
=
.PP
T Trade
6
=
.PP
Weighted Average Price Trade
7
=
.PP
Bunched Trade
8
=
.PP
Late Bunched Trade
9
=
.PP
Prior Reference Price Trade
10
=
.PP
After Hours Trade
11
=
.PP
Exchange for Risk (EFR)
12
=
.PP
Exchange for Swap (EFS )
13
=
.PP
Exchange of Futures for (in Market) Futures (EFM ) (e,g, full sized
for mini)
14
=
.PP
Exchange of Options for Options (EOO)
15
=
.PP
Trading at Settlement
16
=
.PP
All or None
17
=
.PP
Futures Large Order Execution
18
=
.PP
Exchange of Futures for Futures (external market) (EFF)
19
=
.PP
Option Interim Trade
20
=
.PP
Option Cabinet Trade
22
=
.PP
Privately Negotiated Trades
23
=
.PP
Substitution of Futures for Forwards
—\ MiFID Values\ —
24
=
.PP
Error trade
25
=
.PP
Special cum dividend (CD)
26
=
.PP
Special ex dividend (XD)
27
=
.PP
Special cum coupon (CC)
28
=
.PP
Special ex coupon (XC)
29
=
.PP
Cash settlement (CS)
30
=
.PP
Special price (usually net- or all-in price) (SP)
31
=
.PP
Guaranteed delivery (GD)
32
=
.PP
Special cum rights (CR)
33
=
.PP
Special ex rights (XR)
34
=
.PP
Special cum capital repayments (CP)
35
=
.PP
Special ex capital repayments (XP)
36
=
.PP
Special cum bonus (CB)
37
=
.PP
Special ex bonus (XB)
38
=
.PP
Block trade (same as large trade)
39
=
.PP
Worked principal trade (UK-specific)
40
=
.PP
Block Trades - after market
41
=
.PP
Name change
42
=
.PP
Portfolio transfer
43
=
.PP
Prorogation buy - Euronext Paris only. Is used to defer settlement
under French SRD (deferred settlement system) \&.
Trades must be reported as crosses at zero price
44
=
.PP
Prorogation sell - see prorogation buy
45
=
.PP
Option exercise
46
=
.PP
Delta neutral transaction
47
=
.PP
Financing transaction (includes repo and stock lending)
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=TrdType)]
[AllocationInstructionAlert (body_57566677.html?find=TrdType)]
[AllocationReport (body_55566583.html?find=TrdType)]
[TradeCaptureReport (body_54526569.html?find=TrdType)]
[TradeCaptureReportAck (body_55556582.html?find=TrdType)]
[TradeCaptureReportRequest (body_54516568.html?find=TrdType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
