.TH FIX.5.0 "" "" "Tag #83"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
83 (tag83.html)
RptSeq (tag83.html)
\@RptSeq
int
.PP
Sequence number of message within report series. Used to carry
reporting sequence number of the fill as represented on the Trade
Report Side.
.PP
   *   *   *   *   *
Used in messages:
[ListStatus (body_505178.html?find=RptSeq)]
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=RptSeq)]
[MDIncGrp (body_50485150.html?find=RptSeq)]
[TrdCapRptAckSideGrp (body_50485752.html?find=RptSeq)]
[TrdCapRptSideGrp (body_50485449.html?find=RptSeq)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
