.TH FIX.5.0 "" "" "Tag #834"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
834 (tag834.html)
ThresholdAmount (tag834.html)
\@ThresholdAmt
PriceOffset
.PP
Amount that a position has to be in the money before it is
exercised.
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=ThresholdAmount)]
[PositionMaintenanceReport (body_55506577.html?find=ThresholdAmount)]
[PositionMaintenanceRequest (body_55496576.html?find=ThresholdAmount)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
