.TH FIX.5.0 "" "" "Tag #84"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
84 (tag84.html)
CxlQty (tag84.html)
\@CxlQty
Qty
.PP
Total quantity canceled for this order.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[OrdListStatGrp (body_50485155.html?find=CxlQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
