.TH FIX.5.0 "" "" "Tag #846"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
846 (tag846.html)
DiscretionScope (tag846.html)
\@Scope
int
.PP
The scope of the discretion
1
=
.PP
Local (Exchange, ECN, ATS)
2
=
.PP
National
3
=
.PP
Global
4
=
.PP
National excluding local
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DiscretionInstructions (body_49484849.html?find=DiscretionScope)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
