.TH FIX.5.0 "" "" "Tag #849"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
849 (tag849.html)
ParticipationRate (tag849.html)
\@ParticipationRt
Percentage
.PP
For a TargetStrategy=Participate order specifies the target
particpation rate. For other order types this is a volume limit
(i.e. do not be more than this percent of the market volume)
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=ParticipationRate)]
[ExecutionReport (body_5756.html?find=ParticipationRate)]
[MultilegOrderCancelReplace (body_54506567.html?find=ParticipationRate)]
[NewOrderCross (body_5350115.html?find=ParticipationRate)]
[NewOrderMultileg (body_54496566.html?find=ParticipationRate)]
[NewOrderSingle (body_495268.html?find=ParticipationRate)]
[OrderCancelReplaceRequest (body_495571.html?find=ParticipationRate)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=ParticipationRate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
