.TH FIX.5.0 "" "" "Tag #852"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
852 (tag852.html)
PublishTrdIndicator (tag852.html)
\@PubTrdInd
Boolean
.PP
Indicates if a trade should be reported via a market reporting
service.
N
=
.PP
Do Not Report Trade
Y
=
.PP
Report Trade
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=PublishTrdIndicator)]
[TradeCaptureReportAck (body_55556582.html?find=PublishTrdIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
