.TH FIX.5.0 "" "" "Tag #855"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
855 (tag855.html)
SecondaryTrdType (tag855.html)
\@TrdTyp2
int
.PP
Additional TrdType (see tag 828) assigned to a trade by trade match
system.
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=SecondaryTrdType)]
[TradeCaptureReportAck (body_55556582.html?find=SecondaryTrdType)]
[TradeCaptureReportRequest (body_54516568.html?find=SecondaryTrdType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
