.TH FIX.5.0 "" "" "Tag #856"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
856 (tag856.html)
TradeReportType (tag856.html)
\@RptTyp
int
.PP
Type of Trade Report
0
=
.PP
Submit
1
=
.PP
Alleged
2
=
.PP
Accept
3
=
.PP
Decline
4
=
.PP
Addendum
5
=
.PP
No/Was
6
=
.PP
Trade Report Cancel
7
=
.PP
(Locked-In) Trade Break
8
=
.PP
Defaulted
9
=
.PP
Invalid CMTA
10
=
.PP
Pended
11
=
.PP
Alleged New
12
=
.PP
Alleged Addendum
13
=
.PP
Alleged No/Was
14
=
.PP
Alleged Trade Report Cancel
15
=
.PP
Alleged (Locked-In) Trade Break
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TradeReportType)]
[TradeCaptureReportAck (body_55556582.html?find=TradeReportType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
