.TH FIX.5.0 "" "" "Tag #858"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
858 (tag858.html)
SharedCommission (tag858.html)
\@SharedComm
Amt
.PP
Commission to be shared with a third party, e.g. as part of a
directed brokerage commission sharing arrangement.
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=SharedCommission)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
