.TH FIX.5.0 "" "" "Tag #861"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
861 (tag861.html)
ReportedPx (tag861.html)
\@RptedPx
Price
.PP
Reported price (used to differentiate from AvgPx on a confirmation
of a marked-up or marked-down principal trade)
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=ReportedPx)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
