.TH FIX.5.0 "" "" "Tag #876"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
876 (tag876.html)
CPRegType (tag876.html)
\@CPRegT
String
.PP
The registration type of a commercial paper issuance
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=CPRegType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
