.TH FIX.5.0 "" "" "Tag #881"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
881 (tag881.html)
SecondaryTradeReportRefID (tag881.html)
\@TrdRptRefID2
String
.PP
Used to refer to a previous SecondaryTradeReportRefID when amending
the transaction (cancel, replace, release, or reversal).
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=SecondaryTradeReportRefID)]
[TradeCaptureReportAck (body_55556582.html?find=SecondaryTradeReportRefID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
