.TH FIX.5.0 "" "" "Tag #884"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
884 (tag884.html)
UnderlyingStartValue (tag884.html)
\@StartVal
Amt
.PP
Currency value attributed to this collateral at the start of the
agreement
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingStartValue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
