.TH FIX.5.0 "" "" "Tag #889"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
889 (tag889.html)
UnderlyingStipValue (tag889.html)
\@Val
String
.PP
Value of stipulation.
.PP
Same values as StipulationValue (234)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingStipulations (body_49485051.html?find=UnderlyingStipValue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
