.TH FIX.5.0 "" "" "Tag #890"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
890 (tag890.html)
MaturityNetMoney (tag890.html)
\@MatNetMny
Amt
.PP
Net Money at maturity if Zero Coupon and maturity value is
different from par value
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=MaturityNetMoney)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
