.TH FIX.5.0 "" "" "Tag #901"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
901 (tag901.html)
CashOutstanding (tag901.html)
\@CshOutstanding
Amt
.PP
Starting consideration less repayments
.PP
   *   *   *   *   *
Used in messages:
[CollateralAssignment (body_56526589.html?find=CashOutstanding)]
[CollateralInquiry (body_56556666.html?find=CashOutstanding)]
[CollateralReport (body_56546665.html?find=CashOutstanding)]
[CollateralRequest (body_56516588.html?find=CashOutstanding)]
[CollateralResponse (body_56536590.html?find=CashOutstanding)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
