.TH FIX.5.0 "" "" "Tag #903"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
903 (tag903.html)
CollAsgnTransType (tag903.html)
\@TransTyp
int
.PP
Collateral Assignment Transaction Type
0
=
.PP
New
1
=
.PP
Replace
2
=
.PP
Cancel
3
=
.PP
Release
4
=
.PP
Reverse
.PP
   *   *   *   *   *
Used in messages:
[CollateralAssignment (body_56526589.html?find=CollAsgnTransType)]
[CollateralResponse (body_56536590.html?find=CollAsgnTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
