.TH FIX.5.0 "" "" "Tag #905"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
905 (tag905.html)
CollAsgnRespType (tag905.html)
\@RespTyp
int
.PP
Collateral Assignment Response Type
0
=
.PP
Received
1
=
.PP
Accepted
2
=
.PP
Declined
3
=
.PP
Rejected
.PP
   *   *   *   *   *
Used in messages:
[CollateralResponse (body_56536590.html?find=CollAsgnRespType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
