.TH FIX.5.0 "" "" "Tag #911"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
911 (tag911.html)
TotNumReports (tag911.html)
\@TotNumRpts
int
.PP
Total number or reports returned in response to a request
.PP
   *   *   *   *   *
Used in messages:
[CollateralInquiryAck (body_57506671.html?find=TotNumReports)]
[CollateralReport (body_56546665.html?find=TotNumReports)]
[ExecutionReport (body_5756.html?find=TotNumReports)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
