.TH FIX.5.0 "" "" "Tag #919"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
919 (tag919.html)
DeliveryType (tag919.html)
\@DlvryTyp
int
.PP
Identifies type of settlement
0
=
.PP
"Versus Payment": Deliver (if sell) or Receive (if buy) vs.
(against) Payment
1
=
.PP
"Free": Deliver (if sell) or Receive (if buy) Free
2
=
.PP
Tri-Party
3
=
.PP
Hold In Custody
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[FinancingDetails (body_49484850.html?find=DeliveryType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
