.TH FIX.5.0 "" "" "Tag #924"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
924 (tag924.html)
UserRequestType (tag924.html)
\@UserReqTyp
int
.PP
Indicates the action required by a User Request Message
1
=
.PP
Log On User
2
=
.PP
Log Off User
3
=
.PP
Change Password For User
4
=
.PP
Request Individual User Status
.PP
   *   *   *   *   *
Used in messages:
[UserRequest (body_57486669.html?find=UserRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
