.TH FIX.5.0 "" "" "Tag #946"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
946 (tag946.html)
CollInquiryResult (tag946.html)
\@Rslt
int
.PP
Result returned in response to Collateral Inquiry
.PP
4000+ Reserved and available for bi-laterally agreed upon
user-defined values
0
=
.PP
Successful (default)
1
=
.PP
Invalid or unknown instrument
2
=
.PP
Invalid or unknown collateral type
3
=
.PP
Invalid Parties
4
=
.PP
Invalid Transport Type requested
5
=
.PP
Invalid Destination requested
6
=
.PP
No collateral found for the trade specified
7
=
.PP
No collateral found for the order specified
8
=
.PP
Collateral inquiry type not supported
9
=
.PP
Unauthorized for collateral inquiry
99
=
.PP
Other (further information in Text (58) field)
.PP
   *   *   *   *   *
Used in messages:
[CollateralInquiryAck (body_57506671.html?find=CollInquiryResult)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
