.TH FIX.5.0 "" "" "Tag #958"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
958 (tag958.html)
StrategyParameterName (tag958.html)
\@StrtPrmNme
String
.PP
Name of parameter
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StrategyParametersGrp (body_50485654.html?find=StrategyParameterName)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
