.TH FIX.5.0 "" "" "Tag #959"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
959 (tag959.html)
StrategyParameterType (tag959.html)
\@StrtPrmTyp
int
.PP
Datatype of the parameter
1
=
.PP
Int
2
=
.PP
Length
3
=
.PP
NumInGroup
4
=
.PP
SeqNum
5
=
.PP
TagNum
6
=
.PP
Float
7
=
.PP
Qty
8
=
.PP
Price
9
=
.PP
PriceOffset
10
=
.PP
Amt
11
=
.PP
Percentage
12
=
.PP
Char
13
=
.PP
Boolean
14
=
.PP
String
15
=
.PP
MultipleCharValue
16
=
.PP
Currency
17
=
.PP
Exchange
18
=
.PP
Month-Year
19
=
.PP
UTCTimeStamp
20
=
.PP
UTCTimeOnly
21
=
.PP
LocalMktTime
22
=
.PP
UTCDate
23
=
.PP
Data
24
=
.PP
MultipleStringValue
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StrategyParametersGrp (body_50485654.html?find=StrategyParameterType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
