.TH FIX.5.0 "" "" "Tag #960"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
960 (tag960.html)
StrategyParameterValue (tag960.html)
\@StrtPrmVal
String
.PP
Value of the parameter
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StrategyParametersGrp (body_50485654.html?find=StrategyParameterValue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
