.TH FIX.5.0 "" "" "Tag #962"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
962 (tag962.html)
SideTimeInForce (tag962.html)
\@SideTmFrc
UTCTimestamp
.PP
Indicates how long the order as specified in the side stays in
effect. SideTimeInForce allows a two-sided cross order to specify
order behavior separately for each side. Absence of this field
indicates that TimeInForce should be referenced. SideTimeInForce
will override TimeInForce if both are provided.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SideCrossOrdModGrp (body_50485357.html?find=SideTimeInForce)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
