.TH FIX.5.0 "" "" "Tag #963"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
963 (tag963.html)
MDReportID (tag963.html)
\@RptID
int
.PP
Unique identifier for the Market Data Report.
.PP
   *   *   *   *   *
Used in messages:
[MarketDataSnapshotFullRefresh (body_514887.html?find=MDReportID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
