.TH FIX.5.0 "" "" "Tag #964"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
964 (tag964.html)
SecurityReportID (tag964.html)
\@RptID
int
.PP
Security Report ID. Unique identifier for the Security Report.
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinition (body_5155100.html?find=SecurityReportID)]
[SecurityDefinitionUpdateReport (body_57536680.html?find=SecurityReportID)]
[SecurityList (body_5356121.html?find=SecurityReportID)]
[SecurityListUpdateReport (body_57546675.html?find=SecurityReportID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
