.TH FIX.5.0 "" "" "Tag #972"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
972 (tag972.html)
UnderlyingAllocationPercent (tag972.html)
\@AllocPct
Percentage
.PP
Percent of the Strike Price that this underlying represents.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingAllocationPercent)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
