.TH FIX.5.0 "" "" "Tag #980"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
980 (tag980.html)
SecurityUpdateAction (tag980.html)
\@UpdActn
char
A
=
.PP
Add
D
=
.PP
Delete
M
=
.PP
Modify
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinitionUpdateReport (body_57536680.html?find=SecurityUpdateAction)]
[SecurityListUpdateReport (body_57546675.html?find=SecurityUpdateAction)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
