.TH FIX.5.0 "" "" "Tag #987"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
987 (tag987.html)
UnderlyingSettlementDate (tag987.html)
\@StlDt
LocalMktDate
.PP
Date the underlying instrument will settle. Used for derivatives
that deliver into more than one underlying instrument. Settlement
dates can vary across underlying instruments.
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=UnderlyingSettlementDate)]
.PP
   *   *   *   *   *
Used in components:
[UnderlyingAmount (body_49485054.html?find=UnderlyingSettlementDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
