.TH FIX.5.0 "" "" "Tag #992"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
992 (tag992.html)
IndividualAllocType (tag992.html)
\@Typ
int
.PP
Identifies whether the allocation is to be sub-allocated or
allocated to a third party
1
=
.PP
Sub Allocate
2
=
.PP
Third Party Allocation
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AllocAckGrp (body_50484850.html?find=IndividualAllocType)]
[AllocGrp (body_50484851.html?find=IndividualAllocType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
