.TH FIX.5.0 "" "" "Tag #997"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
997 (tag997.html)
TimeUnit (tag997.html)
\@TmUnit
String
.PP
Unit of time associated with the contract.
.PP
NOTE: Additional values may be used by mutual agreement of the
counterparties
H
=
.PP
Hour
Min
=
.PP
Minute
S
=
.PP
Second
D
=
.PP
Day
Wk
=
.PP
Week
Mo
=
.PP
Month
Yr
=
.PP
Year
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=TimeUnit)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
