.TH FIX.5.0 "" "" "Tag #999"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
999 (tag999.html)
LegUnitofMeasure (tag999.html)
\@UOM
String
.PP
Same as UnitofMeasure.
Bbl
=
.PP
Barrels
Bcf
=
.PP
Billion cubic feet
Bu
=
.PP
Bushels
lbs
=
.PP
pounds
Gal
=
.PP
Gallons
MMbbl
=
.PP
Million Barrels
MMBtu
=
.PP
One Million BTU
MWh
=
.PP
Megawatt hours
oz_tr
=
.PP
Troy Ounces
t
=
.PP
Metric Tons (aka Tonne)
tn
=
.PP
Tons (US)
USD
=
.PP
US Dollars
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegUnitofMeasure)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
