.TH FIX.4.1 "" "" "Tag #1"
Tag
Field Name
Data Type
Description
Depr.
Valid values
1 (tag1.html)
Account (tag1.html)
char
.PP
Account mnemonic as agreed between broker and institution.
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=Account)]
[Order - List (body_495369.html?find=Account)]
[Order - Single (body_495268.html?find=Account)]
[Order Cancel/Replace Request (body_495571.html?find=Account)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
