.TH FIX.4.1 "" "" "Tag #112"
Tag
Field Name
Data Type
Description
Depr.
Valid values
112 (tag112.html)
TestReqID (tag112.html)
char
.PP
Identifier included in Test Request message to be returned in
resulting Heartbeat
.PP
   *   *   *   *   *
Used in messages:
[Heartbeat (body_4948.html?find=TestReqID)]
[Test Request (body_5049.html?find=TestReqID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
