.TH FIX.4.1 "" "" "Tag #133"
Tag
Field Name
Data Type
Description
Depr.
Valid values
133 (tag133.html)
OfferPx (tag133.html)
float
.PP
Offer price/rate
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=OfferPx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
