.TH FIX.4.1 "" "" "Tag #152"
Tag
Field Name
Data Type
Description
Depr.
Valid values
152 (tag152.html)
CashOrderQty (tag152.html)
float
.PP
Specifies the approximate order quantity desired in total monetary
units vs. as a number of shares. The broker would be responsible
for converting and calculating a share quantity (OrderQty) based
upon this amount to be used for the actual order and subsequent
messages.
.PP
   *   *   *   *   *
Used in messages:
[Don’t Know Trade (DK) (body_505381.html?find=CashOrderQty)]
[Order - Single (body_495268.html?find=CashOrderQty)]
[Order Cancel Request (body_495470.html?find=CashOrderQty)]
[Order Cancel/Replace Request (body_495571.html?find=CashOrderQty)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
