.TH FIX.4.1 "" "" "Tag #208"
Tag
Field Name
Data Type
Description
Depr.
Valid values
208 (tag208.html)
NotifyBrokerOfCredit (tag208.html)
char
.PP
Indicates whether or not details should be communicated to
BrokerOfCredit (i.e. step-in broker).
N
=
.PP
Details should not be communicated
Y
=
.PP
Details should be communicated
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=NotifyBrokerOfCredit)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
