.TH FIX.4.1 "" "" "Tag #210"
Tag
Field Name
Data Type
Description
Depr.
Valid values
210 (tag210.html)
MaxShow (tag210.html)
int
.PP
Maximum number of shares within an order to be shown to other
customers (i.e. sent via an IOI).
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=MaxShow)]
[Order - Single (body_495268.html?find=MaxShow)]
[Order Cancel/Replace Request (body_495571.html?find=MaxShow)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
