.TH FIX.4.1 "" "" "Tag #211"
Tag
Field Name
Data Type
Description
Depr.
Valid values
211 (tag211.html)
PegDifference (tag211.html)
float
.PP
Price difference for a pegged order.
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=PegDifference)]
[Order - List (body_495369.html?find=PegDifference)]
[Order - Single (body_495268.html?find=PegDifference)]
[Order Cancel/Replace Request (body_495571.html?find=PegDifference)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
