.TH FIX.4.1 "" "" "Tag #43"
Tag
Field Name
Data Type
Description
Depr.
Valid values
43 (tag43.html)
PossDupFlag (tag43.html)
char
.PP
Indicates possible retransmission of message with this sequence
number
N
=
.PP
Original transmission
Y
=
.PP
Possible duplicate
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
