.TH FIX.4.1 "" "" "Tag #47"
Tag
Field Name
Data Type
Description
Depr.
Valid values
47 (tag47.html)
Rule80A(aka OrderCapacity) (tag47.html)
char
.PP
Note that the name of this field is changing to “OrderCapacity” as
Rule80A is a very US market-specific term. Other world markets need
to convey similar information, however, often a subset of the US
values. \&.
See the “Rule80A (aka OrderCapacity) Usage by Market” appendix for
market-specific usage of this field.
A
=
.PP
Agency single order
B
=
.PP
Short exempt transaction (refer to A type)
C
=
.PP
Program Order, non-index arb, for Member firm/org
D
=
.PP
Program Order, index arb, for Member firm/org
E
=
.PP
Registered Equity Market Maker trades
F
=
.PP
Short exempt transaction (refer to W type)
H
=
.PP
Short exempt transaction (refer to I type)
I
=
.PP
Individual Investor, single order
J
=
.PP
Program Order, index arb, for individual customer
K
=
.PP
Program Order, non-index arb, for individual customer
L
=
.PP
Short exempt transaction for member competing market-maker
affiliated with the firm clearing the trade (refer to P and O
types)
M
=
.PP
Program Order, index arb, for other member
N
=
.PP
Program Order, non-index arb, for other member
O
=
.PP
Competing dealer trades
P
=
.PP
Principal
R
=
.PP
Competing dealer trades
S
=
.PP
Specialist trades
T
=
.PP
Competing dealer trades
U
=
.PP
Program Order, index arb, for other agency
W
=
.PP
All other orders as agent for other member
X
=
.PP
Short exempt transaction for member competing market-maker not
affiliated with the firm clearing the trade (refer to W and T
types)
Y
=
.PP
Program Order, non-index arb, for other agency
Z
=
.PP
Short exempt transaction for non-member competing market-maker
(refer to A and R types)
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=Rule80A(aka%20OrderCapacity))]
[Order - List (body_495369.html?find=Rule80A(aka%20OrderCapacity))]
[Order - Single (body_495268.html?find=Rule80A(aka%20OrderCapacity))]
[Order Cancel/Replace Request (body_495571.html?find=Rule80A(aka%20OrderCapacity))]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
