.TH FIX.4.1 "" "" "Tag #97"
Tag
Field Name
Data Type
Description
Depr.
Valid values
97 (tag97.html)
PossResend (tag97.html)
char
.PP
Indicates that message may contain information that has been sent
under another sequence number.
N
=
.PP
Original transmission
Y
=
.PP
Possible resend
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
