.TH FIX.4.3 "" "" "Tag #11"
Tag
Field Name
Data Type
Description
Depr.
Valid values
11 (tag11.html)
ClOrdID (tag11.html)
String
.PP
Unique identifier for Order as assigned by the buy-side
(institution, broker, intermediary etc.) (identified by
SenderCompID or OnBehalfOfCompID as appropriate). Uniqueness must
be guaranteed within a single trading day. Firms, particularly
those which electronically submit multi-day orders, trade globally
or throughout market close periods, should ensure uniqueness across
days, for example by embedding a date within the ClOrdID field.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=ClOrdID)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=ClOrdID)]
[CrossOrderCancelRequest (body_5351117.html?find=ClOrdID)]
[Email (body_495167.html?find=ClOrdID)]
[ExecutionReport (body_5756.html?find=ClOrdID)]
[ListStatus (body_505178.html?find=ClOrdID)]
[ListStrikePrice (body_5254109.html?find=ClOrdID)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=ClOrdID)]
[NewOrderCross (body_5350115.html?find=ClOrdID)]
[NewOrderList (body_495369.html?find=ClOrdID)]
[NewOrderMultileg (body_54496566.html?find=ClOrdID)]
[NewOrderSingle (body_495268.html?find=ClOrdID)]
[OrderCancelReject (body_494857.html?find=ClOrdID)]
[OrderCancelReplaceRequest (body_495571.html?find=ClOrdID)]
[OrderCancelRequest (body_495470.html?find=ClOrdID)]
[OrderMassCancelReport (body_5349114.html?find=ClOrdID)]
[OrderMassCancelRequest (body_5348113.html?find=ClOrdID)]
[OrderStatusRequest (body_495672.html?find=ClOrdID)]
[RegistrationInstructions (body_5256111.html?find=ClOrdID)]
[RegistrationInstructionsResponse (body_5257112.html?find=ClOrdID)]
[SettlementInstructions (body_505684.html?find=ClOrdID)]
[TradeCaptureReport (body_54526569.html?find=ClOrdID)]
[TradeCaptureReportRequest (body_54516568.html?find=ClOrdID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
