.TH FIX.4.3 "" "" "Tag #110"
Tag
Field Name
Data Type
Description
Depr.
Valid values
110 (tag110.html)
MinQty (tag110.html)
Qty
.PP
Minimum quantity of an order to be executed.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=MinQty)]
[ExecutionReport (body_5756.html?find=MinQty)]
[MarketDataIncrementalRefresh (body_514988.html?find=MinQty)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=MinQty)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=MinQty)]
[NewOrderCross (body_5350115.html?find=MinQty)]
[NewOrderList (body_495369.html?find=MinQty)]
[NewOrderMultileg (body_54496566.html?find=MinQty)]
[NewOrderSingle (body_495268.html?find=MinQty)]
[OrderCancelReplaceRequest (body_495571.html?find=MinQty)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
