.TH FIX.4.3 "" "" "Tag #114"
Tag
Field Name
Data Type
Description
Depr.
Valid values
114 (tag114.html)
LocateReqd (tag114.html)
Boolean
.PP
Indicates whether the broker is to locate the stock in conjunction
with a short sell order.
N
=
.PP
Indicates the broker is not required to locate
Y
=
.PP
Indicates the broker is responsible for locating the stock
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=LocateReqd)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=LocateReqd)]
[NewOrderCross (body_5350115.html?find=LocateReqd)]
[NewOrderList (body_495369.html?find=LocateReqd)]
[NewOrderMultileg (body_54496566.html?find=LocateReqd)]
[NewOrderSingle (body_495268.html?find=LocateReqd)]
[OrderCancelReplaceRequest (body_495571.html?find=LocateReqd)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
