.TH FIX.4.3 "" "" "Tag #120"
Tag
Field Name
Data Type
Description
Depr.
Valid values
120 (tag120.html)
SettlCurrency (tag120.html)
Currency
.PP
Currency code of settlement denomination.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=SettlCurrency)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=SettlCurrency)]
[ExecutionReport (body_5756.html?find=SettlCurrency)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=SettlCurrency)]
[NewOrderCross (body_5350115.html?find=SettlCurrency)]
[NewOrderList (body_495369.html?find=SettlCurrency)]
[NewOrderMultileg (body_54496566.html?find=SettlCurrency)]
[NewOrderSingle (body_495268.html?find=SettlCurrency)]
[OrderCancelReplaceRequest (body_495571.html?find=SettlCurrency)]
[TradeCaptureReport (body_54526569.html?find=SettlCurrency)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
