.TH FIX.4.3 "" "" "Tag #121"
Tag
Field Name
Data Type
Description
Depr.
Valid values
121 (tag121.html)
ForexReq (tag121.html)
Boolean
.PP
Indicates request for forex accommodation trade to be executed
along with security transaction.
N
=
.PP
Do not execute Forex after security trade
Y
=
.PP
Execute Forex after security trade
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=ForexReq)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=ForexReq)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=ForexReq)]
[NewOrderCross (body_5350115.html?find=ForexReq)]
[NewOrderList (body_495369.html?find=ForexReq)]
[NewOrderMultileg (body_54496566.html?find=ForexReq)]
[NewOrderSingle (body_495268.html?find=ForexReq)]
[OrderCancelReplaceRequest (body_495571.html?find=ForexReq)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
