.TH FIX.4.3 "" "" "Tag #126"
Tag
Field Name
Data Type
Description
Depr.
Valid values
126 (tag126.html)
ExpireTime (tag126.html)
UTCTimestamp
.PP
Time/Date of order expiration (always expressed in UTC (Universal
Time Coordinated, also known as “GMT”)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=ExpireTime)]
[ExecutionReport (body_5756.html?find=ExpireTime)]
[MarketDataIncrementalRefresh (body_514988.html?find=ExpireTime)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=ExpireTime)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=ExpireTime)]
[NewOrderCross (body_5350115.html?find=ExpireTime)]
[NewOrderList (body_495369.html?find=ExpireTime)]
[NewOrderMultileg (body_54496566.html?find=ExpireTime)]
[NewOrderSingle (body_495268.html?find=ExpireTime)]
[OrderCancelReplaceRequest (body_495571.html?find=ExpireTime)]
[QuoteRequest (body_505482.html?find=ExpireTime)]
[QuoteRequestReject (body_54546571.html?find=ExpireTime)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
