.TH FIX.4.3 "" "" "Tag #128"
Tag
Field Name
Data Type
Description
Depr.
Valid values
128 (tag128.html)
DeliverToCompID (tag128.html)
String
.PP
Assigned value used to identify the firm targeted to receive the
message if the message is delivered by a third party i.e. the third
party firm identifier would be delivered in the TargetCompID field
and the ultimate receiver firm ID in this field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=DeliverToCompID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
