.TH FIX.4.3 "" "" "Tag #129"
Tag
Field Name
Data Type
Description
Depr.
Valid values
129 (tag129.html)
DeliverToSubID (tag129.html)
String
.PP
Assigned value used to identify specific message recipient (i.e.
trader) if the message is delivered by a third party
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=DeliverToSubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
