.TH FIX.4.3 "" "" "Tag #13"
Tag
Field Name
Data Type
Description
Depr.
Valid values
13 (tag13.html)
CommType (tag13.html)
char
.PP
Commission type
1
=
.PP
per share
2
=
.PP
percentage
3
=
.PP
absolute
4
=
.PP
(for CIV buy orders) percentage waived cash discount
5
=
.PP
(for CIV buy orders) percentage waived enhanced units
6
=
.PP
per bond
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=CommType)]
[QuoteStatusReport (body_54566573.html?find=CommType)]
.PP
   *   *   *   *   *
Used in components:
[CommissionData (body_49484848.html?find=CommType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
