.TH FIX.4.3 "" "" "Tag #133"
Tag
Field Name
Data Type
Description
Depr.
Valid values
133 (tag133.html)
OfferPx (tag133.html)
Price
.PP
Offer price/rate
.PP
   *   *   *   *   *
Used in messages:
[MassQuote (body_5250105.html?find=OfferPx)]
[MassQuoteAcknowledgement (body_515398.html?find=OfferPx)]
[Quote (body_505583.html?find=OfferPx)]
[QuoteStatusReport (body_54566573.html?find=OfferPx)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
