.TH FIX.4.3 "" "" "Tag #150"
Tag
Field Name
Data Type
Description
Depr.
Valid values
150 (tag150.html)
ExecType (tag150.html)
char
.PP
Describes the specific ExecutionRpt (i.e. Pending Cancel) while
OrdStatus will always identify the current order status (i.e.
Partially Filled)
0
=
.PP
New
1
=
.PP
Partial fill (Replaced)
2
=
.PP
Fill (Replaced)
3
=
.PP
Done for day
4
=
.PP
Canceled
5
=
.PP
Replace
6
=
.PP
Pending Cancel (e.g. result of Order Cancel Request)
7
=
.PP
Stopped
8
=
.PP
Rejected
9
=
.PP
Suspended
A
=
.PP
Pending New
B
=
.PP
Calculated
C
=
.PP
Expired
D
=
.PP
Restated (ExecutionRpt sent unsolicited by sellside, with
ExecRestatementReason set)
E
=
.PP
Pending Replace (e.g. result of Order Cancel/Replace Request)
F
=
.PP
Trade (partial fill or fill)
G
=
.PP
Trade Correct (formerly an ExecTransType)
H
=
.PP
Trade Cancel (formerly an ExecTransType)
I
=
.PP
Order Status (formerly an ExecTransType)
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ExecType)]
[TradeCaptureReport (body_54526569.html?find=ExecType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
