.TH FIX.4.3 "" "" "Tag #155"
Tag
Field Name
Data Type
Description
Depr.
Valid values
155 (tag155.html)
SettlCurrFxRate (tag155.html)
float
.PP
Foreign exchange rate used to compute SettlCurrAmt from Currency to
SettlCurrency
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=SettlCurrFxRate)]
[ExecutionReport (body_5756.html?find=SettlCurrFxRate)]
[TradeCaptureReport (body_54526569.html?find=SettlCurrFxRate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
