.TH FIX.4.3 "" "" "Tag #158"
Tag
Field Name
Data Type
Description
Depr.
Valid values
158 (tag158.html)
AccruedInterestRate (tag158.html)
Percentage
.PP
Accrued Interest Rate for convertible bonds and fixed income
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AccruedInterestRate)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=AccruedInterestRate)]
[ExecutionReport (body_5756.html?find=AccruedInterestRate)]
[NewOrderCross (body_5350115.html?find=AccruedInterestRate)]
[NewOrderList (body_495369.html?find=AccruedInterestRate)]
[NewOrderSingle (body_495268.html?find=AccruedInterestRate)]
[OrderCancelReplaceRequest (body_495571.html?find=AccruedInterestRate)]
[TradeCaptureReport (body_54526569.html?find=AccruedInterestRate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
