.TH FIX.4.3 "" "" "Tag #159"
Tag
Field Name
Data Type
Description
Depr.
Valid values
159 (tag159.html)
AccruedInterestAmt (tag159.html)
Amt
.PP
Amount of Accrued Interest for convertible bonds and fixed income
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AccruedInterestAmt)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=AccruedInterestAmt)]
[ExecutionReport (body_5756.html?find=AccruedInterestAmt)]
[NewOrderCross (body_5350115.html?find=AccruedInterestAmt)]
[NewOrderList (body_495369.html?find=AccruedInterestAmt)]
[NewOrderSingle (body_495268.html?find=AccruedInterestAmt)]
[OrderCancelReplaceRequest (body_495571.html?find=AccruedInterestAmt)]
[TradeCaptureReport (body_54526569.html?find=AccruedInterestAmt)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
