.TH FIX.4.3 "" "" "Tag #166"
Tag
Field Name
Data Type
Description
Depr.
Valid values
166 (tag166.html)
SettlLocation(replaced) (tag166.html)
String
.PP
No longer used as of FIX 4.3. Included here for reference to prior
versions.
.PP
*** REPLACED FIELD - See "Replaced Features and Supported Approach"
***
.PP
Identifies Settlement Depository or Country Code (ISITC spec)
CED
=
.PP
CEDEL
DTC
=
.PP
Depository Trust Company
EUR
=
.PP
Euroclear
FED
=
.PP
Federal Book Entry
ISO Country Code
=
.PP
Local Market Settle Location
PNY
=
.PP
Physical
PTC
=
.PP
Participant Trust Company
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
