.TH FIX.4.3 "" "" "Tag #167"
Tag
Field Name
Data Type
Description
Depr.
Valid values
167 (tag167.html)
SecurityType (tag167.html)
String
.PP
Indicates type of security. See also the Product and CFICode
fields. It is recommended that CFICode be used instead of
SecurityType for non-Fixed Income instruments.
?
=
.PP
Wildcard entry (used on Security Definition Request message)
ABS
=
.PP
Asset-backed Securities
AMENDED
=
.PP
Amended & Restated
AN
=
.PP
Other Anticipation Notes BAN, GAN, etc.
BA
=
.PP
Bankers Acceptance
BN
=
.PP
Bank Notes
BOX
=
.PP
Bill of Exchanges
BRADY
=
.PP
Brady Bond
BRIDGE
=
.PP
Bridge Loan
CB
=
.PP
Convertible Bond
CD
=
.PP
Certificate of Deposit
CL
=
.PP
Call Loans
CMBS
=
.PP
Corp. Mortgage-backed Securities
CMO
=
.PP
Collateralized Mortgage Obligation
COFO
=
.PP
Certificate of Obligation
COFP
=
.PP
Certificate of Participation
CORP
=
.PP
Corporate Bond
CP
=
.PP
Commercial Paper
CPP
=
.PP
Corporate Private Placement
CS
=
.PP
Common Stock
DEFLTED
=
.PP
Defaulted
DINP
=
.PP
Debtor in Possession
DN
=
.PP
Deposit Notes
DUAL
=
.PP
Dual Currency
FAC
=
.PP
Federal Agency Coupon
FADN
=
.PP
Federal Agency Discount Note
FOR
=
.PP
Foreign Exchange Contract
GO
=
.PP
General Obligation Bonds
IET
=
.PP
IOETTE Mortgage
LOFC
=
.PP
Letter of Credit
LQN
=
.PP
Liquidity Note
MATURED
=
.PP
Matured
MBS
=
.PP
Mortgage-backed Securities
MF
=
.PP
Mutual Fund (i.e. any kind of open-ended Collective Investment
Vehicle)
MIO
=
.PP
Mortgage Interest Only
MLEG
=
.PP
Multi-leg instrument (e.g. options strategy or futures spread.
CFICode can be used to identify if options-based, futures-based,
etc.)
MPO
=
.PP
Mortgage Principal Only
MPP
=
.PP
Mortgage Private Placement
MPT
=
.PP
Miscellaneous Pass-through
MT
=
.PP
Mandatory Tender
MTN
=
.PP
Medium Term Notes
NONE
=
.PP
No Security Type
ONITE
=
.PP
Overnight
PEF
=
.PP
Private Export Funding
PN
=
.PP
Promissory Note
POOL
=
.PP
Agency Pools
PS
=
.PP
Preferred Stock
PZFJ
=
.PP
Plazos Fijos
RAN
=
.PP
Revenue Anticipation Note
REPLACD
=
.PP
Replaced
RETIRED
=
.PP
Retired
REV
=
.PP
Revenue Bonds
RP
=
.PP
Repurchase Agreement
RVLV
=
.PP
Revolver Loan
RVLVTRM
=
.PP
Revolver/Term Loan
RVRP
=
.PP
Reverse Repurchase Agreement
SPCLA
=
.PP
Special Assessment
SPCLO
=
.PP
Special Obligation
SPCLT
=
.PP
Special Tax
STN
=
.PP
Short Term Loan Note
STRUCT
=
.PP
Structured Notes
SWING
=
.PP
Swing Line Facility
TAN
=
.PP
Tax Anticipation Note
TAXA
=
.PP
Tax Allocation
TBA
=
.PP
To be Announced
TBOND
=
.PP
US Treasury Bond
TCAL
=
.PP
Principal strip of a callable bond or note
TD
=
.PP
Time Deposit
TECP
=
.PP
Tax Exempt Commercial Paper
TERM
=
.PP
Term Loan
TINT
=
.PP
Interest strip from any bond or note
TIPS
=
.PP
Treasury Inflation Protected Securities
TPRN
=
.PP
Principal strip from a non-callable bond or note
TRAN
=
.PP
Tax & Revenue Anticipation Note
UST
=
.PP
US Treasury Note/Bond
USTB
=
.PP
US Treasury Bill
VRDN
=
.PP
Variable Rate Demand Note
WAR
=
.PP
Warrant
WITHDRN
=
.PP
Withdrawn
XCN
=
.PP
Extended Comm Note
XLINKD
=
.PP
Indexed Linked
YANK
=
.PP
Yankee Corporate Bond
.PP
   *   *   *   *   *
Used in messages:
[SecurityTypes (body_5354119.html?find=SecurityType)]
[SettlementInstructions (body_505684.html?find=SecurityType)]
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=SecurityType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
