.TH FIX.4.3 "" "" "Tag #169"
Tag
Field Name
Data Type
Description
Depr.
Valid values
169 (tag169.html)
StandInstDbType (tag169.html)
int
.PP
Identifies the Standing Instruction database used
0
=
.PP
Other
1
=
.PP
DTC SID
2
=
.PP
Thomson ALERT
3
=
.PP
A Global Custodian (StandInstDbName must be provided)
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructions (body_505684.html?find=StandInstDbType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
