.TH FIX.4.3 "" "" "Tag #170"
Tag
Field Name
Data Type
Description
Depr.
Valid values
170 (tag170.html)
StandInstDbName (tag170.html)
String
.PP
Name of the Standing Instruction database represented with
StandInstDbType (i.e. the Global Custodian’s name).
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructions (body_505684.html?find=StandInstDbName)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
