.TH FIX.4.3 "" "" "Tag #183"
Tag
Field Name
Data Type
Description
Depr.
Valid values
183 (tag183.html)
CashSettlAgentCode (tag183.html)
String
.PP
BIC (Bank Identification Code--Swift managed) code of the
SettlInstSource\[aq]s local agent bank if SettlDeliveryType=Free
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructions (body_505684.html?find=CashSettlAgentCode)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
