.TH FIX.4.3 "" "" "Tag #192"
Tag
Field Name
Data Type
Description
Depr.
Valid values
192 (tag192.html)
OrderQty2 (tag192.html)
Qty
.PP
OrderQty of the future part of a F/X swap order.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=OrderQty2)]
[MassQuote (body_5250105.html?find=OrderQty2)]
[MassQuoteAcknowledgement (body_515398.html?find=OrderQty2)]
[NewOrderList (body_495369.html?find=OrderQty2)]
[NewOrderSingle (body_495268.html?find=OrderQty2)]
[OrderCancelReplaceRequest (body_495571.html?find=OrderQty2)]
[Quote (body_505583.html?find=OrderQty2)]
[QuoteRequest (body_505482.html?find=OrderQty2)]
[QuoteRequestReject (body_54546571.html?find=OrderQty2)]
[QuoteStatusReport (body_54566573.html?find=OrderQty2)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
