.TH FIX.4.3 "" "" "Tag #206"
Tag
Field Name
Data Type
Description
Depr.
Valid values
206 (tag206.html)
OptAttribute (tag206.html)
char
.PP
Can be used for SecurityType=OPT to identify a particular security.
0-9
=
.PP
single digit version number assigned by exchange following capital
adjustments (0=current, 1=prior, 2=prior to 1, etc).
Can be used for SecurityType
=
.PP
OPT to identify a particular security.
L
=
.PP
Long (a.k.a. American)
S
=
.PP
Short (a.k.a. European)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=OptAttribute)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
