.TH FIX.4.3 "" "" "Tag #209"
Tag
Field Name
Data Type
Description
Depr.
Valid values
209 (tag209.html)
AllocHandlInst (tag209.html)
int
.PP
Indicates how the receiver (i.e. third party) of Allocation message
should handle/process the account details.
1
=
.PP
Match
2
=
.PP
Forward
3
=
.PP
Forward and Match
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AllocHandlInst)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
