.TH FIX.4.3 "" "" "Tag #215"
Tag
Field Name
Data Type
Description
Depr.
Valid values
215 (tag215.html)
NoRoutingIDs (tag215.html)
NumInGroup
.PP
Number of repeating groups of RoutingID and RoutingType values.
.PP
See Volume 3: "Pre-Trade Message Targeting/Routing"
.PP
   *   *   *   *   *
Used in messages:
[Email (body_495167.html?find=NoRoutingIDs)]
[IOI (body_5554.html?find=NoRoutingIDs)]
[News (body_495066.html?find=NoRoutingIDs)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
