.TH FIX.4.3 "" "" "Tag #219"
Tag
Field Name
Data Type
Description
Depr.
Valid values
219 (tag219.html)
Benchmark(Deprecated) (tag219.html)
char
.PP
*** DEPRECATED FIELD - See "Deprecated (Phased-out) Features and
Supported Approach" ***
.PP
For Fixed Income. Identifies the benchmark (e.g. used in
conjunction with the Spread field).
1
=
.PP
CURVE
2
=
.PP
5-YR
3
=
.PP
OLD-5
4
=
.PP
10-YR
5
=
.PP
OLD-10
6
=
.PP
30-YR
7
=
.PP
OLD-30
8
=
.PP
3-MO-LIBOR
9
=
.PP
6-MO-LIBOR
.PP
   *   *   *   *   *
Used in messages:
[IOI (body_5554.html?find=Benchmark(Deprecated))]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
