.TH FIX.4.3 "" "" "Tag #22"
Tag
Field Name
Data Type
Description
Depr.
Valid values
22 (tag22.html)
SecurityIDSource(formerly named: IDSource prior to FIX 4.3) (tag22.html)
String
.PP
Identifies class or source of the SecurityID value. Required if
SecurityID is specified.
1
=
.PP
CUSIP
2
=
.PP
SEDOL
3
=
.PP
QUIK
4
=
.PP
ISIN number
5
=
.PP
RIC code
6
=
.PP
ISO Currency Code
7
=
.PP
ISO Country Code
8
=
.PP
Exchange Symbol
9
=
.PP
Consolidated Tape Association (CTA) Symbol (SIAC CTS/CQS line
format)
A
=
.PP
Bloomberg Symbol
B
=
.PP
Wertpapier
C
=
.PP
Dutch
D
=
.PP
Valoren
E
=
.PP
Sicovam
F
=
.PP
Belgian
G
=
.PP
Common (Clearstream and Euroclear)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=SecurityIDSource(formerly%20named:%20IDSource%20prior%20to%20FIX%204.3))]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
