.TH FIX.4.3 "" "" "Tag #229"
Tag
Field Name
Data Type
Description
Depr.
Valid values
229 (tag229.html)
TradeOriginationDate (tag229.html)
UTCDate
.PP
Used with Fixed Income for Muncipal New Issue Market. Agreement in
principal between counter-parties prior to actual trade date.
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=TradeOriginationDate)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=TradeOriginationDate)]
[CrossOrderCancelRequest (body_5351117.html?find=TradeOriginationDate)]
[ExecutionReport (body_5756.html?find=TradeOriginationDate)]
[ListCancelRequest (body_504875.html?find=TradeOriginationDate)]
[NewOrderCross (body_5350115.html?find=TradeOriginationDate)]
[NewOrderList (body_495369.html?find=TradeOriginationDate)]
[NewOrderSingle (body_495268.html?find=TradeOriginationDate)]
[OrderCancelReject (body_494857.html?find=TradeOriginationDate)]
[OrderCancelReplaceRequest (body_495571.html?find=TradeOriginationDate)]
[QuoteRequest (body_505482.html?find=TradeOriginationDate)]
[QuoteRequestReject (body_54546571.html?find=TradeOriginationDate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
