.TH FIX.4.3 "" "" "Tag #231"
Tag
Field Name
Data Type
Description
Depr.
Valid values
231 (tag231.html)
ContractMultiplier (tag231.html)
float
.PP
Specifies the ratio or multiply factor to convert from "nominal"
units (e.g. contracts) to total units (e.g. shares) (e.g. 1.0, 100,
1000, etc). Applicable For Fixed Income, Convertible Bonds,
Derivatives, etc. Note: If used, quantities should be expressed in
the "nominal" (e.g. contracts vs. shares) amount.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=ContractMultiplier)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
