.TH FIX.4.3 "" "" "Tag #233"
Tag
Field Name
Data Type
Description
Depr.
Valid values
233 (tag233.html)
StipulationType (tag233.html)
String
.PP
For Fixed Income. Type of Stipulation.
.PP
Values include:
.PP
GEOG = Geographics
.PP
ISSUE = Year of Issue
.PP
LOTVAR = Lot Variance (value in percent maximum over- or
under-allocation allowed)
.PP
MAT = Maturity Year
.PP
PIECES = Number of Pieces
.PP
PMAX = Pools Maximum
.PP
PPM = Pools per Million
.PP
PPL = Pools per Lot
.PP
PPT = Pools per Trade
.PP
PROD = Production Year
.PP
TRDVAR = Trade Variance (value in percent maximum over- or
under-allocation allowed)
.PP
WAC = Weighted Average Coupon (value in percent)
.PP
WAL = Weighted Average Life (value in months)
.PP
WALA = Weighted Average Loan Age (value in months)
.PP
WAM = Weighted Average Maturity (value in months)
.PP
or the following Prepayment Speeds
.PP
 SMM = Single Monthly Mortality
.PP
 CPR = Constant Prepayment Rate
.PP
 CPY = Constant Prepayment Yield
.PP
 CPP = Constant Prepayment Penalty
.PP
 ABS = Absolute Prepayment Speed
.PP
 MPR = Monthly Prepayment Rate
.PP
 PSA = % of BMA Prepayment Curve
.PP
 PPC = % of Prospectus Prepayment Curve
.PP
 MHP = % of Manufactured Housing Prepayment Curve
.PP
 HEP = final CPR of Home Equity Prepayment Curve
.PP
Other types may be used by mutual agreement of the counterparties.
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
ABS
=
.PP
Absolute Prepayment Speed
CPP
=
.PP
Constant Prepayment Penalty
CPR
=
.PP
Constant Prepayment Rate
CPY
=
.PP
Constant Prepayment Yield
GEOG
=
.PP
Geographics
HEP
=
.PP
final CPR of Home Equity Prepayment Curve
ISSUE
=
.PP
Year of Issue
LOTVAR
=
.PP
Lot Variance (value in percent maximum over- or under-allocation
allowed)
MAT
=
.PP
Maturity Year
MHP
=
.PP
% of Manufactured Housing Prepayment Curve
MPR
=
.PP
Monthly Prepayment Rate
PIECES
=
.PP
Number of Pieces
PMAX
=
.PP
Pools Maximum
PPC
=
.PP
% of Prospectus Prepayment Curve
PPL
=
.PP
Pools per Lot
PPM
=
.PP
Pools per Million
PPT
=
.PP
Pools per Trade
PROD
=
.PP
Production Year
PSA
=
.PP
% of BMA Prepayment Curve
SMM
=
.PP
Single Monthly Mortality
TRDVAR
=
.PP
Trade Variance (value in percent maximum over- or under-allocation
allowed)
WAC
=
.PP
Weighted Average Coupon (value in percent)
WAL
=
.PP
Weighted Average Life (value in months)
WALA
=
.PP
Weighted Average Loan Age (value in months)
WAM
=
.PP
Weighted Average Maturity (value in months)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Stipulations (body_49484957.html?find=StipulationType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
