.TH FIX.4.3 "" "" "Tag #237"
Tag
Field Name
Data Type
Description
Depr.
Valid values
237 (tag237.html)
TotalTakedown (tag237.html)
Amt
.PP
The price at which the securities are distributed to the different
members of an underwriting group for the primary market in
Municipals, total gross underwriter\[aq]s spread.
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=TotalTakedown)]
[ExecutionReport (body_5756.html?find=TotalTakedown)]
[TradeCaptureReport (body_54526569.html?find=TotalTakedown)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
