.TH FIX.4.3 "" "" "Tag #242"
Tag
Field Name
Data Type
Description
Depr.
Valid values
242 (tag242.html)
UnderlyingIssueDate (tag242.html)
UTCDate
.PP
Underlying security’s IssueDate.
.PP
See IssueDate (225) field for description
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingIssueDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
