.TH FIX.4.3 "" "" "Tag #248"
Tag
Field Name
Data Type
Description
Depr.
Valid values
248 (tag248.html)
LegCouponPaymentDate (tag248.html)
UTCDate
.PP
Multileg instrument\[aq]s individual leg security’s
CouponPaymentDate.
.PP
See CouponPaymentDate (224) field for description
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegCouponPaymentDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
