.TH FIX.4.3 "" "" "Tag #25"
Tag
Field Name
Data Type
Description
Depr.
Valid values
25 (tag25.html)
IOIQltyInd (tag25.html)
char
.PP
Relative quality of indication
H
=
.PP
High
L
=
.PP
Low
M
=
.PP
Medium
.PP
   *   *   *   *   *
Used in messages:
[IOI (body_5554.html?find=IOIQltyInd)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
