.TH FIX.4.3 "" "" "Tag #250"
Tag
Field Name
Data Type
Description
Depr.
Valid values
250 (tag250.html)
LegRepoCollateralSecurityType (tag250.html)
int
.PP
Multileg instrument\[aq]s individual leg security’s
RepoCollateralSecurityType.
.PP
See RepoCollateralSecurityType (239) field for description
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegRepoCollateralSecurityType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
