.TH FIX.4.3 "" "" "Tag #259"
Tag
Field Name
Data Type
Description
Depr.
Valid values
259 (tag259.html)
BasisFeatureDate (tag259.html)
UTCDate
.PP
BasisFeatureDate allows requesting firms within fixed income the
ability to request an alternative yield-to-worst, -maturity,
-extended or other call. This flows through the confirm process.
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=BasisFeatureDate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
