.TH FIX.4.3 "" "" "Tag #263"
Tag
Field Name
Data Type
Description
Depr.
Valid values
263 (tag263.html)
SubscriptionRequestType (tag263.html)
char
.PP
Subscription Request Type
0
=
.PP
Snapshot
1
=
.PP
Snapshot + Updates (Subscribe)
2
=
.PP
Disable previous Snapshot + Update Request (Unsubscribe)
.PP
   *   *   *   *   *
Used in messages:
[DerivativeSecurityListRequest (body_5357122.html?find=SubscriptionRequestType)]
[MarketDataRequest (body_505786.html?find=SubscriptionRequestType)]
[QuoteStatusRequest (body_515297.html?find=SubscriptionRequestType)]
[RFQRequest (body_54556572.html?find=SubscriptionRequestType)]
[SecurityDefinitionRequest (body_515499.html?find=SubscriptionRequestType)]
[SecurityListRequest (body_5355120.html?find=SubscriptionRequestType)]
[SecurityStatusRequest (body_5156101.html?find=SubscriptionRequestType)]
[SecurityTypes (body_5354119.html?find=SubscriptionRequestType)]
[TradeCaptureReportRequest (body_54516568.html?find=SubscriptionRequestType)]
[TradingSessionStatusRequest (body_5248103.html?find=SubscriptionRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
