.TH FIX.4.3 "" "" "Tag #27"
Tag
Field Name
Data Type
Description
Depr.
Valid values
27 (tag27.html)
IOIQty (formerly named: IOIShares prior to FIX 4.3) (tag27.html)
String
.PP
Quantity (e.g. number of shares) in numeric form or relative size.
L
=
.PP
Large
M
=
.PP
Medium
S
=
.PP
Small
.PP
   *   *   *   *   *
Used in messages:
[IOI (body_5554.html?find=IOIQty%20(formerly%20named:%20IOIShares%20prior%20to%20FIX%204.3))]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
