.TH FIX.4.3 "" "" "Tag #277"
Tag
Field Name
Data Type
Description
Depr.
Valid values
277 (tag277.html)
TradeCondition (tag277.html)
MultipleValueString
.PP
Space-delimited list of conditions describing a trade
A
=
.PP
Cash (only) Market
B
=
.PP
Average Price Trade
C
=
.PP
Cash Trade (same day clearing)
D
=
.PP
Next Day (only) Market
E
=
.PP
Opening / Reopening Trade Detail
F
=
.PP
Intraday Trade Detail
G
=
.PP
Rule 127 Trade (NYSE)
H
=
.PP
Rule 155 Trade (Amex)
I
=
.PP
Sold Last (late reporting)
J
=
.PP
Next Day Trade (next day clearing)
K
=
.PP
Opened (late report of opened trade)
L
=
.PP
Seller
M
=
.PP
Sold (out of sequence)
N
=
.PP
Stopped Stock (guarantee of price but does not execute the order)
P
=
.PP
Imbalance More Buyers (Cannot be used in combination with Q)
Q
=
.PP
Imbalance More Sellers (Cannot be used in combination with P)
R
=
.PP
Opening Price
.PP
   *   *   *   *   *
Used in messages:
[MarketDataIncrementalRefresh (body_514988.html?find=TradeCondition)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=TradeCondition)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
