.TH FIX.4.3 "" "" "Tag #297"
Tag
Field Name
Data Type
Description
Depr.
Valid values
297 (tag297.html)
QuoteStatus(formerly named: QuoteAckStatus prior to FIX 4.3) (tag297.html)
int
.PP
Identifies the status of the quote acknowledgement.
0
=
.PP
Accepted
1
=
.PP
Canceled for Symbol(s)
2
=
.PP
Canceled for Security Type(s)
3
=
.PP
Canceled for Underlying
4
=
.PP
Canceled All
5
=
.PP
Rejected
6
=
.PP
Removed from Market
7
=
.PP
Expired
8
=
.PP
Query
9
=
.PP
Quote Not Found
10
=
.PP
Pending
.PP
   *   *   *   *   *
Used in messages:
[MassQuoteAcknowledgement (body_515398.html?find=QuoteStatus(formerly%20named:%20QuoteAckStatus%20prior%20to%20FIX%204.3))]
[QuoteStatusReport (body_54566573.html?find=QuoteStatus(formerly%20named:%20QuoteAckStatus%20prior%20to%20FIX%204.3))]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
