.TH FIX.4.3 "" "" "Tag #301"
Tag
Field Name
Data Type
Description
Depr.
Valid values
301 (tag301.html)
QuoteResponseLevel (tag301.html)
int
.PP
Level of Response requested from receiver of quote messages.
0
=
.PP
No Acknowledgement (Default)
1
=
.PP
Acknowledge only negative or erroneous quotes
2
=
.PP
Acknowledge each quote messages
.PP
   *   *   *   *   *
Used in messages:
[MassQuote (body_5250105.html?find=QuoteResponseLevel)]
[MassQuoteAcknowledgement (body_515398.html?find=QuoteResponseLevel)]
[Quote (body_505583.html?find=QuoteResponseLevel)]
[QuoteCancel (body_515190.html?find=QuoteResponseLevel)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
