.TH FIX.4.3 "" "" "Tag #314"
Tag
Field Name
Data Type
Description
Depr.
Valid values
314 (tag314.html)
UnderlyingMaturityDay(replaced) (tag314.html)
day-of-month
.PP
No longer used as of FIX 4.3. Included here for reference to prior
versions.
.PP
*** REPLACED FIELD - See "Replaced Features and Supported Approach"
***
.PP
Underlying security’s MaturityDay.
.PP
See MaturityDay field for description
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
