.TH FIX.4.3 "" "" "Tag #32"
Tag
Field Name
Data Type
Description
Depr.
Valid values
32 (tag32.html)
LastQty(formerly named: LastShares prior to FIX 4.3) (tag32.html)
Qty
.PP
Quantity (e.g. shares) bought/sold on this (last) fill.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=LastQty(formerly%20named:%20LastShares%20prior%20to%20FIX%204.3))]
[DontKnowTradeDK (body_505381.html?find=LastQty(formerly%20named:%20LastShares%20prior%20to%20FIX%204.3))]
[ExecutionReport (body_5756.html?find=LastQty(formerly%20named:%20LastShares%20prior%20to%20FIX%204.3))]
[TradeCaptureReport (body_54526569.html?find=LastQty(formerly%20named:%20LastShares%20prior%20to%20FIX%204.3))]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
