.TH FIX.4.3 "" "" "Tag #325"
Tag
Field Name
Data Type
Description
Depr.
Valid values
325 (tag325.html)
UnsolicitedIndicator (tag325.html)
Boolean
.PP
Indicates whether or not message is being sent as a result of a
subscription request or not.
N
=
.PP
Message is being sent as a result of a prior request
Y
=
.PP
Message is being sent unsolicited
.PP
   *   *   *   *   *
Used in messages:
[SecurityStatus (body_5157102.html?find=UnsolicitedIndicator)]
[TradingSessionStatus (body_5249104.html?find=UnsolicitedIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
