.TH FIX.4.3 "" "" "Tag #336"
Tag
Field Name
Data Type
Description
Depr.
Valid values
336 (tag336.html)
TradingSessionID (tag336.html)
String
.PP
Identifier for Trading Session
.PP
Can be used to represent a specific market trading session (e.g.
“PRE-OPEN", "CROSS_2", "AFTER-HOURS", "TOSTNET1", "TOSTNET2", etc).
.PP
Values should be bi-laterally agreed to between counterparties.
.PP
Firms may register Trading Session values on the FIX website
(presently a document maintained within “ECN and Exchanges” working
group section).
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=TradingSessionID)]
[Allocation (body_495774.html?find=TradingSessionID)]
[BidRequest (body_5252107.html?find=TradingSessionID)]
[BidResponse (body_5253108.html?find=TradingSessionID)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=TradingSessionID)]
[DerivativeSecurityList (body_54486565.html?find=TradingSessionID)]
[DerivativeSecurityListRequest (body_5357122.html?find=TradingSessionID)]
[ExecutionReport (body_5756.html?find=TradingSessionID)]
[MarketDataIncrementalRefresh (body_514988.html?find=TradingSessionID)]
[MarketDataRequest (body_505786.html?find=TradingSessionID)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=TradingSessionID)]
[MassQuote (body_5250105.html?find=TradingSessionID)]
[MassQuoteAcknowledgement (body_515398.html?find=TradingSessionID)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=TradingSessionID)]
[NewOrderCross (body_5350115.html?find=TradingSessionID)]
[NewOrderList (body_495369.html?find=TradingSessionID)]
[NewOrderMultileg (body_54496566.html?find=TradingSessionID)]
[NewOrderSingle (body_495268.html?find=TradingSessionID)]
[OrderCancelReplaceRequest (body_495571.html?find=TradingSessionID)]
[OrderMassCancelReport (body_5349114.html?find=TradingSessionID)]
[OrderMassCancelRequest (body_5348113.html?find=TradingSessionID)]
[OrderMassStatusRequest (body_54536570.html?find=TradingSessionID)]
[Quote (body_505583.html?find=TradingSessionID)]
[QuoteCancel (body_515190.html?find=TradingSessionID)]
[QuoteRequest (body_505482.html?find=TradingSessionID)]
[QuoteRequestReject (body_54546571.html?find=TradingSessionID)]
[QuoteStatusReport (body_54566573.html?find=TradingSessionID)]
[QuoteStatusRequest (body_515297.html?find=TradingSessionID)]
[RFQRequest (body_54556572.html?find=TradingSessionID)]
[SecurityDefinition (body_5155100.html?find=TradingSessionID)]
[SecurityDefinitionRequest (body_515499.html?find=TradingSessionID)]
[SecurityList (body_5356121.html?find=TradingSessionID)]
[SecurityListRequest (body_5355120.html?find=TradingSessionID)]
[SecurityStatus (body_5157102.html?find=TradingSessionID)]
[SecurityStatusRequest (body_5156101.html?find=TradingSessionID)]
[SecurityTypeRequest (body_5353118.html?find=TradingSessionID)]
[SecurityTypes (body_5354119.html?find=TradingSessionID)]
[SettlementInstructions (body_505684.html?find=TradingSessionID)]
[TradeCaptureReport (body_54526569.html?find=TradingSessionID)]
[TradingSessionStatus (body_5249104.html?find=TradingSessionID)]
[TradingSessionStatusRequest (body_5248103.html?find=TradingSessionID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
