.TH FIX.4.3 "" "" "Tag #342"
Tag
Field Name
Data Type
Description
Depr.
Valid values
342 (tag342.html)
TradSesOpenTime (tag342.html)
UTCTimestamp
.PP
Time of the opening of the trading session
.PP
   *   *   *   *   *
Used in messages:
[TradingSessionStatus (body_5249104.html?find=TradSesOpenTime)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
