.TH FIX.4.3 "" "" "Tag #35"
Tag
Field Name
Data Type
Description
Depr.
Valid values
35 (tag35.html)
MsgType (tag35.html)
String
.PP
Defines message type. ALWAYS THIRD FIELD IN MESSAGE. (Always
unencrypted)
.PP
Note: A "U" as the first character in the MsgType field (i.e. U1,
U2, etc) indicates that the message format is privately defined
between the sender and receiver.
m
=
.PP
List Strike Price
l
=
.PP
Bid Response (lowercase L)
k
=
.PP
Bid Request
j
=
.PP
Business Message Reject
i
=
.PP
Mass Quote
h
=
.PP
Trading Session Status
q
=
.PP
Order Mass Cancel Request
AE
=
.PP
Trade Capture Report
o
=
.PP
Registration Instructions
z
=
.PP
Derivative Security List Request
AI
=
.PP
Quote Status Report
AH
=
.PP
RFQ Request
AG
=
.PP
Quote Request Reject
AF
=
.PP
Order Mass Status Request
n
=
.PP
XML message (e.g. non-FIX MsgType)
AD
=
.PP
Trade Capture Report Request
g
=
.PP
Trading Session Status Request
AC
=
.PP
Multileg Order Cancel/Replace (a.k.a. Multileg Order Modification
Request)
AA
=
.PP
Derivative Security List
r
=
.PP
Order Mass Cancel Report
y
=
.PP
Security List
x
=
.PP
Security List Request
w
=
.PP
Security Types
v
=
.PP
Security Type Request
u
=
.PP
Cross Order Cancel Request
t
=
.PP
Cross Order Cancel/Replace Request (a.k.a. Cross Order Modification
Request)
s
=
.PP
New Order - Cross
AB
=
.PP
New Order - Multileg
9
=
.PP
Order Cancel Reject
7
=
.PP
Advertisement
M
=
.PP
List Status Request
E
=
.PP
Order List
D
=
.PP
Order Single
C
=
.PP
Email
B
=
.PP
News
A
=
.PP
Logon
N
=
.PP
List Status
f
=
.PP
Security Status
P
=
.PP
Allocation ACK
8
=
.PP
Execution Report
0
=
.PP
Heartbeat
1
=
.PP
Test Request
2
=
.PP
Resend Request
3
=
.PP
Reject
4
=
.PP
Sequence Reset
5
=
.PP
Logout
6
=
.PP
Indication of Interest
G
=
.PP
Order Cancel/Replace Request
K
=
.PP
List Cancel Request
e
=
.PP
Security Status Request
d
=
.PP
Security Definition
c
=
.PP
Security Definition Request
b
=
.PP
Mass Quote Acknowledgement
a
=
.PP
Quote Status Request
Z
=
.PP
Quote Cancel
Y
=
.PP
Market Data Request Reject
F
=
.PP
Order Cancel Request
J
=
.PP
Allocation
p
=
.PP
Registration Instructions Response
L
=
.PP
List Execute
X
=
.PP
Market Data-Incremental Refresh
W
=
.PP
Market Data-Snapshot/Full Refresh
V
=
.PP
Market Data Request
T
=
.PP
Settlement Instructions
S
=
.PP
Quote
R
=
.PP
Quote Request
Q
=
.PP
Dont Know Trade (DK)
H
=
.PP
Order Status Request
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=MsgType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
