.TH FIX.4.3 "" "" "Tag #355"
Tag
Field Name
Data Type
Description
Depr.
Valid values
355 (tag355.html)
EncodedText (tag355.html)
data
.PP
Encoded (non-ASCII characters) representation of the Text field in
the encoded format specified via the MessageEncoding field. If
used, the ASCII (English) representation should also be specified
in the Text field.
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=EncodedText)]
[Allocation (body_495774.html?find=EncodedText)]
[AllocationAck (body_505280.html?find=EncodedText)]
[BidRequest (body_5252107.html?find=EncodedText)]
[BidResponse (body_5253108.html?find=EncodedText)]
[BusinessMessageReject (body_5251106.html?find=EncodedText)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=EncodedText)]
[CrossOrderCancelRequest (body_5351117.html?find=EncodedText)]
[DerivativeSecurityList (body_54486565.html?find=EncodedText)]
[DerivativeSecurityListRequest (body_5357122.html?find=EncodedText)]
[DontKnowTradeDK (body_505381.html?find=EncodedText)]
[Email (body_495167.html?find=EncodedText)]
[ExecutionReport (body_5756.html?find=EncodedText)]
[IOI (body_5554.html?find=EncodedText)]
[ListCancelRequest (body_504875.html?find=EncodedText)]
[ListExecute (body_504976.html?find=EncodedText)]
[ListStatus (body_505178.html?find=EncodedText)]
[ListStatusRequest (body_505077.html?find=EncodedText)]
[ListStrikePrice (body_5254109.html?find=EncodedText)]
[Logout (body_5453.html?find=EncodedText)]
[MarketDataIncrementalRefresh (body_514988.html?find=EncodedText)]
[MarketDataRequestReject (body_515089.html?find=EncodedText)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=EncodedText)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=EncodedText)]
[NewOrderCross (body_5350115.html?find=EncodedText)]
[NewOrderList (body_495369.html?find=EncodedText)]
[NewOrderMultileg (body_54496566.html?find=EncodedText)]
[NewOrderSingle (body_495268.html?find=EncodedText)]
[News (body_495066.html?find=EncodedText)]
[OrderCancelReject (body_494857.html?find=EncodedText)]
[OrderCancelReplaceRequest (body_495571.html?find=EncodedText)]
[OrderCancelRequest (body_495470.html?find=EncodedText)]
[OrderMassCancelReport (body_5349114.html?find=EncodedText)]
[OrderMassCancelRequest (body_5348113.html?find=EncodedText)]
[Quote (body_505583.html?find=EncodedText)]
[QuoteRequest (body_505482.html?find=EncodedText)]
[QuoteRequestReject (body_54546571.html?find=EncodedText)]
[Reject (body_5251.html?find=EncodedText)]
[SecurityDefinition (body_5155100.html?find=EncodedText)]
[SecurityDefinitionRequest (body_515499.html?find=EncodedText)]
[SecurityList (body_5356121.html?find=EncodedText)]
[SecurityListRequest (body_5355120.html?find=EncodedText)]
[SecurityStatus (body_5157102.html?find=EncodedText)]
[SecurityTypeRequest (body_5353118.html?find=EncodedText)]
[SecurityTypes (body_5354119.html?find=EncodedText)]
[TradeCaptureReport (body_54526569.html?find=EncodedText)]
[TradeCaptureReportRequest (body_54516568.html?find=EncodedText)]
[TradingSessionStatus (body_5249104.html?find=EncodedText)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
