.TH FIX.4.3 "" "" "Tag #366"
Tag
Field Name
Data Type
Description
Depr.
Valid values
366 (tag366.html)
AllocPrice (tag366.html)
Price
.PP
Executed price for an AllocAccount entry used when using “executed
price” vs. “average price” allocations (e.g. Japan).
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AllocPrice)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
