.TH FIX.4.3 "" "" "Tag #374"
Tag
Field Name
Data Type
Description
Depr.
Valid values
374 (tag374.html)
BidRequestTransType (tag374.html)
char
.PP
Identifies the Bid Request message type.
C
=
.PP
Cancel
N
=
.PP
New
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=BidRequestTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
