.TH FIX.4.3 "" "" "Tag #38"
Tag
Field Name
Data Type
Description
Depr.
Valid values
38 (tag38.html)
OrderQty (tag38.html)
Qty
.PP
Quantity ordered. This represents the number of shares for equities
or based on normal convention the number of contracts for options,
futures, convertible bonds, etc.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[QuoteRequest (body_505482.html?find=OrderQty)]
[QuoteRequestReject (body_54546571.html?find=OrderQty)]
.PP
   *   *   *   *   *
Used in components:
[OrderQtyData (body_49484949.html?find=OrderQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
