.TH FIX.4.3 "" "" "Tag #380"
Tag
Field Name
Data Type
Description
Depr.
Valid values
380 (tag380.html)
BusinessRejectReason (tag380.html)
int
.PP
Code to identify reason for a Business Message Reject message.
0
=
.PP
Other
1
=
.PP
Unkown ID
2
=
.PP
Unknown Security
3
=
.PP
Unsupported Message Type
4
=
.PP
Application not available
5
=
.PP
Conditionally Required Field Missing
6
=
.PP
Not authorized
7
=
.PP
DeliverTo firm not available at this time
.PP
   *   *   *   *   *
Used in messages:
[BusinessMessageReject (body_5251106.html?find=BusinessRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
