.TH FIX.4.3 "" "" "Tag #388"
Tag
Field Name
Data Type
Description
Depr.
Valid values
388 (tag388.html)
DiscretionInst (tag388.html)
char
.PP
Code to identify the price a DiscretionOffset is related to and
should be mathematically added to.
0
=
.PP
Related to displayed price
1
=
.PP
Related to market price
2
=
.PP
Related to primary price
3
=
.PP
Related to local primary price
4
=
.PP
Related to midpoint price
5
=
.PP
Related to last trade price
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=DiscretionInst)]
[ExecutionReport (body_5756.html?find=DiscretionInst)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=DiscretionInst)]
[NewOrderCross (body_5350115.html?find=DiscretionInst)]
[NewOrderList (body_495369.html?find=DiscretionInst)]
[NewOrderMultileg (body_54496566.html?find=DiscretionInst)]
[NewOrderSingle (body_495268.html?find=DiscretionInst)]
[OrderCancelReplaceRequest (body_495571.html?find=DiscretionInst)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
