.TH FIX.4.3 "" "" "Tag #389"
Tag
Field Name
Data Type
Description
Depr.
Valid values
389 (tag389.html)
DiscretionOffset (tag389.html)
PriceOffset
.PP
Amount (signed) added to the “related to” price specified via
DiscretionInst.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=DiscretionOffset)]
[ExecutionReport (body_5756.html?find=DiscretionOffset)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=DiscretionOffset)]
[NewOrderCross (body_5350115.html?find=DiscretionOffset)]
[NewOrderList (body_495369.html?find=DiscretionOffset)]
[NewOrderMultileg (body_54496566.html?find=DiscretionOffset)]
[NewOrderSingle (body_495268.html?find=DiscretionOffset)]
[OrderCancelReplaceRequest (body_495571.html?find=DiscretionOffset)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
