.TH FIX.4.3 "" "" "Tag #394"
Tag
Field Name
Data Type
Description
Depr.
Valid values
394 (tag394.html)
BidType (tag394.html)
int
.PP
Code to identify the type of Bid Request.
1
=
.PP
Non Disclosed Style (e.g. US/European)
2
=
.PP
Disclosed Style (e.g. Japanese)
3
=
.PP
No Bidding Process
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=BidType)]
[NewOrderList (body_495369.html?find=BidType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
