.TH FIX.4.3 "" "" "Tag #395"
Tag
Field Name
Data Type
Description
Depr.
Valid values
395 (tag395.html)
NumTickets (tag395.html)
int
.PP
Total number of tickets.
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=NumTickets)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
