.TH FIX.4.3 "" "" "Tag #399"
Tag
Field Name
Data Type
Description
Depr.
Valid values
399 (tag399.html)
BidDescriptorType (tag399.html)
int
.PP
Code to identify the type of BidDescriptor.
1
=
.PP
Sector
2
=
.PP
Country
3
=
.PP
Index
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=BidDescriptorType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
