.TH FIX.4.3 "" "" "Tag #40"
Tag
Field Name
Data Type
Description
Depr.
Valid values
40 (tag40.html)
OrdType (tag40.html)
char
.PP
Order type.
1
=
.PP
Market
2
=
.PP
Limit
3
=
.PP
Stop
4
=
.PP
Stop limit
5
=
.PP
Market on close (Deprecated)
6
=
.PP
With or without
7
=
.PP
Limit or better
8
=
.PP
Limit with or without
9
=
.PP
On basis
A
=
.PP
On close (Deprecated)
B
=
.PP
Limit on close (Deprecated)
C
=
.PP
Forex - Market (Deprecated)
D
=
.PP
Previously quoted
E
=
.PP
Previously indicated
F
=
.PP
Forex - Limit (Deprecated)
G
=
.PP
Forex - Swap
H
=
.PP
Forex - Previously Quoted (Deprecated)
I
=
.PP
Funari (Limit Day Order with unexecuted portion handled as Market
On Close. e.g. Japan)
J
=
.PP
Market If Touched (MIT)
K
=
.PP
Market with Leftover as Limit (market order then unexecuted
quantity becomes limit order at last price)
L
=
.PP
Previous Fund Valuation Point (Historic pricing) (for CIV)
M
=
.PP
Next Fund Valuation Point (Forward pricing) (for CIV)
P
=
.PP
Pegged
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=OrdType)]
[ExecutionReport (body_5756.html?find=OrdType)]
[MassQuote (body_5250105.html?find=OrdType)]
[MassQuoteAcknowledgement (body_515398.html?find=OrdType)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=OrdType)]
[NewOrderCross (body_5350115.html?find=OrdType)]
[NewOrderList (body_495369.html?find=OrdType)]
[NewOrderMultileg (body_54496566.html?find=OrdType)]
[NewOrderSingle (body_495268.html?find=OrdType)]
[OrderCancelReplaceRequest (body_495571.html?find=OrdType)]
[Quote (body_505583.html?find=OrdType)]
[QuoteRequest (body_505482.html?find=OrdType)]
[QuoteRequestReject (body_54546571.html?find=OrdType)]
[QuoteStatusReport (body_54566573.html?find=OrdType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
