.TH FIX.4.3 "" "" "Tag #41"
Tag
Field Name
Data Type
Description
Depr.
Valid values
41 (tag41.html)
OrigClOrdID (tag41.html)
String
.PP
ClOrdID of the previous order (NOT the initial order of the day) as
assigned by the institution, used to identify the previous order in
cancel and cancel/replace requests.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=OrigClOrdID)]
[CrossOrderCancelRequest (body_5351117.html?find=OrigClOrdID)]
[ExecutionReport (body_5756.html?find=OrigClOrdID)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=OrigClOrdID)]
[OrderCancelReject (body_494857.html?find=OrigClOrdID)]
[OrderCancelReplaceRequest (body_495571.html?find=OrigClOrdID)]
[OrderCancelRequest (body_495470.html?find=OrigClOrdID)]
[OrderMassCancelReport (body_5349114.html?find=OrigClOrdID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
