.TH FIX.4.3 "" "" "Tag #415"
Tag
Field Name
Data Type
Description
Depr.
Valid values
415 (tag415.html)
ProgPeriodInterval (tag415.html)
int
.PP
Time in minutes between each ListStatus report sent by SellSide.
Zero means don’t send status.
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=ProgPeriodInterval)]
[NewOrderList (body_495369.html?find=ProgPeriodInterval)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
