.TH FIX.4.3 "" "" "Tag #417"
Tag
Field Name
Data Type
Description
Depr.
Valid values
417 (tag417.html)
NumBidders (tag417.html)
int
.PP
Indicates the total number of bidders on the list
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=NumBidders)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
