.TH FIX.4.3 "" "" "Tag #419"
Tag
Field Name
Data Type
Description
Depr.
Valid values
419 (tag419.html)
BasisPxType (tag419.html)
char
.PP
Code to represent the basis price type.
2
=
.PP
Closing Price at morning session
3
=
.PP
Closing Price
4
=
.PP
Current price
5
=
.PP
SQ
6
=
.PP
VWAP through a day
7
=
.PP
VWAP through a morning session
8
=
.PP
VWAP through an afternoon session
9
=
.PP
VWAP through a day except YORI (an opening auction)
A
=
.PP
VWAP through a morning session except YORI (an opening auction)
B
=
.PP
VWAP through an afternoon session except YORI (an opening auction)
C
=
.PP
Strike
D
=
.PP
Open
Z
=
.PP
Others
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=BasisPxType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
