.TH FIX.4.3 "" "" "Tag #420"
Tag
Field Name
Data Type
Description
Depr.
Valid values
420 (tag420.html)
NoBidComponents (tag420.html)
NumInGroup
.PP
Indicates the number of list entries.
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=NoBidComponents)]
[BidResponse (body_5253108.html?find=NoBidComponents)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
