.TH FIX.4.3 "" "" "Tag #430"
Tag
Field Name
Data Type
Description
Depr.
Valid values
430 (tag430.html)
NetGrossInd (tag430.html)
int
.PP
Code to represent whether value is net (inclusive of tax) or gross.
1
=
.PP
Net
2
=
.PP
Gross
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=NetGrossInd)]
[BidResponse (body_5253108.html?find=NetGrossInd)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
