.TH FIX.4.3 "" "" "Tag #431"
Tag
Field Name
Data Type
Description
Depr.
Valid values
431 (tag431.html)
ListOrderStatus (tag431.html)
int
.PP
Code to represent the status of a list order.
1
=
.PP
InBiddingProcess
2
=
.PP
ReceivedForExecution
3
=
.PP
Executing
4
=
.PP
Canceling
5
=
.PP
Alert
6
=
.PP
All Done
7
=
.PP
Reject
.PP
   *   *   *   *   *
Used in messages:
[ListStatus (body_505178.html?find=ListOrderStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
