.TH FIX.4.3 "" "" "Tag #432"
Tag
Field Name
Data Type
Description
Depr.
Valid values
432 (tag432.html)
ExpireDate (tag432.html)
LocalMktDate
.PP
Date of order expiration (last day the order can trade), always
expressed in terms of the local market date. The time at which the
order expires is determined by the local market’s business
practices
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=ExpireDate)]
[ExecutionReport (body_5756.html?find=ExpireDate)]
[MarketDataIncrementalRefresh (body_514988.html?find=ExpireDate)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=ExpireDate)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=ExpireDate)]
[NewOrderCross (body_5350115.html?find=ExpireDate)]
[NewOrderList (body_495369.html?find=ExpireDate)]
[NewOrderMultileg (body_54496566.html?find=ExpireDate)]
[NewOrderSingle (body_495268.html?find=ExpireDate)]
[OrderCancelReplaceRequest (body_495571.html?find=ExpireDate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
