.TH FIX.4.3 "" "" "Tag #437"
Tag
Field Name
Data Type
Description
Depr.
Valid values
437 (tag437.html)
ContraTradeQty (tag437.html)
Qty
.PP
Quantity traded with the ContraBroker.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ContraTradeQty)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
