.TH FIX.4.3 "" "" "Tag #447"
Tag
Field Name
Data Type
Description
Depr.
Valid values
447 (tag447.html)
PartyIDSource (tag447.html)
char
.PP
Identifies class or source of the PartyID value. Required if
PartyID is specified. Note: applicable values depend upon PartyRole
specified.
.PP
See “Appendix 6-G – Use of <Parties> Component Block”
.PP
Valid values:
.PP
Applicable to all PartyRoles unless otherwise specified:
.PP
B = BIC (Bank Identification Code—Swift managed) code (ISO 9362 -
See "Appendix 6-B")
.PP
C = Generally accepted market participant identifier (e.g. NASD
mnemonic)
.PP
D = Proprietary/Custom code
.PP
E = ISO Country Code
.PP
F = Settlement Entity Location (note if Local Market Settlement use
“E = ISO Country Code”) (see “Appendix 6-G” for
1
=
.PP
Korean Investor ID
2
=
.PP
Taiwanese Qualified Foreign Investor ID QFII / FID
3
=
.PP
Taiwanese Trading Account
4
=
.PP
Malaysian Central Depository (MCD) number
5
=
.PP
Chinese B Share (Shezhen and Shanghai)
6
=
.PP
UK National Insurance or Pension Number
7
=
.PP
US Social Security Number
8
=
.PP
US Employer Identification Number
9
=
.PP
Australian Business Number
A
=
.PP
Australian Tax File Number
B
=
.PP
BIC (Bank Identification CodeSwift managed) code (ISO 9362 - See
Appendix 6-B)
C
=
.PP
Generally accepted market participant identifier (e.g. NASD
mnemonic)
D
=
.PP
Proprietary/Custom code
E
=
.PP
ISO Country Code
F
=
.PP
Settlement Entity Location (note if Local Market Settlement use E =
ISO Country Code) (see Appendix 6-G for valid values)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Parties (body_49484950.html?find=PartyIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
