.TH FIX.4.3 "" "" "Tag #453"
Tag
Field Name
Data Type
Description
Depr.
Valid values
453 (tag453.html)
NoPartyIDs (tag453.html)
NumInGroup
.PP
Number of PartyID, PartyIDSource, and PartyRole entries
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Parties (body_49484950.html?find=NoPartyIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
