.TH FIX.4.3 "" "" "Tag #46"
Tag
Field Name
Data Type
Description
Depr.
Valid values
46 (tag46.html)
RelatdSym (no longer used) (tag46.html)
String
.PP
No longer used as of FIX 4.3. Included here for reference to prior
versions.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
