.TH FIX.4.3 "" "" "Tag #460"
Tag
Field Name
Data Type
Description
Depr.
Valid values
460 (tag460.html)
Product (tag460.html)
int
.PP
Indicates the type of product the security is associated with. See
also the CFICode (461) and SecurityType (167) fields.
1
=
.PP
AGENCY
10
=
.PP
MORTGAGE
11
=
.PP
MUNICIPAL
12
=
.PP
OTHER
2
=
.PP
COMMODITY
3
=
.PP
CORPORATE
4
=
.PP
CURRENCY
5
=
.PP
EQUITY
6
=
.PP
GOVERNMENT
7
=
.PP
INDEX
8
=
.PP
LOAN
9
=
.PP
MONEYMARKET
.PP
   *   *   *   *   *
Used in messages:
[SecurityTypes (body_5354119.html?find=Product)]
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=Product)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
