.TH FIX.4.3 "" "" "Tag #465"
Tag
Field Name
Data Type
Description
Depr.
Valid values
465 (tag465.html)
QuantityType (tag465.html)
int
.PP
Designates the type of quantities (e.g. OrderQty) specified. Used
for MBS and TIPS Fixed Income security types.
1
=
.PP
SHARES
2
=
.PP
BONDS
3
=
.PP
CURRENTFACE
4
=
.PP
ORIGINALFACE
5
=
.PP
CURRENCY
6
=
.PP
CONTRACTS
7
=
.PP
OTHER
8
=
.PP
PAR (see Volume 1 Glossary)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=QuantityType)]
[ExecutionReport (body_5756.html?find=QuantityType)]
[IOI (body_5554.html?find=QuantityType)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=QuantityType)]
[NewOrderCross (body_5350115.html?find=QuantityType)]
[NewOrderList (body_495369.html?find=QuantityType)]
[NewOrderMultileg (body_54496566.html?find=QuantityType)]
[NewOrderSingle (body_495268.html?find=QuantityType)]
[OrderCancelReplaceRequest (body_495571.html?find=QuantityType)]
[QuoteRequest (body_505482.html?find=QuantityType)]
[QuoteRequestReject (body_54546571.html?find=QuantityType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
