.TH FIX.4.3 "" "" "Tag #472"
Tag
Field Name
Data Type
Description
Depr.
Valid values
472 (tag472.html)
LocaleOfIssue (tag472.html)
String
.PP
Identifies the locale. For Municipal Security Issuers other than
state or province. Refer to
.PP
http://www.atmos.albany.edu/cgi/stagrep-cgi
.PP
Reference the IATA city codes for values.
.PP
Note IATA (International Air Transport Association) maintains the
codes at www.iata.org. See “Volume 7 – PRODUCT: FIXED INCOME” for
example.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=LocaleOfIssue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
