.TH FIX.4.3 "" "" "Tag #475"
Tag
Field Name
Data Type
Description
Depr.
Valid values
475 (tag475.html)
InvestorCountryOfResidence (tag475.html)
Country
.PP
The ISO 3166 Country code (2 character) identifying which country
the beneficial investor is resident for tax purposes.
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=InvestorCountryOfResidence)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
