.TH FIX.4.3 "" "" "Tag #477"
Tag
Field Name
Data Type
Description
Depr.
Valid values
477 (tag477.html)
DistribPaymentMethod (tag477.html)
int
.PP
A code identifying the payment method for a (fractional)
distribution.
.PP
1 = CREST
.PP
2 = NSCC
.PP
3 = Euroclear
.PP
4 = Clearstream
.PP
5 = Cheque
.PP
6 = Telegraphic Transfer
.PP
7 = FedWire
.PP
8 = Direct Credit (BECS, BACS)
.PP
9 = ACH Credit
.PP
10 = BPAY
.PP
11 = High Value Clearing System (HVACS)
.PP
12 = Reinvest in fund
.PP
13 through 998 are reserved for future use
.PP
Values above 1000 are available for use by private agreement among
counterparties
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=DistribPaymentMethod)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
