.TH FIX.4.3 "" "" "Tag #484"
Tag
Field Name
Data Type
Description
Depr.
Valid values
484 (tag484.html)
ExecPriceType (tag484.html)
char
.PP
For CIV - Identifies how the execution price LastPx was calculated
from the fund unit/share price(s) calculated at the fund valuation
point.
B
=
.PP
Bid price
C
=
.PP
Creation price
D
=
.PP
Creation price plus adjustment %
E
=
.PP
Creation price plus adjustment amount
O
=
.PP
Offer price
P
=
.PP
Offer price minus adjustment %
Q
=
.PP
Offer price minus adjustment amount
S
=
.PP
Single price
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ExecPriceType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
