.TH FIX.4.3 "" "" "Tag #486"
Tag
Field Name
Data Type
Description
Depr.
Valid values
486 (tag486.html)
DateOfBirth (tag486.html)
LocalMktDate
.PP
The date of birth applicable to the individual, e.g. required to
open some types of tax-exempt account.
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=DateOfBirth)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
