.TH FIX.4.3 "" "" "Tag #492"
Tag
Field Name
Data Type
Description
Depr.
Valid values
492 (tag492.html)
PaymentMethod (tag492.html)
int
.PP
A code identifying the Settlement payment method.
.PP
1 = CREST
.PP
2 = NSCC
.PP
3 = Euroclear
.PP
4 = Clearstream
.PP
5 = Cheque
.PP
6 = Telegraphic Transfer
.PP
7 = FedWire
.PP
8 = Debit Card
.PP
9 = Direct Debit (BECS)
.PP
10 = Direct Credit (BECS)
.PP
11 = Credit Card
.PP
12 = ACH Debit
.PP
13 = ACH Credit
.PP
14 = BPAY
.PP
15 = High Value Clearing System (HVACS)
.PP
16 through 998 are reserved for future use
.PP
Values above 1000 are available for use by private agreement among
counterparties
1
=
.PP
CREST
2
=
.PP
NSCC
3
=
.PP
Euroclear
4
=
.PP
Clearstream
5
=
.PP
Cheque
6
=
.PP
Telegraphic Transfer
7
=
.PP
FedWire
8
=
.PP
Debit Card
9
=
.PP
Direct Debit (BECS)
10
=
.PP
Direct Credit (BECS)
11
=
.PP
Credit Card
12
=
.PP
ACH Debit
13
=
.PP
ACH Credit
14
=
.PP
BPAY
15
=
.PP
High Value Clearing System (HVACS)
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructions (body_505684.html?find=PaymentMethod)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
