.TH FIX.4.3 "" "" "Tag #495"
Tag
Field Name
Data Type
Description
Depr.
Valid values
495 (tag495.html)
TaxAdvantageType (tag495.html)
int
.PP
For CIV - a code identifying the type of tax exempt account in
which purchased shares/units are to be held.
.PP
0=None/Not Applicable (default)
.PP
1 = Maxi ISA (UK)
.PP
2 = TESSA (UK)
.PP
3 = Mini Cash ISA (UK)
.PP
4 = Mini Stocks and Shares ISA (UK)
.PP
5 = Mini Insurance ISA (UK)
.PP
6 = Current year payment (US)
.PP
7 = Prior year payment (US)
.PP
8 = Asset transfer (US)
.PP
9 = Employee - prior year (US)
.PP
10 = Employee – current year (US)
.PP
11 = Employer - prior year (US)
.PP
12 = Employer – current year (US)
.PP
13 = Non-fund prototype IRA (US)
.PP
14 = Non-fund qualified plan (US)
.PP
15 = Defined contribution plan (US)
.PP
16 = Individual Retirement Account (US)
.PP
17 = Individual Retirement Account – Rollover (US)
.PP
18 = KEOGH (US)
.PP
19 = Profit Sharing Plan (US)
.PP
20 = 401K (US)
.PP
21 = Self-Directed IRA (US)
.PP
22 = 403(b) (US)
.PP
23 = 457 (US)
.PP
24 = Roth IRA (fund prototype) (US)
.PP
25 = Roth IRA (non-prototype) (US)
.PP
26 = Roth Conversion IRA (fund prototype) (US)
.PP
27 = Roth Conversion IRA (non-prototype) (US)
.PP
28 = Education IRA (fund prototype) (US)
.PP
29 = Education IRA (non-prototype) (US)
.PP
30 – 998 are reserved for future use by recognized taxation
authorities
.PP
999=Other
.PP
values above 1000 are available for use by private agreement among
counterparties
0
=
.PP
None/Not Applicable (default)
1
=
.PP
Maxi ISA (UK)
2
=
.PP
TESSA (UK)
3
=
.PP
Mini Cash ISA (UK)
4
=
.PP
Mini Stocks and Shares ISA (UK)
5
=
.PP
Mini Insurance ISA (UK)
6
=
.PP
Current year payment (US)
7
=
.PP
Prior year payment (US)
8
=
.PP
Asset transfer (US)
9
=
.PP
Employee - prior year (US)
10
=
.PP
Employee – current year (US)
11
=
.PP
Employer - prior year (US)
12
=
.PP
Employer – current year (US)
13
=
.PP
Non-fund prototype IRA (US)
14
=
.PP
Non-fund qualified plan (US)
15
=
.PP
Defined contribution plan (US)
16
=
.PP
Individual Retirement Account (US)
17
=
.PP
Individual Retirement Account – Rollover (US)
18
=
.PP
KEOGH (US)
19
=
.PP
Profit Sharing Plan (US)
20
=
.PP
401K (US)
21
=
.PP
Self-Directed IRA (US)
22
=
.PP
403(b) (US)
23
=
.PP
457 (US)
24
=
.PP
Roth IRA (fund prototype) (US)
25
=
.PP
Roth IRA (non-prototype) (US)
26
=
.PP
Roth Conversion IRA (fund prototype) (US)
27
=
.PP
Roth Conversion IRA (non-prototype) (US)
28
=
.PP
Education IRA (fund prototype) (US)
29
=
.PP
Education IRA (non-prototype) (US)
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=TaxAdvantageType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
