.TH FIX.4.3 "" "" "Tag #497"
Tag
Field Name
Data Type
Description
Depr.
Valid values
497 (tag497.html)
FundRenewWaiv (tag497.html)
char
.PP
A one character code identifying whether the Fund based renewal
commission is to be waived.
N
=
.PP
No
Y
=
.PP
Yes
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CommissionData (body_49484848.html?find=FundRenewWaiv)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
