.TH FIX.4.3 "" "" "Tag #504"
Tag
Field Name
Data Type
Description
Depr.
Valid values
504 (tag504.html)
PaymentDate (tag504.html)
LocalMktDate
.PP
The date written on a cheque or date payment should be submitted to
the relevant clearing system.
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructions (body_505684.html?find=PaymentDate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
