.TH FIX.4.3 "" "" "Tag #506"
Tag
Field Name
Data Type
Description
Depr.
Valid values
506 (tag506.html)
RegistStatus (tag506.html)
char
.PP
Registration status as returned by the broker or (for CIV) the fund
manager:
.PP
A = Accepted
.PP
R = Rejected
.PP
H = Held
.PP
N = Reminder – i.e. Registration Instructions are still outstanding
A
=
.PP
Accept
H
=
.PP
Held
N
=
.PP
Reminder
R
=
.PP
Reject
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructionsResponse (body_5257112.html?find=RegistStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
