.TH FIX.4.3 "" "" "Tag #508"
Tag
Field Name
Data Type
Description
Depr.
Valid values
508 (tag508.html)
RegistRefID (tag508.html)
String
.PP
Reference identifier for the RegistID with Cancel and Replace
RegistTransType transaction types.
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=RegistRefID)]
[RegistrationInstructionsResponse (body_5257112.html?find=RegistRefID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
