.TH FIX.4.3 "" "" "Tag #512"
Tag
Field Name
Data Type
Description
Depr.
Valid values
512 (tag512.html)
DistribPercentage (tag512.html)
Percentage
.PP
The amount of each distribution to go to this beneficiary,
expressed as a percentage
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=DistribPercentage)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
