.TH FIX.4.3 "" "" "Tag #519"
Tag
Field Name
Data Type
Description
Depr.
Valid values
519 (tag519.html)
ContAmtType (tag519.html)
int
.PP
Type of Contract Amount.
.PP
For UK
1
=
.PP
Commission Amount (actual)
2
=
.PP
Commission % (actual)
3
=
.PP
Initial Charge Amount
4
=
.PP
Initial Charge %
5
=
.PP
Discount Amount
6
=
.PP
Discount %
7
=
.PP
Dilution Levy Amount
8
=
.PP
Dilution Levy %
9
=
.PP
Exit Charge Amount
10
=
.PP
Exit Charge %
11
=
.PP
Fund-based Renewal Commission % (a.k.a. Trail commission)
12
=
.PP
Projected Fund Value (i.e. for investments intended to realise or
exceed a specific future value)
13
=
.PP
Fund-based Renewal Commission Amount (based on Order value)
14
=
.PP
Fund-based Renewal Commission Amount (based on Projected Fund
value)
15
=
.PP
Net Settlement Amount
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ContAmtType)]
[TradeCaptureReport (body_54526569.html?find=ContAmtType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
