.TH FIX.4.3 "" "" "Tag #52"
Tag
Field Name
Data Type
Description
Depr.
Valid values
52 (tag52.html)
SendingTime (tag52.html)
UTCTimestamp
.PP
Time of message transmission (always expressed in UTC (Universal
Time Coordinated, also known as “GMT”)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=SendingTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
