.TH FIX.4.3 "" "" "Tag #523"
Tag
Field Name
Data Type
Description
Depr.
Valid values
523 (tag523.html)
PartySubID (tag523.html)
String
.PP
Sub-identifier (e.g. Clearing Account for PartyRole=Clearing Firm,
Locate ID # for PartyRole=Locate/Lending Firm, etc). Not required
when using PartyID, PartyIDSource, and PartyRole.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Parties (body_49484950.html?find=PartySubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
