.TH FIX.4.3 "" "" "Tag #527"
Tag
Field Name
Data Type
Description
Depr.
Valid values
527 (tag527.html)
SecondaryExecID (tag527.html)
String
.PP
Assigned by the party which accepts the order. Can be used to
provide the ExecID used by an exchange or executing system.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=SecondaryExecID)]
[ExecutionReport (body_5756.html?find=SecondaryExecID)]
[TradeCaptureReport (body_54526569.html?find=SecondaryExecID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
