.TH FIX.4.3 "" "" "Tag #528"
Tag
Field Name
Data Type
Description
Depr.
Valid values
528 (tag528.html)
OrderCapacity (tag528.html)
char
.PP
Designates the capacity of the firm placing the order.
A
=
.PP
Agency
G
=
.PP
Proprietary
I
=
.PP
Individual
P
=
.PP
Principal (Note for CMS purposes, Principal includes Proprietary)
R
=
.PP
Riskless Principal
W
=
.PP
Agent for Other Member
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=OrderCapacity)]
[ExecutionReport (body_5756.html?find=OrderCapacity)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=OrderCapacity)]
[NewOrderCross (body_5350115.html?find=OrderCapacity)]
[NewOrderList (body_495369.html?find=OrderCapacity)]
[NewOrderMultileg (body_54496566.html?find=OrderCapacity)]
[NewOrderSingle (body_495268.html?find=OrderCapacity)]
[OrderCancelReplaceRequest (body_495571.html?find=OrderCapacity)]
[TradeCaptureReport (body_54526569.html?find=OrderCapacity)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
