.TH FIX.4.3 "" "" "Tag #529"
Tag
Field Name
Data Type
Description
Depr.
Valid values
529 (tag529.html)
OrderRestrictions (tag529.html)
MultipleValueString
.PP
Restrictions associated with an order. If more than one restriction
is applicable to an order, this field can contain multiple
instructions separated by space.
1
=
.PP
Program Trade
2
=
.PP
Index Arbitrage
3
=
.PP
Non-Index Arbitrage
4
=
.PP
Competing Market Maker
5
=
.PP
Acting as Market Maker or Specialist in the security
6
=
.PP
Acting as Market Maker or Specialist in the underlying security of
a derivative security
7
=
.PP
Foreign Entity (of foreign governmnet or regulatory jurisdiction)
8
=
.PP
External Market Participant
9
=
.PP
External Inter-connected Market Linkage
A
=
.PP
Riskless Arbitrage
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=OrderRestrictions)]
[ExecutionReport (body_5756.html?find=OrderRestrictions)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=OrderRestrictions)]
[NewOrderCross (body_5350115.html?find=OrderRestrictions)]
[NewOrderList (body_495369.html?find=OrderRestrictions)]
[NewOrderMultileg (body_54496566.html?find=OrderRestrictions)]
[NewOrderSingle (body_495268.html?find=OrderRestrictions)]
[OrderCancelReplaceRequest (body_495571.html?find=OrderRestrictions)]
[TradeCaptureReport (body_54526569.html?find=OrderRestrictions)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
