.TH FIX.4.3 "" "" "Tag #532"
Tag
Field Name
Data Type
Description
Depr.
Valid values
532 (tag532.html)
MassCancelRejectReason (tag532.html)
char
.PP
Reason Order Mass Cancel Request was rejected
0
=
.PP
Mass Cancel Not Supported
1
=
.PP
Invalid or unknown Security
2
=
.PP
Invalid or unknown underlying
3
=
.PP
Invalid or unknown Product
4
=
.PP
Invalid or unknown CFICode
5
=
.PP
Invalid or unknown Security Type
6
=
.PP
Invalid or unknown trading session
.PP
   *   *   *   *   *
Used in messages:
[OrderMassCancelReport (body_5349114.html?find=MassCancelRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
