.TH FIX.4.3 "" "" "Tag #535"
Tag
Field Name
Data Type
Description
Depr.
Valid values
535 (tag535.html)
AffectedOrderID (tag535.html)
String
.PP
OrderID of an order affected by a mass cancel request.
.PP
   *   *   *   *   *
Used in messages:
[OrderMassCancelReport (body_5349114.html?find=AffectedOrderID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
