.TH FIX.4.3 "" "" "Tag #538"
Tag
Field Name
Data Type
Description
Depr.
Valid values
538 (tag538.html)
NestedPartyRole (tag538.html)
int
.PP
PartyRole value within a nested repeating group.
.PP
Same values as PartyRole (452)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NestedParties (body_49484856.html?find=NestedPartyRole)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
