.TH FIX.4.3 "" "" "Tag #54"
Tag
Field Name
Data Type
Description
Depr.
Valid values
54 (tag54.html)
Side (tag54.html)
char
.PP
Side of order
1
=
.PP
Buy
2
=
.PP
Sell
3
=
.PP
Buy minus
4
=
.PP
Sell plus
5
=
.PP
Sell short
6
=
.PP
Sell short exempt
7
=
.PP
Undisclosed (valid for IOI and List Order messages only)
8
=
.PP
Cross (orders where counterparty is an exchange, valid for all
messages except IOIs)
9
=
.PP
Cross short
A
=
.PP
Cross short exempt
B
=
.PP
As Defined (for use with multileg instruments)
C
=
.PP
Opposite (for use with multileg instruments)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=Side)]
[BidRequest (body_5252107.html?find=Side)]
[BidResponse (body_5253108.html?find=Side)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=Side)]
[CrossOrderCancelRequest (body_5351117.html?find=Side)]
[DontKnowTradeDK (body_505381.html?find=Side)]
[ExecutionReport (body_5756.html?find=Side)]
[IOI (body_5554.html?find=Side)]
[ListStrikePrice (body_5254109.html?find=Side)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=Side)]
[NewOrderCross (body_5350115.html?find=Side)]
[NewOrderList (body_495369.html?find=Side)]
[NewOrderMultileg (body_54496566.html?find=Side)]
[NewOrderSingle (body_495268.html?find=Side)]
[OrderCancelReplaceRequest (body_495571.html?find=Side)]
[OrderCancelRequest (body_495470.html?find=Side)]
[OrderMassCancelReport (body_5349114.html?find=Side)]
[OrderMassCancelRequest (body_5348113.html?find=Side)]
[OrderMassStatusRequest (body_54536570.html?find=Side)]
[OrderStatusRequest (body_495672.html?find=Side)]
[QuoteRequest (body_505482.html?find=Side)]
[QuoteRequestReject (body_54546571.html?find=Side)]
[SettlementInstructions (body_505684.html?find=Side)]
[TradeCaptureReport (body_54526569.html?find=Side)]
[TradeCaptureReportRequest (body_54516568.html?find=Side)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
