.TH FIX.4.3 "" "" "Tag #546"
Tag
Field Name
Data Type
Description
Depr.
Valid values
546 (tag546.html)
Scope (tag546.html)
MultipleValueString
.PP
Defines the scope of a data element.
1
=
.PP
Local (Exchange, ECN, ATS)
2
=
.PP
National
3
=
.PP
Global
.PP
   *   *   *   *   *
Used in messages:
[MarketDataIncrementalRefresh (body_514988.html?find=Scope)]
[MarketDataRequest (body_505786.html?find=Scope)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=Scope)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
