.TH FIX.4.3 "" "" "Tag #552"
Tag
Field Name
Data Type
Description
Depr.
Valid values
552 (tag552.html)
NoSides (tag552.html)
NumInGroup
.PP
Number of Side repeating group instances.
1
=
.PP
one side
2
=
.PP
both sides
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=NoSides)]
[CrossOrderCancelRequest (body_5351117.html?find=NoSides)]
[NewOrderCross (body_5350115.html?find=NoSides)]
[TradeCaptureReport (body_54526569.html?find=NoSides)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
