.TH FIX.4.3 "" "" "Tag #555"
Tag
Field Name
Data Type
Description
Depr.
Valid values
555 (tag555.html)
NoLegs (tag555.html)
NumInGroup
.PP
Number of InstrumentLeg repeating group instances.
.PP
   *   *   *   *   *
Used in messages:
[DerivativeSecurityList (body_54486565.html?find=NoLegs)]
[ExecutionReport (body_5756.html?find=NoLegs)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=NoLegs)]
[NewOrderMultileg (body_54496566.html?find=NoLegs)]
[SecurityDefinition (body_5155100.html?find=NoLegs)]
[SecurityDefinitionRequest (body_515499.html?find=NoLegs)]
[SecurityList (body_5356121.html?find=NoLegs)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
