.TH FIX.4.3 "" "" "Tag #561"
Tag
Field Name
Data Type
Description
Depr.
Valid values
561 (tag561.html)
RoundLot (tag561.html)
Qty
.PP
The trading lot size of a security
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinition (body_5155100.html?find=RoundLot)]
[SecurityList (body_5356121.html?find=RoundLot)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
