.TH FIX.4.3 "" "" "Tag #566"
Tag
Field Name
Data Type
Description
Depr.
Valid values
566 (tag566.html)
LegPrice (tag566.html)
Price
.PP
Price for leg of a multileg
.PP
See Price (44) field for description
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=LegPrice)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=LegPrice)]
[NewOrderMultileg (body_54496566.html?find=LegPrice)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
