.TH FIX.4.3 "" "" "Tag #569"
Tag
Field Name
Data Type
Description
Depr.
Valid values
569 (tag569.html)
TradeRequestType (tag569.html)
int
.PP
Type of Trade Capture Report.
0
=
.PP
All trades
1
=
.PP
Matched trades matching Criteria provided on request (parties,
order id, instrument, input source, etc.)
2
=
.PP
Unmatched trades that match criteria
3
=
.PP
Unreported trades that match criteria
4
=
.PP
Advisories that match criteria
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReportRequest (body_54516568.html?find=TradeRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
