.TH FIX.4.3 "" "" "Tag #573"
Tag
Field Name
Data Type
Description
Depr.
Valid values
573 (tag573.html)
MatchStatus (tag573.html)
char
.PP
The status of this trade with respect to matching or comparison.
0
=
.PP
compared, matched or affirmed
1
=
.PP
uncompared, unmatched, or unaffirmed
2
=
.PP
advisory or alert
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=MatchStatus)]
[TradeCaptureReportRequest (body_54516568.html?find=MatchStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
