.TH FIX.4.3 "" "" "Tag #574"
Tag
Field Name
Data Type
Description
Depr.
Valid values
574 (tag574.html)
MatchType (tag574.html)
String
.PP
The point in the matching process at which this trade was matched.
A1
=
.PP
Exact match on Trade Date, Stock Symbol, Quantity, Price, Trade
Type, and Special Trade Indicator plus four badges and execution
time (within two-minute window)
A2
=
.PP
Exact match on Trade Date, Stock Symbol, Quantity, Price, Trade
Type, and Special Trade Indicator plus four badges
A3
=
.PP
Exact match on Trade Date, Stock Symbol, Quantity, Price, Trade
Type, and Special Trade Indicator plus two badges and execution
time (within two-minute window)
A4
=
.PP
Exact match on Trade Date, Stock Symbol, Quantity, Price, Trade
Type, and
A5
=
.PP
Exact match on Trade Date, Stock Symbol, Quantity, Price, Trade
Type, and Special Trade Indicator plus execution time (within
two-minute window)
AQ
=
.PP
Compared records resulting from stamped advisories or specialist
M1
=
.PP
ACT M1 Match / Exact Match on Trade Date, Stock Symbol, Quantity,
Price, Trade Type, and Special Trade Indicator minus badges and
times
M2
=
.PP
ACT M2 Match / Summarized Match minus badges and times
M3
=
.PP
ACT Accepted Trade
M4
=
.PP
ACT Default Trade
M5
=
.PP
ACT Default After M2
M6
=
.PP
ACT M6 Match
MT
=
.PP
Non-ACT / OCS Locked In
S1
=
.PP
Summarized Match using A1 to A5 exact match criteria except
quantity is summarized
S2
=
.PP
Summarized Match using A1 to A5 exact match criteria except
quantity is summarized
S3
=
.PP
Summarized Match using A1 to A5 exact match criteria except
quantity is summarized
S4
=
.PP
Summarized Match using A1 to A5 exact match criteria except
quantity is summarized
S5
=
.PP
Summarized Match using A1 to A5 exact match criteria except
quantity is summarized
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=MatchType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
