.TH FIX.4.3 "" "" "Tag #577"
Tag
Field Name
Data Type
Description
Depr.
Valid values
577 (tag577.html)
ClearingInstruction (tag577.html)
int
.PP
Eligibility of this trade for clearing and central counterparty
processing
0
=
.PP
process normally
1
=
.PP
exclude from all netting
2
=
.PP
bilateral netting only
3
=
.PP
ex clearing
4
=
.PP
special trade
5
=
.PP
multilateral netting
6
=
.PP
clear against central counterparty
7
=
.PP
exclude from central counterparty
8
=
.PP
Manual mode (pre-posting and/or pre-giveup)
9
=
.PP
Automatic posting mode (trade posting to the position account
number specified)
10
=
.PP
Automatic give-up mode (trade give-up to the give-up destination
number specified)
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=ClearingInstruction)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
