.TH FIX.4.3 "" "" "Tag #580"
Tag
Field Name
Data Type
Description
Depr.
Valid values
580 (tag580.html)
NoDates (tag580.html)
int
.PP
Number of Date fields provided in date range
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReportRequest (body_54516568.html?find=NoDates)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
