.TH FIX.4.3 "" "" "Tag #581"
Tag
Field Name
Data Type
Description
Depr.
Valid values
581 (tag581.html)
AccountType (tag581.html)
int
.PP
Type of account associated with an order
1
=
.PP
Account is carried on customer Side of Books
2
=
.PP
Account is carried on non-Customer Side of books
3
=
.PP
House Trader
4
=
.PP
Floor Trader
6
=
.PP
Account is carried on non-customer side of books and is cross
margined
7
=
.PP
Account is house trader and is cross margined
8
=
.PP
Joint Backoffice Account (JBO)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=AccountType)]
[ExecutionReport (body_5756.html?find=AccountType)]
[MassQuote (body_5250105.html?find=AccountType)]
[MassQuoteAcknowledgement (body_515398.html?find=AccountType)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=AccountType)]
[NewOrderCross (body_5350115.html?find=AccountType)]
[NewOrderList (body_495369.html?find=AccountType)]
[NewOrderMultileg (body_54496566.html?find=AccountType)]
[NewOrderSingle (body_495268.html?find=AccountType)]
[OrderCancelReject (body_494857.html?find=AccountType)]
[OrderCancelReplaceRequest (body_495571.html?find=AccountType)]
[OrderCancelRequest (body_495470.html?find=AccountType)]
[Quote (body_505583.html?find=AccountType)]
[QuoteCancel (body_515190.html?find=AccountType)]
[QuoteStatusReport (body_54566573.html?find=AccountType)]
[QuoteStatusRequest (body_515297.html?find=AccountType)]
[TradeCaptureReport (body_54526569.html?find=AccountType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
