.TH FIX.4.3 "" "" "Tag #583"
Tag
Field Name
Data Type
Description
Depr.
Valid values
583 (tag583.html)
ClOrdLinkID (tag583.html)
String
.PP
Permits order originators to tie together groups of orders in which
trades resulting from orders are associated for a specific purpose,
for example the calculation of average execution price for a
customer.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=ClOrdLinkID)]
[CrossOrderCancelRequest (body_5351117.html?find=ClOrdLinkID)]
[ExecutionReport (body_5756.html?find=ClOrdLinkID)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=ClOrdLinkID)]
[NewOrderCross (body_5350115.html?find=ClOrdLinkID)]
[NewOrderList (body_495369.html?find=ClOrdLinkID)]
[NewOrderMultileg (body_54496566.html?find=ClOrdLinkID)]
[NewOrderSingle (body_495268.html?find=ClOrdLinkID)]
[OrderCancelReject (body_494857.html?find=ClOrdLinkID)]
[OrderCancelReplaceRequest (body_495571.html?find=ClOrdLinkID)]
[OrderCancelRequest (body_495470.html?find=ClOrdLinkID)]
[OrderStatusRequest (body_495672.html?find=ClOrdLinkID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
