.TH FIX.4.3 "" "" "Tag #588"
Tag
Field Name
Data Type
Description
Depr.
Valid values
588 (tag588.html)
LegFutSettDate (tag588.html)
LocalMMktDate
.PP
Refer to description for FutSettDate[64]
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=LegFutSettDate)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=LegFutSettDate)]
[NewOrderMultileg (body_54496566.html?find=LegFutSettDate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
