.TH FIX.4.3 "" "" "Tag #589"
Tag
Field Name
Data Type
Description
Depr.
Valid values
589 (tag589.html)
DayBookingInst (tag589.html)
char
.PP
Indicates whether or not automatic booking can occur.
.PP
0 = Can trigger booking without reference to the order initiator
("auto")
.PP
1 = Speak with order initiator before booking ("speak first")
0
=
.PP
Can trigger booking without reference to the order initiator
("auto")
1
=
.PP
Speak with order initiator before booking ("speak first")
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=DayBookingInst)]
[ExecutionReport (body_5756.html?find=DayBookingInst)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=DayBookingInst)]
[NewOrderCross (body_5350115.html?find=DayBookingInst)]
[NewOrderList (body_495369.html?find=DayBookingInst)]
[NewOrderMultileg (body_54496566.html?find=DayBookingInst)]
[NewOrderSingle (body_495268.html?find=DayBookingInst)]
[OrderCancelReplaceRequest (body_495571.html?find=DayBookingInst)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
