.TH FIX.4.3 "" "" "Tag #591"
Tag
Field Name
Data Type
Description
Depr.
Valid values
591 (tag591.html)
PreallocMethod (tag591.html)
char
.PP
Indicates the method of preallocation.
.PP
0 = Pro-rata
.PP
1 = Do not pro-rata = discuss first
0
=
.PP
Pro-rata
1
=
.PP
Do not pro-rata = discuss first
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=PreallocMethod)]
[ExecutionReport (body_5756.html?find=PreallocMethod)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=PreallocMethod)]
[NewOrderCross (body_5350115.html?find=PreallocMethod)]
[NewOrderList (body_495369.html?find=PreallocMethod)]
[NewOrderMultileg (body_54496566.html?find=PreallocMethod)]
[NewOrderSingle (body_495268.html?find=PreallocMethod)]
[OrderCancelReplaceRequest (body_495571.html?find=PreallocMethod)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
