.TH FIX.4.3 "" "" "Tag #622"
Tag
Field Name
Data Type
Description
Depr.
Valid values
622 (tag622.html)
EncodedLegSecurityDesc (tag622.html)
data
.PP
Multileg instrument\[aq]s individual security’s
EncodedSecurityDesc.
.PP
See EncodedSecurityDesc (351) field for description
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=EncodedLegSecurityDesc)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
