.TH FIX.4.3 "" "" "Tag #626"
Tag
Field Name
Data Type
Description
Depr.
Valid values
626 (tag626.html)
AllocType (tag626.html)
int
.PP
Describes the specific type or purpose of an Allocation message
(i.e. "Buyside Calculated")
1
=
.PP
Buyside Calculated (includes MiscFees and NetMoney)
2
=
.PP
Buyside Preliminary (without MiscFees and NetMoney)
3
=
.PP
Sellside Calculated Using Preliminary (includes MiscFees and
NetMoney)
4
=
.PP
Sellside Calculated Without Preliminary (sent unsolicited by
sellside, includes MiscFees and NetMoney)
5
=
.PP
Buyside Ready-To-Book - Single Order
6
=
.PP
Buyside Ready-To-Book - Combined Set of Orders
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AllocType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
