.TH FIX.4.3 "" "" "Tag #630"
Tag
Field Name
Data Type
Description
Depr.
Valid values
630 (tag630.html)
HopRefID (tag630.html)
SeqNum
.PP
Reference identifier assigned by HopCompID (628) associated with
the message sent. It is recommended that this value be the
MsgSeqNum (34) of the message sent by the third party.
.PP
Applicable when messages are communicated/re-distributed via third
parties which function as service bureaus or “hubs”. Only
applicable if OnBehalfOfCompID (115) is being used.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=HopRefID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
