.TH FIX.4.3 "" "" "Tag #634"
Tag
Field Name
Data Type
Description
Depr.
Valid values
634 (tag634.html)
OfferYield (tag634.html)
Percentage
.PP
Offer yield
.PP
   *   *   *   *   *
Used in messages:
[MassQuote (body_5250105.html?find=OfferYield)]
[MassQuoteAcknowledgement (body_515398.html?find=OfferYield)]
[Quote (body_505583.html?find=OfferYield)]
[QuoteStatusReport (body_54566573.html?find=OfferYield)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
