.TH FIX.4.3 "" "" "Tag #635"
Tag
Field Name
Data Type
Description
Depr.
Valid values
635 (tag635.html)
ClearingFeeIndicator (tag635.html)
String
.PP
Indicates type of fee being assessed of the customer for trade
executions at an exchange. Applicable for futures markets only at
this time.
1
=
.PP
1st year delegate trading for his own account
2
=
.PP
2nd year delegate trading for his own account
3
=
.PP
3rd year delegate trading for his own account
4
=
.PP
4th year delegate trading for his own account
5
=
.PP
5th year delegate trading for his own account
9
=
.PP
6th year and beyond delegate trading for his own account
B
=
.PP
CBOE Member
C
=
.PP
Non-member and Customer
E
=
.PP
Equity Member and Clearing Member
F
=
.PP
Full and Associate Member trading for own account and as floor
H
=
.PP
106.H and 106.J Firms
I
=
.PP
GIM, IDEM and COM Membership Interest Holders
L
=
.PP
Lessee and 106.F Employees
M
=
.PP
All other ownership types
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5352116.html?find=ClearingFeeIndicator)]
[ExecutionReport (body_5756.html?find=ClearingFeeIndicator)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=ClearingFeeIndicator)]
[NewOrderCross (body_5350115.html?find=ClearingFeeIndicator)]
[NewOrderList (body_495369.html?find=ClearingFeeIndicator)]
[NewOrderMultileg (body_54496566.html?find=ClearingFeeIndicator)]
[NewOrderSingle (body_495268.html?find=ClearingFeeIndicator)]
[OrderCancelReplaceRequest (body_495571.html?find=ClearingFeeIndicator)]
[TradeCaptureReport (body_54526569.html?find=ClearingFeeIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
