.TH FIX.4.3 "" "" "Tag #639"
Tag
Field Name
Data Type
Description
Depr.
Valid values
639 (tag639.html)
PriceImprovement (tag639.html)
PriceOffset
.PP
Amount of price improvement.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=PriceImprovement)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
