.TH FIX.4.3 "" "" "Tag #643"
Tag
Field Name
Data Type
Description
Depr.
Valid values
643 (tag643.html)
OfferForwardPoints2 (tag643.html)
PriceOffset
.PP
Offer F/X forward points of the future portion of a F/X swap quote
added to spot rate. May be a negative value.
.PP
   *   *   *   *   *
Used in messages:
[MassQuote (body_5250105.html?find=OfferForwardPoints2)]
[MassQuoteAcknowledgement (body_515398.html?find=OfferForwardPoints2)]
[Quote (body_505583.html?find=OfferForwardPoints2)]
[QuoteStatusReport (body_54566573.html?find=OfferForwardPoints2)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
