.TH FIX.4.3 "" "" "Tag #644"
Tag
Field Name
Data Type
Description
Depr.
Valid values
644 (tag644.html)
RFQReqID (tag644.html)
String
.PP
RFQ Request ID – used to identify an RFQ Request.
.PP
   *   *   *   *   *
Used in messages:
[QuoteRequest (body_505482.html?find=RFQReqID)]
[QuoteRequestReject (body_54546571.html?find=RFQReqID)]
[RFQRequest (body_54556572.html?find=RFQReqID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
