.TH FIX.4.3 "" "" "Tag #647"
Tag
Field Name
Data Type
Description
Depr.
Valid values
647 (tag647.html)
MinBidSize (tag647.html)
Qty
.PP
Used to indicate a minimum quantity for a bid. If this field is
used the BidSize field is interpreted as the maximum bid size
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=MinBidSize)]
[QuoteStatusReport (body_54566573.html?find=MinBidSize)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
