.TH FIX.4.3 "" "" "Tag #65"
Tag
Field Name
Data Type
Description
Depr.
Valid values
65 (tag65.html)
SymbolSfx (tag65.html)
String
.PP
Additional information about the security (e.g. preferred,
warrants, etc.). Note also see SecurityType (167).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=SymbolSfx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
