.TH FIX.4.3 "" "" "Tag #654"
Tag
Field Name
Data Type
Description
Depr.
Valid values
654 (tag654.html)
LegRefID (tag654.html)
String
.PP
Unique indicator for a specific leg.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=LegRefID)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=LegRefID)]
[NewOrderMultileg (body_54496566.html?find=LegRefID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
