.TH FIX.4.3 "" "" "Tag #658"
Tag
Field Name
Data Type
Description
Depr.
Valid values
658 (tag658.html)
QuoteRequestRejectReason (tag658.html)
Int
.PP
Reason Quote was rejected:
1
=
.PP
Unknown symbol (Security)
2
=
.PP
Exchange(Security) closed
3
=
.PP
Quote Request exceeds limit
4
=
.PP
Too late to enter
5
=
.PP
Invalid price
6
=
.PP
Not authorized to request quote
.PP
   *   *   *   *   *
Used in messages:
[QuoteRequestReject (body_54546571.html?find=QuoteRequestRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
