.TH FIX.4.3 "" "" "Tag #77"
Tag
Field Name
Data Type
Description
Depr.
Valid values
77 (tag77.html)
PositionEffect(formerly named: OpenClose prior to FIX 4.3) (tag77.html)
char
.PP
Indicates whether the resulting position after a trade should be an
opening position or closing position. Used for omnibus accounting -
where accounts are held on a gross basis instead of being netted
together.
C
=
.PP
Close
F
=
.PP
FIFO
O
=
.PP
Open
R
=
.PP
Rolled
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[ExecutionReport (body_5756.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[NewOrderCross (body_5350115.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[NewOrderList (body_495369.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[NewOrderMultileg (body_54496566.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[NewOrderSingle (body_495268.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[OrderCancelReplaceRequest (body_495571.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
[TradeCaptureReport (body_54526569.html?find=PositionEffect(formerly%20named:%20OpenClose%20prior%20to%20FIX%204.3))]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
