.TH FIX.4.3 "" "" "Tag #78"
Tag
Field Name
Data Type
Description
Depr.
Valid values
78 (tag78.html)
NoAllocs (tag78.html)
NumInGroup
.PP
Number of repeating AllocAccount/AllocPrice entries.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=NoAllocs)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=NoAllocs)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=NoAllocs)]
[NewOrderCross (body_5350115.html?find=NoAllocs)]
[NewOrderList (body_495369.html?find=NoAllocs)]
[NewOrderMultileg (body_54496566.html?find=NoAllocs)]
[NewOrderSingle (body_495268.html?find=NoAllocs)]
[OrderCancelReplaceRequest (body_495571.html?find=NoAllocs)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
