.TH FIX.4.3 "" "" "Tag #79"
Tag
Field Name
Data Type
Description
Depr.
Valid values
79 (tag79.html)
AllocAccount (tag79.html)
String
.PP
Sub-account mnemonic
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AllocAccount)]
[CrossOrderCancelReplaceRequest (body_5352116.html?find=AllocAccount)]
[MultilegOrderCancelReplaceRequest (body_54506567.html?find=AllocAccount)]
[NewOrderCross (body_5350115.html?find=AllocAccount)]
[NewOrderList (body_495369.html?find=AllocAccount)]
[NewOrderMultileg (body_54496566.html?find=AllocAccount)]
[NewOrderSingle (body_495268.html?find=AllocAccount)]
[OrderCancelReplaceRequest (body_495571.html?find=AllocAccount)]
[SettlementInstructions (body_505684.html?find=AllocAccount)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
