.TH FIX.4.3 "" "" "Tag #86"
Tag
Field Name
Data Type
Description
Depr.
Valid values
86 (tag86.html)
DlvyInst(no longer used) (tag86.html)
String
.PP
Free format text field to indicate delivery instructions
.PP
No longer used. Included here for reference to prior versions.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
