.TH FIX.4.3 "" "" "Tag #87"
Tag
Field Name
Data Type
Description
Depr.
Valid values
87 (tag87.html)
AllocStatus (tag87.html)
int
.PP
Identifies status of allocation.
0
=
.PP
accepted (successfully processed)
1
=
.PP
rejected
2
=
.PP
partial accept
3
=
.PP
received (received, not yet processed)
.PP
   *   *   *   *   *
Used in messages:
[AllocationAck (body_505280.html?find=AllocStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
