.TH FIX.4.3 "" "" "Tag #88"
Tag
Field Name
Data Type
Description
Depr.
Valid values
88 (tag88.html)
AllocRejCode (tag88.html)
int
.PP
Identifies reason for rejection.
0
=
.PP
unknown account(s)
1
=
.PP
incorrect quantity
2
=
.PP
incorrect average price
3
=
.PP
unknown executing broker mnemonic
4
=
.PP
commission difference
5
=
.PP
unknown OrderID
6
=
.PP
unknown ListID
7
=
.PP
other
.PP
   *   *   *   *   *
Used in messages:
[AllocationAck (body_505280.html?find=AllocRejCode)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
