.TH FIX.4.3 "" "" "Tag #93"
Tag
Field Name
Data Type
Description
Depr.
Valid values
93 (tag93.html)
SignatureLength (tag93.html)
Length
.PP
Number of bytes in signature field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardTrailer (body_49485053.html?find=SignatureLength)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
