.TH FIX.4.3 "" "" "Tag #95"
Tag
Field Name
Data Type
Description
Depr.
Valid values
95 (tag95.html)
RawDataLength (tag95.html)
Length
.PP
Number of bytes in raw data field.
.PP
   *   *   *   *   *
Used in messages:
[Email (body_495167.html?find=RawDataLength)]
[Logon (body_494965.html?find=RawDataLength)]
[News (body_495066.html?find=RawDataLength)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
