.TH FIX.4.4 "" "" "Tag #10"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
10 (tag10.html)
CheckSum (tag10.html)
String
.PP
Three byte, simple checksum (see Volume 2: "Checksum Calculation"
for description). ALWAYS LAST FIELD IN MESSAGE; i.e. serves, with
the trailing <SOH>, as the end-of-message delimiter. Always defined
as three characters. (Always unencrypted)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardTrailer (body_49485053.html?find=CheckSum)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
