.TH FIX.4.4 "" "" "Tag #120"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
120 (tag120.html)
SettlCurrency (tag120.html)
\@SettlCcy
Currency
.PP
Currency code of settlement denomination.
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=SettlCurrency)]
[ExecutionReport (body_5756.html?find=SettlCurrency)]
[MultilegOrderCancelReplace (body_54506567.html?find=SettlCurrency)]
[NewOrderMultileg (body_54496566.html?find=SettlCurrency)]
[NewOrderSingle (body_495268.html?find=SettlCurrency)]
[OrderCancelReplaceRequest (body_495571.html?find=SettlCurrency)]
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=SettlCurrency)]
[ListOrdGrp (body_50485148.html?find=SettlCurrency)]
[SideCrossOrdModGrp (body_50485357.html?find=SettlCurrency)]
[TrdCapRptSideGrp (body_50485449.html?find=SettlCurrency)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
