.TH FIX.4.4 "" "" "Tag #13"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
13 (tag13.html)
CommType (tag13.html)
\@CommTyp
char
.PP
Commission type
1
=
.PP
Per Unit
2
=
.PP
Percent
3
=
.PP
Absolute
4
=
.PP
PctWaivedCshDisc
5
=
.PP
PctWaivedEnUnits
6
=
.PP
PerBond
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=CommType)]
[QuoteResponse (body_54576574.html?find=CommType)]
[QuoteStatusReport (body_54566573.html?find=CommType)]
.PP
   *   *   *   *   *
Used in components:
[CommissionData (body_49484848.html?find=CommType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
