.TH FIX.4.4 "" "" "Tag #152"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
152 (tag152.html)
CashOrderQty (tag152.html)
\@Cash
Qty
.PP
Specifies the approximate order quantity desired in total monetary
units vs. as tradeable units (e.g. number of shares). The broker or
fund manager (for CIV orders) would be responsible for converting
and calculating a tradeable unit (e.g. share) quantity (OrderQty
(38)) based upon this amount to be used for the actual order and
subsequent messages.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[OrderQtyData (body_49484949.html?find=CashOrderQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
