.TH FIX.4.4 "" "" "Tag #159"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
159 (tag159.html)
AccruedInterestAmt (tag159.html)
\@AcrdIntAmt
Amt
.PP
Amount of Accrued Interest for convertible bonds and fixed income
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=AccruedInterestAmt)]
[AllocationReport (body_55566583.html?find=AccruedInterestAmt)]
[CollateralAssignment (body_56526589.html?find=AccruedInterestAmt)]
[CollateralInquiry (body_56556666.html?find=AccruedInterestAmt)]
[CollateralReport (body_56546665.html?find=AccruedInterestAmt)]
[CollateralRequest (body_56516588.html?find=AccruedInterestAmt)]
[CollateralResponse (body_56536590.html?find=AccruedInterestAmt)]
[Confirmation (body_55486575.html?find=AccruedInterestAmt)]
[ExecutionReport (body_5756.html?find=AccruedInterestAmt)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptSideGrp (body_50485449.html?find=AccruedInterestAmt)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
