.TH FIX.4.4 "" "" "Tag #167"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
167 (tag167.html)
SecurityType (tag167.html)
\@SecTyp
String
.PP
Indicates type of security. See also the Product (460) and CFICode
(46) fields. It is recommended that CFICode be used instead of
SecurityType for non-Fixed Income instruments.
.PP
Example values (grouped by Product field value) (Note: additional
values may be used by mutual agreement of the counterparties):
.PP
* Identify the Issuer in the "Issuer" field(06)
.PP
*** REPLACED values - See "Replaced Features and Supported
Approach" ***
.PP
NOTE: Additional values may be used by mutual agreement of the
counterparties)
ABS
=
.PP
AssetbackedSecurities
AMENDED
=
.PP
AmendedRestated
AN
=
.PP
OtherAnticipationNotesBANGANEtc
BA
=
.PP
BankersAcceptance
BN
=
.PP
BankNotes
BOX
=
.PP
BillOfExchanges
BRADY
=
.PP
BradyBond
BRIDGE
=
.PP
BridgeLoan
BUYSELL
=
.PP
BuySellback
CB
=
.PP
ConvertibleBond
CD
=
.PP
CertificateOfDeposit
CL
=
.PP
CallLoans
CMBS
=
.PP
CorpMortgagebackedSecurities
CMO
=
.PP
CollateralizedMortgageObligation
COFO
=
.PP
CertificateOfObligation
COFP
=
.PP
CertificateOfParticipation
CORP
=
.PP
CorporateBond
CP
=
.PP
CommercialPaper
CPP
=
.PP
CorporatePrivatePlacement
CS
=
.PP
CommonStock
DEFLTED
=
.PP
Defaulted
DINP
=
.PP
DebtorInPossession
DN
=
.PP
DepositNotes
DUAL
=
.PP
DualCurrency
EUCD
=
.PP
EuroCertificateOfDeposit
EUCORP
=
.PP
EuroCorporateBond
EUCP
=
.PP
EuroCommercialPaper
EUSOV
=
.PP
EuroSovereigns
EUSUPRA
=
.PP
EuroSupranationalCoupons
FAC
=
.PP
FederalAgencyCoupon
FADN
=
.PP
FederalAgencyDiscountNote
FOR
=
.PP
ForeignExchangeContract
FORWARD
=
.PP
Forward
FUT
=
.PP
Future
GO
=
.PP
GeneralObligationBonds
IET
=
.PP
IOETTEMortgage
LOFC
=
.PP
LetterOfCredit
LQN
=
.PP
LiquidityNote
MATURED
=
.PP
Matured
MBS
=
.PP
MortgagebackedSecurities
MF
=
.PP
MutualFund
MIO
=
.PP
MortgageInterestOnly
MLEG
=
.PP
MultilegInstrument
MPO
=
.PP
MortgagePrincipalOnly
MPP
=
.PP
MortgagePrivatePlacement
MPT
=
.PP
MiscellaneousPassthrough
MT
=
.PP
MandatoryTender
MTN
=
.PP
MediumTermNotes
NONE
=
.PP
NoSecurityType
ONITE
=
.PP
Overnight
OPT
=
.PP
Option
PEF
=
.PP
PrivateExportFunding
PFAND
=
.PP
Pfandbriefe
PN
=
.PP
PromissoryNote
PS
=
.PP
PreferredStock
PZFJ
=
.PP
PlazosFijos
RAN
=
.PP
RevenueAnticipationNote
REPLACD
=
.PP
Replaced
REPO
=
.PP
Repurchase
RETIRED
=
.PP
Retired
REV
=
.PP
RevenueBonds
RVLV
=
.PP
RevolverLoan
RVLVTRM
=
.PP
RevolverTermLoan
SECLOAN
=
.PP
SecuritiesLoan
SECPLEDGE
=
.PP
SecuritiesPledge
SPCLA
=
.PP
SpecialAssessment
SPCLO
=
.PP
SpecialObligation
SPCLT
=
.PP
SpecialTax
STN
=
.PP
ShortTermLoanNote
STRUCT
=
.PP
StructuredNotes
SUPRA
=
.PP
USDSupranationalCoupons
SWING
=
.PP
SwingLineFacility
TAN
=
.PP
TaxAnticipationNote
TAXA
=
.PP
TaxAllocation
TBA
=
.PP
ToBeAnnounced
TBILL
=
.PP
USTreasuryBill
TBOND
=
.PP
USTreasuryBond
TCAL
=
.PP
PrincipalStripOfACallableBondOrNote
TD
=
.PP
TimeDeposit
TECP
=
.PP
TaxExemptCommercialPaper
TERM
=
.PP
TermLoan
TINT
=
.PP
InterestStripFromAnyBondOrNote
TIPS
=
.PP
TreasuryInflationProtectedSecurities
TNOTE
=
.PP
USTreasuryNote
TPRN
=
.PP
PrincipalStripFromANoncallableBondOrNote
TRAN
=
.PP
TaxRevenueAnticipationNote
UST
=
.PP
USTreasuryNoteDeprecatedValueUseTNOTE
USTB
=
.PP
USTreasuryBillDeprecatedValueUseTBILL
VRDN
=
.PP
VariableRateDemandNote
WAR
=
.PP
Warrant
WITHDRN
=
.PP
Withdrawn
WLD
=
.PP
WildcardEntry
XCN
=
.PP
ExtendedCommNote
XLINKD
=
.PP
IndexedLinked
YANK
=
.PP
YankeeCorporateBond
YCD
=
.PP
YankeeCertificateOfDeposit
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstructionAck (body_505280.html?find=SecurityType)]
[AllocationReportAck (body_55576584.html?find=SecurityType)]
[SecurityTypeRequest (body_5353118.html?find=SecurityType)]
[SettlementInstructionRequest (body_56496586.html?find=SecurityType)]
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=SecurityType)]
[SecTypesGrp (body_50485354.html?find=SecurityType)]
[SettlInstGrp (body_50485355.html?find=SecurityType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
