.TH FIX.4.4 "" "" "Tag #168"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
168 (tag168.html)
EffectiveTime (tag168.html)
\@EfctvTm
UTCTimestamp
.PP
Time the details within the message should take effect (always
expressed in UTC (Universal Time Coordinated, also known as "GMT")
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=EffectiveTime)]
[ExecutionReport (body_5756.html?find=EffectiveTime)]
[MultilegOrderCancelReplace (body_54506567.html?find=EffectiveTime)]
[NewOrderCross (body_5350115.html?find=EffectiveTime)]
[NewOrderMultileg (body_54496566.html?find=EffectiveTime)]
[NewOrderSingle (body_495268.html?find=EffectiveTime)]
[OrderCancelReplaceRequest (body_495571.html?find=EffectiveTime)]
[SettlementInstructionRequest (body_56496586.html?find=EffectiveTime)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=EffectiveTime)]
[SettlInstGrp (body_50485355.html?find=EffectiveTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
