.TH FIX.4.4 "" "" "Tag #172"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
172 (tag172.html)
SettlDeliveryType (tag172.html)
\@DlvryTyp
int
.PP
Identifies type of settlement
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlInstructionsData (body_49484954.html?find=SettlDeliveryType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
