.TH FIX.4.4 "" "" "Tag #175"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
175 (tag175.html)
SettlInstCode (tag175.html)
String
.PP
No longer used as of FIX 4.4. Included here for reference to prior
versions.
.PP
*** REPLACED FIELD - See "Replaced Features and Supported Approach"
***
.PP
BIC (Bank Identification Code—Swift managed) code of the
institution involved (i.e. for multi-company institution firms)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
