.TH FIX.4.4 "" "" "Tag #180"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
180 (tag180.html)
SecuritySettlAgentContactName (tag180.html)
String
.PP
No longer used as of FIX 4.4. Included here for reference to prior
versions.
.PP
*** REPLACED FIELD - See "Replaced Features and Supported Approach"
***
.PP
Name of contact at local agent bank for SettlInstSource\[aq]s
account if SettlLocation is not a depository
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
