.TH FIX.4.4 "" "" "Tag #182"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
182 (tag182.html)
CashSettlAgentName (tag182.html)
String
.PP
No longer used as of FIX 4.4. Included here for reference to prior
versions.
.PP
*** REPLACED FIELD - See "Replaced Features and Supported Approach"
***
.PP
Name of SettlInstSource\[aq]s local agent bank if
SettlDeliveryType=Free
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
