.TH FIX.4.4 "" "" "Tag #188"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
188 (tag188.html)
BidSpotRate (tag188.html)
\@BidSpotRt
Price
.PP
Bid F/X spot rate.
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=BidSpotRate)]
[QuoteResponse (body_54576574.html?find=BidSpotRate)]
[QuoteStatusReport (body_54566573.html?find=BidSpotRate)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=BidSpotRate)]
[QuotEntryGrp (body_50485251.html?find=BidSpotRate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
