.TH FIX.4.4 "" "" "Tag #189"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
189 (tag189.html)
BidForwardPoints (tag189.html)
\@BidFwdPnts
PriceOffset
.PP
Bid F/X forward points added to spot rate. May be a negative value.
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=BidForwardPoints)]
[QuoteResponse (body_54576574.html?find=BidForwardPoints)]
[QuoteStatusReport (body_54566573.html?find=BidForwardPoints)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=BidForwardPoints)]
[QuotEntryGrp (body_50485251.html?find=BidForwardPoints)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
