.TH FIX.4.4 "" "" "Tag #199"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
199 (tag199.html)
NoIOIQualifiers (tag199.html)
\@NoIOIQuals
NumInGroup
.PP
Number of repeating groups of IOIQualifiers (04).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[IOIQualGrp (body_50485052.html?find=NoIOIQualifiers)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
