.TH FIX.4.4 "" "" "Tag #21"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
21 (tag21.html)
HandlInst (tag21.html)
\@HandlInst
char
.PP
Instructions for order handling on Broker trading floor
1
=
.PP
AutoExecPriv
2
=
.PP
AutoExecPub
3
=
.PP
Manual
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=HandlInst)]
[ExecutionReport (body_5756.html?find=HandlInst)]
[MultilegOrderCancelReplace (body_54506567.html?find=HandlInst)]
[NewOrderCross (body_5350115.html?find=HandlInst)]
[NewOrderMultileg (body_54496566.html?find=HandlInst)]
[NewOrderSingle (body_495268.html?find=HandlInst)]
[OrderCancelReplaceRequest (body_495571.html?find=HandlInst)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=HandlInst)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
