.TH FIX.4.4 "" "" "Tag #211"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
211 (tag211.html)
PegOffsetValue (tag211.html)
\@OfstVal
float
.PP
Amount (signed) added to the peg for a pegged order in the context
of the PegOffsetType (836)
.PP
(Prior to FIX 4.4 this field was of type PriceOffset)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PegInstructions (body_49484951.html?find=PegOffsetValue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
