.TH FIX.4.4 "" "" "Tag #22"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
22 (tag22.html)
SecurityIDSource (tag22.html)
\@Src
String
.PP
Identifies class or source of the SecurityID (48) value. Required
if SecurityID is specified.
1
=
.PP
CUSIP
2
=
.PP
SEDOL
3
=
.PP
QUIK
4
=
.PP
ISIN
5
=
.PP
RIC
6
=
.PP
ISOCurr
7
=
.PP
ISOCountry
8
=
.PP
ExchSymb
9
=
.PP
CTA
A
=
.PP
Blmbrg
B
=
.PP
Wertpapier
C
=
.PP
Dutch
D
=
.PP
Valoren
E
=
.PP
Sicovam
F
=
.PP
Belgian
G
=
.PP
Common
H
=
.PP
ClearingHouse
I
=
.PP
FpML
J
=
.PP
OptionPriceReportingAuthority
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=SecurityIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
