.TH FIX.4.4 "" "" "Tag #223"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
223 (tag223.html)
CouponRate (tag223.html)
\@CpnRt
Percentage
.PP
The rate of interest that, when multiplied by the principal, par
value, or face value of a bond, provides the currency amount of the
periodic interest payment. The coupon is always cited, along with
maturity, in any quotation of a bond\[aq]s price.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=CouponRate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
