.TH FIX.4.4 "" "" "Tag #233"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
233 (tag233.html)
StipulationType (tag233.html)
\@Typ
String
.PP
Type of Stipulation
ABS
=
.PP
AbsolutePrepaymentSpeed
AMT
=
.PP
AMT
AUTOREINV
=
.PP
AutoReinvestmentAtRateOrBetter
BANKQUAL
=
.PP
BankQualified
BGNCON
=
.PP
BargainConditions
COUPON
=
.PP
CouponRange
CPP
=
.PP
ConstantPrepaymentPenalty
CPR
=
.PP
ConstantPrepaymentRate
CPY
=
.PP
ConstantPrepaymentYield
CURRENCY
=
.PP
ISOCurrencyCode
CUSTOMDATE
=
.PP
CustomStartendDate
GEOG
=
.PP
GeographicsAndRange
HAIRCUT
=
.PP
ValuationDiscount
HEP
=
.PP
finalCPROfHomeEquityPrepaymentCurve
INSURED
=
.PP
Insured
ISSUE
=
.PP
YearOrYearMonthOfIssue
ISSUER
=
.PP
IssuersTicker
ISSUESIZE
=
.PP
issueSizeRange
LOOKBACK
=
.PP
LookbackDays
LOT
=
.PP
ExplicitLotIdentifier
LOTVAR
=
.PP
LotVarianceValueInPercentMaximumOverOrUnderallocationAllowed
MAT
=
.PP
MaturityYearAndMonth
MATURITY
=
.PP
MaturityRange
MAXDNOM
=
.PP
MaximumDenomination
MAXSUBS
=
.PP
MaximumSubstitutionsRepo
MHP
=
.PP
PercentOfManufacturedHousingPrepaymentCurve
MINDNOM
=
.PP
MinimumDenomination
MININCR
=
.PP
MinimumIncrement
MINQTY
=
.PP
MinimumQuantity
MPR
=
.PP
MonthlyPrepaymentRate
PAYFREQ
=
.PP
PaymentFrequencyCalendar
PIECES
=
.PP
NumberOfPieces
PMAX
=
.PP
PoolsMaximum
PMIN
=
.PP
PoolsMinimum
PPC
=
.PP
PercentOfProspectusPrepaymentCurve
PPL
=
.PP
PoolsPerLot
PPM
=
.PP
PoolsPerMillion
PPT
=
.PP
PoolsPerTrade
PRICE
=
.PP
PriceRange
PRICEFREQ
=
.PP
PricingFrequency
PROD
=
.PP
ProductionYear
PROTECT
=
.PP
CallProtection
PSA
=
.PP
PercentOfBMAPrepaymentCurve
PURPOSE
=
.PP
Purpose
PXSOURCE
=
.PP
BenchmarkPriceSource
RATING
=
.PP
RatingSourceAndRange
REDEMPTION
=
.PP
TypeOfRedemptionValuesAre:
RESTRICTED
=
.PP
Restricted
SECTOR
=
.PP
MarketSector
SECTYPE
=
.PP
SecurityTypeIncludedOrExcluded
SMM
=
.PP
SingleMonthlyMortality
STRUCT
=
.PP
Structure
SUBSFREQ
=
.PP
SubstitutionsFrequencyRepo
SUBSLEFT
=
.PP
SubstitutionsLeftRepo
TEXT
=
.PP
FreeformText
TRDVAR
=
.PP
TradeVarianceValueInPercentMaximumOverOrUnderallocationAllowed
WAC
=
.PP
WeightedAverageCoupon
WAL
=
.PP
WeightedAverageLifeCoupon
WALA
=
.PP
WeightedAverageLoanAge
WAM
=
.PP
WeightedAverageMaturity
WHOLE
=
.PP
WholePool
YIELD
=
.PP
YieldRange
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Stipulations (body_49484957.html?find=StipulationType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
