.TH FIX.4.4 "" "" "Tag #235"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
235 (tag235.html)
YieldType (tag235.html)
\@Typ
String
.PP
Type of yield
AFTERTAX
=
.PP
AfterTaxYield
ANNUAL
=
.PP
AnnualYield
ATISSUE
=
.PP
YieldAtIssue
AVGMATURITY
=
.PP
YieldToAvgMaturity
BOOK
=
.PP
BookYield
CALL
=
.PP
YieldToNextCall
CHANGE
=
.PP
YieldChangeSinceClose
CLOSE
=
.PP
ClosingYield
COMPOUND
=
.PP
CompoundYield
CURRENT
=
.PP
CurrentYield
GOVTEQUIV
=
.PP
GvntEquivalentYield
GROSS
=
.PP
TrueGrossYield
INFLATION
=
.PP
YieldInflationAssumption
INVERSEFLOATER
=
.PP
InvFloaterBondYield
LASTCLOSE
=
.PP
MostRecentClosingYield
LASTMONTH
=
.PP
ClosingYieldMostRecentMonth
LASTQUARTER
=
.PP
ClosingYieldMostRecentQuarter
LASTYEAR
=
.PP
ClosingYieldMostRecentYear
LONGAVGLIFE
=
.PP
YieldToLongestAverageLife
MARK
=
.PP
MarkToMarketYield
MATURITY
=
.PP
YieldToMaturity
NEXTREFUND
=
.PP
YieldToNextRefundSinking
OPENAVG
=
.PP
OpenAverageYield
PREVCLOSE
=
.PP
PreviousCloseYield
PROCEEDS
=
.PP
ProceedsYield
PUT
=
.PP
YieldToNextPut
SEMIANNUAL
=
.PP
Semi
SHORTAVGLIFE
=
.PP
YieldToShortestAverageLife
SIMPLE
=
.PP
SimpleYield
TAXEQUIV
=
.PP
TaxEquivalentYield
TENDER
=
.PP
YieldtoTenderDate
TRUE
=
.PP
TrueYield
VALUE1_32
=
.PP
YieldValueOf132
WORST
=
.PP
YieldToWorstConvention
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[YieldData (body_49485050.html?find=YieldType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
