.TH FIX.4.4 "" "" "Tag #239"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
239 (tag239.html)
RepoCollateralSecurityType (tag239.html)
\@RepoCollSecTyp
int
.PP
*** DEPRECATED FIELD - See "Deprecated (Phased-out) Features and
Supported Approach" ***
.PP
Identifies the collateral used in the transaction.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=RepoCollateralSecurityType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
