.TH FIX.4.4 "" "" "Tag #251"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
251 (tag251.html)
LegRepurchaseTerm (tag251.html)
\@RepoTrm
int
.PP
*** DEPRECATED FIELD - See "Deprecated (Phased-out) Features and
Supported Approach" ***
.PP
Multileg instrument\[aq]s individual leg security’s RepurchaseTerm.
.PP
See RepurchaseTerm (226) field for description
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegRepurchaseTerm)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
