.TH FIX.4.4 "" "" "Tag #265"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
265 (tag265.html)
MDUpdateType (tag265.html)
\@UpdtTyp
int
.PP
Specifies the type of Market Data update
0
=
.PP
Full
1
=
.PP
Incremental
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequest (body_505786.html?find=MDUpdateType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
