.TH FIX.4.4 "" "" "Tag #269"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
269 (tag269.html)
MDEntryType (tag269.html)
\@Typ
char
.PP
Type Market Data entry
0
=
.PP
Bid
1
=
.PP
Offer
2
=
.PP
Trade
3
=
.PP
IndexValue
4
=
.PP
Opening
5
=
.PP
Closing
6
=
.PP
Settlement
7
=
.PP
TradingHigh
8
=
.PP
TradingLow
9
=
.PP
TradingVWAP
A
=
.PP
Imbalance
B
=
.PP
TradeVolume
C
=
.PP
OpenInterest
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=MDEntryType)]
[MDIncGrp (body_50485150.html?find=MDEntryType)]
[MDReqGrp (body_50485151.html?find=MDEntryType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
