.TH FIX.4.4 "" "" "Tag #275"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
275 (tag275.html)
MDMkt (tag275.html)
\@Mkt
Exchange
.PP
Market posting quote / trade.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=MDMkt)]
[MDIncGrp (body_50485150.html?find=MDMkt)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
