.TH FIX.4.4 "" "" "Tag #281"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
281 (tag281.html)
MDReqRejReason (tag281.html)
\@ReqRejResn
char
.PP
Reason for the rejection of a Market Data request
0
=
.PP
UnknownSym
1
=
.PP
DupID
2
=
.PP
InsBand
3
=
.PP
InsPerm
4
=
.PP
UnsuppSub
5
=
.PP
UnsuppMktDepth
6
=
.PP
UnsuppMDUpdate
7
=
.PP
UnsuppAggBk
8
=
.PP
UnsuppEntry
9
=
.PP
UnsuppTrdSessionID
A
=
.PP
UnsuppScope
B
=
.PP
UnsuppPositionEffectSettleFlag
C
=
.PP
UnsuppMDImplicitDelete
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequestReject (body_515089.html?find=MDReqRejReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
