.TH FIX.4.4 "" "" "Tag #286"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
286 (tag286.html)
OpenCloseSettlFlag (tag286.html)
\@OpenClsSettlFlag
MultipleValueString
.PP
Flag that identifies a market data entry
.PP
(Prior to FIX 4.3 this field was of type char)
0
=
.PP
DailyOpen
1
=
.PP
SessionOpen
2
=
.PP
DeliverySettlement
3
=
.PP
ExpectedEntry
4
=
.PP
EntryFromPrevBusinessDay
5
=
.PP
TheoreticalPrice
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequest (body_505786.html?find=OpenCloseSettlFlag)]
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=OpenCloseSettlFlag)]
[MDIncGrp (body_50485150.html?find=OpenCloseSettlFlag)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
