.TH FIX.4.4 "" "" "Tag #289"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
289 (tag289.html)
MDEntrySeller (tag289.html)
\@Seller
String
.PP
Selling party in a trade
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=MDEntrySeller)]
[MDIncGrp (body_50485150.html?find=MDEntrySeller)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
