.TH FIX.4.4 "" "" "Tag #29"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
29 (tag29.html)
LastCapacity (tag29.html)
\@LastCpcty
char
.PP
Broker capacity in order execution
1
=
.PP
A
2
=
.PP
XA
3
=
.PP
XP
4
=
.PP
P
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=LastCapacity)]
.PP
   *   *   *   *   *
Used in components:
[ExecAllocGrp (body_50484952.html?find=LastCapacity)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
