.TH FIX.4.4 "" "" "Tag #292"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
292 (tag292.html)
CorporateAction (tag292.html)
\@CorpActn
MultipleValueString
.PP
Identifies the type of Corporate Action
A
=
.PP
ExDividend
B
=
.PP
ExDist
C
=
.PP
ExRights
D
=
.PP
New
E
=
.PP
ExInterest
.PP
   *   *   *   *   *
Used in messages:
[MarketDataSnapshotFullRefresh (body_514887.html?find=CorporateAction)]
[SecurityStatus (body_5157102.html?find=CorporateAction)]
.PP
   *   *   *   *   *
Used in components:
[MDIncGrp (body_50485150.html?find=CorporateAction)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
