.TH FIX.4.4 "" "" "Tag #295"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
295 (tag295.html)
NoQuoteEntries (tag295.html)
\@NoQuotEntries
NumInGroup
.PP
The number of quote entries for a QuoteSet.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[QuotCxlEntriesGrp (body_50485249.html?find=NoQuoteEntries)]
[QuotEntryAckGrp (body_50485250.html?find=NoQuoteEntries)]
[QuotEntryGrp (body_50485251.html?find=NoQuoteEntries)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
