.TH FIX.4.4 "" "" "Tag #296"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
296 (tag296.html)
NoQuoteSets (tag296.html)
\@NoQuotSets
NumInGroup
.PP
The number of sets of quotes in the message.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[QuotSetAckGrp (body_50485256.html?find=NoQuoteSets)]
[QuotSetGrp (body_50485257.html?find=NoQuoteSets)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
