.TH FIX.4.4 "" "" "Tag #297"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
297 (tag297.html)
QuoteStatus (tag297.html)
\@Stat
int
.PP
Identifies the status of the quote acknowledgement
0
=
.PP
Accpt
1
=
.PP
CxlSym
2
=
.PP
CxlSecType
3
=
.PP
CxlUnder
4
=
.PP
CxlAll
5
=
.PP
Rej
6
=
.PP
Removed
7
=
.PP
Expired
8
=
.PP
Query
9
=
.PP
QuoteNotFound
10
=
.PP
Pending
11
=
.PP
Pass
12
=
.PP
LockedMarketWarning
13
=
.PP
CrossMarketWarning
14
=
.PP
CanceledDueToLockMarket
15
=
.PP
CanceledDueToCrossMarket
.PP
   *   *   *   *   *
Used in messages:
[MassQuoteAcknowledgement (body_515398.html?find=QuoteStatus)]
[QuoteStatusReport (body_54566573.html?find=QuoteStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
