.TH FIX.4.4 "" "" "Tag #298"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
298 (tag298.html)
QuoteCancelType (tag298.html)
\@CxlTyp
int
.PP
Identifies the type of quote cancel.
1
=
.PP
CxlSym
2
=
.PP
CxlSecType
3
=
.PP
CxlUnder
4
=
.PP
CxlAll
.PP
   *   *   *   *   *
Used in messages:
[QuoteCancel (body_515190.html?find=QuoteCancelType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
