.TH FIX.4.4 "" "" "Tag #318"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
318 (tag318.html)
UnderlyingCurrency (tag318.html)
\@Ccy
Currency
.PP
Underlying security’s Currency.
.PP
See Currency (5) field for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingCurrency)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
