.TH FIX.4.4 "" "" "Tag #321"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
321 (tag321.html)
SecurityRequestType (tag321.html)
\@ReqTyp
int
.PP
Type of Security Definition Request.
0
=
.PP
ReqSecID
1
=
.PP
ReqSecIDPRov
2
=
.PP
ReqSecListTypes
3
=
.PP
ReqSecList
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinitionRequest (body_515499.html?find=SecurityRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
