.TH FIX.4.4 "" "" "Tag #323"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
323 (tag323.html)
SecurityResponseType (tag323.html)
\@RspTyp
int
.PP
Type of Security Definition message response
1
=
.PP
AccptSecProp
2
=
.PP
AccptSecPropRev
3
=
.PP
SecListTypesRet
4
=
.PP
SecListRet
5
=
.PP
RejSecProp
6
=
.PP
NoMatch
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinition (body_5155100.html?find=SecurityResponseType)]
[SecurityTypes (body_5354119.html?find=SecurityResponseType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
