.TH FIX.4.4 "" "" "Tag #326"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
326 (tag326.html)
SecurityTradingStatus (tag326.html)
\@TrdgStat
int
.PP
Identifies the trading status applicable to the transaction
1
=
.PP
OpenDelay
2
=
.PP
TrdHalt
3
=
.PP
Resume
4
=
.PP
NoOpen
5
=
.PP
PxInd
6
=
.PP
TrdRngInd
7
=
.PP
MktImbBuy
8
=
.PP
MktBalSell
9
=
.PP
MktOnClsImbBuy
10
=
.PP
MktOnClsImbSell
11
=
.PP
na
12
=
.PP
NoMktImb
13
=
.PP
NoMktOnClsImb
14
=
.PP
ITSPreOpn
15
=
.PP
NewPxInd
16
=
.PP
TrdDisTime
17
=
.PP
Ready
18
=
.PP
NotAvail
19
=
.PP
NotTraded
20
=
.PP
Unknown
21
=
.PP
Pre-Open
22
=
.PP
OpeningRotation
23
=
.PP
FastMarket
.PP
   *   *   *   *   *
Used in messages:
[SecurityStatus (body_5157102.html?find=SecurityTradingStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
