.TH FIX.4.4 "" "" "Tag #327"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
327 (tag327.html)
HaltReason (tag327.html)
\@HaltRsn
char
.PP
Denotes the reason for the Opening Delay or Trading Halt
D
=
.PP
NewsDiss
E
=
.PP
OrdInfl
I
=
.PP
OrdImb
M
=
.PP
AddInfo
P
=
.PP
NewsPend
X
=
.PP
EquipChange
.PP
   *   *   *   *   *
Used in messages:
[SecurityStatus (body_5157102.html?find=HaltReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
