.TH FIX.4.4 "" "" "Tag #333"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
333 (tag333.html)
LowPx (tag333.html)
\@LowPx
Price
.PP
Represents an indication of the low end of the price range for a
security prior to the open or reopen
.PP
   *   *   *   *   *
Used in messages:
[SecurityStatus (body_5157102.html?find=LowPx)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
