.TH FIX.4.4 "" "" "Tag #339"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
339 (tag339.html)
TradSesMode (tag339.html)
\@Mode
int
.PP
Trading Session Mode
1
=
.PP
Testing
2
=
.PP
Simulated
3
=
.PP
Production
.PP
   *   *   *   *   *
Used in messages:
[TradingSessionStatus (body_5249104.html?find=TradSesMode)]
[TradingSessionStatusRequest (body_5248103.html?find=TradSesMode)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
