.TH FIX.4.4 "" "" "Tag #349"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
349 (tag349.html)
EncodedIssuer (tag349.html)
\@EncIssr
data
.PP
Encoded (non-ASCII characters) representation of the Issuer field
in the encoded format specified via the MessageEncoding (347)
field. If used, the ASCII (English) representation should also be
specified in the Issuer field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=EncodedIssuer)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
