.TH FIX.4.4 "" "" "Tag #35"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
35 (tag35.html)
MsgType (tag35.html)
String
.PP
Defines message type ALWAYS THIRD FIELD IN MESSAGE. (Always
unencrypted)
.PP
Note: A "U" as the first character in the MsgType field (i.e. U,
U2, etc) indicates that the message format is privately defined
between the sender and receiver.
0
=
.PP
Heartbeat
1
=
.PP
TestRequest
2
=
.PP
ResendRequest
3
=
.PP
Reject
4
=
.PP
SequenceReset
5
=
.PP
Logout
6
=
.PP
IOI
7
=
.PP
Advertisement
8
=
.PP
ExecutionReport
9
=
.PP
OrderCancelReject
a
=
.PP
QuoteStatusRequest
A
=
.PP
Logon
AA
=
.PP
DerivativeSecurityList
AB
=
.PP
NewOrderMultileg
AC
=
.PP
MultilegOrderCancelReplace
AD
=
.PP
TradeCaptureReportRequest
AE
=
.PP
TradeCaptureReport
AF
=
.PP
OrderMassStatusRequest
AG
=
.PP
QuoteRequestReject
AH
=
.PP
RFQRequest
AI
=
.PP
QuoteStatusReport
AJ
=
.PP
QuoteResponse
AK
=
.PP
Confirmation
AL
=
.PP
PositionMaintenanceRequest
AM
=
.PP
PositionMaintenanceReport
AN
=
.PP
RequestForPositions
AO
=
.PP
RequestForPositionsAck
AP
=
.PP
PositionReport
AQ
=
.PP
TradeCaptureReportRequestAck
AR
=
.PP
TradeCaptureReportAck
AS
=
.PP
AllocationReport
AT
=
.PP
AllocationReportAck
AU
=
.PP
ConfirmationAck
AV
=
.PP
SettlementInstructionRequest
AW
=
.PP
AssignmentReport
AX
=
.PP
CollateralRequest
AY
=
.PP
CollateralAssignment
AZ
=
.PP
CollateralResponse
B
=
.PP
News
b
=
.PP
MassQuoteAcknowledgement
BA
=
.PP
CollateralReport
BB
=
.PP
CollateralInquiry
BC
=
.PP
NetworkCounterpartySystemStatusRequest
BD
=
.PP
NetworkCounterpartySystemStatusResponse
BE
=
.PP
UserRequest
BF
=
.PP
UserResponse
BG
=
.PP
CollateralInquiryAck
BH
=
.PP
ConfirmationRequest
C
=
.PP
Email
c
=
.PP
SecurityDefinitionRequest
d
=
.PP
SecurityDefinition
D
=
.PP
NewOrderSingle
e
=
.PP
SecurityStatusRequest
E
=
.PP
NewOrderList
F
=
.PP
OrderCancelRequest
f
=
.PP
SecurityStatus
G
=
.PP
OrderCancelReplaceRequest
g
=
.PP
TradingSessionStatusRequest
H
=
.PP
OrderStatusRequest
h
=
.PP
TradingSessionStatus
i
=
.PP
MassQuote
j
=
.PP
BusinessMessageReject
J
=
.PP
AllocationInstruction
k
=
.PP
BidRequest
K
=
.PP
ListCancelRequest
l
=
.PP
BidResponse
L
=
.PP
ListExecute
m
=
.PP
ListStrikePrice
M
=
.PP
ListStatusRequest
n
=
.PP
XMLNonFIX
N
=
.PP
ListStatus
o
=
.PP
RegistrationInstructions
p
=
.PP
RegistrationInstructionsResponse
P
=
.PP
AllocationInstructionAck
q
=
.PP
OrderMassCancelRequest
Q
=
.PP
DontKnowTradeDK
R
=
.PP
QuoteRequest
r
=
.PP
OrderMassCancelReport
S
=
.PP
Quote
s
=
.PP
NewOrderCross
T
=
.PP
SettlementInstructions
t
=
.PP
CrossOrderCancelReplaceRequest
u
=
.PP
CrossOrderCancelRequest
V
=
.PP
MarketDataRequest
v
=
.PP
SecurityTypeRequest
w
=
.PP
SecurityTypes
W
=
.PP
MarketDataSnapshotFullRefresh
x
=
.PP
SecurityListRequest
X
=
.PP
MarketDataIncrementalRefresh
Y
=
.PP
MarketDataRequestReject
y
=
.PP
SecurityList
Z
=
.PP
QuoteCancel
z
=
.PP
DerivativeSecurityListRequest
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=MsgType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
