.TH FIX.4.4 "" "" "Tag #359"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
359 (tag359.html)
EncodedHeadline (tag359.html)
\@EncHeadline
data
.PP
Encoded (non-ASCII characters) representation of the Headline (48)
field in the encoded format specified via the MessageEncoding (347)
field. If used, the ASCII (English) representation should also be
specified in the Headline field.
.PP
   *   *   *   *   *
Used in messages:
[News (body_495066.html?find=EncodedHeadline)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
