.TH FIX.4.4 "" "" "Tag #363"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
363 (tag363.html)
EncodedUnderlyingIssuer (tag363.html)
\@EncUndIssr
data
.PP
Encoded (non-ASCII characters) representation of the
UnderlyingIssuer (306) field in the encoded format specified via
the MessageEncoding (347) field. If used, the ASCII (English)
representation should also be specified in the UnderlyingIssuer
field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=EncodedUnderlyingIssuer)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
