.TH FIX.4.4 "" "" "Tag #364"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
364 (tag364.html)
EncodedUnderlyingSecurityDescLen (tag364.html)
\@EncUndSecDescLen
Length
.PP
Byte length of encoded (non-ASCII characters)
EncodedUnderlyingSecurityDesc (365) field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=EncodedUnderlyingSecurityDescLen)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
