.TH FIX.4.4 "" "" "Tag #372"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
372 (tag372.html)
RefMsgType (tag372.html)
\@RefMsgTyp
String
.PP
The MsgType (35) of the FIX message being referenced.
.PP
   *   *   *   *   *
Used in messages:
[BusinessMessageReject (body_5251106.html?find=RefMsgType)]
[Logon (body_494965.html?find=RefMsgType)]
[Reject (body_5251.html?find=RefMsgType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
