.TH FIX.4.4 "" "" "Tag #373"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
373 (tag373.html)
SessionRejectReason (tag373.html)
int
.PP
Code to identify reason for a session-level Reject message
0
=
.PP
InvalidTagNumber
1
=
.PP
RequiredTagMissing
2
=
.PP
TagNotDefinedForThisMessageType
3
=
.PP
UndefinedTag
4
=
.PP
TagSpecifiedWithoutAValue
5
=
.PP
ValueIsIncorrectOutOfRangeForThisTag
6
=
.PP
IncorrectDataFormatForValue
7
=
.PP
DecryptionProblem
8
=
.PP
SignatureProblem
9
=
.PP
CompIDProblem
10
=
.PP
SendingTimeAccuracyProblem
11
=
.PP
InvalidMsgType
12
=
.PP
XMLValidationError
13
=
.PP
TagAppearsMoreThanOnce
14
=
.PP
TagSpecifiedOutOfRequiredOrder
15
=
.PP
RepeatingGroupFieldsOutOfOrder
16
=
.PP
IncorrectNumInGroupCountForRepeatingGroup
17
=
.PP
NonDataValueIncludesFieldDelimiterSOHCharacter
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[Reject (body_5251.html?find=SessionRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
