.TH FIX.4.4 "" "" "Tag #38"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
38 (tag38.html)
OrderQty (tag38.html)
\@Qty
Qty
.PP
Quantity ordered. This represents the number of shares for equities
or par, face or nominal value for FI instruments.
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[OrdAllocGrp (body_50485154.html?find=OrderQty)]
[OrderQtyData (body_49484949.html?find=OrderQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
