.TH FIX.4.4 "" "" "Tag #380"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
380 (tag380.html)
BusinessRejectReason (tag380.html)
\@BizRejRsn
int
.PP
Code to identify reason for a Business Message Reject message
0
=
.PP
Other
1
=
.PP
UnknID
2
=
.PP
UnknSec
3
=
.PP
UnknMsgType
4
=
.PP
AppNA
5
=
.PP
CondFldMiss
6
=
.PP
NotAuth
7
=
.PP
NoDelivToFirm
.PP
   *   *   *   *   *
Used in messages:
[BusinessMessageReject (body_5251106.html?find=BusinessRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
