.TH FIX.4.4 "" "" "Tag #388"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
388 (tag388.html)
DiscretionInst (tag388.html)
\@DsctnInst
char
.PP
Code to identify the price a DiscretionOffsetValue (389) is related
to and should be mathematically added to
0
=
.PP
RelDispPx
1
=
.PP
RelMktPx
2
=
.PP
RelPrimPx
3
=
.PP
RelLocPrimPx
4
=
.PP
RelMidPx
5
=
.PP
RelLstPx
6
=
.PP
RelVWAP
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DiscretionInstructions (body_49484849.html?find=DiscretionInst)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
