.TH FIX.4.4 "" "" "Tag #403"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
403 (tag403.html)
LiquidityPctHigh (tag403.html)
\@LqdtyPctHigh
Percentage
.PP
Upper liquidity indicator if TotalNumSecurities (393) > \&.
Represented as a percentage.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[BidDescReqGrp (body_50484854.html?find=LiquidityPctHigh)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
