.TH FIX.4.4 "" "" "Tag #405"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
405 (tag405.html)
EFPTrackingError (tag405.html)
\@EFPTrkngErr
Percentage
.PP
Eg Used in EFP trades 2% (EFP – Exchange for Physical ).
Represented as a percentage.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[BidDescReqGrp (body_50484854.html?find=EFPTrackingError)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
