.TH FIX.4.4 "" "" "Tag #419"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
419 (tag419.html)
BasisPxType (tag419.html)
\@BasisPxTyp
char
.PP
Code to represent the basis price type
2
=
.PP
ClsPxMorn
3
=
.PP
ClsPx
4
=
.PP
CurrPx
5
=
.PP
SQ
6
=
.PP
VWAPDay
7
=
.PP
VWAPMorn
8
=
.PP
VWAPAft
9
=
.PP
VWAPDayXYORI
A
=
.PP
VWAPMornXYORI
B
=
.PP
VWAPAftXYORI
C
=
.PP
Strike
D
=
.PP
Open
Z
=
.PP
Others
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=BasisPxType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
