.TH FIX.4.4 "" "" "Tag #429"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
429 (tag429.html)
ListStatusType (tag429.html)
\@ListStatTyp
int
.PP
Code to represent the status type
1
=
.PP
Ack
2
=
.PP
Resp
3
=
.PP
Timed
4
=
.PP
ExecStart
5
=
.PP
AllDone
6
=
.PP
Alert
.PP
   *   *   *   *   *
Used in messages:
[ListStatus (body_505178.html?find=ListStatusType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
