.TH FIX.4.4 "" "" "Tag #433"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
433 (tag433.html)
ListExecInstType (tag433.html)
\@ListExecInstTyp
char
.PP
Identifies the type of ListExecInst (69)
1
=
.PP
Immed
2
=
.PP
Wait
3
=
.PP
ExchCIVSell
4
=
.PP
ExchCIVBuyTop
5
=
.PP
ExchCIVBuyWD
.PP
   *   *   *   *   *
Used in messages:
[NewOrderList (body_495369.html?find=ListExecInstType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
