.TH FIX.4.4 "" "" "Tag #434"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
434 (tag434.html)
CxlRejResponseTo (tag434.html)
\@CxlRejRspTo
char
.PP
Identifies the type of request that a Cancel Reject is in response
to
1
=
.PP
OrdCxlReq
2
=
.PP
OrdCxlRepReq
.PP
   *   *   *   *   *
Used in messages:
[OrderCancelReject (body_494857.html?find=CxlRejResponseTo)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
