.TH FIX.4.4 "" "" "Tag #447"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
447 (tag447.html)
PartyIDSource (tag447.html)
\@Src
char
.PP
Identifies class or source of the PartyID (448) value. Required if
PartyID is specified. Note: applicable values depend upon PartyRole
(452) specified.
.PP
See "Appendix 6-G – Use of <Parties> Component Block"
1
=
.PP
KoreanInvestorID
2
=
.PP
TaiwaneseQualified
3
=
.PP
TaiwaneseTradingAcct
4
=
.PP
MCDnumber
5
=
.PP
ChineseBShare
6
=
.PP
UKNationalInsPenNumber
7
=
.PP
USSocialSecurity
8
=
.PP
USEmployerIDNumber
9
=
.PP
AustralianBusinessNumber
A
=
.PP
AustralianTaxFileNumber
B
=
.PP
BIC
C
=
.PP
AccptMarketPart
D
=
.PP
PropCode
E
=
.PP
ISOCode
F
=
.PP
SettlEntLoc
G
=
.PP
MIC
H
=
.PP
CSDPartCode
I
=
.PP
DirectedDefinedISITC
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Parties (body_49484950.html?find=PartyIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
