.TH FIX.4.4 "" "" "Tag #448"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
448 (tag448.html)
PartyID (tag448.html)
\@ID
String
.PP
Party identifier/code. See PartyIDSource (447) and PartyRole (452).
.PP
See "Appendix 6-G – Use of <Parties> Component Block"
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Parties (body_49484950.html?find=PartyID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
