.TH FIX.4.4 "" "" "Tag #449"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
449 (tag449.html)
TotalVolumeTradedDate (tag449.html)
UTCDateOnly
.PP
No longer used as of FIX 4.4. Included here for reference to prior
versions.
.PP
*** REPLACED FIELD - See "Replaced Features and Supported Approach"
***
.PP
Date of TotalVolumeTraded (387).
.PP
(prior to FIX 4.4 field was of type UTCDate)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
