.TH FIX.4.4 "" "" "Tag #459"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
459 (tag459.html)
UnderlyingSecurityAltIDSource (tag459.html)
\@AltIDSrc
String
.PP
Identifies class or source of the UnderlyingSecurityAltID (458)
value. Required if UnderlyingSecurityAltID is specified.
.PP
Valid values:
.PP
Same
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UndSecAltIDGrp (body_50485551.html?find=UnderlyingSecurityAltIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
