.TH FIX.4.4 "" "" "Tag #47"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
47 (tag47.html)
Rule80A(No Longer Used) (tag47.html)
char
.PP
No longer used as of FIX.4.4. Included here for reference to prior
versions.
.PP
Note that the name of this field is changing to "OrderCapacity" as
Rule80A is a very US market-specific term. Other world markets need
to convey similar information, however, often a subset of the US
values. See the "Rule80A (aka OrderCapacity) Usage by Market"
appendix for market-specific usage of this field.
A
=
.PP
AgencySingle
B
=
.PP
ShtExTranA
C
=
.PP
PrgNonIndexArbMem
D
=
.PP
PrgIndexArbMem
E
=
.PP
MarketMaker
F
=
.PP
ShtExTranW
H
=
.PP
ShtExTranI
I
=
.PP
InvInestor
J
=
.PP
PrgNonIndexArbInv
K
=
.PP
PrgIndexArbInv
L
=
.PP
ShtExTranMem
M
=
.PP
PrgNonIndexArbOthMem
N
=
.PP
PrgIndexArbOthMem
O
=
.PP
CompetingDealer
P
=
.PP
Principal
R
=
.PP
CompDealer1
S
=
.PP
Specialist
T
=
.PP
CompDealer2
U
=
.PP
PrgIndexArbOthAgn
W
=
.PP
AllOtherAgn
X
=
.PP
ShtExTranMemWT
Y
=
.PP
PrgNonIndexArbOthAgn
Z
=
.PP
ShtExTranNonMem
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
