.TH FIX.4.4 "" "" "Tag #471"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
471 (tag471.html)
StateOrProvinceOfIssue (tag471.html)
\@StPrv
String
.PP
A two-character state or province abbreviation.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=StateOrProvinceOfIssue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
