.TH FIX.4.4 "" "" "Tag #480"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
480 (tag480.html)
CancellationRights (tag480.html)
\@CxllationRights
char
.PP
For CIV – A one character code identifying whether Cancellation
rights/Cooling off period applies
M
=
.PP
NoWaiver
N
=
.PP
NoExecOnly
O
=
.PP
NoInstit
Y
=
.PP
Yes
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=CancellationRights)]
[ExecutionReport (body_5756.html?find=CancellationRights)]
[MultilegOrderCancelReplace (body_54506567.html?find=CancellationRights)]
[NewOrderCross (body_5350115.html?find=CancellationRights)]
[NewOrderList (body_495369.html?find=CancellationRights)]
[NewOrderMultileg (body_54496566.html?find=CancellationRights)]
[NewOrderSingle (body_495268.html?find=CancellationRights)]
[OrderCancelReplaceRequest (body_495571.html?find=CancellationRights)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
