.TH FIX.4.4 "" "" "Tag #481"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
481 (tag481.html)
MoneyLaunderingStatus (tag481.html)
\@MnyLaunderingStat
char
.PP
A one character code identifying Money laundering status
1
=
.PP
ExBelowLim
2
=
.PP
ExClientMoneyType
3
=
.PP
ExAuthCredit
N
=
.PP
NotChecked
Y
=
.PP
Passed
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=MoneyLaunderingStatus)]
[ExecutionReport (body_5756.html?find=MoneyLaunderingStatus)]
[MultilegOrderCancelReplace (body_54506567.html?find=MoneyLaunderingStatus)]
[NewOrderCross (body_5350115.html?find=MoneyLaunderingStatus)]
[NewOrderList (body_495369.html?find=MoneyLaunderingStatus)]
[NewOrderMultileg (body_54496566.html?find=MoneyLaunderingStatus)]
[NewOrderSingle (body_495268.html?find=MoneyLaunderingStatus)]
[OrderCancelReplaceRequest (body_495571.html?find=MoneyLaunderingStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
