.TH FIX.4.4 "" "" "Tag #484"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
484 (tag484.html)
ExecPriceType (tag484.html)
\@ExecPxTyp
char
.PP
For CIV - Identifies how the execution price LastPx (3) was
calculated from the fund unit/share price(s) calculated at the fund
valuation point
B
=
.PP
BidPrice
C
=
.PP
CreationPrice
D
=
.PP
CreationPriceAdjPct
E
=
.PP
CreationPriceAdjAmt
O
=
.PP
OfferPrice
P
=
.PP
OfferPriceMinusAdjPct
Q
=
.PP
OfferPriceMinusAdjAmt
S
=
.PP
SinglePrice
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ExecPriceType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
