.TH FIX.4.4 "" "" "Tag #492"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
492 (tag492.html)
PaymentMethod (tag492.html)
\@PmtMethod
int
.PP
A code identifying the Settlement payment method.
.PP
16 through 998 are reserved for future use
.PP
Values above 000 are available for use by private agreement among
counterparties
1
=
.PP
CREST
2
=
.PP
NSCC
3
=
.PP
Euroclear
4
=
.PP
Clearstream
5
=
.PP
Cheque
6
=
.PP
TelegraphicTransfer
7
=
.PP
FedWire
8
=
.PP
DebitCard
9
=
.PP
DirectDebitBECS
10
=
.PP
DirectCreditBECS
11
=
.PP
CreditCard
12
=
.PP
ACHDebit
13
=
.PP
ACHCredit
14
=
.PP
BPAY
15
=
.PP
HighValueClearingSystemHVACS
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlInstGrp (body_50485355.html?find=PaymentMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
