.TH FIX.4.4 "" "" "Tag #493"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
493 (tag493.html)
RegistAcctType (tag493.html)
\@AcctTyp
String
.PP
For CIV – a fund manager-defined code identifying which of the fund
manager’s account types is required.
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=RegistAcctType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
