.TH FIX.4.4 "" "" "Tag #495"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
495 (tag495.html)
TaxAdvantageType (tag495.html)
\@TaxAdvantageTyp
int
.PP
For CIV - a code identifying the type of tax exempt account in
which purchased shares/units are to be held
0
=
.PP
None
1
=
.PP
MaxiISAUK
2
=
.PP
TESSAUK
3
=
.PP
MiniCashISAUK
4
=
.PP
MiniStocksAndSharesISAUK
5
=
.PP
MiniInsuranceISAUK
6
=
.PP
CurrentYearPaymentUS
7
=
.PP
PriorYearPaymentUS
8
=
.PP
AssetTransferUS
9
=
.PP
EmployeePriorYearUS
10
=
.PP
EmployeeCurrentYearUS
11
=
.PP
EmployerPriorYearUS
12
=
.PP
EmployerCurrentYearUS
13
=
.PP
NonfundPrototypeIRAUS
14
=
.PP
NonfundQualifiedPlanUS
15
=
.PP
DefinedContributionPlanUS
16
=
.PP
IndividualRetirementAccountUS
17
=
.PP
IndividualRetirementAccountRolloverUS
18
=
.PP
KEOGHUS
19
=
.PP
ProfitSharingPlanUS
20
=
.PP
401KUS
21
=
.PP
SelfDirectedIRAUS
22
=
.PP
403bUS
23
=
.PP
457US
24
=
.PP
RothIRAFundPrototypeUS
25
=
.PP
RothIRANonprototypeUS
26
=
.PP
RothConversionIRAFundPrototypeUS
27
=
.PP
RothConversionIRANonprototypeUS
28
=
.PP
EducationIRAFundPrototypeUS
29
=
.PP
EducationIRANonprototypeUS
999
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=TaxAdvantageType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
