.TH FIX.4.4 "" "" "Tag #499"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
499 (tag499.html)
CashDistribAgentCode (tag499.html)
\@CshDistribAgentCode
String
.PP
BIC (Bank Identification Code--Swift managed) code of agent bank
for cash distributions
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RgstDistInstGrp (body_50485350.html?find=CashDistribAgentCode)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
