.TH FIX.4.4 "" "" "Tag #507"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
507 (tag507.html)
RegistRejReasonCode (tag507.html)
\@RejRsnCd
int
.PP
Reason(s) why Registration Instructions has been rejected.
.PP
The reason may be further amplified in the RegistRejReasonCode
field.
.PP
Possible values of reason code include:
1
=
.PP
InvalidAccountType
2
=
.PP
InvalidTaxExemptType
3
=
.PP
InvalidOwnershipType
4
=
.PP
InvalidNoRegDetls
5
=
.PP
InvalidRegSeqNo
6
=
.PP
InvalidRegDtls
7
=
.PP
InvalidMailingDtls
8
=
.PP
InvalidMailingInst
9
=
.PP
InvalidInvestorID
10
=
.PP
InvalidInvestorIDSource
11
=
.PP
InvalidDateOfBirth
12
=
.PP
InvalidInvestorCountryOfResidence
13
=
.PP
InvalidNoDistribInstns
14
=
.PP
InvalidDistribPercentage
15
=
.PP
InvalidDistribPaymentMethod
16
=
.PP
InvalidCashDistribAgentAcctName
17
=
.PP
InvalidCashDistribAgentCode
18
=
.PP
InvalidCashDistribAgentAcctNum
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructionsResponse (body_5257112.html?find=RegistRejReasonCode)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
