.TH FIX.4.4 "" "" "Tag #511"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
511 (tag511.html)
RegistEmail (tag511.html)
\@Email
String
.PP
Email address relating to Registration name and address details
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RgstDtlsGrp (body_50485351.html?find=RegistEmail)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
