.TH FIX.4.4 "" "" "Tag #519"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
519 (tag519.html)
ContAmtType (tag519.html)
\@ContAmtTyp
int
.PP
Type of ContAmtValue (520).
.PP
NOTE That Commission Amount / % in Contract Amounts is the
commission actually charged, rather than the commission
instructions given in Fields 2/3.
.PP
For UK
1
=
.PP
CommissionAmt
2
=
.PP
CommissionPct
3
=
.PP
InitialChargeAmt
4
=
.PP
InitialChargePct
5
=
.PP
DiscountAmt
6
=
.PP
DiscountPCt
7
=
.PP
DilutionLevyAmt
8
=
.PP
DilutionLevyPct
9
=
.PP
ExitChargeAmt
10
=
.PP
ExitChargePct
11
=
.PP
FundBasedRenewalComm
12
=
.PP
ProjectedFundValue
13
=
.PP
FundBasedRenewalCommAmtOrd
14
=
.PP
FundBasedRenewalCommAmtProj
15
=
.PP
NetSettlementAmount
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ContAmtGrp (body_50484949.html?find=ContAmtType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
