.TH FIX.4.4 "" "" "Tag #521"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
521 (tag521.html)
ContAmtCurr (tag521.html)
\@ContAmtCurr
Currency
.PP
Specifies currency for the Contract amount if different from the
Deal Currency - see "Appendix 6-A; Valid Currency Codes".
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ContAmtGrp (body_50484949.html?find=ContAmtCurr)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
