.TH FIX.4.4 "" "" "Tag #522"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
522 (tag522.html)
OwnerType (tag522.html)
\@OwnerTyp
int
.PP
Identifies the type of owner
1
=
.PP
IndivInvestor
2
=
.PP
PublicCompany
3
=
.PP
PrivateCompany
4
=
.PP
IndivTrustee
5
=
.PP
CompanyTrustee
6
=
.PP
PensionPlan
7
=
.PP
CustodianMinorsAct
8
=
.PP
Trusts
9
=
.PP
Fiduciaries
10
=
.PP
NetworkingSubAcct
11
=
.PP
Non-ProfitOrg
12
=
.PP
CorpBody
13
=
.PP
Nominee
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RgstDtlsGrp (body_50485351.html?find=OwnerType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
