.TH FIX.4.4 "" "" "Tag #524"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
524 (tag524.html)
NestedPartyID (tag524.html)
\@ID
String
.PP
PartyID value within a nested repeating group.
.PP
Same values as PartyID (448)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NestedParties (body_49484856.html?find=NestedPartyID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
