.TH FIX.4.4 "" "" "Tag #528"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
528 (tag528.html)
OrderCapacity (tag528.html)
\@Cpcty
char
.PP
Designates the capacity of the firm placing the order
.PP
(as of FIX 4.3, this field replaced Rule80A (tag 47) --used in
conjunction with OrderRestrictions (529) field)
.PP
(see Volume : "Glossary" for value definitions)
A
=
.PP
Agency
G
=
.PP
Proprietary
I
=
.PP
Individual
P
=
.PP
Principal
R
=
.PP
RisklessPrincipal
W
=
.PP
AgentOtherMember
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=OrderCapacity)]
[MultilegOrderCancelReplace (body_54506567.html?find=OrderCapacity)]
[NewOrderMultileg (body_54496566.html?find=OrderCapacity)]
[NewOrderSingle (body_495268.html?find=OrderCapacity)]
[OrderCancelReplaceRequest (body_495571.html?find=OrderCapacity)]
[Quote (body_505583.html?find=OrderCapacity)]
[QuoteRequest (body_505482.html?find=OrderCapacity)]
[QuoteResponse (body_54576574.html?find=OrderCapacity)]
[TradeCaptureReportAck (body_55556582.html?find=OrderCapacity)]
.PP
   *   *   *   *   *
Used in components:
[CpctyConfGrp (body_50484951.html?find=OrderCapacity)]
[ListOrdGrp (body_50485148.html?find=OrderCapacity)]
[SideCrossOrdModGrp (body_50485357.html?find=OrderCapacity)]
[TrdCapRptSideGrp (body_50485449.html?find=OrderCapacity)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
