.TH FIX.4.4 "" "" "Tag #53"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
53 (tag53.html)
Quantity (tag53.html)
\@Qty
Qty
.PP
Overall/total quantity (e.g. number of shares)
.PP
(Prior to FIX 4.2 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=Quantity)]
[AllocationInstruction (body_495774.html?find=Quantity)]
[AllocationReport (body_55566583.html?find=Quantity)]
[CollateralAssignment (body_56526589.html?find=Quantity)]
[CollateralInquiry (body_56556666.html?find=Quantity)]
[CollateralInquiryAck (body_57506671.html?find=Quantity)]
[CollateralReport (body_56546665.html?find=Quantity)]
[CollateralRequest (body_56516588.html?find=Quantity)]
[CollateralResponse (body_56536590.html?find=Quantity)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
