.TH FIX.4.4 "" "" "Tag #530"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
530 (tag530.html)
MassCancelRequestType (tag530.html)
\@MassCxlReqTyp
char
.PP
Specifies scope of Order Mass Cancel Request
1
=
.PP
CxlOrdersSecurity
2
=
.PP
CxlOrdersUnderlyingSecurity
3
=
.PP
CxlOrdersProduct
4
=
.PP
CxlOrdersCFICode
5
=
.PP
CxlOrdersSecurityType
6
=
.PP
CxlOrdersTrdSession
7
=
.PP
CxlAllOrders
.PP
   *   *   *   *   *
Used in messages:
[OrderMassCancelReport (body_5349114.html?find=MassCancelRequestType)]
[OrderMassCancelRequest (body_5348113.html?find=MassCancelRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
