.TH FIX.4.4 "" "" "Tag #532"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
532 (tag532.html)
MassCancelRejectReason (tag532.html)
\@MassCxlRejRsn
char
.PP
Reason Order Mass Cancel Request was rejected
0
=
.PP
MassCxlNotSupported
1
=
.PP
InvalidSecurity
2
=
.PP
InvalidUnderlying
3
=
.PP
InvalidProduct
4
=
.PP
InvalidCFICode
5
=
.PP
InvalidSecurityType
6
=
.PP
InvalidTrdSession
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[OrderMassCancelReport (body_5349114.html?find=MassCancelRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
