.TH FIX.4.4 "" "" "Tag #540"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
540 (tag540.html)
TotalAccruedInterestAmt (tag540.html)
\@TotAcrdIntAmt
Amt
.PP
*** DEPRECATED FIELD - See "Deprecated (Phased-out) Features and
Supported Approach" ***
.PP
Total Amount of Accrued Interest for convertible bonds and fixed
income
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=TotalAccruedInterestAmt)]
[AllocationReport (body_55566583.html?find=TotalAccruedInterestAmt)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
