.TH FIX.4.4 "" "" "Tag #543"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
543 (tag543.html)
InstrRegistry (tag543.html)
\@Rgstry
String
.PP
The location at which records of ownership are maintained for this
instrument, and at which ownership changes must be recorded.
BIC
=
.PP
Custodian
ISO
=
.PP
Country
ZZ
=
.PP
Physical
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=InstrRegistry)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
