.TH FIX.4.4 "" "" "Tag #545"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
545 (tag545.html)
NestedPartySubID (tag545.html)
\@ID
String
.PP
PartySubID value within a nested repeating group.
.PP
Same values as PartySubID (523)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NstdPtysSubGrp (body_50485556.html?find=NestedPartySubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
