.TH FIX.4.4 "" "" "Tag #548"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
548 (tag548.html)
CrossID (tag548.html)
\@CrssID
String
.PP
Identifier for a cross order. Must be unique during a given trading
day. Recommend that firms use the order date as part of the CrossID
for Good Till Cancel (GT) orders.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=CrossID)]
[CrossOrderCancelRequest (body_5352117.html?find=CrossID)]
[ExecutionReport (body_5756.html?find=CrossID)]
[NewOrderCross (body_5350115.html?find=CrossID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
