.TH FIX.4.4 "" "" "Tag #549"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
549 (tag549.html)
CrossType (tag549.html)
\@CrssTyp
int
.PP
Type of cross being submitted to a market
1
=
.PP
CrossAON
2
=
.PP
CrossIOC
3
=
.PP
CrossOneSide
4
=
.PP
CrossSamePrice
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=CrossType)]
[CrossOrderCancelRequest (body_5352117.html?find=CrossType)]
[ExecutionReport (body_5756.html?find=CrossType)]
[NewOrderCross (body_5350115.html?find=CrossType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
