.TH FIX.4.4 "" "" "Tag #555"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
555 (tag555.html)
NoLegs (tag555.html)
\@NoLegs
NumInGroup
.PP
Number of InstrumentLeg repeating group instances.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=NoLegs)]
[InstrmtLegGrp (body_50484957.html?find=NoLegs)]
[InstrmtLegIOIGrp (body_50485048.html?find=NoLegs)]
[InstrmtLegSecListGrp (body_50485049.html?find=NoLegs)]
[LegOrdGrp (body_50485053.html?find=NoLegs)]
[LegQuotGrp (body_50485055.html?find=NoLegs)]
[LegQuotStatGrp (body_50485056.html?find=NoLegs)]
[QuotReqLegsGrp (body_50485254.html?find=NoLegs)]
[TrdInstrmtLegGrp (body_50485451.html?find=NoLegs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
