.TH FIX.4.4 "" "" "Tag #557"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
557 (tag557.html)
TotNoSecurityTypes (tag557.html)
\@TotNoSecTyps
int
.PP
Indicates total number of security types in the event that multiple
Security Type messages are used to return results
.PP
(Prior to FIX 4.4 this field was named TotalNumSecurityTypes)
.PP
   *   *   *   *   *
Used in messages:
[SecurityTypes (body_5354119.html?find=TotNoSecurityTypes)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
