.TH FIX.4.4 "" "" "Tag #563"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
563 (tag563.html)
MultiLegRptTypeReq (tag563.html)
\@MLEGRptTypReq
int
.PP
Indicates the method of execution reporting requested by issuer of
the order
0
=
.PP
Report by mulitleg security only
1
=
.PP
Report by multileg security and by instrument legs belonging to the
multileg security
2
=
.PP
Report by instrument legs belonging to the multileg security only
.PP
   *   *   *   *   *
Used in messages:
[MultilegOrderCancelReplace (body_54506567.html?find=MultiLegRptTypeReq)]
[NewOrderMultileg (body_54496566.html?find=MultiLegRptTypeReq)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
