.TH FIX.4.4 "" "" "Tag #565"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
565 (tag565.html)
LegCoveredOrUncovered (tag565.html)
\@Cover
int
.PP
CoveredOrUncovered for leg of a multileg
.PP
See CoveredOrUncovered (203) field for description
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegCoveredOrUncovered)]
[LegOrdGrp (body_50485053.html?find=LegCoveredOrUncovered)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegCoveredOrUncovered)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
