.TH FIX.4.4 "" "" "Tag #569"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
569 (tag569.html)
TradeRequestType (tag569.html)
\@ReqTyp
int
.PP
Type of Trade Capture Report
0
=
.PP
AllTrades
1
=
.PP
MatchedTrades
2
=
.PP
UnmatchedTrades
3
=
.PP
UnreportedTrades
4
=
.PP
AdvisoriesMatch
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReportRequest (body_54516568.html?find=TradeRequestType)]
[TradeCaptureReportRequestAck (body_55546581.html?find=TradeRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
