.TH FIX.4.4 "" "" "Tag #574"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
574 (tag574.html)
MatchType (tag574.html)
\@MtchTyp
String
.PP
The point in the matching process at which this trade was matched
A1
=
.PP
ExactMatchOnTradeDateStockSymbolQuantityPriceTradeTypeAndSpecialTradeIndicatorPlusFourBadgesAndExecutionTime
A2
=
.PP
ExactMatchOnTradeDateStockSymbolQuantityPriceTradeTypeAndSpecialTradeIndicatorPlusFourBadges
A3
=
.PP
ExactMatchOnTradeDateStockSymbolQuantityPriceTradeTypeAndSpecialTradeIndicatorPlusTwoBadgesAndExecutionTime
A4
=
.PP
ExactMatchOnTradeDateStockSymbolQuantityPriceTradeTypeAndSpecialTradeIndicatorPlusTwoBadges
A5
=
.PP
ExactMatchOnTradeDateStockSymbolQuantityPriceTradeTypeAndSpecialTradeIndicatorPlusExecutionTime
ACTM1
=
.PP
NASDAQACTM1Match
ACTM2
=
.PP
NASDAQACTM2Match
ACTM3
=
.PP
NASDAQACTAcceptedTrade
ACTM4
=
.PP
NASDAQACTDefaultTrade
ACTM5
=
.PP
NASDAQACTDefaultAfterM2
ACTM6
=
.PP
NASDAQACTM6Match
ACTMT
=
.PP
NASDAQNonACT
AQ
=
.PP
ComparedRecordsResultingFromStampedAdvisoriesOrSpecialistAcceptsPairOffs
M1
=
.PP
ExactMatchOnTradeDateStockSymbolQuantityPriceTradeTypeAndSpecialTradeIndicatorMinusBadgesAndTimes
M2
=
.PP
SummarizedMatchMinusBadgesAndTimes
MT
=
.PP
OCSLockedIn
S1
=
.PP
SummarizedMatchUsingA1
S2
=
.PP
SummarizedMatchUsingA2
S3
=
.PP
SummarizedMatchUsingA3
S4
=
.PP
SummarizedMatchUsingA4
S5
=
.PP
SummarizedMatchUsingA5
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=MatchType)]
[AllocationReport (body_55566583.html?find=MatchType)]
[TradeCaptureReport (body_54526569.html?find=MatchType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
