.TH FIX.4.4 "" "" "Tag #575"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
575 (tag575.html)
OddLot (tag575.html)
\@OddLot
Boolean
.PP
This trade is to be treated as an odd lot
.PP
Values:
.PP
Y = treat as odd lot
.PP
N = treat as round lot
.PP
If this field is not specified, the default will be "N"
N
=
.PP
No
Y
=
.PP
Yes
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptSideGrp (body_50485449.html?find=OddLot)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
