.TH FIX.4.4 "" "" "Tag #577"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
577 (tag577.html)
ClearingInstruction (tag577.html)
\@ClrngInstrctn
int
.PP
Eligibility of this trade for clearing and central counterparty
processing
0
=
.PP
processNormally
1
=
.PP
excludeFromAllNetting
2
=
.PP
bilateralNettingOnly
3
=
.PP
exClearing
4
=
.PP
specialTrade
5
=
.PP
multilateralNetting
6
=
.PP
clearAgainstCentralCounterparty
7
=
.PP
excludeFromCentralCounterparty
8
=
.PP
ManualModePrepostingAndorPregiveup
9
=
.PP
AutomaticPostingModeTradePostingToThePositionAccountNumberSpecified
10
=
.PP
AutomaticGiveupModeTradeGiveupToTheGiveupDestinationNumberSpecified
11
=
.PP
QualifiedServiceRepresentativeQSR
12
=
.PP
CustomerTrade
13
=
.PP
SelfClearing
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ClrInstGrp (body_50484855.html?find=ClearingInstruction)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
