.TH FIX.4.4 "" "" "Tag #587"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
587 (tag587.html)
LegSettlType (tag587.html)
\@SettlTyp
char
.PP
Refer to values for SettlType[63]
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegSettlType)]
[InstrmtLegSecListGrp (body_50485049.html?find=LegSettlType)]
[LegOrdGrp (body_50485053.html?find=LegSettlType)]
[LegQuotGrp (body_50485055.html?find=LegSettlType)]
[LegQuotStatGrp (body_50485056.html?find=LegSettlType)]
[QuotReqLegsGrp (body_50485254.html?find=LegSettlType)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegSettlType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
