.TH FIX.4.4 "" "" "Tag #589"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
589 (tag589.html)
DayBookingInst (tag589.html)
\@DayBkngInst
char
.PP
Indicates whether or not automatic booking can occur.
0
=
.PP
Can trigger booking without reference to the order initiator auto
1
=
.PP
Speak with order initiator before booking speak first
2
=
.PP
Accumulate
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=DayBookingInst)]
[MultilegOrderCancelReplace (body_54506567.html?find=DayBookingInst)]
[NewOrderMultileg (body_54496566.html?find=DayBookingInst)]
[NewOrderSingle (body_495268.html?find=DayBookingInst)]
[OrderCancelReplaceRequest (body_495571.html?find=DayBookingInst)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=DayBookingInst)]
[SideCrossOrdModGrp (body_50485357.html?find=DayBookingInst)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
