.TH FIX.4.4 "" "" "Tag #59"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
59 (tag59.html)
TimeInForce (tag59.html)
\@TmInForce
char
.PP
Specifies how long the order remains in effect. Absence of this
field is interpreted as DAY.
0
=
.PP
Day
1
=
.PP
GoodTillCancel
2
=
.PP
AtTheOpening
3
=
.PP
ImmediateOrCancel
4
=
.PP
FillOrKill
5
=
.PP
GoodTillCrossing
6
=
.PP
GoodTillDate
7
=
.PP
AtTheClose
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=TimeInForce)]
[ExecutionReport (body_5756.html?find=TimeInForce)]
[MultilegOrderCancelReplace (body_54506567.html?find=TimeInForce)]
[NewOrderCross (body_5350115.html?find=TimeInForce)]
[NewOrderMultileg (body_54496566.html?find=TimeInForce)]
[NewOrderSingle (body_495268.html?find=TimeInForce)]
[OrderCancelReplaceRequest (body_495571.html?find=TimeInForce)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=TimeInForce)]
[MDFullGrp (body_50485149.html?find=TimeInForce)]
[MDIncGrp (body_50485150.html?find=TimeInForce)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
