.TH FIX.4.4 "" "" "Tag #60"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
60 (tag60.html)
TransactTime (tag60.html)
\@TxnTm
UTCTimestamp
.PP
Time of execution/order creation (expressed in UTC (Universal Time
Coordinated, also known as "GMT")
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=TransactTime)]
[AllocationInstruction (body_495774.html?find=TransactTime)]
[AllocationInstructionAck (body_505280.html?find=TransactTime)]
[AllocationReport (body_55566583.html?find=TransactTime)]
[AllocationReportAck (body_55576584.html?find=TransactTime)]
[CollateralAssignment (body_56526589.html?find=TransactTime)]
[CollateralRequest (body_56516588.html?find=TransactTime)]
[CollateralResponse (body_56536590.html?find=TransactTime)]
[Confirmation (body_55486575.html?find=TransactTime)]
[ConfirmationRequest (body_57516672.html?find=TransactTime)]
[Confirmation_Ack (body_56486585.html?find=TransactTime)]
[CrossOrderCancelReplaceRequest (body_5351116.html?find=TransactTime)]
[CrossOrderCancelRequest (body_5352117.html?find=TransactTime)]
[ExecutionReport (body_5756.html?find=TransactTime)]
[IOI (body_5554.html?find=TransactTime)]
[ListCancelRequest (body_504875.html?find=TransactTime)]
[ListExecute (body_504976.html?find=TransactTime)]
[ListStatus (body_505178.html?find=TransactTime)]
[MultilegOrderCancelReplace (body_54506567.html?find=TransactTime)]
[NewOrderCross (body_5350115.html?find=TransactTime)]
[NewOrderMultileg (body_54496566.html?find=TransactTime)]
[NewOrderSingle (body_495268.html?find=TransactTime)]
[OrderCancelReject (body_494857.html?find=TransactTime)]
[OrderCancelReplaceRequest (body_495571.html?find=TransactTime)]
[OrderCancelRequest (body_495470.html?find=TransactTime)]
[OrderMassCancelReport (body_5349114.html?find=TransactTime)]
[OrderMassCancelRequest (body_5348113.html?find=TransactTime)]
[PositionMaintenanceReport (body_55506577.html?find=TransactTime)]
[PositionMaintenanceRequest (body_55496576.html?find=TransactTime)]
[Quote (body_505583.html?find=TransactTime)]
[QuoteResponse (body_54576574.html?find=TransactTime)]
[QuoteStatusReport (body_54566573.html?find=TransactTime)]
[RequestForPositions (body_55516578.html?find=TransactTime)]
[SecurityStatus (body_5157102.html?find=TransactTime)]
[SettlementInstructionRequest (body_56496586.html?find=TransactTime)]
[SettlementInstructions (body_505684.html?find=TransactTime)]
[TradeCaptureReport (body_54526569.html?find=TransactTime)]
[TradeCaptureReportAck (body_55556582.html?find=TransactTime)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=TransactTime)]
[QuotEntryAckGrp (body_50485250.html?find=TransactTime)]
[QuotEntryGrp (body_50485251.html?find=TransactTime)]
[QuotReqGrp (body_50485253.html?find=TransactTime)]
[QuotReqRjctGrp (body_50485255.html?find=TransactTime)]
[TrdCapDtGrp (body_50485457.html?find=TransactTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
