.TH FIX.4.4 "" "" "Tag #62"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
62 (tag62.html)
ValidUntilTime (tag62.html)
\@ValidUntilTm
UTCTimestamp
.PP
Indicates expiration time of indication message (always expressed
in UTC (Universal Time Coordinated, also known as "GMT")
.PP
   *   *   *   *   *
Used in messages:
[IOI (body_5554.html?find=ValidUntilTime)]
[Quote (body_505583.html?find=ValidUntilTime)]
[QuoteResponse (body_54576574.html?find=ValidUntilTime)]
[QuoteStatusReport (body_54566573.html?find=ValidUntilTime)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=ValidUntilTime)]
[QuotEntryGrp (body_50485251.html?find=ValidUntilTime)]
[QuotReqGrp (body_50485253.html?find=ValidUntilTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
