.TH FIX.4.4 "" "" "Tag #623"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
623 (tag623.html)
LegRatioQty (tag623.html)
\@RatioQty
float
.PP
The ratio of quantity for this individual leg relative to the
entire multileg security.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegRatioQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
