.TH FIX.4.4 "" "" "Tag #626"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
626 (tag626.html)
AllocType (tag626.html)
\@AllocType
int
.PP
Describes the specific type or purpose of an Allocation message
(i.e. "Buyside Calculated")
1
=
.PP
BuysideCalc
2
=
.PP
BuysidePrelim
3
=
.PP
SellsideCalc
4
=
.PP
SellsideCalcWithoutPrelim
5
=
.PP
BuysideReadyToBookSingle
6
=
.PP
BuysideReadyToBookCombined
7
=
.PP
WarehouseInstruction
8
=
.PP
RequestToIntermediary
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=AllocType)]
[AllocationInstructionAck (body_505280.html?find=AllocType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
