.TH FIX.4.4 "" "" "Tag #628"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
628 (tag628.html)
HopCompID (tag628.html)
\@ID
String
.PP
Assigned value used to identify the third party firm which
delivered a specific message either from the firm which originated
the message or from another third party (if multiple "hops" are
performed). It is recommended that this value be the SenderCompID
(49) of the third party.
.PP
Applicable when messages are communicated/re-distributed via third
parties which function as service bureaus or "hubs". Only
applicable if OnBehalfOfCompID (5) is being used.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Hop (body_50485653.html?find=HopCompID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
