.TH FIX.4.4 "" "" "Tag #629"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
629 (tag629.html)
HopSendingTime (tag629.html)
\@Snt
UTCTimestamp
.PP
Time that HopCompID (628) sent the message. It is recommended that
this value be the SendingTime (52) of the message sent by the third
party.
.PP
Applicable when messages are communicated/re-distributed via third
parties which function as service bureaus or "hubs". Only
applicable if OnBehalfOfCompID (5) is being used.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Hop (body_50485653.html?find=HopSendingTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
