.TH FIX.4.4 "" "" "Tag #633"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
633 (tag633.html)
MidYield (tag633.html)
\@MidYld
Percentage
.PP
Mid yield
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=MidYield)]
[QuoteResponse (body_54576574.html?find=MidYield)]
[QuoteStatusReport (body_54566573.html?find=MidYield)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=MidYield)]
[QuotEntryGrp (body_50485251.html?find=MidYield)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
