.TH FIX.4.4 "" "" "Tag #635"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
635 (tag635.html)
ClearingFeeIndicator (tag635.html)
\@ClrFeeInd
String
.PP
Indicates type of fee being assessed of the customer for trade
executions at an exchange. Applicable for futures markets only at
this time.
.PP
(Values source CBOT, CME, NYBOT, and NYMEX):
1
=
.PP
1stYearDelegate
2
=
.PP
2ndYearDelegate
3
=
.PP
3rdYearDelegate
4
=
.PP
4thYearDelegate
5
=
.PP
5thYearDelegate
9
=
.PP
6thYearDelegate
B
=
.PP
CBOEMember
C
=
.PP
NonMemberCustomer
E
=
.PP
EquityClearingMember
F
=
.PP
FullAssociateMember
H
=
.PP
106H106J
I
=
.PP
GIMIDEMCOMMembership
L
=
.PP
Lessee106F
M
=
.PP
AllOthers
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ClearingFeeIndicator)]
[MultilegOrderCancelReplace (body_54506567.html?find=ClearingFeeIndicator)]
[NewOrderMultileg (body_54496566.html?find=ClearingFeeIndicator)]
[NewOrderSingle (body_495268.html?find=ClearingFeeIndicator)]
[OrderCancelReplaceRequest (body_495571.html?find=ClearingFeeIndicator)]
[TradeCaptureReportAck (body_55556582.html?find=ClearingFeeIndicator)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=ClearingFeeIndicator)]
[SideCrossOrdModGrp (body_50485357.html?find=ClearingFeeIndicator)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
