.TH FIX.4.4 "" "" "Tag #642"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
642 (tag642.html)
BidForwardPoints2 (tag642.html)
\@BidFwdPnts2
PriceOffset
.PP
Bid F/X forward points of the future portion of a F/X swap quote
added to spot rate. May be a negative value.
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=BidForwardPoints2)]
[QuoteResponse (body_54576574.html?find=BidForwardPoints2)]
[QuoteStatusReport (body_54566573.html?find=BidForwardPoints2)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=BidForwardPoints2)]
[QuotEntryGrp (body_50485251.html?find=BidForwardPoints2)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
