.TH FIX.4.4 "" "" "Tag #653"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
653 (tag653.html)
SecDefStatus (tag653.html)
int
.PP
No longer used as of FIX 4.3. Included here for reference to prior
versions.
.PP
*** REPLACED FIELD - See "Replaced Features and Supported Approach"
***
.PP
State of a security definition request made to a market. Useful for
markets, such as derivatives markets, where market participants are
permitted to define instruments for subsequent trading
0
=
.PP
PendingApproval
1
=
.PP
ApprovedAccepted
2
=
.PP
Rejected
3
=
.PP
UnauthorizedRequest
4
=
.PP
InvalidDefinitionRequest
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
