.TH FIX.4.4 "" "" "Tag #658"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
658 (tag658.html)
QuoteRequestRejectReason (tag658.html)
\@ReqRejRsn
int
.PP
Reason Quote was rejected:
1
=
.PP
UnknownSym
2
=
.PP
ExchangeClosed
3
=
.PP
QuoteRequestExLimit
4
=
.PP
TooLate
5
=
.PP
InvPrice
6
=
.PP
NotAuthToReqQuote
7
=
.PP
NoMatchForInquiry
8
=
.PP
NoMarketForInstrument
9
=
.PP
NoInventory
10
=
.PP
Pass
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[QuoteRequestReject (body_54546571.html?find=QuoteRequestRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
