.TH FIX.4.4 "" "" "Tag #659"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
659 (tag659.html)
SideComplianceID (tag659.html)
\@SideComplianceID
String
.PP
ID within repeating group of sides which is used to represent this
transaction for compliance purposes (e.g. OATS reporting).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SideCrossOrdModGrp (body_50485357.html?find=SideComplianceID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
