.TH FIX.4.4 "" "" "Tag #666"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
666 (tag666.html)
ConfirmTransType (tag666.html)
\@CnfmTransTyp
int
.PP
Identifies the Confirmation transaction type
0
=
.PP
New
1
=
.PP
Replace
2
=
.PP
Cancel
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=ConfirmTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
