.TH FIX.4.4 "" "" "Tag #673"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
673 (tag673.html)
LegAllocQty (tag673.html)
\@AllocQty
Qty
.PP
Leg allocation quantity.
.PP
See AllocQty (80) for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[LegPreAllocGrp (body_50485054.html?find=LegAllocQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
