.TH FIX.4.4 "" "" "Tag #674"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
674 (tag674.html)
LegAllocAcctIDSource (tag674.html)
\@AllocAcctIDSrc
String
.PP
The source of the LegAllocAccount (67)
.PP
See AllocAcctIDSource (66) for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[LegPreAllocGrp (body_50485054.html?find=LegAllocAcctIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
