.TH FIX.4.4 "" "" "Tag #679"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
679 (tag679.html)
LegBenchmarkPrice (tag679.html)
\@Px
Price
.PP
Used to identify the price of the benchmark security.
.PP
See BenchmarkPrice (662) for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[LegBenchmarkCurveData (body_49484854.html?find=LegBenchmarkPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
