.TH FIX.4.4 "" "" "Tag #687"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
687 (tag687.html)
LegQty (tag687.html)
\@Qty
Qty
.PP
Quantity of this leg, e.g. in Quote dialog.
.PP
See Quantity (53) for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegQty)]
[LegOrdGrp (body_50485053.html?find=LegQty)]
[LegQuotGrp (body_50485055.html?find=LegQty)]
[LegQuotStatGrp (body_50485056.html?find=LegQty)]
[QuotReqLegsGrp (body_50485254.html?find=LegQty)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
