.TH FIX.4.4 "" "" "Tag #698"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
698 (tag698.html)
YieldRedemptionPriceType (tag698.html)
\@RedPxTyp
int
.PP
The price type of the YieldRedemptionPrice (697)
.PP
See PriceType (423) for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[YieldData (body_49485050.html?find=YieldRedemptionPriceType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
