.TH FIX.4.4 "" "" "Tag #703"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
703 (tag703.html)
PosType (tag703.html)
\@Typ
String
.PP
Used to identify the type of quantity that is being returned
ALC
=
.PP
AllocationTradeQty
AS
=
.PP
OptionAssignment
ASF
=
.PP
AsofTradeQty
DLV
=
.PP
DeliveryQty
ETR
=
.PP
ElectronicTradeQty
EX
=
.PP
OptionExerciseQty
FIN
=
.PP
EndofDayQty
IAS
=
.PP
IntraSpreadQty
IES
=
.PP
InterSpreadQty
PA
=
.PP
AdjustmentQty
PIT
=
.PP
PitTradeQty
SOD
=
.PP
StartofDayQty
SPL
=
.PP
IntegralSplit
TA
=
.PP
TransactionFromAssignment
TOT
=
.PP
TotalTransactionQty
TQ
=
.PP
TransactionQuantity
TRF
=
.PP
TransferTradeQty
TX
=
.PP
TransactionFromExercise
XM
=
.PP
CrossMarginQty
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PositionQty (body_49484953.html?find=PosType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
