.TH FIX.4.4 "" "" "Tag #705"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
705 (tag705.html)
ShortQty (tag705.html)
\@Short
Qty
.PP
Short Quantity
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PositionQty (body_49484953.html?find=ShortQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
