.TH FIX.4.4 "" "" "Tag #706"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
706 (tag706.html)
PosQtyStatus (tag706.html)
\@Stat
int
.PP
Status of this position
0
=
.PP
Submitted
1
=
.PP
Accepted
2
=
.PP
Rejected
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PositionQty (body_49484953.html?find=PosQtyStatus)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
