.TH FIX.4.4 "" "" "Tag #709"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
709 (tag709.html)
PosTransType (tag709.html)
\@TxnTyp
int
.PP
Identifies the type of position transaction
1
=
.PP
Exercise
2
=
.PP
DoNotExercise
3
=
.PP
PositionAdjustment
4
=
.PP
PositionChangeSubmissionMarginDisposition
5
=
.PP
Pledge
.PP
   *   *   *   *   *
Used in messages:
[PositionMaintenanceReport (body_55506577.html?find=PosTransType)]
[PositionMaintenanceRequest (body_55496576.html?find=PosTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
