.TH FIX.4.4 "" "" "Tag #71"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
71 (tag71.html)
AllocTransType (tag71.html)
\@TransTyp
char
.PP
Identifies allocation transaction type
.PP
*** SOME VALUES HAVE BEEN REPLACED - See "Replaced Features and
Supported Approach" ***
0
=
.PP
New
1
=
.PP
Replace
2
=
.PP
Cancel
3
=
.PP
Preliminary
4
=
.PP
Calculated
5
=
.PP
CalculatedWithoutPreliminary
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=AllocTransType)]
[AllocationReport (body_55566583.html?find=AllocTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
