.TH FIX.4.4 "" "" "Tag #712"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
712 (tag712.html)
PosMaintAction (tag712.html)
\@Actn
int
.PP
Maintenance Action to be performed
1
=
.PP
New
2
=
.PP
Replace
3
=
.PP
Cancel
.PP
   *   *   *   *   *
Used in messages:
[PositionMaintenanceReport (body_55506577.html?find=PosMaintAction)]
[PositionMaintenanceRequest (body_55496576.html?find=PosMaintAction)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
