.TH FIX.4.4 "" "" "Tag #715"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
715 (tag715.html)
ClearingBusinessDate (tag715.html)
\@BizDt
LocalMktDate
.PP
The "Clearing Business Date" referred to by this maintenance
request.
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=ClearingBusinessDate)]
[CollateralAssignment (body_56526589.html?find=ClearingBusinessDate)]
[CollateralInquiry (body_56556666.html?find=ClearingBusinessDate)]
[CollateralInquiryAck (body_57506671.html?find=ClearingBusinessDate)]
[CollateralReport (body_56546665.html?find=ClearingBusinessDate)]
[CollateralRequest (body_56516588.html?find=ClearingBusinessDate)]
[PositionMaintenanceReport (body_55506577.html?find=ClearingBusinessDate)]
[PositionMaintenanceRequest (body_55496576.html?find=ClearingBusinessDate)]
[PositionReport (body_55536580.html?find=ClearingBusinessDate)]
[RequestForPositions (body_55516578.html?find=ClearingBusinessDate)]
[TradeCaptureReport (body_54526569.html?find=ClearingBusinessDate)]
[TradeCaptureReportRequest (body_54516568.html?find=ClearingBusinessDate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
