.TH FIX.4.4 "" "" "Tag #716"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
716 (tag716.html)
SettlSessID (tag716.html)
\@SetSesID
String
.PP
Identifies a specific settlement session
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=SettlSessID)]
[CollateralAssignment (body_56526589.html?find=SettlSessID)]
[CollateralInquiry (body_56556666.html?find=SettlSessID)]
[CollateralInquiryAck (body_57506671.html?find=SettlSessID)]
[CollateralReport (body_56546665.html?find=SettlSessID)]
[CollateralRequest (body_56516588.html?find=SettlSessID)]
[PositionMaintenanceReport (body_55506577.html?find=SettlSessID)]
[PositionMaintenanceRequest (body_55496576.html?find=SettlSessID)]
[PositionReport (body_55536580.html?find=SettlSessID)]
[RequestForPositions (body_55516578.html?find=SettlSessID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
