.TH FIX.4.4 "" "" "Tag #719"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
719 (tag719.html)
ContraryInstructionIndicator (tag719.html)
\@CntraryInstrctnInd
Boolean
.PP
Required to be set to true (Y) when a position maintenance request
is being performed contrary to current money position.
.PP
Required when an exercise of an out of the money position is
requested or an abandonement (do not exercise ) for an in the money
position.
.PP
   *   *   *   *   *
Used in messages:
[PositionMaintenanceRequest (body_55496576.html?find=ContraryInstructionIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
