.TH FIX.4.4 "" "" "Tag #720"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
720 (tag720.html)
PriorSpreadIndicator (tag720.html)
\@PriorSpreadInd
Boolean
.PP
Indicates if requesting a rollover of prior day’s spread
submissions.
.PP
   *   *   *   *   *
Used in messages:
[PositionMaintenanceRequest (body_55496576.html?find=PriorSpreadIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
