.TH FIX.4.4 "" "" "Tag #724"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
724 (tag724.html)
PosReqType (tag724.html)
\@ReqTyp
int
.PP
Unique identifier for the position maintenance request as assigned
by the submitter
0
=
.PP
Positions
1
=
.PP
Trades
2
=
.PP
Exercises
3
=
.PP
Assignments
.PP
   *   *   *   *   *
Used in messages:
[PositionReport (body_55536580.html?find=PosReqType)]
[RequestForPositions (body_55516578.html?find=PosReqType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
