.TH FIX.4.4 "" "" "Tag #725"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
725 (tag725.html)
ResponseTransportType (tag725.html)
\@RspTransportTyp
int
.PP
Identifies how the response to the request should be transmitted
0
=
.PP
Inband
1
=
.PP
OutofBand
.PP
   *   *   *   *   *
Used in messages:
[CollateralInquiry (body_56556666.html?find=ResponseTransportType)]
[CollateralInquiryAck (body_57506671.html?find=ResponseTransportType)]
[RequestForPositions (body_55516578.html?find=ResponseTransportType)]
[RequestForPositionsAck (body_55526579.html?find=ResponseTransportType)]
[TradeCaptureReportAck (body_55556582.html?find=ResponseTransportType)]
[TradeCaptureReportRequest (body_54516568.html?find=ResponseTransportType)]
[TradeCaptureReportRequestAck (body_55546581.html?find=ResponseTransportType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
