.TH FIX.4.4 "" "" "Tag #726"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
726 (tag726.html)
ResponseDestination (tag726.html)
\@RspDest
String
.PP
URI (Uniform Resource Identifier) for details) or other
pre-arranged value. Used in conjunction with ResponseTransportType
(725) value of Out-of-Band to identify the out-of-band destination.
.PP
See "Appendix 6-B FIX Fields Based Upon Other Standards"
.PP
   *   *   *   *   *
Used in messages:
[CollateralInquiry (body_56556666.html?find=ResponseDestination)]
[CollateralInquiryAck (body_57506671.html?find=ResponseDestination)]
[RequestForPositions (body_55516578.html?find=ResponseDestination)]
[RequestForPositionsAck (body_55526579.html?find=ResponseDestination)]
[TradeCaptureReportAck (body_55556582.html?find=ResponseDestination)]
[TradeCaptureReportRequest (body_54516568.html?find=ResponseDestination)]
[TradeCaptureReportRequestAck (body_55546581.html?find=ResponseDestination)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
