.TH FIX.4.4 "" "" "Tag #727"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
727 (tag727.html)
TotalNumPosReports (tag727.html)
\@TotRpts
int
.PP
Total number of Position Reports being returned.
.PP
   *   *   *   *   *
Used in messages:
[PositionReport (body_55536580.html?find=TotalNumPosReports)]
[RequestForPositionsAck (body_55526579.html?find=TotalNumPosReports)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
