.TH FIX.4.4 "" "" "Tag #728"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
728 (tag728.html)
PosReqResult (tag728.html)
\@Rslt
int
.PP
Result of Request for Position
.PP
4000+ Reserved and available for bi-laterally agreed upon
user-defined values
0
=
.PP
ValidRequest
1
=
.PP
InvalidOrUnsupportedRequest
2
=
.PP
NoPositionsFoundThatMatchCriteria
3
=
.PP
NotAuthorizedToRequestPositions
4
=
.PP
RequestForPositionNotSupported
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[PositionReport (body_55536580.html?find=PosReqResult)]
[RequestForPositionsAck (body_55526579.html?find=PosReqResult)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
