.TH FIX.4.4 "" "" "Tag #729"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
729 (tag729.html)
PosReqStatus (tag729.html)
\@Stat
int
.PP
Status of Request for Positions
0
=
.PP
Completed
1
=
.PP
CompletedWithWarnings
2
=
.PP
Rejected
.PP
   *   *   *   *   *
Used in messages:
[RequestForPositionsAck (body_55526579.html?find=PosReqStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
