.TH FIX.4.4 "" "" "Tag #737"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
737 (tag737.html)
AllocSettlCurrAmt (tag737.html)
\@AllocSettlCurrAmt
Amt
.PP
Total amount due expressed in settlement currency (includes the
effect of the forex transaction) for a specific AllocAccount (79).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=AllocSettlCurrAmt)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
