.TH FIX.4.4 "" "" "Tag #749"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
749 (tag749.html)
TradeRequestResult (tag749.html)
\@ReqRslt
int
.PP
Result of Trade Request
.PP
4000+ Reserved and available for bi-laterally agreed upon
user-defined values
0
=
.PP
Successful
1
=
.PP
InvalidOrUnknownInstrument
2
=
.PP
InvalidTypeOfTradeRequested
3
=
.PP
InvalidParties
4
=
.PP
InvalidTransportTypeRequested
5
=
.PP
InvalidDestinationRequested
8
=
.PP
TradeRequestTypeNotSupported
9
=
.PP
UnauthorizedForTradeCaptureReportRequest
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReportRequestAck (body_55546581.html?find=TradeRequestResult)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
