.TH FIX.4.4 "" "" "Tag #751"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
751 (tag751.html)
TradeReportRejectReason (tag751.html)
\@RptRejRsn
int
.PP
Reason Trade Capture Request was rejected.
.PP
4000+ Reserved and available for bi-laterally agreed upon
user-defined values
0
=
.PP
SuccessfulDefault
1
=
.PP
InvalidPartyInformation
2
=
.PP
UnknownInstrument
3
=
.PP
UnauthorizedToReportTrades
4
=
.PP
InvalidTradeType
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReportAck (body_55556582.html?find=TradeReportRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
