.TH FIX.4.4 "" "" "Tag #752"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
752 (tag752.html)
SideMultiLegReportingType (tag752.html)
\@MLegRptTyp
int
.PP
Used to indicate if the side being reported on Trade Capture Report
represents a leg of a multileg instrument or a single security
1
=
.PP
SingleSecurity
2
=
.PP
IndividualLegOfAMultilegSecurity
3
=
.PP
MultilegSecurity
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptSideGrp (body_50485449.html?find=SideMultiLegReportingType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
