.TH FIX.4.4 "" "" "Tag #753"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
753 (tag753.html)
NoPosAmt (tag753.html)
\@NoPosAmt
NumInGroup
.PP
Number of position amount entries.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PositionAmountData (body_49484952.html?find=NoPosAmt)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
