.TH FIX.4.4 "" "" "Tag #761"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
761 (tag761.html)
BenchmarkSecurityIDSource (tag761.html)
\@SecIDSrc
String
.PP
Identifies class or source of the BenchmarkSecurityID (699) value.
Required if BenchmarkSecurityID is specified.
.PP
Same values as the SecurityIDSource (22) field
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SpreadOrBenchmarkCurveData (body_49484956.html?find=BenchmarkSecurityIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
