.TH FIX.4.4 "" "" "Tag #770"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
770 (tag770.html)
TrdRegTimestampType (tag770.html)
\@Typ
int
.PP
Traded / Regulatory timestamp type
.PP
Note of Applicability: values are required in US futures markets by
the CFTC to support computerized trade reconstruction.
.PP
(see Volume : "Glossary" for value definitions)
1
=
.PP
ExecutionTime
2
=
.PP
TimeIn
3
=
.PP
TimeOut
4
=
.PP
BrokerReceipt
5
=
.PP
BrokerExecution
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdRegTimestamps (body_49485048.html?find=TrdRegTimestampType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
