.TH FIX.4.4 "" "" "Tag #779"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
779 (tag779.html)
LastUpdateTime (tag779.html)
\@LastUpdateTm
UTCTimestamp
.PP
Timestamp of last update to data item (or creation if no updates
made since creation).
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructionRequest (body_56496586.html?find=LastUpdateTime)]
.PP
   *   *   *   *   *
Used in components:
[SettlInstGrp (body_50485355.html?find=LastUpdateTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
