.TH FIX.4.4 "" "" "Tag #782"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
782 (tag782.html)
SettlPartyID (tag782.html)
\@ID
String
.PP
PartyID value within a settlement parties component. Nested
repeating group.
.PP
Same values as PartyID (448)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlParties (body_49484955.html?find=SettlPartyID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
