.TH FIX.4.4 "" "" "Tag #787"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
787 (tag787.html)
DlvyInstType (tag787.html)
\@InstTyp
char
.PP
Used to indicate whether a delivery instruction is used for
securities or cash settlement
C
=
.PP
cash
S
=
.PP
securities
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DlvyInstGrp (body_50485553.html?find=DlvyInstType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
