.TH FIX.4.4 "" "" "Tag #79"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
79 (tag79.html)
AllocAccount (tag79.html)
\@Acct
String
.PP
Sub-account mnemonic
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=AllocAccount)]
[ConfirmationRequest (body_57516672.html?find=AllocAccount)]
[SettlementInstructionRequest (body_56496586.html?find=AllocAccount)]
.PP
   *   *   *   *   *
Used in components:
[AllocAckGrp (body_50484850.html?find=AllocAccount)]
[AllocGrp (body_50484851.html?find=AllocAccount)]
[PreAllocGrp (body_50485157.html?find=AllocAccount)]
[PreAllocMlegGrp (body_50485248.html?find=AllocAccount)]
[TrdAllocGrp (body_50485448.html?find=AllocAccount)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
