.TH FIX.4.4 "" "" "Tag #801"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
801 (tag801.html)
NoSettlPartySubIDs (tag801.html)
\@NoSettlPtySubIDs
NumInGroup
.PP
Number of SettlPartySubID (785) and SettlPartySubIDType (786)
entries
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlPtysSubGrp (body_50485554.html?find=NoSettlPartySubIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
