.TH FIX.4.4 "" "" "Tag #802"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
802 (tag802.html)
NoPartySubIDs (tag802.html)
\@NoPtySubIDs
NumInGroup
.PP
Number of PartySubID (523)and PartySubIDType (803) entries
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PtysSubGrp (body_50485555.html?find=NoPartySubIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
