.TH FIX.4.4 "" "" "Tag #803"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
803 (tag803.html)
PartySubIDType (tag803.html)
\@Typ
int
.PP
Type of PartySubID (523) value
.PP
4000+ = Reserved and available for bi-laterally agreed upon user
defined values
1
=
.PP
Firm
2
=
.PP
Person
3
=
.PP
System
4
=
.PP
Application
5
=
.PP
FullLegalNameOfFirm
6
=
.PP
PostalAddress
7
=
.PP
PhoneNumber
8
=
.PP
EmailAddress
9
=
.PP
ContactName
10
=
.PP
SecuritiesAccountNumber
11
=
.PP
RegistrationNumber
12
=
.PP
RegisteredAddress
13
=
.PP
RegulatoryStatus
14
=
.PP
RegistrationName
15
=
.PP
CashAccount
16
=
.PP
BIC
17
=
.PP
CSDParticipantmemberCode
18
=
.PP
RegisteredAddress
19
=
.PP
FundaccountName
20
=
.PP
TelexNumber
21
=
.PP
FaxNumber
22
=
.PP
SecuritiesAccountName
23
=
.PP
CashAccountName
24
=
.PP
Department
25
=
.PP
LocationDesk
26
=
.PP
PositionAccountType
4000
=
.PP
ReservedAndAvailableForBilaterallyAgreedUponUserDefinedValues
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PtysSubGrp (body_50485555.html?find=PartySubIDType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
