.TH FIX.4.4 "" "" "Tag #807"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
807 (tag807.html)
Nested2PartySubIDType (tag807.html)
\@Typ
int
.PP
Type of Nested2PartySubID (760) value. Second instance of
<NestedParties>.
.PP
Same values as PartySubIDType (803)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NstdPtys2SubGrp (body_50485557.html?find=Nested2PartySubIDType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
