.TH FIX.4.4 "" "" "Tag #814"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
814 (tag814.html)
ApplQueueResolution (tag814.html)
\@ApplQuResolution
int
.PP
Resolution taken when ApplQueueDepth (813) exceeds ApplQueueMax
(812) or system specified maximum queue size.
0
=
.PP
NoActionTaken
1
=
.PP
QueueFlushed
2
=
.PP
OverlayLast
3
=
.PP
EndSession
.PP
   *   *   *   *   *
Used in messages:
[MarketDataIncrementalRefresh (body_514988.html?find=ApplQueueResolution)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=ApplQueueResolution)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
