.TH FIX.4.4 "" "" "Tag #816"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
816 (tag816.html)
NoAltMDSource (tag816.html)
\@NoAltMDSrc
NumInGroup
.PP
Number of alternative market data sources
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDRjctGrp (body_50485152.html?find=NoAltMDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
