.TH FIX.4.4 "" "" "Tag #817"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
817 (tag817.html)
AltMDSourceID (tag817.html)
\@AltMDSrcID
String
.PP
Session layer source for market data
.PP
(For the standard FIX session layer, this would be the TargetCompID
(56) where market data can be obtained).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDRjctGrp (body_50485152.html?find=AltMDSourceID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
