.TH FIX.4.4 "" "" "Tag #819"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
819 (tag819.html)
AvgPxIndicator (tag819.html)
\@AvgPxInd
int
.PP
Average Pricing Indicator
0
=
.PP
NoAveragePricing
1
=
.PP
TradeAveragePriceGroup
2
=
.PP
LastTradeAveragePriceGroup
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=AvgPxIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
