.TH FIX.4.4 "" "" "Tag #826"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
826 (tag826.html)
TradeAllocIndicator (tag826.html)
\@AllocInd
int
.PP
Identifies how the trade is to be allocated
0
=
.PP
AllocationNotRequired
1
=
.PP
AllocationRequiredAllocationInformationNotProvided
2
=
.PP
UseAllocationProvidedWithTheTrade
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptSideGrp (body_50485449.html?find=TradeAllocIndicator)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
