.TH FIX.4.4 "" "" "Tag #827"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
827 (tag827.html)
ExpirationCycle (tag827.html)
\@ExpirationCycle
int
.PP
Part of trading cycle when an instrument expires. Field is
applicable for derivatives.
0
=
.PP
ExpireOnTradingSessionClose
1
=
.PP
ExpireOnTradingSessionOpen
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinition (body_5155100.html?find=ExpirationCycle)]
[SecurityDefinitionRequest (body_515499.html?find=ExpirationCycle)]
.PP
   *   *   *   *   *
Used in components:
[RelSymDerivSecGrp (body_50485348.html?find=ExpirationCycle)]
[SecListGrp (body_50485353.html?find=ExpirationCycle)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
