.TH FIX.4.4 "" "" "Tag #828"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
828 (tag828.html)
TrdType (tag828.html)
\@TrdTyp
int
.PP
Type of Trade
0
=
.PP
RegularTrade
1
=
.PP
BlockTrade
2
=
.PP
EFP
3
=
.PP
Transfer
4
=
.PP
LateTrade
5
=
.PP
TTrade
6
=
.PP
WeightedAveragePriceTrade
7
=
.PP
BunchedTrade
8
=
.PP
LateBunchedTrade
9
=
.PP
PriorReferencePriceTrade
10
=
.PP
AfterHoursTrade
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TrdType)]
[TradeCaptureReportAck (body_55556582.html?find=TrdType)]
[TradeCaptureReportRequest (body_54516568.html?find=TrdType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
