.TH FIX.4.4 "" "" "Tag #829"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
829 (tag829.html)
TrdSubType (tag829.html)
\@TrdSubTyp
int
.PP
Further qualification to the trade type
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TrdSubType)]
[TradeCaptureReportAck (body_55556582.html?find=TrdSubType)]
[TradeCaptureReportRequest (body_54516568.html?find=TrdSubType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
