.TH FIX.4.4 "" "" "Tag #836"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
836 (tag836.html)
PegOffsetType (tag836.html)
\@OfstTyp
int
.PP
Type of Peg Offset value
0
=
.PP
Price
1
=
.PP
BasisPoints
2
=
.PP
Ticks
3
=
.PP
PriceTierLevel
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PegInstructions (body_49484951.html?find=PegOffsetType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
