.TH FIX.4.4 "" "" "Tag #838"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
838 (tag838.html)
PegRoundDirection (tag838.html)
\@RndDir
int
.PP
If the calculated peg price is not a valid tick price, specifies
whether to round the price to be more or less aggressive
1
=
.PP
MoreAggressive
2
=
.PP
MorePassive
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PegInstructions (body_49484951.html?find=PegRoundDirection)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
