.TH FIX.4.4 "" "" "Tag #839"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
839 (tag839.html)
PeggedPrice (tag839.html)
\@PeggedPx
Price
.PP
The price the order is currently pegged at
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=PeggedPrice)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
