.TH FIX.4.4 "" "" "Tag #847"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
847 (tag847.html)
TargetStrategy (tag847.html)
\@TgtStrategy
int
.PP
The target strategy of the order
.PP
1000+ = Reserved and available for bi-laterally agreed upon user
defined values
1
=
.PP
VWAP
2
=
.PP
Participate
3
=
.PP
MininizeMarketImpact
1000
=
.PP
ReservedAndAvailableForBilaterallyAgreedUponUserDefinedValues
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=TargetStrategy)]
[ExecutionReport (body_5756.html?find=TargetStrategy)]
[MultilegOrderCancelReplace (body_54506567.html?find=TargetStrategy)]
[NewOrderCross (body_5350115.html?find=TargetStrategy)]
[NewOrderMultileg (body_54496566.html?find=TargetStrategy)]
[NewOrderSingle (body_495268.html?find=TargetStrategy)]
[OrderCancelReplaceRequest (body_495571.html?find=TargetStrategy)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=TargetStrategy)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
