.TH FIX.4.4 "" "" "Tag #85"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
85 (tag85.html)
NoDlvyInst (tag85.html)
\@NoDlvyInst
NumInGroup
.PP
Number of delivery instruction fields in repeating group.
.PP
Note this field was removed in FIX 4.1 and reinstated in FIX 4.4.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DlvyInstGrp (body_50485553.html?find=NoDlvyInst)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
