.TH FIX.4.4 "" "" "Tag #853"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
853 (tag853.html)
ShortSaleReason (tag853.html)
\@ShrtSaleRsn
int
.PP
Reason for short sale
0
=
.PP
DealerSoldShort
1
=
.PP
DealerSoldShortExempt
2
=
.PP
SellingCustomerSoldShort
3
=
.PP
SellingCustomerSoldShortExempt
4
=
.PP
QSROrAGUContraSideSoldShort
5
=
.PP
QSROrAGUContraSideSoldShortExempt
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=ShortSaleReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
