.TH FIX.4.4 "" "" "Tag #865"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
865 (tag865.html)
EventType (tag865.html)
\@EventTyp
int
.PP
Code to represent the type of event
1
=
.PP
Put
2
=
.PP
Call
3
=
.PP
Tender
4
=
.PP
SinkingFundCall
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[EvntGrp (body_50485548.html?find=EventType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
