.TH FIX.4.4 "" "" "Tag #866"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
866 (tag866.html)
EventDate (tag866.html)
\@Dt
LocalMktDate
.PP
Date of event
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[EvntGrp (body_50485548.html?find=EventDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
