.TH FIX.4.4 "" "" "Tag #871"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
871 (tag871.html)
InstrAttribType (tag871.html)
\@Typ
int
.PP
Code to represent the type of instrument attribute
1
=
.PP
Flat
2
=
.PP
ZeroCoupon
3
=
.PP
InterestBearing
4
=
.PP
NoPeriodicPayments
5
=
.PP
VariableRate
6
=
.PP
LessFeeForPut
7
=
.PP
SteppedCoupon
8
=
.PP
CouponPeriod
9
=
.PP
WhenIssued
10
=
.PP
OriginalIssueDiscount
11
=
.PP
CallablePuttable
12
=
.PP
EscrowedToMaturity
13
=
.PP
EscrowedToRedemptionDate
14
=
.PP
Prerefunded
15
=
.PP
InDefault
16
=
.PP
Unrated
17
=
.PP
Taxable
18
=
.PP
Indexed
19
=
.PP
SubjectToAlternativeMinimumTax
20
=
.PP
OriginalIssueDiscountPrice
21
=
.PP
CallableBelowMaturityValue
22
=
.PP
CallableWithoutNoticeByMailToHolderUnlessRegistered
99
=
.PP
Text
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AttrbGrp (body_50485552.html?find=InstrAttribType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
