.TH FIX.4.4 "" "" "Tag #874"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
874 (tag874.html)
InterestAccrualDate (tag874.html)
\@IntAcrl
LocalMktDate
.PP
The start date used for calculating accrued interest on debt
instruments which are being sold between interest payment dates.
Often but not always the same as the Issue Date and the Dated Date
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=InterestAccrualDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
