.TH FIX.4.4 "" "" "Tag #875"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
875 (tag875.html)
CPProgram (tag875.html)
\@CPPgm
int
.PP
The program under which a commercial paper is issued
1
=
.PP
3a3
2
=
.PP
42
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=CPProgram)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
