.TH FIX.4.4 "" "" "Tag #883"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
883 (tag883.html)
UnderlyingEndPrice (tag883.html)
\@EndPx
Price
.PP
Price (percent-of-par or per unit) of the underlying security or
basket at the end of the agreement.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingEndPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
