.TH FIX.4.4 "" "" "Tag #891"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
891 (tag891.html)
MiscFeeBasis (tag891.html)
\@Basis
int
.PP
Defines the unit for a miscellaneous fee.
0
=
.PP
Absolute
1
=
.PP
PerUnit
2
=
.PP
Percentage
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MiscFeesGrp (body_50485153.html?find=MiscFeeBasis)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
