.TH FIX.4.4 "" "" "Tag #897"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
897 (tag897.html)
NoTrades (tag897.html)
\@NoTrds
NumInGroup
.PP
Number of trades in repeating group.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCollGrp (body_50485450.html?find=NoTrades)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
