.TH FIX.4.4 "" "" "Tag #898"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
898 (tag898.html)
MarginRatio (tag898.html)
\@MgnRatio
Percentage
.PP
The fraction of the cash consideration that must be collateralized,
expressed as a percent. A MarginRatio of 02% indicates that the
value of the collateral (after deducting for "haircut") must exceed
the cash consideration by 2%.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[FinancingDetails (body_49484850.html?find=MarginRatio)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
