.TH FIX.4.4 "" "" "Tag #899"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
899 (tag899.html)
MarginExcess (tag899.html)
\@MgnExcess
Amt
.PP
Excess margin amount (deficit if value is negative)
.PP
   *   *   *   *   *
Used in messages:
[CollateralAssignment (body_56526589.html?find=MarginExcess)]
[CollateralInquiry (body_56556666.html?find=MarginExcess)]
[CollateralReport (body_56546665.html?find=MarginExcess)]
[CollateralRequest (body_56516588.html?find=MarginExcess)]
[CollateralResponse (body_56536590.html?find=MarginExcess)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
