.TH FIX.4.4 "" "" "Tag #906"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
906 (tag906.html)
CollAsgnRejectReason (tag906.html)
\@RejRsn
int
.PP
Collateral Assignment Reject Reason
0
=
.PP
UnknownDeal
1
=
.PP
UnknownOrInvalidInstrument
2
=
.PP
UnauthorizedTransaction
3
=
.PP
InsufficientCollateral
4
=
.PP
InvalidTypeOfCollateral
5
=
.PP
ExcessiveSubstitution
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[CollateralResponse (body_56536590.html?find=CollAsgnRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
