.TH FIX.4.4 "" "" "Tag #907"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
907 (tag907.html)
CollAsgnRefID (tag907.html)
\@RefID
String
.PP
Collateral Assignment Identifier to which a transaction refers
.PP
   *   *   *   *   *
Used in messages:
[CollateralAssignment (body_56526589.html?find=CollAsgnRefID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
