.TH FIX.4.4 "" "" "Tag #912"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
912 (tag912.html)
LastRptRequested (tag912.html)
\@LastRptReqed
Boolean
.PP
Indicates whether this message is that last report message in
response to a request, such as Order Mass Status Request.
N
=
.PP
Not last message
Y
=
.PP
Last message
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=LastRptRequested)]
[CollateralReport (body_56546665.html?find=LastRptRequested)]
[ExecutionReport (body_5756.html?find=LastRptRequested)]
[TradeCaptureReport (body_54526569.html?find=LastRptRequested)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
