.TH FIX.4.4 "" "" "Tag #920"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
920 (tag920.html)
EndAccruedInterestAmt (tag920.html)
\@EndAcrdIntAmt
Amt
.PP
Accrued Interest Amount applicable to a financing transaction on
the End Date.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=EndAccruedInterestAmt)]
[AllocationReport (body_55566583.html?find=EndAccruedInterestAmt)]
[CollateralAssignment (body_56526589.html?find=EndAccruedInterestAmt)]
[CollateralInquiry (body_56556666.html?find=EndAccruedInterestAmt)]
[CollateralReport (body_56546665.html?find=EndAccruedInterestAmt)]
[CollateralRequest (body_56516588.html?find=EndAccruedInterestAmt)]
[CollateralResponse (body_56536590.html?find=EndAccruedInterestAmt)]
[Confirmation (body_55486575.html?find=EndAccruedInterestAmt)]
[ExecutionReport (body_5756.html?find=EndAccruedInterestAmt)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptSideGrp (body_50485449.html?find=EndAccruedInterestAmt)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
