.TH FIX.4.4 "" "" "Tag #928"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
928 (tag928.html)
StatusValue (tag928.html)
\@StatValu
int
.PP
Indicates the status of a network connection
1
=
.PP
Connected
2
=
.PP
NotConnectedDownExpectedUp
3
=
.PP
NotConnectedDownExpectedDown
4
=
.PP
InProcess
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CompIDStatGrp (body_50484948.html?find=StatusValue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
