.TH FIX.4.4 "" "" "Tag #929"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
929 (tag929.html)
StatusText (tag929.html)
\@StatText
String
.PP
A text description associated with a network status.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CompIDStatGrp (body_50484948.html?find=StatusText)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
