.TH FIX.4.4 "" "" "Tag #936"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
936 (tag936.html)
NoCompIDs (tag936.html)
\@NoCompIDs
NumInGroup
.PP
Number of CompID entries in a repeating group.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CompIDReqGrp (body_50484857.html?find=NoCompIDs)]
[CompIDStatGrp (body_50484948.html?find=NoCompIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
