.TH FIX.4.4 "" "" "Tag #940"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
940 (tag940.html)
AffirmStatus (tag940.html)
\@AffirmStat
int
.PP
Identifies the status of the ConfirmationAck
1
=
.PP
Received
2
=
.PP
ConfirmRejected
3
=
.PP
Affirmed
.PP
   *   *   *   *   *
Used in messages:
[Confirmation_Ack (body_56486585.html?find=AffirmStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
