.TH FIX.4.4 "" "" "Tag #943"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
943 (tag943.html)
TimeBracket (tag943.html)
\@TmBkt
String
.PP
A code that represents a time interval in which a fill or trade
occurred.
.PP
Required for US futures markets.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=TimeBracket)]
[TradeCaptureReportRequest (body_54516568.html?find=TimeBracket)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptSideGrp (body_50485449.html?find=TimeBracket)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
