.TH FIX.4.4 "" "" "Tag #946"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
946 (tag946.html)
CollInquiryResult (tag946.html)
\@Rslt
int
.PP
Result returned in response to Collateral Inquiry
.PP
4000+ Reserved and available for bi-laterally agreed upon
user-defined values
0
=
.PP
Successful
1
=
.PP
InvalidOrUnknownInstrument
2
=
.PP
InvalidOrUnknownCollateralType
3
=
.PP
InvalidParties
4
=
.PP
InvalidTransportTypeRequested
5
=
.PP
InvalidDestinationRequested
6
=
.PP
NoCollateralFoundForTheTradeSpecified
7
=
.PP
NoCollateralFoundForTheOrderSpecified
8
=
.PP
CollateralInquiryTypeNotSupported
9
=
.PP
UnauthorizedForCollateralInquiry
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[CollateralInquiryAck (body_57506671.html?find=CollInquiryResult)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
