.TH FIX.4.4 "" "" "Tag #952"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
952 (tag952.html)
NoNested3PartySubIDs (tag952.html)
\@NoNst3PtySubIDs
NumInGroup
.PP
Number of Nested3PartySubIDs (953) entries
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NstdPtys3SubGrp (body_50485648.html?find=NoNested3PartySubIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
