.TH FIX.4.0 "" "" "Tag #11"
Tag
Field Name
Data Type
Description
Depr.
Valid values
11 (tag11.html)
ClOrdID (tag11.html)
char
.PP
Unique identifier for Order as assigned by institution. Uniqueness
must be guaranteed within a single trading day. Firms which
electronically submit multi-day orders should consider embedding a
date within the ClOrderID field to assure uniqueness across days.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=ClOrdID)]
[Email (body_495167.html?find=ClOrdID)]
[Execution Report (body_5756.html?find=ClOrdID)]
[List Status (body_505178.html?find=ClOrdID)]
[Order - List (body_495369.html?find=ClOrdID)]
[Order - Single (body_495268.html?find=ClOrdID)]
[Order Cancel Reject (body_494857.html?find=ClOrdID)]
[Order Cancel Request (body_495470.html?find=ClOrdID)]
[Order Cancel/Replace Request (body_495571.html?find=ClOrdID)]
[Order Status Request (body_495672.html?find=ClOrdID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
