.TH FIX.4.0 "" "" "Tag #114"
Tag
Field Name
Data Type
Description
Depr.
Valid values
114 (tag114.html)
LocateReqd (tag114.html)
char
.PP
Indicates whether the broker is to locate the stock in conjuction
with a short sell order.
N
=
.PP
Indicates the broker is not required to locate
Y
=
.PP
Indicates the broker is responsible for locating the stock
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=LocateReqd)]
[Order - Single (body_495268.html?find=LocateReqd)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
