.TH FIX.4.0 "" "" "Tag #118"
Tag
Field Name
Data Type
Description
Depr.
Valid values
118 (tag118.html)
NetMoney (tag118.html)
float
.PP
Total amount due as the result of the transaction (e.g. for Buy
order - principal + commission + fees) reported in currency of
execution.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=NetMoney)]
[Execution Report (body_5756.html?find=NetMoney)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
