.TH FIX.4.0 "" "" "Tag #121"
Tag
Field Name
Data Type
Description
Depr.
Valid values
121 (tag121.html)
ForexReq (tag121.html)
char
.PP
Indicates request for forex accommodation trade to be executed
along with security transaction.
N
=
.PP
Do not execute Forex after security trade
Y
=
.PP
Execute Forex after security trade
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=ForexReq)]
[Order - Single (body_495268.html?find=ForexReq)]
[Order Cancel/Replace Request (body_495571.html?find=ForexReq)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
