.TH FIX.4.0 "" "" "Tag #124"
Tag
Field Name
Data Type
Description
Depr.
Valid values
124 (tag124.html)
NoExecs (tag124.html)
int
.PP
No of execution record groups to follow.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=NoExecs)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
