.TH FIX.4.0 "" "" "Tag #13"
Tag
Field Name
Data Type
Description
Depr.
Valid values
13 (tag13.html)
CommType (tag13.html)
char
.PP
Commission type
1
=
.PP
per share
2
=
.PP
percentage
3
=
.PP
absolute
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=CommType)]
[Execution Report (body_5756.html?find=CommType)]
[Order - List (body_495369.html?find=CommType)]
[Order - Single (body_495268.html?find=CommType)]
[Order Cancel/Replace Request (body_495571.html?find=CommType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
