.TH FIX.4.0 "" "" "Tag #132"
Tag
Field Name
Data Type
Description
Depr.
Valid values
132 (tag132.html)
BidPx (tag132.html)
float
.PP
Bid price/rate
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=BidPx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
