.TH FIX.4.0 "" "" "Tag #136"
Tag
Field Name
Data Type
Description
Depr.
Valid values
136 (tag136.html)
NoMiscFees (tag136.html)
int
.PP
Number of repeating groups of miscellaneous fees
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=NoMiscFees)]
[Execution Report (body_5756.html?find=NoMiscFees)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
