.TH FIX.4.0 "" "" "Tag #138"
Tag
Field Name
Data Type
Description
Depr.
Valid values
138 (tag138.html)
MiscFeeCurr (tag138.html)
char
.PP
Currency of miscellaneous fee
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=MiscFeeCurr)]
[Execution Report (body_5756.html?find=MiscFeeCurr)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
