.TH FIX.4.0 "" "" "Tag #14"
Tag
Field Name
Data Type
Description
Depr.
Valid values
14 (tag14.html)
CumQty (tag14.html)
int
.PP
Total number of shares filled.
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=CumQty)]
[List Status (body_505178.html?find=CumQty)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
