.TH FIX.4.0 "" "" "Tag #31"
Tag
Field Name
Data Type
Description
Depr.
Valid values
31 (tag31.html)
LastPx (tag31.html)
float
.PP
Price of last fill. Field not required for ExecTransType = 3
(Status)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=LastPx)]
[Don’t Know Trade (DK) (body_505381.html?find=LastPx)]
[Execution Report (body_5756.html?find=LastPx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
