.TH FIX.4.0 "" "" "Tag #32"
Tag
Field Name
Data Type
Description
Depr.
Valid values
32 (tag32.html)
LastShares (tag32.html)
int
.PP
Quantity of shares bought/sold on this fill. Field not required for
ExecTransType = 3 (Status)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=LastShares)]
[Don’t Know Trade (DK) (body_505381.html?find=LastShares)]
[Execution Report (body_5756.html?find=LastShares)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
