.TH FIX.4.0 "" "" "Tag #36"
Tag
Field Name
Data Type
Description
Depr.
Valid values
36 (tag36.html)
NewSeqNo (tag36.html)
int
.PP
New sequence number
.PP
   *   *   *   *   *
Used in messages:
[Sequence Reset (body_5352.html?find=NewSeqNo)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
