.TH FIX.4.0 "" "" "Tag #38"
Tag
Field Name
Data Type
Description
Depr.
Valid values
38 (tag38.html)
OrderQty (tag38.html)
int
.PP
Number of shares ordered
.PP
   *   *   *   *   *
Used in messages:
[Don’t Know Trade (DK) (body_505381.html?find=OrderQty)]
[Execution Report (body_5756.html?find=OrderQty)]
[Order - List (body_495369.html?find=OrderQty)]
[Order - Single (body_495268.html?find=OrderQty)]
[Order Cancel Request (body_495470.html?find=OrderQty)]
[Order Cancel/Replace Request (body_495571.html?find=OrderQty)]
[Quote Request (body_505482.html?find=OrderQty)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
