.TH FIX.4.0 "" "" "Tag #39"
Tag
Field Name
Data Type
Description
Depr.
Valid values
39 (tag39.html)
OrdStatus (tag39.html)
char
.PP
Identifies current status of order.
0
=
.PP
New
1
=
.PP
Partially filled
2
=
.PP
Filled
3
=
.PP
Done for day
4
=
.PP
Canceled
5
=
.PP
Replaced
6
=
.PP
Pending Cancel/Replace
7
=
.PP
Stopped
8
=
.PP
Rejected
9
=
.PP
Suspended
A
=
.PP
Pending New
B
=
.PP
Calculated
C
=
.PP
Expired
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=OrdStatus)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
