.TH FIX.4.0 "" "" "Tag #42"
Tag
Field Name
Data Type
Description
Depr.
Valid values
42 (tag42.html)
OrigTime (tag42.html)
time
.PP
Time of message origination (always expressed in GMT)
.PP
   *   *   *   *   *
Used in messages:
[Email (body_495167.html?find=OrigTime)]
[News (body_495066.html?find=OrigTime)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
