.TH FIX.4.0 "" "" "Tag #47"
Tag
Field Name
Data Type
Description
Depr.
Valid values
47 (tag47.html)
Rule80A (tag47.html)
char
.PP
Indicates order type upon which exchange Rule 80A is applied.
A
=
.PP
Agency single order
C
=
.PP
Program Order, non-index arb, for Member firm/org
D
=
.PP
Program Order, index arb, for Member firm/org
I
=
.PP
Individual Investor, single order
J
=
.PP
Program Order, index arb, for individual customer
K
=
.PP
Program Order, non-index arb, for individual customer
M
=
.PP
Program Order, index arb, for other member
N
=
.PP
Program Order, non-index arb, for other member
U
=
.PP
Program Order, index arb, for other agency
W
=
.PP
All other orders as agent for other member
Y
=
.PP
Program Order, non-index arb, for other agency
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=Rule80A)]
[Order - List (body_495369.html?find=Rule80A)]
[Order - Single (body_495268.html?find=Rule80A)]
[Order Cancel/Replace Request (body_495571.html?find=Rule80A)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
