.TH FIX.4.0 "" "" "Tag #53"
Tag
Field Name
Data Type
Description
Depr.
Valid values
53 (tag53.html)
Shares (tag53.html)
int
.PP
Number of shares
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=Shares)]
[Allocation (body_495774.html?find=Shares)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
