.TH FIX.4.0 "" "" "Tag #6"
Tag
Field Name
Data Type
Description
Depr.
Valid values
6 (tag6.html)
AvgPx (tag6.html)
float
.PP
Calculated average price of all fills on this order.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AvgPx)]
[Execution Report (body_5756.html?find=AvgPx)]
[List Status (body_505178.html?find=AvgPx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
