.TH FIX.4.0 "" "" "Tag #60"
Tag
Field Name
Data Type
Description
Depr.
Valid values
60 (tag60.html)
TransactTime (tag60.html)
time
.PP
Time of execution/order creation (expressed in GMT)
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=TransactTime)]
[Allocation (body_495774.html?find=TransactTime)]
[Allocation ACK (body_505280.html?find=TransactTime)]
[Execution Report (body_5756.html?find=TransactTime)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
