.TH FIX.4.0 "" "" "Tag #76"
Tag
Field Name
Data Type
Description
Depr.
Valid values
76 (tag76.html)
ExecBroker (tag76.html)
char
.PP
Identifies executing / give-up broker. Standard NASD market-maker
mnemonic is preferred.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=ExecBroker)]
[Allocation ACK (body_505280.html?find=ExecBroker)]
[Execution Report (body_5756.html?find=ExecBroker)]
[Order - List (body_495369.html?find=ExecBroker)]
[Order - Single (body_495268.html?find=ExecBroker)]
[Order Cancel Reject (body_494857.html?find=ExecBroker)]
[Order Cancel Request (body_495470.html?find=ExecBroker)]
[Order Cancel/Replace Request (body_495571.html?find=ExecBroker)]
[Order Status Request (body_495672.html?find=ExecBroker)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
