.TH FIX.4.0 "" "" "Tag #82"
Tag
Field Name
Data Type
Description
Depr.
Valid values
82 (tag82.html)
NoRpts (tag82.html)
int
.PP
Total number of reports within series.
.PP
   *   *   *   *   *
Used in messages:
[List Status (body_505178.html?find=NoRpts)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
