.TH FIX.4.0 "" "" "Tag #84"
Tag
Field Name
Data Type
Description
Depr.
Valid values
84 (tag84.html)
CxlQty (tag84.html)
int
.PP
Total number of shares canceled for this order.
.PP
   *   *   *   *   *
Used in messages:
[List Status (body_505178.html?find=CxlQty)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
