.TH FIX.4.0 "" "" "Tag #86"
Tag
Field Name
Data Type
Description
Depr.
Valid values
86 (tag86.html)
DlvyInst (tag86.html)
char
.PP
Free format text field to indicate delivery instructions
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=DlvyInst)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
