.TH FIX.5.0SP2 "" "" "Tag #1"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1 (tag1.html)
Account (tag1.html)
\@Acct
String
.PP
Account mnemonic as agreed between buy and sell sides, e.g. broker
and institution or investor/intermediary and fund manager.
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=Account)]
[CollateralAssignment (body_56526589.html?find=Account)]
[CollateralInquiry (body_56556666.html?find=Account)]
[CollateralInquiryAck (body_57506671.html?find=Account)]
[CollateralReport (body_56546665.html?find=Account)]
[CollateralRequest (body_56516588.html?find=Account)]
[CollateralResponse (body_56536590.html?find=Account)]
[ExecutionReport (body_5756.html?find=Account)]
[MassQuote (body_5250105.html?find=Account)]
[MassQuoteAcknowledgement (body_515398.html?find=Account)]
[MultilegOrderCancelReplace (body_54506567.html?find=Account)]
[NewOrderMultileg (body_54496566.html?find=Account)]
[NewOrderSingle (body_495268.html?find=Account)]
[OrderCancelReject (body_494857.html?find=Account)]
[OrderCancelReplaceRequest (body_495571.html?find=Account)]
[OrderCancelRequest (body_495470.html?find=Account)]
[OrderMassStatusRequest (body_54536570.html?find=Account)]
[OrderStatusRequest (body_495672.html?find=Account)]
[PositionMaintenanceReport (body_55506577.html?find=Account)]
[PositionMaintenanceRequest (body_55496576.html?find=Account)]
[PositionReport (body_55536580.html?find=Account)]
[Quote (body_505583.html?find=Account)]
[QuoteCancel (body_515190.html?find=Account)]
[QuoteResponse (body_54576574.html?find=Account)]
[QuoteStatusReport (body_54566573.html?find=Account)]
[QuoteStatusRequest (body_515297.html?find=Account)]
[RegistrationInstructions (body_5256111.html?find=Account)]
[RegistrationInstructionsResponse (body_5257112.html?find=Account)]
[RequestForPositions (body_55516578.html?find=Account)]
[RequestForPositionsAck (body_55526579.html?find=Account)]
.PP
   *   *   *   *   *
Used in components:
[BidCompReqGrp (body_50484852.html?find=Account)]
[ListOrdGrp (body_50485148.html?find=Account)]
[QuotReqGrp (body_50485253.html?find=Account)]
[QuotReqRjctGrp (body_50485255.html?find=Account)]
[SideCrossOrdModGrp (body_50485357.html?find=Account)]
[TrdCapRptAckSideGrp (body_50485752.html?find=Account)]
[TrdCapRptSideGrp (body_50485449.html?find=Account)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
