.TH FIX.5.0SP2 "" "" "Tag #1003"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1003 (tag1003.html)
TradeID (tag1003.html)
\@TrdID
String
.PP
The unique ID assigned to the trade entity once it is received or
matched by the exchange or central counterparty.
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TradeID)]
[TradeCaptureReportAck (body_55556582.html?find=TradeID)]
[TradeCaptureReportRequest (body_54516568.html?find=TradeID)]
[TradeCaptureReportRequestAck (body_55546581.html?find=TradeID)]
.PP
   *   *   *   *   *
Used in components:
[ExecAllocGrp (body_50484952.html?find=TradeID)]
[MDIncGrp (body_50485150.html?find=TradeID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
