.TH FIX.5.0SP2 "" "" "Tag #1005"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1005 (tag1005.html)
SideTradeReportID (tag1005.html)
\@RptID
String
.PP
Used on a multi-sided trade to designate the ReportID
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=SideTradeReportID)]
[TrdCapRptSideGrp (body_50485449.html?find=SideTradeReportID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
