.TH FIX.5.0SP2 "" "" "Tag #1017"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1017 (tag1017.html)
LegOptionRatio (tag1017.html)
\@LegOptionRatio
float
.PP
Expresses the risk of an option leg
.PP
Value must be between -1 and 1.
.PP
A Call Option will require a ratio value between 0 and 1
.PP
A Put Option will require a ratio value between -1 and 0
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegOptionRatio)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
