.TH FIX.5.0SP2 "" "" "Tag #1024"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1024 (tag1024.html)
MDOriginType (tag1024.html)
\@MDOrigTyp
int
.PP
Used to describe the origin of an entry in the book
0
=
.PP
Book
1
=
.PP
Off-Book
2
=
.PP
Cross
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=MDOriginType)]
[MDIncGrp (body_50485150.html?find=MDOriginType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
