.TH FIX.5.0SP2 "" "" "Tag #1029"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1029 (tag1029.html)
CustDirectedOrder (tag1029.html)
\@CustDrctdOrd
Boolean
.PP
Indicates if the customer directed this order to a specific
execution venue "Y" or not "N".
.PP
A default of "N" customer did not direct this order should be used
in the case where the information is both missing and essential.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=CustDirectedOrder)]
[NewOrderSingle (body_495268.html?find=CustDirectedOrder)]
[OrderCancelReplaceRequest (body_495571.html?find=CustDirectedOrder)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
