.TH FIX.5.0SP2 "" "" "Tag #1032"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1032 (tag1032.html)
OrderHandlingInstSource (tag1032.html)
\@OrdHndlInstSrc
int
.PP
Identifies the class or source of the "OrderHandlingInst" values.
Scope of this will apply to both CustOrderHandlingInst and
DeskOrderHandlingInst fields.
.PP
Required if CustOrderHandlingInst and/or DeskOrderHandlingInst is
specified.
1
=
.PP
NASD OATS
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=OrderHandlingInstSource)]
[NewOrderSingle (body_495268.html?find=OrderHandlingInstSource)]
[OrderCancelReplaceRequest (body_495571.html?find=OrderHandlingInstSource)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
