.TH FIX.5.0SP2 "" "" "Tag #1033"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1033 (tag1033.html)
DeskType (tag1033.html)
\@DskTyp
String
.PP
Type of trading desk.
—\ NASD OATS\ —
A
=
.PP
Agency
AR
=
.PP
Arbitrage
D
=
.PP
Derivatives
IN
=
.PP
International
IS
=
.PP
Institutional
O
=
.PP
Other
PF
=
.PP
Preferred Trading
PR
=
.PP
Proprietary
PT
=
.PP
Program Trading
S
=
.PP
Sales
T
=
.PP
Trading
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdRegTimestamps (body_49485048.html?find=DeskType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
