.TH FIX.5.0SP2 "" "" "Tag #1034"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1034 (tag1034.html)
DeskTypeSource (tag1034.html)
\@DskTypSrc
int
.PP
Identifies the class or source of DeskType(1033) values. Required
if DeskType(1033) is specified.
1
=
.PP
NASD OATS
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdRegTimestamps (body_49485048.html?find=DeskTypeSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
