.TH FIX.5.0SP2 "" "" "Tag #1035"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1035 (tag1035.html)
DeskOrderHandlingInst (tag1035.html)
\@DskOrdHndlInst
MultipleStringValue
.PP
Codes that apply special information that the Broker / Dealer needs
to report.
.PP
NOTE: This field and its values have no bearing on the ExecInst and
TimeInForce fields. These values should not be used instead of
ExecInst or TimeInForce. This field and its values are intended for
compliance reporting only.
—\ NASD OATS\ —
ADD
=
.PP
Add-on Order
AON
=
.PP
All or None
CNH
=
.PP
Cash Not Held
DIR
=
.PP
Directed Order
E.W
=
.PP
Exchange for Physical Transaction
FOK
=
.PP
Fill or Kill
IO
=
.PP
Imbalance Only
IOC
=
.PP
Immediate or Cancel
LOO
=
.PP
Limit On Open
LOC
=
.PP
Limit on Close
MAO
=
.PP
Market at Open
MAC
=
.PP
Market at Close
MOO
=
.PP
Market on Open
MOC
=
.PP
Market On Close
MQT
=
.PP
Minimum Quantity
NH
=
.PP
Not Held
OVD
=
.PP
Over the Day
PEG
=
.PP
Pegged
RSV
=
.PP
Reserve Size Order
S.W
=
.PP
Stop Stock Transaction
SCL
=
.PP
Scale
TMO
=
.PP
Time Order
TS
=
.PP
Trailing Stop
WRK
=
.PP
Work
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdRegTimestamps (body_49485048.html?find=DeskOrderHandlingInst)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
