.TH FIX.5.0SP2 "" "" "Tag #1036"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1036 (tag1036.html)
ExecAckStatus (tag1036.html)
\@ExecAckStat
char
.PP
The status of this execution acknowledgement message.
0
=
.PP
Received, not yet processed
1
=
.PP
Accepted
2
=
.PP
Don\[aq]t know / Rejected
.PP
   *   *   *   *   *
Used in messages:
[ExecutionAcknowledgement (body_57576678.html?find=ExecAckStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
