.TH FIX.5.0SP2 "" "" "Tag #1037"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1037 (tag1037.html)
UnderlyingDeliveryAmount (tag1037.html)
\@UndlyDlvAmt
Amt
.PP
Indicates the underlying position amount to be delivered
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PosUndInstrmtGrp (body_50485156.html?find=UnderlyingDeliveryAmount)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
