.TH FIX.5.0SP2 "" "" "Tag #1041"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1041 (tag1041.html)
FirmTradeID (tag1041.html)
\@FirmTrdID
String
.PP
The ID assigned to a trade by the Firm to track a trade within the
Firm system. This ID can be assigned either before or after
submission to the exchange or central counterpary
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=FirmTradeID)]
[TradeCaptureReportAck (body_55556582.html?find=FirmTradeID)]
[TradeCaptureReportRequest (body_54516568.html?find=FirmTradeID)]
[TradeCaptureReportRequestAck (body_55546581.html?find=FirmTradeID)]
.PP
   *   *   *   *   *
Used in components:
[ExecAllocGrp (body_50484952.html?find=FirmTradeID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
