.TH FIX.5.0SP2 "" "" "Tag #1056"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1056 (tag1056.html)
CalculatedCcyLastQty (tag1056.html)
\@CalcCcyLastQty
Qty
.PP
Used for the calculated quantity of the other side of the currency
trade. Can be derived from LastQty and LastPx.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=CalculatedCcyLastQty)]
[TradeCaptureReport (body_54526569.html?find=CalculatedCcyLastQty)]
[TradeCaptureReportAck (body_55556582.html?find=CalculatedCcyLastQty)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
