.TH FIX.5.0SP2 "" "" "Tag #106"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
106 (tag106.html)
Issuer (tag106.html)
\@Issr
String
.PP
Name of security issuer (e.g. International Business Machines,
GNMA).
.PP
see also Volume 7: "PRODUCT: FIXED INCOME - Euro Issuer Values"
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=Issuer)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
