.TH FIX.5.0SP2 "" "" "Tag #1066"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1066 (tag1066.html)
OfferSwapPoints (tag1066.html)
\@OfrSwapPnts
PriceOffset
.PP
The offer FX Swap points for an FX Swap. It is the "far offer
forward points - near bid forward points". Value can be negative.
Expressed in decimal form. For example, 61.99 points is expressed
and sent as 0.006199
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=OfferSwapPoints)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
