.TH FIX.5.0SP2 "" "" "Tag #1081"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1081 (tag1081.html)
RefOrderIDSource (tag1081.html)
\@RefOrdIDSrc
char
.PP
Used to specify what identifier, provided in order depth market
data, to use when hitting (taking) a specific order.
0
=
.PP
SecondaryOrderID(198)
1
=
.PP
OrderID(37)
2
=
.PP
MDEntryID(278)
3
=
.PP
QuoteEntryID(299)
4
=
.PP
Original order ID
.PP
   *   *   *   *   *
Used in messages:
[NewOrderMultileg (body_54496566.html?find=RefOrderIDSource)]
[NewOrderSingle (body_495268.html?find=RefOrderIDSource)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=RefOrderIDSource)]
[TradeReportOrderDetail (body_50495251.html?find=RefOrderIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
