.TH FIX.5.0SP2 "" "" "Tag #1082"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1082 (tag1082.html)
SecondaryDisplayQty (tag1082.html)
\@SecDspQty
Qty
.PP
Used for reserve orders when DisplayQty applies to the primary
execution market (e.g.an ECN) and another quantity is to be shown
at other markets (e.g. the exchange). On orders specifies the qty
to be displayed, on execution reports the currently displayed
quantity.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DisplayInstruction (body_49485057.html?find=SecondaryDisplayQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
