.TH FIX.5.0SP2 "" "" "Tag #1087"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1087 (tag1087.html)
DisplayMinIncr (tag1087.html)
\@DspMinIncr
Qty
.PP
Defines the minimum increment to be used when calculating a random
refresh of DisplayQty. A user specifies this when he wants a larger
increment than the standard provided by the market (e.g. the round
lot size).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DisplayInstruction (body_49485057.html?find=DisplayMinIncr)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
