.TH FIX.5.0SP2 "" "" "Tag #1088"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1088 (tag1088.html)
RefreshQty (tag1088.html)
\@RfrshQty
Qty
.PP
Defines the quantity used to refresh DisplayQty.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DisplayInstruction (body_49485057.html?find=RefreshQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
