.TH FIX.5.0SP2 "" "" "Tag #1092"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1092 (tag1092.html)
PriceProtectionScope (tag1092.html)
\@PxPrtScp
char
.PP
Defines the type of price protection the customer requires on their
order.
0
=
.PP
None
1
=
.PP
Local (Exchange, ECN, ATS)
2
=
.PP
National (Across all national markets)
3
=
.PP
Global (Across all markets)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=PriceProtectionScope)]
[ExecutionReport (body_5756.html?find=PriceProtectionScope)]
[MultilegOrderCancelReplace (body_54506567.html?find=PriceProtectionScope)]
[NewOrderCross (body_5350115.html?find=PriceProtectionScope)]
[NewOrderMultileg (body_54496566.html?find=PriceProtectionScope)]
[NewOrderSingle (body_495268.html?find=PriceProtectionScope)]
[OrderCancelReplaceRequest (body_495571.html?find=PriceProtectionScope)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=PriceProtectionScope)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
