.TH FIX.5.0SP2 "" "" "Tag #1093"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1093 (tag1093.html)
LotType (tag1093.html)
\@LotTyp
char
.PP
Defines the lot type assigned to the order.
1
=
.PP
Odd Lot
2
=
.PP
Round Lot
3
=
.PP
Block Lot
4
=
.PP
Round lot based upon UnitOfMeasure(996)
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=LotType)]
.PP
   *   *   *   *   *
Used in components:
[LotTypeRules (body_50495052.html?find=LotType)]
[MDFullGrp (body_50485149.html?find=LotType)]
[MDIncGrp (body_50485150.html?find=LotType)]
[TradeReportOrderDetail (body_50495251.html?find=LotType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
