.TH FIX.5.0SP2 "" "" "Tag #1094"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1094 (tag1094.html)
PegPriceType (tag1094.html)
\@PegPxTyp
int
.PP
Defines the type of peg.
1
=
.PP
Last peg (last sale)
2
=
.PP
Mid-price peg (midprice of inside quote)
3
=
.PP
Opening peg
4
=
.PP
Market peg
5
=
.PP
Primary peg (primary market - buy at bid or sell at offer)
7
=
.PP
Peg to VWAP
8
=
.PP
Trailing Stop Peg
9
=
.PP
Peg to Limit Price
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PegInstructions (body_49484951.html?find=PegPriceType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
