.TH FIX.5.0SP2 "" "" "Tag #1100"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1100 (tag1100.html)
TriggerType (tag1100.html)
\@TrgrTyp
char
.PP
Defines when the trigger will hit, i.e. the action specified by the
trigger instructions will come into effect.
1
=
.PP
Partial Execution
2
=
.PP
Specified Trading Session
3
=
.PP
Next Auction
4
=
.PP
Price Movement
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
