.TH FIX.5.0SP2 "" "" "Tag #1106"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1106 (tag1106.html)
TriggerSecurityDesc (tag1106.html)
\@TrgrSecDesc
String
.PP
Defines the security description of the security whose prices will
be tracked by the trigger logic.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerSecurityDesc)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
