.TH FIX.5.0SP2 "" "" "Tag #1108"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1108 (tag1108.html)
TriggerPriceTypeScope (tag1108.html)
\@TrgrPxTypScp
char
.PP
Defines the type of price protection the customer requires on their
order.
0
=
.PP
None
1
=
.PP
Local (Exchange, ECN, ATS)
2
=
.PP
National (Across all national markets)
3
=
.PP
Global (Across all markets)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerPriceTypeScope)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
