.TH FIX.5.0SP2 "" "" "Tag #1111"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1111 (tag1111.html)
TriggerOrderType (tag1111.html)
\@TrgrOrdTyp
char
.PP
The OrdType the order should have after the trigger has hit.
Required to express orders that change from Limit to Market. Other
values from OrdType (40) may be used if appropriate and bilaterally
agreed upon.
1
=
.PP
Market
2
=
.PP
Limit
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerOrderType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
