.TH FIX.5.0SP2 "" "" "Tag #1114"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1114 (tag1114.html)
TriggerTradingSessionSubID (tag1114.html)
\@TrgrTrdSessSubID
String
.PP
Defines the subordinate trading session at which the order will be
activated.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TriggeringInstruction (body_49485148.html?find=TriggerTradingSessionSubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
