.TH FIX.5.0SP2 "" "" "Tag #1125"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1125 (tag1125.html)
OrigTradeDate (tag1125.html)
\@OrigTrdDt
LocalMktDate
.PP
Used to preserve original trade date when original trade is being
referenced in a subsequent trade transaction such as a transfer
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=OrigTradeDate)]
[TradeCaptureReportAck (body_55556582.html?find=OrigTradeDate)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
