.TH FIX.5.0SP2 "" "" "Tag #1126"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1126 (tag1126.html)
OrigTradeID (tag1126.html)
\@OrigTrdID
String
.PP
Used to preserve original trade id when original trade is being
referenced in a subsequent trade transaction such as a transfer
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=OrigTradeID)]
[TradeCaptureReportAck (body_55556582.html?find=OrigTradeID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
