.TH FIX.5.0SP2 "" "" "Tag #1130"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1130 (tag1130.html)
RefApplVerID (tag1130.html)
\@RefApplVerID
String
.PP
Specifies the service pack release being applied to a message at
the session level. Enumerated field with values assigned at time of
service pack release. Uses same values as ApplVerID
0
=
.PP
FIX27
1
=
.PP
FIX30
2
=
.PP
FIX40
3
=
.PP
FIX41
4
=
.PP
FIX42
5
=
.PP
FIX43
6
=
.PP
FIX44
7
=
.PP
FIX50
8
=
.PP
FIX50SP1
9
=
.PP
FIX50SP2
.PP
   *   *   *   *   *
Used in messages:
[BusinessMessageReject (body_5251106.html?find=RefApplVerID)]
[Reject (body_5251.html?find=RefApplVerID)]
.PP
   *   *   *   *   *
Used in components:
[MsgTypeGrp (body_50485756.html?find=RefApplVerID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
