.TH FIX.5.0SP2 "" "" "Tag #1133"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1133 (tag1133.html)
ExDestinationIDSource (tag1133.html)
\@ExDestIDSrc
char
.PP
The ID source of ExDestination
B
=
.PP
BIC (Bank Identification Code) (ISO 9362)
C
=
.PP
Generally accepted market participant identifier (e.g. NASD
mnemonic)
D
=
.PP
Proprietary / Custom code
E
=
.PP
ISO Country Code
G
=
.PP
MIC (ISO 10383 - Market Identifier Code)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=ExDestinationIDSource)]
[MultilegOrderCancelReplace (body_54506567.html?find=ExDestinationIDSource)]
[NewOrderCross (body_5350115.html?find=ExDestinationIDSource)]
[NewOrderMultileg (body_54496566.html?find=ExDestinationIDSource)]
[NewOrderSingle (body_495268.html?find=ExDestinationIDSource)]
[OrderCancelReplaceRequest (body_495571.html?find=ExDestinationIDSource)]
[Quote (body_505583.html?find=ExDestinationIDSource)]
[QuoteResponse (body_54576574.html?find=ExDestinationIDSource)]
[QuoteStatusReport (body_54566573.html?find=ExDestinationIDSource)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=ExDestinationIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
