.TH FIX.5.0SP2 "" "" "Tag #1134"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1134 (tag1134.html)
ReportedPxDiff (tag1134.html)
\@ReportedPxDiff
Boolean
.PP
Indicates that the reported price that is different from the market
price. The price difference should be stated by using field 828
TrdType and, if required, field 829 TrdSubType
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=ReportedPxDiff)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
