.TH FIX.5.0SP2 "" "" "Tag #1136"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1136 (tag1136.html)
AllocClearingFeeIndicator (tag1136.html)
\@ClrFeeInd
String
.PP
ClearingFeeIndicator(635) for Allocation, see
ClearingFeeIndicator(635) for permitted values.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdAllocGrp (body_50485448.html?find=AllocClearingFeeIndicator)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
