.TH FIX.5.0SP2 "" "" "Tag #1138"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1138 (tag1138.html)
DisplayQty (tag1138.html)
\@DisplayQty
Qty
.PP
The quantity to be displayed \&.
Required for reserve orders. On orders specifies the qty to be
displayed, on execution reports the currently displayed quantity.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DisplayInstruction (body_49485057.html?find=DisplayQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
