.TH FIX.5.0SP2 "" "" "Tag #1142"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1142 (tag1142.html)
MatchAlgorithm (tag1142.html)
\@MtchAlgo
String
.PP
The types of algorithm used to match orders in a specific security.
Possilbe value types are FIFO, Allocation, Pro-rata, Lead Market
Maker, Currency Calender.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MatchRules (body_50495053.html?find=MatchAlgorithm)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
