.TH FIX.5.0SP2 "" "" "Tag #1143"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1143 (tag1143.html)
MaxPriceVariation (tag1143.html)
\@MxPxVar
float
.PP
The maximum price variation of an execution from one event to the
next for a given security.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[BaseTradingRules (body_50495149.html?find=MaxPriceVariation)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
