.TH FIX.5.0SP2 "" "" "Tag #1145"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1145 (tag1145.html)
EventTime (tag1145.html)
\@Tm
UTCTimestamp
.PP
Specific time of event. To be used in combination with EventDate
[866]
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[EvntGrp (body_50485548.html?find=EventTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
