.TH FIX.5.0SP2 "" "" "Tag #1146"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1146 (tag1146.html)
MinPriceIncrementAmount (tag1146.html)
\@MinPxIncrAmt
Amt
.PP
Minimum price increment amount associated with the
MinPriceIncrement ( tag 969). For listed derivatives, the value can
be calculated by multiplying MinPriceIncrement by
ContractValueFactor(231).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=MinPriceIncrementAmount)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
