.TH FIX.5.0SP2 "" "" "Tag #1147"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1147 (tag1147.html)
UnitOfMeasureQty (tag1147.html)
\@UOMQty
Qty
.PP
Used to indicate the quantity of the underlying commodity unit of
measure on which the contract is based, such as, 2500 lbs of lean
cattle, 1000 barrels of crude oil, 1000 bushels of corn, etc.
UnitOfMeasureQty is required for UnitOfMeasure(996) Variable
Quantity UOMs enumerations. Refer to the definition of
UnitOfMeasure(996) for more information on the use of
UnitOfMeasureQty.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=UnitOfMeasureQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
