.TH FIX.5.0SP2 "" "" "Tag #1148"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1148 (tag1148.html)
LowLimitPrice (tag1148.html)
\@LowLmtPx
Price
.PP
Allowable low limit price for the trading day. A key parameter in
validating order price. Used as the lower band for validating order
prices. Orders submitted with prices below the lower limit will be
rejected
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PriceLimits (body_50495050.html?find=LowLimitPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
