.TH FIX.5.0SP2 "" "" "Tag #1150"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1150 (tag1150.html)
TradingReferencePrice (tag1150.html)
\@TrdgRefPx
Price
.PP
Reference price for the current trading price range usually
representing the mid price between the HighLimitPrice and
LowLimitPrice. The value may be the settlement price or closing
price of the prior trading day.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PriceLimits (body_50495050.html?find=TradingReferencePrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
