.TH FIX.5.0SP2 "" "" "Tag #1153"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1153 (tag1153.html)
SettlementCycleNo (tag1153.html)
\@CycleNo
int
.PP
Settlement cycle in which the settlement obligation was generated
.PP
   *   *   *   *   *
Used in messages:
[SettlementObligationReport (body_4948506681.html?find=SettlementCycleNo)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
