.TH FIX.5.0SP2 "" "" "Tag #1159"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1159 (tag1159.html)
SettlObligMode (tag1159.html)
\@SettlMode
int
.PP
Used to identify the reporting mode of the settlement obligation
which is either preliminary or final
1
=
.PP
Preliminary
2
=
.PP
Final
.PP
   *   *   *   *   *
Used in messages:
[SettlementObligationReport (body_4948506681.html?find=SettlObligMode)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
