.TH FIX.5.0SP2 "" "" "Tag #1161"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1161 (tag1161.html)
SettlObligID (tag1161.html)
\@SettlID
String
.PP
Unique ID for this settlement instruction.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlObligationInstructions (body_50494849.html?find=SettlObligID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
