.TH FIX.5.0SP2 "" "" "Tag #1162"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1162 (tag1162.html)
SettlObligTransType (tag1162.html)
\@SettlTransTyp
char
.PP
Transaction Type - required except where SettlInstMode is 5=Reject
SSI request
C
=
.PP
Cancel
N
=
.PP
New
R
=
.PP
Replace
T
=
.PP
Restate
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlObligationInstructions (body_50494849.html?find=SettlObligTransType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
