.TH FIX.5.0SP2 "" "" "Tag #1164"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1164 (tag1164.html)
SettlObligSource (tag1164.html)
\@SettlSrc
char
.PP
Used to identify whether these delivery instructions are for the
buyside or the sellside.
1
=
.PP
Instructions of Broker
2
=
.PP
Instructions for Institution
3
=
.PP
Investor
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlDetails (body_50495157.html?find=SettlObligSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
