.TH FIX.5.0SP2 "" "" "Tag #1167"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1167 (tag1167.html)
QuoteEntryStatus (tag1167.html)
\@QtEntSts
int
.PP
Identifies the status of an individual quote. See also
QuoteStatus(297) which is used for single Quotes.
0
=
.PP
Accepted
5
=
.PP
Rejected
6
=
.PP
Removed from Market
7
=
.PP
Expired
12
=
.PP
Locked Market Warning
13
=
.PP
Cross Market Warning
14
=
.PP
Canceled due to Lock Market
15
=
.PP
Canceled due to Cross Market
16
=
.PP
Active
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=QuoteEntryStatus)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
