.TH FIX.5.0SP2 "" "" "Tag #1171"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1171 (tag1171.html)
PrivateQuote (tag1171.html)
\@PrvtQt
Boolean
.PP
Specifies whether a quote is public, i.e. available to the market,
or private, i.e. available to a specified counterparty only.
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=PrivateQuote)]
[QuoteRequest (body_505482.html?find=PrivateQuote)]
[QuoteRequestReject (body_54546571.html?find=PrivateQuote)]
[RFQRequest (body_54556572.html?find=PrivateQuote)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
