.TH FIX.5.0SP2 "" "" "Tag #1173"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1173 (tag1173.html)
MDSubBookType (tag1173.html)
\@MDSubBkTyp
int
.PP
Describes a class of sub book, e.g. for the separation of various
lot types. The Sub Book Type indicates that the following Market
Data Entries belong to a non-integrated Sub Book. Whenever provided
the Sub Book must be used together with MDPriceLevel and
MDEntryPositionNo in order to sort the order properly.
.PP
Values are bilaterally agreed.
.PP
   *   *   *   *   *
Used in messages:
[MarketDataSnapshotFullRefresh (body_514887.html?find=MDSubBookType)]
.PP
   *   *   *   *   *
Used in components:
[MDIncGrp (body_50485150.html?find=MDSubBookType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
