.TH FIX.5.0SP2 "" "" "Tag #1174"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1174 (tag1174.html)
SecurityTradingEvent (tag1174.html)
\@SecTrdEvnt
int
.PP
Identifies an event related to a SecurityTradingStatus(326). An
event occurs and is gone, it is not a state that applies for a
period of time.
1
=
.PP
Order imbalance, auction is extended
2
=
.PP
Trading resumes (after Halt)
3
=
.PP
Price Volatility Interruption
4
=
.PP
Change of Trading Session
5
=
.PP
Change of Trading Subsession
6
=
.PP
Change of Security Trading Status
7
=
.PP
Change of Book Type
8
=
.PP
Change of Market Depth
.PP
   *   *   *   *   *
Used in messages:
[SecurityStatus (body_5157102.html?find=SecurityTradingEvent)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
