.TH FIX.5.0SP2 "" "" "Tag #1176"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1176 (tag1176.html)
StatsType (tag1176.html)
\@StatsTyp
int
.PP
Type of statistics
1
=
.PP
Exchange Last
2
=
.PP
High / Low Price
3
=
.PP
Average Price (VWAP, TWAP ... )
4
=
.PP
Turnover (Price * Qty)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StatsIndGrp (body_50494851.html?find=StatsType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
