.TH FIX.5.0SP2 "" "" "Tag #1179"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1179 (tag1179.html)
MDSecSize (tag1179.html)
\@MDSecSize
Qty
.PP
A part of the MDEntrySize(271) that represents secondary interest
as specified by MDSecSizeType(1178).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SecSizesGrp (body_50494850.html?find=MDSecSize)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
