.TH FIX.5.0SP2 "" "" "Tag #1186"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1186 (tag1186.html)
SecurityXMLSchema (tag1186.html)
\@Schema
String
.PP
The schema used to validate the contents of SecurityXML
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SecurityXML (body_49485448.html?find=SecurityXMLSchema)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
