.TH FIX.5.0SP2 "" "" "Tag #1187"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1187 (tag1187.html)
RefreshIndicator (tag1187.html)
\@RefInd
Boolean
.PP
Set by the sender to tell the receiver to perform an immediate
refresh of the book due to disruptions in the accompanying
real-time feed
.PP
\[aq]Y\[aq] - Mandatory refresh by all participants
.PP
\[aq]N\[aq] - Process as required
.PP
   *   *   *   *   *
Used in messages:
[MarketDataSnapshotFullRefresh (body_514887.html?find=RefreshIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
