.TH FIX.5.0SP2 "" "" "Tag #1191"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1191 (tag1191.html)
PriceUnitOfMeasure (tag1191.html)
\@PxUOM
String
.PP
Used to express the UOM of the price if different from the
contract. In futures, this can be different for cross-rate products
in which the price is quoted in units differently from the contract
—\ Fixed Magnitude UOM\ —
Bcf
=
.PP
Billion cubic feet
MMbbl
=
.PP
Million Barrels
MMBtu
=
.PP
One Million BTU
MWh
=
.PP
Megawatt hours
—\ Variable Quantity UOM\ —
Bbl
=
.PP
Barrels
Bu
=
.PP
Bushels
lbs
=
.PP
pounds
Gal
=
.PP
Gallons
oz_tr
=
.PP
Troy Ounces
t
=
.PP
Metric Tons (aka Tonne)
tn
=
.PP
Tons (US)
USD
=
.PP
US Dollars
Alw
=
.PP
Allowances
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=PriceUnitOfMeasure)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
