.TH FIX.5.0SP2 "" "" "Tag #1194"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1194 (tag1194.html)
ExerciseStyle (tag1194.html)
\@ExerStyle
int
.PP
Type of exercise of a derivatives security
0
=
.PP
European
1
=
.PP
American
2
=
.PP
Bermuda
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=ExerciseStyle)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
