.TH FIX.5.0SP2 "" "" "Tag #1197"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1197 (tag1197.html)
ValuationMethod (tag1197.html)
\@ValMeth
String
.PP
Specifies the type of valuation method applied.
EQTY
=
.PP
premium style
FUT
=
.PP
futures style mark-to-market
FUTDA
=
.PP
futures style with an attached cash adjustment
CDS
=
.PP
CDS style collateralization of market to market and coupon
CDSD
=
.PP
CDS in delivery - use recovery rate to calculate obligation
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=ValuationMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
