.TH FIX.5.0SP2 "" "" "Tag #1199"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1199 (tag1199.html)
CapPrice (tag1199.html)
\@CapPx
Price
.PP
Used to express the ceiling price of a capped call
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=CapPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
