.TH FIX.5.0SP2 "" "" "Tag #120"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
120 (tag120.html)
SettlCurrency (tag120.html)
\@SettlCcy
Currency
.PP
Currency code of settlement denomination.
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=SettlCurrency)]
[ExecutionReport (body_5756.html?find=SettlCurrency)]
[MultilegOrderCancelReplace (body_54506567.html?find=SettlCurrency)]
[NewOrderMultileg (body_54496566.html?find=SettlCurrency)]
[NewOrderSingle (body_495268.html?find=SettlCurrency)]
[OrderCancelReplaceRequest (body_495571.html?find=SettlCurrency)]
[PositionMaintenanceReport (body_55506577.html?find=SettlCurrency)]
[PositionMaintenanceRequest (body_55496576.html?find=SettlCurrency)]
[PositionReport (body_55536580.html?find=SettlCurrency)]
[Quote (body_505583.html?find=SettlCurrency)]
[RequestForPositions (body_55516578.html?find=SettlCurrency)]
[RequestForPositionsAck (body_55526579.html?find=SettlCurrency)]
[SettlementInstructionRequest (body_56496586.html?find=SettlCurrency)]
[TradeCaptureReport (body_54526569.html?find=SettlCurrency)]
[TradeCaptureReportAck (body_55556582.html?find=SettlCurrency)]
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=SettlCurrency)]
[ListOrdGrp (body_50485148.html?find=SettlCurrency)]
[MDFullGrp (body_50485149.html?find=SettlCurrency)]
[MDIncGrp (body_50485150.html?find=SettlCurrency)]
[QuotReqGrp (body_50485253.html?find=SettlCurrency)]
[SettlInstGrp (body_50485355.html?find=SettlCurrency)]
[SettlObligationInstructions (body_50494849.html?find=SettlCurrency)]
[SideCrossOrdModGrp (body_50485357.html?find=SettlCurrency)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
