.TH FIX.5.0SP2 "" "" "Tag #1201"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1201 (tag1201.html)
NoStrikeRules (tag1201.html)
NumInGroup
.PP
Number of strike rule entries. This block specifies the rules for
determining how new strikes should be listed within the stated
price range of the underlying instrument
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StrikeRules (body_50494957.html?find=NoStrikeRules)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
