.TH FIX.5.0SP2 "" "" "Tag #1202"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1202 (tag1202.html)
StartStrikePxRange (tag1202.html)
\@StartStrkPxRng
Price
.PP
Starting price for the range to which the StrikeIncrement applies.
Price refers to the price of the underlying
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StrikeRules (body_50494957.html?find=StartStrikePxRange)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
