.TH FIX.5.0SP2 "" "" "Tag #1205"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1205 (tag1205.html)
NoTickRules (tag1205.html)
NumInGroup
.PP
Number of tick rules. This block specifies the rules for
determining how a security ticks, i.e. the price increments at
which it can be quoted and traded, depending on the current price
of the security
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TickRules (body_50494956.html?find=NoTickRules)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
