.TH FIX.5.0SP2 "" "" "Tag #1207"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1207 (tag1207.html)
EndTickPriceRange (tag1207.html)
\@EndTickPxRng
Price
.PP
Ending price range for the specified tick increment
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TickRules (body_50494956.html?find=EndTickPriceRange)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
