.TH FIX.5.0SP2 "" "" "Tag #1208"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1208 (tag1208.html)
TickIncrement (tag1208.html)
\@TickIncr
Price
.PP
Tick increment for stated price range. Specifies the valid price
increments at which a security can be quoted and traded
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TickRules (body_50494956.html?find=TickIncrement)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
