.TH FIX.5.0SP2 "" "" "Tag #1209"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1209 (tag1209.html)
TickRuleType (tag1209.html)
\@TickRuleTyp
int
.PP
Specifies the type of tick rule which is being described
0
=
.PP
Regular
1
=
.PP
Variable
2
=
.PP
Fixed
3
=
.PP
Traded as a spread leg
4
=
.PP
Settled as a spread leg
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TickRules (body_50494956.html?find=TickRuleType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
