.TH FIX.5.0SP2 "" "" "Tag #1215"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1215 (tag1215.html)
DerivativeSymbolSfx (tag1215.html)
\@Sfx
String
.PP
Refer to definition for SymbolSfx(65)
—\ For Fixed Income\ —
CD
=
.PP
EUCP with lump-sum interest rather than discount price
WI
=
.PP
"When Issued" for a security to be reissued under an old CUSIP or
ISIN
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeInstrument (body_50495248.html?find=DerivativeSymbolSfx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
