.TH FIX.5.0SP2 "" "" "Tag #1219"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1219 (tag1219.html)
DerivativeSecurityAltID (tag1219.html)
\@ID
String
.PP
Refer to definition for SecurityAltID(455)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeSecurityAltIDGrp (body_50494853.html?find=DerivativeSecurityAltID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
