.TH FIX.5.0SP2 "" "" "Tag #1221"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1221 (tag1221.html)
SecondaryLowLimitPrice (tag1221.html)
\@LowLmtPx
Price
.PP
Refer to definition of LowLimitPrice(1148)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SecondaryPriceLimits (body_50495049.html?find=SecondaryLowLimitPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
