.TH FIX.5.0SP2 "" "" "Tag #1229"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1229 (tag1229.html)
MaturityMonthYearIncrement (tag1229.html)
\@MMYIncr
int
.PP
Increment between successive maturities for an option class
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MaturityRules (body_50495048.html?find=MaturityMonthYearIncrement)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
