.TH FIX.5.0SP2 "" "" "Tag #123"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
123 (tag123.html)
GapFillFlag (tag123.html)
Boolean
.PP
Indicates that the Sequence Reset message is replacing
administrative or application messages which will not be resent.
N
=
.PP
Sequence Reset, Ignore Msg Seq Num (N/A For FIXML - Not Used)
Y
=
.PP
Gap Fill Message, Msg Seq Num Field Valid
.PP
   *   *   *   *   *
Used in messages:
[SequenceReset (body_5352.html?find=GapFillFlag)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
