.TH FIX.5.0SP2 "" "" "Tag #1231"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1231 (tag1231.html)
MinLotSize (tag1231.html)
\@MinLotSz
Qty
.PP
Minimum lot size allowed based on lot type specified in
LotType(1093)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[LotTypeRules (body_50495052.html?find=MinLotSize)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
