.TH FIX.5.0SP2 "" "" "Tag #1237"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1237 (tag1237.html)
NoOrdTypeRules (tag1237.html)
NumInGroup
.PP
Number of order types
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[OrdTypeRules (body_50495056.html?find=NoOrdTypeRules)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
