.TH FIX.5.0SP2 "" "" "Tag #124"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
124 (tag124.html)
NoExecs (tag124.html)
NumInGroup
.PP
No of execution repeating group entries to follow.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ExecAllocGrp (body_50484952.html?find=NoExecs)]
[ExecCollGrp (body_50484953.html?find=NoExecs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
