.TH FIX.5.0SP2 "" "" "Tag #1240"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1240 (tag1240.html)
SecondaryTradingReferencePrice (tag1240.html)
\@TrdgRefPx
Price
.PP
Refer to definition for TradingReferencePrice(1150)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SecondaryPriceLimits (body_50495049.html?find=SecondaryTradingReferencePrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
