.TH FIX.5.0SP2 "" "" "Tag #1242"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1242 (tag1242.html)
FlexProductEligibilityIndicator (tag1242.html)
\@FlexProdElig
Boolean
.PP
Used to indicate if a product or group of product supports the
creation of flexible securities
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=FlexProductEligibilityIndicator)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
