.TH FIX.5.0SP2 "" "" "Tag #1244"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1244 (tag1244.html)
FlexibleIndicator (tag1244.html)
\@FlexInd
Boolean
.PP
Used to indicate a derivatives security that can be defined using
flexible terms. The terms commonly permitted to be defined by
market participants are expiration date and strike price.
FlexibleIndicator is an alternative CFICode(461)
Standard/Non-standard attribute.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=FlexibleIndicator)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
