.TH FIX.5.0SP2 "" "" "Tag #1256"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1256 (tag1256.html)
DerivativeSecurityStatus (tag1256.html)
\@Status
String
1
=
.PP
Active
2
=
.PP
Inactive
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeInstrument (body_50495248.html?find=DerivativeSecurityStatus)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
