.TH FIX.5.0SP2 "" "" "Tag #1283"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1283 (tag1283.html)
DerivativeSecurityXML (tag1283.html)
data
.PP
Refer to definition of SecurityXML(1185)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeSecurityXML (body_49485449.html?find=DerivativeSecurityXML)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
