.TH FIX.5.0SP2 "" "" "Tag #1287"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1287 (tag1287.html)
DerivativeEventType (tag1287.html)
\@EventTyp
int
1
=
.PP
Put
2
=
.PP
Call
3
=
.PP
Tender
4
=
.PP
Sinking Fund Call
5
=
.PP
Activation
6
=
.PP
Inactiviation
7
=
.PP
Last Eligible Trade Date
8
=
.PP
Swap Start Date
9
=
.PP
Swap End Date
10
=
.PP
Swap Roll Date
11
=
.PP
Swap Next Start Date
12
=
.PP
Swap Next Roll Date
13
=
.PP
First Delivery Date
14
=
.PP
Last Delivery Date
15
=
.PP
Initial Inventory Due Date
16
=
.PP
Final Inventory Due Date
17
=
.PP
First Intent Date
18
=
.PP
Last Intent Date
19
=
.PP
Position Removal Date
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeEventsGrp (body_50494854.html?find=DerivativeEventType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
