.TH FIX.5.0SP2 "" "" "Tag #1294"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1294 (tag1294.html)
DerivativeInstrumentPartyIDSource (tag1294.html)
\@Src
String
.PP
Refer to definition of PartyIDSource(447)
—\ For PartyRole = "InvestorID" and for CIV\ —
6
=
.PP
UK National Insurance or Pension Number
7
=
.PP
US Social Security Number
8
=
.PP
US Employer or Tax ID Number
9
=
.PP
Australian Business Number
A
=
.PP
Australian Tax File Number
—\ For PartyRole = "InvestorID" and for Equities\ —
1
=
.PP
Korean Investor ID
2
=
.PP
Taiwanese Qualified Foreign Investor ID QFII/FID
3
=
.PP
Taiwanese Trading Acct
4
=
.PP
Malaysian Central Depository (MCD) number
5
=
.PP
Chinese Investor ID
—\ For PartyRole="Broker of Credit"\ —
I
=
.PP
Directed broker three character acronym as defined in ISITC "ETC
Best Practice" guidelines document
—\ For all PartyRoles\ —
B
=
.PP
BIC (Bank Identification Code - SWIFT managed) code (ISO9362 - See
"Appendix 6-B")
C
=
.PP
Generally accepted market participant identifier (e.g. NASD
mnemonic)
D
=
.PP
Proprietary / Custom code
E
=
.PP
ISO Country Code
F
=
.PP
Settlement Entity Location (note if Local Market Settlement use
"E=ISO Country Code") (see "Appendix 6-G" for valid values)
G
=
.PP
MIC (ISO 10383 - Market Identificer Code) (See "Appendix 6-C")
H
=
.PP
CSD participant/member code (e.g.. Euroclear, DTC, CREST or
Kassenverein number)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeInstrumentParties (body_50495249.html?find=DerivativeInstrumentPartyIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
