.TH FIX.5.0SP2 "" "" "Tag #1300"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1300 (tag1300.html)
MarketSegmentID (tag1300.html)
\@MktSegID
String
.PP
Identifies the market segment
.PP
   *   *   *   *   *
Used in messages:
[DerivativeSecurityListRequest (body_5357122.html?find=MarketSegmentID)]
[MarketDefinition (body_4948546685.html?find=MarketSegmentID)]
[MarketDefinitionRequest (body_4948536684.html?find=MarketSegmentID)]
[MarketDefinitionUpdateReport (body_4948556686.html?find=MarketSegmentID)]
[News (body_495066.html?find=MarketSegmentID)]
[OrderMassActionReport (body_4949496690.html?find=MarketSegmentID)]
[OrderMassActionRequest (body_4949506765.html?find=MarketSegmentID)]
[OrderMassCancelReport (body_5349114.html?find=MarketSegmentID)]
[OrderMassCancelRequest (body_5348113.html?find=MarketSegmentID)]
[SecurityDefinitionRequest (body_515499.html?find=MarketSegmentID)]
[SecurityList (body_5356121.html?find=MarketSegmentID)]
[SecurityListRequest (body_5355120.html?find=MarketSegmentID)]
[SecurityListUpdateReport (body_57546675.html?find=MarketSegmentID)]
[SecurityStatus (body_5157102.html?find=MarketSegmentID)]
[SecurityStatusRequest (body_5156101.html?find=MarketSegmentID)]
[SecurityTypeRequest (body_5353118.html?find=MarketSegmentID)]
[SecurityTypes (body_5354119.html?find=MarketSegmentID)]
[TradeCaptureReport (body_54526569.html?find=MarketSegmentID)]
[TradeCaptureReportAck (body_55556582.html?find=MarketSegmentID)]
[TradingSessionListRequest (body_4948496673.html?find=MarketSegmentID)]
[TradingSessionStatus (body_5249104.html?find=MarketSegmentID)]
[TradingSessionStatusRequest (body_5248103.html?find=MarketSegmentID)]
.PP
   *   *   *   *   *
Used in components:
[MarketSegmentGrp (body_50495150.html?find=MarketSegmentID)]
[TrdSessLstGrp (body_50485757.html?find=MarketSegmentID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
