.TH FIX.5.0SP2 "" "" "Tag #1301"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1301 (tag1301.html)
MarketID (tag1301.html)
\@MktID
Exchange
.PP
Identifies the Market
.PP
   *   *   *   *   *
Used in messages:
[DerivativeSecurityListRequest (body_5357122.html?find=MarketID)]
[MarketDefinition (body_4948546685.html?find=MarketID)]
[MarketDefinitionRequest (body_4948536684.html?find=MarketID)]
[MarketDefinitionUpdateReport (body_4948556686.html?find=MarketID)]
[News (body_495066.html?find=MarketID)]
[OrderMassActionReport (body_4949496690.html?find=MarketID)]
[OrderMassActionRequest (body_4949506765.html?find=MarketID)]
[OrderMassCancelReport (body_5349114.html?find=MarketID)]
[OrderMassCancelRequest (body_5348113.html?find=MarketID)]
[SecurityDefinitionRequest (body_515499.html?find=MarketID)]
[SecurityList (body_5356121.html?find=MarketID)]
[SecurityListRequest (body_5355120.html?find=MarketID)]
[SecurityListUpdateReport (body_57546675.html?find=MarketID)]
[SecurityStatus (body_5157102.html?find=MarketID)]
[SecurityStatusRequest (body_5156101.html?find=MarketID)]
[SecurityTypeRequest (body_5353118.html?find=MarketID)]
[SecurityTypes (body_5354119.html?find=MarketID)]
[TradeCaptureReport (body_54526569.html?find=MarketID)]
[TradeCaptureReportAck (body_55556582.html?find=MarketID)]
[TradingSessionListRequest (body_4948496673.html?find=MarketID)]
[TradingSessionStatus (body_5249104.html?find=MarketID)]
[TradingSessionStatusRequest (body_5248103.html?find=MarketID)]
.PP
   *   *   *   *   *
Used in components:
[MarketSegmentGrp (body_50495150.html?find=MarketID)]
[TrdSessLstGrp (body_50485757.html?find=MarketID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
