.TH FIX.5.0SP2 "" "" "Tag #1302"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1302 (tag1302.html)
MaturityMonthYearIncrementUnits (tag1302.html)
\@MMYIncrUnits
int
.PP
Unit of measure for the Maturity Month Year Increment
0
=
.PP
Months
1
=
.PP
Days
2
=
.PP
Weeks
3
=
.PP
Years
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MaturityRules (body_50495048.html?find=MaturityMonthYearIncrementUnits)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
