.TH FIX.5.0SP2 "" "" "Tag #1303"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1303 (tag1303.html)
MaturityMonthYearFormat (tag1303.html)
\@MMYFmt
int
.PP
Format used to generate the MaturityMonthYear for each option
0
=
.PP
YearMonth Only (default)
1
=
.PP
YearMonthDay
2
=
.PP
YearMonthWeek
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MaturityRules (body_50495048.html?find=MaturityMonthYearFormat)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
