.TH FIX.5.0SP2 "" "" "Tag #1304"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1304 (tag1304.html)
StrikeExerciseStyle (tag1304.html)
\@StrkExrStyle
int
.PP
Expiration Style for an option class:
0
=
.PP
European
1
=
.PP
American
2
=
.PP
Bermuda
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StrikeRules (body_50494957.html?find=StrikeExerciseStyle)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
