.TH FIX.5.0SP2 "" "" "Tag #1307"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1307 (tag1307.html)
DerivativeSecurityListRequestType (tag1307.html)
\@ListReqTyp
int
.PP
Identifies the type of Security List Request
0
=
.PP
Symbol
1
=
.PP
SecurityType and or CFICode
2
=
.PP
Product
3
=
.PP
TradingSessionID
4
=
.PP
All Securities
5
=
.PP
UndelyingSymbol
6
=
.PP
Underlying SecurityType and or CFICode
7
=
.PP
Underlying Product
8
=
.PP
MarketID or MarketID + MarketSegmentID
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
