.TH FIX.5.0SP2 "" "" "Tag #1309"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1309 (tag1309.html)
NoTradingSessionRules (tag1309.html)
NumInGroup
.PP
Allows trading rules to be expressed by trading session
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TradingSessionRulesGrp (body_50495148.html?find=NoTradingSessionRules)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
