.TH FIX.5.0SP2 "" "" "Tag #1310"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1310 (tag1310.html)
NoMarketSegments (tag1310.html)
NumInGroup
.PP
Number of Market Segments on which a security may trade.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MarketSegmentGrp (body_50495150.html?find=NoMarketSegments)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
