.TH FIX.5.0SP2 "" "" "Tag #1311"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1311 (tag1311.html)
NoDerivativeInstrAttrib (tag1311.html)
NumInGroup
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeInstrumentAttribute (body_50495154.html?find=NoDerivativeInstrAttrib)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
