.TH FIX.5.0SP2 "" "" "Tag #1320"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1320 (tag1320.html)
DerivativeListMethod (tag1320.html)
\@ListMeth
int
.PP
Indicates whether instruments are pre-listed only or can also be
defined via user request
0
=
.PP
pre-listed only
1
=
.PP
user requested
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeInstrument (body_50495248.html?find=DerivativeListMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
