.TH FIX.5.0SP2 "" "" "Tag #1323"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1323 (tag1323.html)
DerivativePutOrCall (tag1323.html)
\@PutCall
int
.PP
Indicates whether an Option is for a put or call
0
=
.PP
Put
1
=
.PP
Call
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DerivativeInstrument (body_50495248.html?find=DerivativePutOrCall)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
