.TH FIX.5.0SP2 "" "" "Tag #1325"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1325 (tag1325.html)
ParentMktSegmID (tag1325.html)
\@ParentMktSegmID
String
.PP
Reference to a parent Market Segment. See MarketSegmentID(1300)
.PP
   *   *   *   *   *
Used in messages:
[MarketDefinition (body_4948546685.html?find=ParentMktSegmID)]
[MarketDefinitionRequest (body_4948536684.html?find=ParentMktSegmID)]
[MarketDefinitionUpdateReport (body_4948556686.html?find=ParentMktSegmID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
