.TH FIX.5.0SP2 "" "" "Tag #1329"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1329 (tag1329.html)
FeeMultiplier (tag1329.html)
\@FeeMult
float
.PP
This is a multiplier that Clearing (Fee system) will use to
calculate fees and will be sent to the firms on their confirms.
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=FeeMultiplier)]
[TradeCaptureReportAck (body_55556582.html?find=FeeMultiplier)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
