.TH FIX.5.0SP2 "" "" "Tag #1333"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1333 (tag1333.html)
UnderlyingLegSecurityIDSource (tag1333.html)
\@Src
String
.PP
Refer to definition for SecurityIDSource(22)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingLegInstrument (body_50495152.html?find=UnderlyingLegSecurityIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
