.TH FIX.5.0SP2 "" "" "Tag #1334"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1334 (tag1334.html)
NoUnderlyingLegSecurityAltID (tag1334.html)
NumInGroup
.PP
Refer to definition for NoSecurityAltID(454)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingLegSecurityAltIDGrp (body_50494856.html?find=NoUnderlyingLegSecurityAltID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
