.TH FIX.5.0SP2 "" "" "Tag #1347"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1347 (tag1347.html)
ApplReqType (tag1347.html)
\@ApplReqTyp
int
.PP
Type of Application Message Request being made.
0
=
.PP
Retransmission of application messages for the specified
Applications
1
=
.PP
Subscription to the specified Applications
2
=
.PP
Request for the last ApplLastSeqNum published for the specified
Applications
3
=
.PP
Request valid set of Applications
4
=
.PP
Unsubscribe to the specified Applications
5
=
.PP
Cancel retransmission
6
=
.PP
Cancel retransmission and unsubscribe to the specified applications
.PP
   *   *   *   *   *
Used in messages:
[ApplicationMessageRequest (body_4948566687.html?find=ApplReqType)]
[ApplicationMessageRequestAck (body_4948576688.html?find=ApplReqType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
