.TH FIX.5.0SP2 "" "" "Tag #1350"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1350 (tag1350.html)
ApplLastSeqNum (tag1350.html)
\@ApplLastSeqNum
SeqNum
.PP
Application sequence number of last message in transmission
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ApplicationSequenceControl (body_49485355.html?find=ApplLastSeqNum)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
