.TH FIX.5.0SP2 "" "" "Tag #1352"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1352 (tag1352.html)
ApplResendFlag (tag1352.html)
\@ApplResendFlag
Boolean
.PP
Used to indicate that a message is being sent in response to an
Application Message Request. It is possible for both ApplResendFlag
and PossDupFlag to be set on the same message if the Sender\[aq]s
cache size is greater than zero and the message is being resent due
to a session level resend request
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ApplicationSequenceControl (body_49485355.html?find=ApplResendFlag)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
