.TH FIX.5.0SP2 "" "" "Tag #1353"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1353 (tag1353.html)
ApplResponseID (tag1353.html)
\@ApplRespID
String
.PP
Identifier for the Applicaton Message Request Ack
.PP
   *   *   *   *   *
Used in messages:
[ApplicationMessageRequestAck (body_4948576688.html?find=ApplResponseID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
