.TH FIX.5.0SP2 "" "" "Tag #1354"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1354 (tag1354.html)
ApplResponseError (tag1354.html)
\@ApplRespErr
int
.PP
Used to return an error code or text associated with a response to
an Application Request.
0
=
.PP
Application does not exist
1
=
.PP
Messages requested are not available
2
=
.PP
User not authorized for application
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ApplIDRequestAckGrp (body_50494954.html?find=ApplResponseError)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
