.TH FIX.5.0SP2 "" "" "Tag #1355"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1355 (tag1355.html)
RefApplID (tag1355.html)
\@RefApplID
String
.PP
Reference to the unique application identifier which corresponds to
ApplID(1180) from the Application Sequence Group component
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ApplIDReportGrp (body_50494955.html?find=RefApplID)]
[ApplIDRequestAckGrp (body_50494954.html?find=RefApplID)]
[ApplIDRequestGrp (body_50494953.html?find=RefApplID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
