.TH FIX.5.0SP2 "" "" "Tag #1356"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1356 (tag1356.html)
ApplReportID (tag1356.html)
\@ApplRptID
String
.PP
Identifier for the Application Sequence Reset
.PP
   *   *   *   *   *
Used in messages:
[ApplicationMessageReport (body_4949486689.html?find=ApplReportID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
