.TH FIX.5.0SP2 "" "" "Tag #1357"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1357 (tag1357.html)
RefApplLastSeqNum (tag1357.html)
\@RefApplLastSeqNum
SeqNum
.PP
Application sequence number of last message in transmission.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ApplIDReportGrp (body_50494955.html?find=RefApplLastSeqNum)]
[ApplIDRequestAckGrp (body_50494954.html?find=RefApplLastSeqNum)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
