.TH FIX.5.0SP2 "" "" "Tag #1363"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1363 (tag1363.html)
FillExecID (tag1363.html)
\@FillExecID
String
.PP
Refer to ExecID(17). Used when multiple partial fills are reported
in single Execution Report. ExecID and FillExecID should not
overlap,
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[FillsGrp (body_50494950.html?find=FillExecID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
