.TH FIX.5.0SP2 "" "" "Tag #1364"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1364 (tag1364.html)
FillPx (tag1364.html)
\@FillPx
Price
.PP
Price of Fill. Refer to LastPx(31).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[FillsGrp (body_50494950.html?find=FillPx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
