.TH FIX.5.0SP2 "" "" "Tag #1368"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1368 (tag1368.html)
TradSesEvent (tag1368.html)
\@TradSesEvent
int
.PP
Identifies an event related to a TradSesStatus(340). An event
occurs and is gone, it is not a state that applies for a period of
time.
0
=
.PP
Trading resumes (after Halt)
1
=
.PP
Change of Trading Session
2
=
.PP
Change of Trading Subsession
3
=
.PP
Change of Trading Status
.PP
   *   *   *   *   *
Used in messages:
[TradingSessionStatus (body_5249104.html?find=TradSesEvent)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
