.TH FIX.5.0SP2 "" "" "Tag #1370"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1370 (tag1370.html)
NoNotAffectedOrders (tag1370.html)
NumInGroup
.PP
Number of not affected orders in the repeating group of order ids.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NotAffectedOrdersGrp (body_50494949.html?find=NoNotAffectedOrders)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
