.TH FIX.5.0SP2 "" "" "Tag #1373"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1373 (tag1373.html)
MassActionType (tag1373.html)
\@MassActionType
int
.PP
Specifies the type of action requested
1
=
.PP
Suspend orders
2
=
.PP
Release orders from suspension
3
=
.PP
Cancel orders
.PP
   *   *   *   *   *
Used in messages:
[OrderMassActionReport (body_4949496690.html?find=MassActionType)]
[OrderMassActionRequest (body_4949506765.html?find=MassActionType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
