.TH FIX.5.0SP2 "" "" "Tag #1374"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1374 (tag1374.html)
MassActionScope (tag1374.html)
\@MassActionScope
int
.PP
Specifies scope of Order Mass Action Request.
1
=
.PP
All orders for a security
2
=
.PP
All orders for an underlying security
3
=
.PP
All orders for a Product
4
=
.PP
All orders for a CFICode
5
=
.PP
All orders for a SecurityType
6
=
.PP
All orders for a trading session
7
=
.PP
All orders
8
=
.PP
All orders for a Market
9
=
.PP
All orders for a Market Segment
10
=
.PP
All orders for a Security Group
11
=
.PP
Cancel for Security Issuer
12
=
.PP
Cancel for Issuer of Underlying Security
.PP
   *   *   *   *   *
Used in messages:
[OrderMassActionReport (body_4949496690.html?find=MassActionScope)]
[OrderMassActionRequest (body_4949506765.html?find=MassActionScope)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
