.TH FIX.5.0SP2 "" "" "Tag #1375"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1375 (tag1375.html)
MassActionResponse (tag1375.html)
\@MassActionResponse
int
.PP
Specifies the action taken by counterparty order handling system as
a result of the action type indicated in MassActionType of the
Order Mass Action Request.
0
=
.PP
Rejected - See MassActionRejectReason(1376)
1
=
.PP
Accepted
.PP
   *   *   *   *   *
Used in messages:
[OrderMassActionReport (body_4949496690.html?find=MassActionResponse)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
