.TH FIX.5.0SP2 "" "" "Tag #1376"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1376 (tag1376.html)
MassActionRejectReason (tag1376.html)
\@MassActionRejectReason
int
.PP
Reason Order Mass Action Request was rejected
0
=
.PP
Mass Action Not Supported
1
=
.PP
Invalid or unknown security
2
=
.PP
Invalid or unknown underlying security
3
=
.PP
Invalid or unknown Product
4
=
.PP
Invalid or unknown CFICode
5
=
.PP
Invalid or unknown SecurityType
6
=
.PP
Invalid or unknown trading session
7
=
.PP
Invalid or unknown Market
8
=
.PP
Invalid or unknown Market Segment
9
=
.PP
Invalid or unknown Security Group
10
=
.PP
Invalid or unknown Security Issuer
11
=
.PP
Invalid or unknown Issuer of Underlying Security
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[OrderMassActionReport (body_4949496690.html?find=MassActionRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
