.TH FIX.5.0SP2 "" "" "Tag #1378"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1378 (tag1378.html)
MultilegPriceMethod (tag1378.html)
\@MlegPxMeth
int
.PP
Code to represent how the multileg price is to be interpreted when
applied to the legs.
.PP
(See Volume : "Glossary" for further value definitions)
0
=
.PP
Net Price
1
=
.PP
Reversed Net Price
2
=
.PP
Yield Difference
3
=
.PP
Individual
4
=
.PP
Contract Weighted Average Price
5
=
.PP
Multiplied Price
.PP
   *   *   *   *   *
Used in messages:
[MultilegOrderCancelReplace (body_54506567.html?find=MultilegPriceMethod)]
[NewOrderMultileg (body_54496566.html?find=MultilegPriceMethod)]
.PP
   *   *   *   *   *
Used in components:
[BaseTradingRules (body_50495149.html?find=MultilegPriceMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
