.TH FIX.5.0SP2 "" "" "Tag #1381"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1381 (tag1381.html)
LegDividendYield (tag1381.html)
\@LegDividendYield
Percentage
.PP
Refer to definition for DividendYield(1380).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegDividendYield)]
[LegOrdGrp (body_50485053.html?find=LegDividendYield)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegDividendYield)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
