.TH FIX.5.0SP2 "" "" "Tag #1382"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1382 (tag1382.html)
CurrencyRatio (tag1382.html)
\@CurrencyRatio
float
.PP
Specifies the currency ratio between the currency used for a
multileg price and the currency used by the outright book defined
by the leg. Example: Multileg quoted in EUR, outright leg in USD
and 1 EUR = 0,7 USD then CurrencyRatio = 0.7
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=CurrencyRatio)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
