.TH FIX.5.0SP2 "" "" "Tag #1385"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1385 (tag1385.html)
ContingencyType (tag1385.html)
\@ContingencyType
int
.PP
Defines the type of contingency.
1
=
.PP
One Cancels the Other (OCO)
2
=
.PP
One Triggers the Other (OTO)
3
=
.PP
One Updates the Other (OUO) - Absolute Quantity Reduction
4
=
.PP
One Updates the Other (OUO) - Proportional Quantity Reduction
.PP
   *   *   *   *   *
Used in messages:
[ListStatus (body_505178.html?find=ContingencyType)]
[NewOrderList (body_495369.html?find=ContingencyType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
