.TH FIX.5.0SP2 "" "" "Tag #1386"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1386 (tag1386.html)
ListRejectReason (tag1386.html)
\@ListRejectReason
int
.PP
Identifies the reason for rejection of a New Order List message.
Note that OrdRejReason(103) is used if the rejection is based on
properties of an individual order part of the List.
0
=
.PP
Broker / Exchange option
2
=
.PP
Exchange closed
4
=
.PP
Too late to enter
5
=
.PP
Unknown order
6
=
.PP
Duplicate Order (e.g. dupe ClOrdID)
11
=
.PP
Unsupported order characteristic
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[ListStatus (body_505178.html?find=ListRejectReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
