.TH FIX.5.0SP2 "" "" "Tag #1389"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1389 (tag1389.html)
TrdRepIndicator (tag1389.html)
\@TrdRepInd
Boolean
.PP
Specifies whether the trade should be reported (or not) to parties
of the provided TrdRepPartyRole(1388). Used to override standard
reporting behavior by the receiver of the trade report and thereby
complements the PublTrdIndicator( tag1390).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdRepIndicatorsGrp (body_50494951.html?find=TrdRepIndicator)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
