.TH FIX.5.0SP2 "" "" "Tag #1390"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1390 (tag1390.html)
TradePublishIndicator (tag1390.html)
\@TrdPubInd
int
.PP
Indicates if a trade should be reported via a market reporting
service. The indicator governs all reporting services of the
recipient. Replaces PublishTrdIndicator(852).
0
=
.PP
Do Not Publish Trade
1
=
.PP
Publish Trade
2
=
.PP
Deferred Publication
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TradePublishIndicator)]
[TradeCaptureReportAck (body_55556582.html?find=TradePublishIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
