.TH FIX.5.0SP2 "" "" "Tag #1395"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1395 (tag1395.html)
MarketUpdateAction (tag1395.html)
\@MktUpdtActn
char
.PP
Specifies the action taken for the specified MarketID(1301) +
MarketSegmentID(1300).
A
=
.PP
Add
D
=
.PP
Delete
M
=
.PP
Modify
.PP
   *   *   *   *   *
Used in messages:
[MarketDefinitionUpdateReport (body_4948556686.html?find=MarketUpdateAction)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
