.TH FIX.5.0SP2 "" "" "Tag #1397"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1397 (tag1397.html)
EncodedMktSegmDescLen (tag1397.html)
\@EncodedMktSegmDescLen
Length
.PP
Byte length of encoded (non-ASCII characters)
EncodedMktSegmDesc(1324) field.
.PP
   *   *   *   *   *
Used in messages:
[MarketDefinition (body_4948546685.html?find=EncodedMktSegmDescLen)]
[MarketDefinitionUpdateReport (body_4948556686.html?find=EncodedMktSegmDescLen)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
