.TH FIX.5.0SP2 "" "" "Tag #1398"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1398 (tag1398.html)
EncodedMktSegmDesc (tag1398.html)
\@EncodedMktSegmDesc
data
.PP
Encoded (non-ASCII characters) representation of the
MarketSegmDesc(1396) field in the encoded format specified via the
MessageEncoding(347) field. If used, the ASCII (English)
representation should also be specified in the MarketSegmDesc
field.
.PP
   *   *   *   *   *
Used in messages:
[MarketDefinition (body_4948546685.html?find=EncodedMktSegmDesc)]
[MarketDefinitionUpdateReport (body_4948556686.html?find=EncodedMktSegmDesc)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
