.TH FIX.5.0SP2 "" "" "Tag #1400"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1400 (tag1400.html)
EncryptedPasswordMethod (tag1400.html)
\@EncPwdMethod
int
.PP
Enumeration defining the encryption method used to encrypt password
fields.
.PP
At this time there are no encryption methods defined by FPL.
.PP
   *   *   *   *   *
Used in messages:
[Logon (body_494965.html?find=EncryptedPasswordMethod)]
[UserRequest (body_57486669.html?find=EncryptedPasswordMethod)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
