.TH FIX.5.0SP2 "" "" "Tag #1403"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1403 (tag1403.html)
EncryptedNewPasswordLen (tag1403.html)
Length
.PP
Length of the EncryptedNewPassword(1404) field
.PP
   *   *   *   *   *
Used in messages:
[Logon (body_494965.html?find=EncryptedNewPasswordLen)]
[UserRequest (body_57486669.html?find=EncryptedNewPasswordLen)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
