.TH FIX.5.0SP2 "" "" "Tag #1406"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1406 (tag1406.html)
RefApplExtID (tag1406.html)
\@RefApplExtID
int
.PP
The extension pack number associated with an application message.
.PP
   *   *   *   *   *
Used in messages:
[BusinessMessageReject (body_5251106.html?find=RefApplExtID)]
[Reject (body_5251.html?find=RefApplExtID)]
.PP
   *   *   *   *   *
Used in components:
[MsgTypeGrp (body_50485756.html?find=RefApplExtID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
