.TH FIX.5.0SP2 "" "" "Tag #1409"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1409 (tag1409.html)
SessionStatus (tag1409.html)
\@SessStat
int
.PP
Status of a FIX session
0
=
.PP
Session active
1
=
.PP
Session password changed
2
=
.PP
Session password due to expire
3
=
.PP
New session password does not comply with policy
4
=
.PP
Session logout complete
5
=
.PP
Invalid username or password
6
=
.PP
Account locked
7
=
.PP
Logons are not allowed at this time
8
=
.PP
Password expired
.PP
   *   *   *   *   *
Used in messages:
[Logon (body_494965.html?find=SessionStatus)]
[Logout (body_5453.html?find=SessionStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
