.TH FIX.5.0SP2 "" "" "Tag #1412"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1412 (tag1412.html)
Nested4PartySubID (tag1412.html)
\@ID
String
.PP
Refer to definition of PartySubID(523)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NstdPtys4SubGrp (body_50495250.html?find=Nested4PartySubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
