.TH FIX.5.0SP2 "" "" "Tag #1413"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1413 (tag1413.html)
NoNested4PartySubIDs (tag1413.html)
\@NoNested4PartySubIDs
NumInGroup
.PP
Refer to definition of NoPartySubIDs(802)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NstdPtys4SubGrp (body_50495250.html?find=NoNested4PartySubIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
