.TH FIX.5.0SP2 "" "" "Tag #1414"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1414 (tag1414.html)
NoNested4PartyIDs (tag1414.html)
\@NoNested4PartyIDs
NumInGroup
.PP
Refer to definition of NoPartyIDs(453)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NestedParties4 (body_49485357.html?find=NoNested4PartyIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
