.TH FIX.5.0SP2 "" "" "Tag #1427"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1427 (tag1427.html)
SideExecID (tag1427.html)
\@SideExecID
String
.PP
When reporting trades, used to reference the identifier of the
execution (ExecID) being reported if different ExecIDs were
assigned to each side of the trade.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=SideExecID)]
[TrdCapRptSideGrp (body_50485449.html?find=SideExecID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
