.TH FIX.5.0SP2 "" "" "Tag #1429"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1429 (tag1429.html)
OrderDelayUnit (tag1429.html)
\@OrdDelayUnit
int
.PP
Time unit in which the OrderDelay(1428) is expressed
0
=
.PP
Seconds (default if not specified)
1
=
.PP
Tenths of a second
2
=
.PP
Hundredths of a second
3
=
.PP
milliseconds
4
=
.PP
microseconds
5
=
.PP
nanoseconds
10
=
.PP
minutes
11
=
.PP
hours
12
=
.PP
days
13
=
.PP
weeks
14
=
.PP
months
15
=
.PP
years
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=OrderDelayUnit)]
[TrdCapRptSideGrp (body_50485449.html?find=OrderDelayUnit)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
