.TH FIX.5.0SP2 "" "" "Tag #1432"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1432 (tag1432.html)
OrigCustOrderCapacity (tag1432.html)
\@OrigCustOrdCpcty
int
.PP
The customer capacity for this trade at the time of the
order/execution.
.PP
Primarily used by futures exchanges to indicate the CTICode
(customer type indicator) as required by the US CFTC (Commodity
Futures Trading Commission).
1
=
.PP
Member trading for their own account
2
=
.PP
Clearing Firm trading for its proprietary account
3
=
.PP
Member trading for another member
4
=
.PP
All other
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TradeReportOrderDetail (body_50495251.html?find=OrigCustOrderCapacity)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
