.TH FIX.5.0SP2 "" "" "Tag #1433"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1433 (tag1433.html)
RefApplReqID (tag1433.html)
\@RefID
String
.PP
Used to reference a previously submitted ApplReqID (1346) from
within a subsequent ApplicationMessageRequest(MsgType=BW)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ApplIDRequestAckGrp (body_50494954.html?find=RefApplReqID)]
[ApplIDRequestGrp (body_50494953.html?find=RefApplReqID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
