.TH FIX.5.0SP2 "" "" "Tag #1434"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1434 (tag1434.html)
ModelType (tag1434.html)
\@ModelTyp
int
.PP
Type of pricing model used
0
=
.PP
Utility provided standard model
1
=
.PP
Proprietary (user supplied) model
.PP
   *   *   *   *   *
Used in messages:
[PositionReport (body_55536580.html?find=ModelType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
