.TH FIX.5.0SP2 "" "" "Tag #1440"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1440 (tag1440.html)
LegFlowScheduleType (tag1440.html)
\@FlowSchedTyp
int
.PP
The industry standard flow schedule by which electricity or natural
gas is traded. Schedules exist by regions and on-peak and off-peak
status, such as "Western Peak".
0
=
.PP
NERC Eastern Off-Peak
1
=
.PP
NERC Western Off-Peak
2
=
.PP
NERC Calendar-All Days in month
3
=
.PP
NERC Eastern Peak
4
=
.PP
NERC Western Peak
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegFlowScheduleType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
