.TH FIX.5.0SP2 "" "" "Tag #1444"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1444 (tag1444.html)
SideLiquidityInd (tag1444.html)
\@LqdtyInd
int
.PP
Indicator to identify whether this fill was a result of a liquidity
provider providing or liquidity taker taking the liquidity.
Applicable only for OrdStatus of Partial or Filled.
1
=
.PP
Added Liquidity
2
=
.PP
Removed Liquidity
3
=
.PP
Liquidity Routed Out
4
=
.PP
Auction
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptSideGrp (body_50485449.html?find=SideLiquidityInd)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
