.TH FIX.5.0SP2 "" "" "Tag #1446"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1446 (tag1446.html)
RateSource (tag1446.html)
\@RtSrc
int
.PP
Identifies the source of rate information.
.PP
For FX, the reference source to be used for the FX spot rate.
0
=
.PP
Bloomberg
1
=
.PP
Reuters
2
=
.PP
Telerate
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RateSource (body_49485450.html?find=RateSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
