.TH FIX.5.0SP2 "" "" "Tag #1448"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1448 (tag1448.html)
ReferencePage (tag1448.html)
\@RefPg
String
.PP
Identifies the reference "page" from the rate source.
.PP
For FX, the reference page to the spot rate to be used for the
reference FX spot rate.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RateSource (body_49485450.html?find=ReferencePage)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
