.TH FIX.5.0SP2 "" "" "Tag #1450"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1450 (tag1450.html)
Seniority (tag1450.html)
\@Snrty
String
.PP
Specifies which issue (underlying bond) will receive payment
priority in the event of a default.
.PP
Used to define a CDS instrument.
SD
=
.PP
Senior Secured
SR
=
.PP
Senior
SB
=
.PP
Subordinated
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=Seniority)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
