.TH FIX.5.0SP2 "" "" "Tag #1452"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1452 (tag1452.html)
OriginalNotionalPercentageOutstanding (tag1452.html)
\@OrigNotlPctOut
Percentage
.PP
Used to reflect the Original value prior to the application of a
credit event. See NotionalPercentageOutstanding(1451).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=OriginalNotionalPercentageOutstanding)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
