.TH FIX.5.0SP2 "" "" "Tag #146"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
146 (tag146.html)
NoRelatedSym (tag146.html)
NumInGroup
.PP
Specifies the number of repeating symbols specified.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtGrp (body_50484955.html?find=NoRelatedSym)]
[InstrmtMDReqGrp (body_50485050.html?find=NoRelatedSym)]
[QuotReqGrp (body_50485253.html?find=NoRelatedSym)]
[QuotReqRjctGrp (body_50485255.html?find=NoRelatedSym)]
[RFQReqGrp (body_50485349.html?find=NoRelatedSym)]
[RelSymDerivSecGrp (body_50485348.html?find=NoRelatedSym)]
[RelSymDerivSecUpdGrp (body_50494855.html?find=NoRelatedSym)]
[SecListGrp (body_50485353.html?find=NoRelatedSym)]
[SecLstUpdRelSymGrp (body_50485655.html?find=NoRelatedSym)]
[StrmAsgnReqInstrmtGrp (body_50495348.html?find=NoRelatedSym)]
[StrmAsgnRptInstrmtGrp (body_50495349.html?find=NoRelatedSym)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
