.TH FIX.5.0SP2 "" "" "Tag #1462"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1462 (tag1462.html)
TargetPartyID (tag1462.html)
\@ID
String
.PP
PartyID value within an target party repeating group.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TargetParties (body_49485451.html?find=TargetPartyID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
