.TH FIX.5.0SP2 "" "" "Tag #1465"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1465 (tag1465.html)
SecurityListID (tag1465.html)
\@ListID
String
.PP
Specifies an identifier for a Security List
.PP
   *   *   *   *   *
Used in messages:
[SecurityList (body_5356121.html?find=SecurityListID)]
[SecurityListRequest (body_5355120.html?find=SecurityListID)]
[SecurityListUpdateReport (body_57546675.html?find=SecurityListID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
