.TH FIX.5.0SP2 "" "" "Tag #1466"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1466 (tag1466.html)
SecurityListRefID (tag1466.html)
\@ListRefID
String
.PP
Specifies a reference from one Security List to another. Used to
support a hierarchy of Security Lists.
.PP
   *   *   *   *   *
Used in messages:
[SecurityList (body_5356121.html?find=SecurityListRefID)]
[SecurityListUpdateReport (body_57546675.html?find=SecurityListRefID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
