.TH FIX.5.0SP2 "" "" "Tag #1468"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1468 (tag1468.html)
EncodedSecurityListDescLen (tag1468.html)
Length
.PP
Byte length of encoded (non-ASCII characters)
EncodedSecurityListDesc (tbd) field.
.PP
   *   *   *   *   *
Used in messages:
[SecurityList (body_5356121.html?find=EncodedSecurityListDescLen)]
[SecurityListUpdateReport (body_57546675.html?find=EncodedSecurityListDescLen)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
