.TH FIX.5.0SP2 "" "" "Tag #1469"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1469 (tag1469.html)
EncodedSecurityListDesc (tag1469.html)
data
.PP
Encoded (non-ASCII characters) representation of the
SecurityListDesc (1467) field in the encoded format specified via
the MessageEncoding (347) field. If used, the ASCII (English)
representation should also be specified in the SecurityListDesc
field.
.PP
   *   *   *   *   *
Used in messages:
[SecurityList (body_5356121.html?find=EncodedSecurityListDesc)]
[SecurityListUpdateReport (body_57546675.html?find=EncodedSecurityListDesc)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
