.TH FIX.5.0SP2 "" "" "Tag #1470"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1470 (tag1470.html)
SecurityListType (tag1470.html)
\@ListTyp
int
.PP
Specifies a type of Security List.
1
=
.PP
Industry Classification
2
=
.PP
Trading List
3
=
.PP
Market / Market Segment List
4
=
.PP
Newspaper List
.PP
   *   *   *   *   *
Used in messages:
[SecurityList (body_5356121.html?find=SecurityListType)]
[SecurityListRequest (body_5355120.html?find=SecurityListType)]
[SecurityListUpdateReport (body_57546675.html?find=SecurityListType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
