.TH FIX.5.0SP2 "" "" "Tag #1471"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1471 (tag1471.html)
SecurityListTypeSource (tag1471.html)
\@LstTypSrc
int
.PP
Specifies a specific source for a SecurityListType. Relevant when a
certain type can be provided from various sources.
1
=
.PP
ICB (Industry Classification Benchmark) published by Dow Jones and
FTSE - www.icbenchmark.com
2
=
.PP
NAICS (North American Industry Classification System). Replaced SIC
(Standard Industry Classification) www.census.gov/naics or
www.naics.com.
3
=
.PP
GICS (Global Industry Classification Standard) published by
Standards & Poor
.PP
   *   *   *   *   *
Used in messages:
[SecurityList (body_5356121.html?find=SecurityListTypeSource)]
[SecurityListRequest (body_5355120.html?find=SecurityListTypeSource)]
[SecurityListUpdateReport (body_57546675.html?find=SecurityListTypeSource)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
