.TH FIX.5.0SP2 "" "" "Tag #1473"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1473 (tag1473.html)
NewsCategory (tag1473.html)
\@NewsCatgy
int
.PP
Category of news mesage.
0
=
.PP
Company News
1
=
.PP
Marketplace News
2
=
.PP
Financial Market News
3
=
.PP
Technical News
99
=
.PP
Other News
.PP
   *   *   *   *   *
Used in messages:
[News (body_495066.html?find=NewsCategory)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
