.TH FIX.5.0SP2 "" "" "Tag #1477"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1477 (tag1477.html)
NewsRefType (tag1477.html)
\@RefTyp
int
.PP
Type of reference to another News Message item. Defines if the
referenced news item is a replacement, is in a different language,
or is complimentary.
0
=
.PP
Replacement
1
=
.PP
Other Language
2
=
.PP
Complimentary
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NewsRefGrp (body_50495252.html?find=NewsRefType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
