.TH FIX.5.0SP2 "" "" "Tag #1479"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1479 (tag1479.html)
StrikePriceBoundaryMethod (tag1479.html)
\@StrkPxBndryMeth
int
.PP
Specifies the boundary condition to be used for the strike price
relative to the underlying price at the point of option exercise.
1
=
.PP
Less than underlying price is in-the-money (ITM)
2
=
.PP
Less than or equal to the underlying price is in-the-money(ITM)
3
=
.PP
Equal to the underlying price is in-the-money(ITM)
4
=
.PP
Greater than or equal to underlying price is in-the-money(ITM)
5
=
.PP
Greater than underlying is in-the-money(ITM)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=StrikePriceBoundaryMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
