.TH FIX.5.0SP2 "" "" "Tag #1480"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1480 (tag1480.html)
StrikePriceBoundaryPrecision (tag1480.html)
\@StrkPxBndryPrcsn
Percentage
.PP
Used in combination with StrikePriceBoundaryMethod to specify the
percentage of the strike price in relation to the underlying price.
The percentage is generally 100 or greater for puts and 100 or less
for calls.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=StrikePriceBoundaryPrecision)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
