.TH FIX.5.0SP2 "" "" "Tag #1481"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1481 (tag1481.html)
UnderlyingPriceDeterminationMethod (tag1481.html)
\@PxDtrmnMeth
int
.PP
Specifies how the underlying price is determined at the point of
option exercise. The underlying price may be set to the current
settlement price, set to a special reference, set to the optimal
value of the underlying during the defined period (“Look-back”) or
set to the average value of the underlying during the defined
period ("Asian option").
1
=
.PP
Regular
2
=
.PP
Special reference
3
=
.PP
Optimal value (Lookback)
4
=
.PP
Average value (Asian option)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=UnderlyingPriceDeterminationMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
