.TH FIX.5.0SP2 "" "" "Tag #1484"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1484 (tag1484.html)
ComplexEventType (tag1484.html)
\@Typ
int
.PP
Identifies the type of complex event.
1
=
.PP
Capped
2
=
.PP
Trigger
3
=
.PP
Knock-in up
4
=
.PP
Kock-in down
5
=
.PP
Knock-out up
6
=
.PP
Knock-out down
7
=
.PP
Underlying
8
=
.PP
Reset Barrier
9
=
.PP
Rolling Barrier
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEvents (body_50495253.html?find=ComplexEventType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
