.TH FIX.5.0SP2 "" "" "Tag #1486"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1486 (tag1486.html)
ComplexEventPrice (tag1486.html)
\@Px
Price
.PP
Specifies the price at which the complex event takes effect. Impact
of the event price is determined by the ComplexEventType(1484).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEvents (body_50495253.html?find=ComplexEventPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
