.TH FIX.5.0SP2 "" "" "Tag #1489"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1489 (tag1489.html)
ComplexEventPriceTimeType (tag1489.html)
\@PxTmTyp
int
.PP
Specifies when the complex event outcome takes effect. The outcome
of a complex event is a payout or barrier action as specified by
the ComplexEventType.
1
=
.PP
Expiration
2
=
.PP
Immediate (At Any Time)
3
=
.PP
Specified Date/Time
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEvents (body_50495253.html?find=ComplexEventPriceTimeType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
