.TH FIX.5.0SP2 "" "" "Tag #1490"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1490 (tag1490.html)
ComplexEventCondition (tag1490.html)
\@Cond
int
.PP
Specifies the condition between complex events when more than one
event is specified.
.PP
Multiple barrier events would use an "or" condition since only one
can be effective at a given time. A set of digital range events
would use an “and” condition since both conditions must be in
effect for a payout to result.
1
=
.PP
And
2
=
.PP
Or
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEvents (body_50495253.html?find=ComplexEventCondition)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
