.TH FIX.5.0SP2 "" "" "Tag #1491"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1491 (tag1491.html)
NoComplexEventDates (tag1491.html)
NumInGroup
.PP
Number of complex event date occurrences for a given complex event.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEventDates (body_50495254.html?find=NoComplexEventDates)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
