.TH FIX.5.0SP2 "" "" "Tag #1492"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1492 (tag1492.html)
ComplexEventStartDate (tag1492.html)
\@StartDt
UTCTimestamp
.PP
Specifies the start date of the date range on which a complex event
is effective. The start date will be set equal to the end date for
single day events such as Bermuda options
.PP
ComplexEventStartDate must always be less than or equal to
ComplexEventEndDate.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEventDates (body_50495254.html?find=ComplexEventStartDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
