.TH FIX.5.0SP2 "" "" "Tag #1494"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1494 (tag1494.html)
NoComplexEventTimes (tag1494.html)
NumInGroup
.PP
Number of complex event time occurrences for a given complex event
date
.PP
The default in case of an absence of time fields is
00:00:00-23:59:59.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEventTimes (body_50495255.html?find=NoComplexEventTimes)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
