.TH FIX.5.0SP2 "" "" "Tag #1495"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1495 (tag1495.html)
ComplexEventStartTime (tag1495.html)
\@StartTm
UTCTimeOnly
.PP
Specifies the start time of the time range on which a complex event
date is effective.
.PP
ComplexEventStartTime must always be less than or equal to
ComplexEventEndTime.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEventTimes (body_50495255.html?find=ComplexEventStartTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
