.TH FIX.5.0SP2 "" "" "Tag #1496"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1496 (tag1496.html)
ComplexEventEndTime (tag1496.html)
\@EndTm
UTCTimeOnly
.PP
Specifies the end time of the time range on which a complex event
date is effective.
.PP
ComplexEventEndTime must always be greater than or equal to
ComplexEventStartTime.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ComplexEventTimes (body_50495255.html?find=ComplexEventEndTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
