.TH FIX.5.0SP2 "" "" "Tag #1498"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1498 (tag1498.html)
StreamAsgnReqType (tag1498.html)
\@AsgnReqTyp
int
.PP
Type of stream assignment request.
1
=
.PP
Stream assignment for new customer(s)
2
=
.PP
Stream assignment for existing customer(s)
.PP
   *   *   *   *   *
Used in messages:
[StreamAssignmentReport (body_4949536768.html?find=StreamAsgnReqType)]
[StreamAssignmentRequest (body_4949526767.html?find=StreamAsgnReqType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
