.TH FIX.5.0SP2 "" "" "Tag #1499"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1499 (tag1499.html)
NoAsgnReqs (tag1499.html)
NumInGroup
.PP
Number of assignment requests.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StrmAsgnReqGrp (body_50495256.html?find=NoAsgnReqs)]
[StrmAsgnRptGrp (body_50495257.html?find=NoAsgnReqs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
