.TH FIX.5.0SP2 "" "" "Tag #1500"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1500 (tag1500.html)
MDStreamID (tag1500.html)
\@MDStrmID
String
.PP
The identifier or name of the price stream.
.PP
   *   *   *   *   *
Used in messages:
[MarketDataSnapshotFullRefresh (body_514887.html?find=MDStreamID)]
.PP
   *   *   *   *   *
Used in components:
[InstrmtMDReqGrp (body_50485050.html?find=MDStreamID)]
[MDIncGrp (body_50485150.html?find=MDStreamID)]
[StrmAsgnReqInstrmtGrp (body_50495348.html?find=MDStreamID)]
[StrmAsgnRptInstrmtGrp (body_50495349.html?find=MDStreamID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
