.TH FIX.5.0SP2 "" "" "Tag #1501"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1501 (tag1501.html)
StreamAsgnRptID (tag1501.html)
\@RptID
String
.PP
Unique identifier of the stream assignment report provided by the
respondent.
.PP
   *   *   *   *   *
Used in messages:
[StreamAssignmentReport (body_4949536768.html?find=StreamAsgnRptID)]
[StreamAssignmentReportACK (body_4949546769.html?find=StreamAsgnRptID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
