.TH FIX.5.0SP2 "" "" "Tag #1502"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1502 (tag1502.html)
StreamAsgnRejReason (tag1502.html)
\@RejRsn
int
.PP
Reason code for stream assignment request reject.
0
=
.PP
Unknown client
1
=
.PP
Exceeds maximum size
2
=
.PP
Unknown or Invalid currency pair
3
=
.PP
No available stream
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[StreamAssignmentReportACK (body_4949546769.html?find=StreamAsgnRejReason)]
.PP
   *   *   *   *   *
Used in components:
[StrmAsgnRptInstrmtGrp (body_50495349.html?find=StreamAsgnRejReason)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
