.TH FIX.5.0SP2 "" "" "Tag #1504"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1504 (tag1504.html)
RelSymTransactTime (tag1504.html)
\@TxnTm
UTCTimestamp
.PP
See TransactTime(60)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelSymDerivSecGrp (body_50485348.html?find=RelSymTransactTime)]
[RelSymDerivSecUpdGrp (body_50494855.html?find=RelSymTransactTime)]
[SecListGrp (body_50485353.html?find=RelSymTransactTime)]
[SecLstUpdRelSymGrp (body_50485655.html?find=RelSymTransactTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
