.TH FIX.5.0SP2 "" "" "Tag #1507"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1507 (tag1507.html)
PartyListResponseType (tag1507.html)
\@Typ
int
.PP
Indicates the type of response that has been requested.
0
=
.PP
Return all available information on parties and related parties.
(May not be combined with other values.)
1
=
.PP
Return only party information. (Excludes information like risk
limits from being reported. May not be combined with any other
value except 2.)
2
=
.PP
Include information on related parties.
3
=
.PP
Include risk limit information.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PartyListResponseTypeGrp (body_50495350.html?find=PartyListResponseType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
