.TH FIX.5.0SP2 "" "" "Tag #1510"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1510 (tag1510.html)
PartyDetailsListReportID (tag1510.html)
\@RptID
String
.PP
Identifier for the Party Details List Report.
.PP
   *   *   *   *   *
Used in messages:
[PartyDetailsListReport (body_4949566771.html?find=PartyDetailsListReportID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
