.TH FIX.5.0SP2 "" "" "Tag #1513"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1513 (tag1513.html)
NoPartyList (tag1513.html)
NumInGroup
.PP
Number of PartyListGrp.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PartyListGrp (body_50495353.html?find=NoPartyList)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
