.TH FIX.5.0SP2 "" "" "Tag #1515"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1515 (tag1515.html)
PartyRelationship (tag1515.html)
\@Rltnshp
int
.PP
Used to specify the type of the party relationship.
0
=
.PP
Is also
1
=
.PP
Clears for
2
=
.PP
Clears through
3
=
.PP
Trades for
4
=
.PP
Trades through
5
=
.PP
Sponsors
6
=
.PP
Sponsored through
7
=
.PP
Provides guarantee for
8
=
.PP
Is guaranteed by
9
=
.PP
Member of
10
=
.PP
Has members
11
=
.PP
Provides marketplace for
12
=
.PP
Participant of marketplace
13
=
.PP
Carries positions for
14
=
.PP
Posts trades to
15
=
.PP
Enters trades for
16
=
.PP
Enters trades through
17
=
.PP
Provides quotes to
18
=
.PP
Requests quotes from
19
=
.PP
Invests for
20
=
.PP
Invests through
21
=
.PP
Brokers trades for
22
=
.PP
Brokers trades through
23
=
.PP
Provides trading services for
24
=
.PP
Uses trading services of
25
=
.PP
Approves of
26
=
.PP
Approved by
27
=
.PP
Parent firm for
28
=
.PP
Subsidiary of
29
=
.PP
Regulatory owner of
30
=
.PP
Owned by (regulatory)
31
=
.PP
Controls
32
=
.PP
Is controlled by
33
=
.PP
Legal / titled owner of
34
=
.PP
Owned by (legal / title)
35
=
.PP
Beneficial owner of
36
=
.PP
Owned by (beneficial)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PartyRelationships (body_50495352.html?find=PartyRelationship)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
