.TH FIX.5.0SP2 "" "" "Tag #1519"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1519 (tag1519.html)
NoPartyAltSubIDs (tag1519.html)
NumInGroup
.PP
Number of PartyAltSubIDs
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AltPtysSubGrp (body_50495356.html?find=NoPartyAltSubIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
