.TH FIX.5.0SP2 "" "" "Tag #1529"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1529 (tag1529.html)
NoRiskLimits (tag1529.html)
NumInGroup
.PP
Number of RiskLimits.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RiskLimits (body_50495449.html?find=NoRiskLimits)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
