.TH FIX.5.0SP2 "" "" "Tag #153"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
153 (tag153.html)
AllocAvgPx (tag153.html)
\@AvgPx
Price
.PP
AvgPx (6) for a specific AllocAccount (79)
.PP
For Fixed Income this is always expressed as "percent of par" price
type.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=AllocAvgPx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
