.TH FIX.5.0SP2 "" "" "Tag #1530"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1530 (tag1530.html)
RiskLimitType (tag1530.html)
\@Typ
int
.PP
Used to specify the type of risk limit amount of position limit
quantity.
1
=
.PP
Gross Limit
2
=
.PP
Net Limit
3
=
.PP
Exposure
4
=
.PP
Long Limit
5
=
.PP
Short Limit
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RiskLimits (body_50495449.html?find=RiskLimitType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
