.TH FIX.5.0SP2 "" "" "Tag #155"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
155 (tag155.html)
SettlCurrFxRate (tag155.html)
\@SettlCurrFxRt
float
.PP
Foreign exchange rate used to compute SettlCurrAmt (9) from
Currency (5) to SettlCurrency (20)
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=SettlCurrFxRate)]
[ExecutionReport (body_5756.html?find=SettlCurrFxRate)]
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=SettlCurrFxRate)]
[SettlObligationInstructions (body_50494849.html?find=SettlCurrFxRate)]
[TrdCapRptAckSideGrp (body_50485752.html?find=SettlCurrFxRate)]
[TrdCapRptSideGrp (body_50485449.html?find=SettlCurrFxRate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
