.TH FIX.5.0SP2 "" "" "Tag #1550"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1550 (tag1550.html)
RiskMaturityTime (tag1550.html)
\@MatTm
TZTimeOnly
.PP
Risk instrument\[aq]s MaturityTime
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RiskInstrumentScope (body_50495450.html?find=RiskMaturityTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
