.TH FIX.5.0SP2 "" "" "Tag #1552"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1552 (tag1552.html)
RiskSeniority (tag1552.html)
\@Snrty
String
.PP
Risk instrument\[aq]s Seniority.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RiskInstrumentScope (body_50495450.html?find=RiskSeniority)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
