.TH FIX.5.0SP2 "" "" "Tag #1553"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1553 (tag1553.html)
RiskPutOrCall (tag1553.html)
\@PutCall
int
.PP
Risk instrument\[aq]s PutOrCall.
0
=
.PP
Put
1
=
.PP
Call
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RiskInstrumentScope (body_50495450.html?find=RiskPutOrCall)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
