.TH FIX.5.0SP2 "" "" "Tag #1559"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1559 (tag1559.html)
NoRiskWarningLevels (tag1559.html)
NumInGroup
.PP
Number of RiskWarningLevels
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RiskWarningLevels (body_50495452.html?find=NoRiskWarningLevels)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
