.TH FIX.5.0SP2 "" "" "Tag #156"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
156 (tag156.html)
SettlCurrFxRateCalc (tag156.html)
\@SettlCurrFxRtCalc
char
.PP
Specifies whether or not SettlCurrFxRate (55) should be multiplied
or divided.
M
=
.PP
Multiply
D
=
.PP
Divide
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=SettlCurrFxRateCalc)]
[ExecutionReport (body_5756.html?find=SettlCurrFxRateCalc)]
[Quote (body_505583.html?find=SettlCurrFxRateCalc)]
[QuoteResponse (body_54576574.html?find=SettlCurrFxRateCalc)]
[QuoteStatusReport (body_54566573.html?find=SettlCurrFxRateCalc)]
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=SettlCurrFxRateCalc)]
[TrdCapRptAckSideGrp (body_50485752.html?find=SettlCurrFxRateCalc)]
[TrdCapRptSideGrp (body_50485449.html?find=SettlCurrFxRateCalc)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
