.TH FIX.5.0SP2 "" "" "Tag #1570"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1570 (tag1570.html)
RelatedPartyAltID (tag1570.html)
\@ID
String
.PP
PartyID value within a RelatedPartyAltIDs repeating group.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelatedPartyAltIDs (body_50495456.html?find=RelatedPartyAltID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
