.TH FIX.5.0SP2 "" "" "Tag #1573"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1573 (tag1573.html)
RelatedPartyAltSubID (tag1573.html)
\@ID
String
.PP
PartySubID value within a RelatedPartyAltIDs repeating group.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelatedAltPtysSubGrp (body_50495457.html?find=RelatedPartyAltSubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
