.TH FIX.5.0SP2 "" "" "Tag #1575"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1575 (tag1575.html)
NoRelatedContextPartyIDs (tag1575.html)
NumInGroup
.PP
Number of RelatedContextParties.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelatedContextParties (body_50495548.html?find=NoRelatedContextPartyIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
