.TH FIX.5.0SP2 "" "" "Tag #1594"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1594 (tag1594.html)
RelationshipRiskSecurityAltID (tag1594.html)
\@AltID
String
.PP
Relationship Risk instrument\[aq]s SecurityAltID.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelationshipRiskSecAltIDGrp (body_50495552.html?find=RelationshipRiskSecurityAltID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
