.TH FIX.5.0SP2 "" "" "Tag #1595"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1595 (tag1595.html)
RelationshipRiskSecurityAltIDSource (tag1595.html)
\@AltIDSrc
String
.PP
Relationship Risk instrument\[aq]s SecurityAltIDSource.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelationshipRiskSecAltIDGrp (body_50495552.html?find=RelationshipRiskSecurityAltIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
