.TH FIX.5.0SP2 "" "" "Tag #1596"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1596 (tag1596.html)
RelationshipRiskProduct (tag1596.html)
\@Prod
int
.PP
Relationship Risk instrument\[aq]s Product.
1
=
.PP
AGENCY
2
=
.PP
COMMODITY
3
=
.PP
CORPORATE
4
=
.PP
CURRENCY
5
=
.PP
EQUITY
6
=
.PP
GOVERNMENT
7
=
.PP
INDEX
8
=
.PP
LOAN
9
=
.PP
MONEYMARKET
10
=
.PP
MORTGAGE
11
=
.PP
MUNICIPAL
12
=
.PP
OTHER
13
=
.PP
FINANCING
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelationshipRiskInstrumentScope (body_50495551.html?find=RelationshipRiskProduct)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
