.TH FIX.5.0SP2 "" "" "Tag #1611"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1611 (tag1611.html)
RelationshipRiskInstrumentSettlType (tag1611.html)
\@SettlTyp
String
.PP
Relationship Risk instrument\[aq]s SettlType.
0
=
.PP
Regular / FX Spot settlement (T+1 or T+2 depending on currency)
1
=
.PP
Cash (TOD / T+0)
2
=
.PP
Next Day (TOM / T+1)
3
=
.PP
T+2
4
=
.PP
T+3
5
=
.PP
T+4
6
=
.PP
Future
7
=
.PP
When And If Issued
8
=
.PP
Sellers Option
9
=
.PP
T+5
B
=
.PP
Broken date - for FX expressing non-standard tenor, SettlDate (64)
must be specified
C
=
.PP
FX Spot Next settlement (Spot+1, aka next day)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelationshipRiskInstrumentScope (body_50495551.html?find=RelationshipRiskInstrumentSettlType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
