.TH FIX.5.0SP2 "" "" "Tag #1612"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1612 (tag1612.html)
RelationshipRiskInstrumentMultiplier (tag1612.html)
\@Mult
float
.PP
Relationship risk instrument\[aq]s RiskInstrumentMultiplier.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelationshipRiskInstrumentScope (body_50495551.html?find=RelationshipRiskInstrumentMultiplier)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
