.TH FIX.5.0SP2 "" "" "Tag #1619"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1619 (tag1619.html)
RelationshipRiskEncodedSecurityDesc (tag1619.html)
data
.PP
Encoded (non-ASCII characters) representation of the
RelationshipRiskSecurityDesc (1610) field in the encoded format
specified via the MessageEncoding (347) field. If used, the ASCII
(English) representation should also be specified in the
RelationshipRiskSecurityDesc field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RelationshipRiskInstrumentScope (body_50495551.html?find=RelationshipRiskEncodedSecurityDesc)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
