.TH FIX.5.0SP2 "" "" "Tag #1620"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1620 (tag1620.html)
RiskEncodedSecurityDescLen (tag1620.html)
Length
.PP
Byte length of encoded (non-ASCII characters)
RiskEncodedSecurityDesc (1620) field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RiskInstrumentScope (body_50495450.html?find=RiskEncodedSecurityDescLen)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
