.TH FIX.5.0SP2 "" "" "Tag #1621"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
1621 (tag1621.html)
RiskEncodedSecurityDesc (tag1621.html)
data
.PP
Encoded (non-ASCII characters) representation of the
RiskSecurityDesc (1556) field in the encoded format specified via
the MessageEncoding (347) field. If used, the ASCII (English)
representation should also be specified in the RiskSecurityDesc
field.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RiskInstrumentScope (body_50495450.html?find=RiskEncodedSecurityDesc)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
