.TH FIX.5.0SP2 "" "" "Tag #166"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
166 (tag166.html)
SettlLocation (tag166.html)
String
.PP
Identifies Settlement Depository or Country Code, ISITC spec
FIX.4.2
CED
=
.PP
CEDEL
DTC
=
.PP
Depository Trust Company
EUR
=
.PP
Euro clear
FED
=
.PP
Federal Book Entry
ISO_Country_Code
=
.PP
Local Market Settle Location
PNY
=
.PP
Physical
PTC
=
.PP
Participant Trust Company
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
