.TH FIX.5.0SP2 "" "" "Tag #171"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
171 (tag171.html)
StandInstDbID (tag171.html)
\@StandInstDbID
String
.PP
Unique identifier used on the Standing Instructions database for
the Standing Instructions to be referenced.
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructionRequest (body_56496586.html?find=StandInstDbID)]
.PP
   *   *   *   *   *
Used in components:
[SettlInstructionsData (body_49484954.html?find=StandInstDbID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
