.TH FIX.5.0SP2 "" "" "Tag #195"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
195 (tag195.html)
LastForwardPoints (tag195.html)
\@LastFwdPnts
PriceOffset
.PP
F/X forward points added to LastSpotRate (94). May be a negative
value. Expressed in decimal form. For example, 61.99 points is
expressed and sent as 0.006199
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=LastForwardPoints)]
[TradeCaptureReport (body_54526569.html?find=LastForwardPoints)]
[TradeCaptureReportAck (body_55556582.html?find=LastForwardPoints)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
