.TH FIX.5.0SP2 "" "" "Tag #196"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
196 (tag196.html)
AllocLinkID (tag196.html)
\@LinkID
String
.PP
Can be used to link two different Allocation messages (each with
unique AllocID (70)) together, i.e. for F/X "Netting" or "Swaps".
Should be unique.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=AllocLinkID)]
[AllocationInstructionAlert (body_57566677.html?find=AllocLinkID)]
[AllocationReport (body_55566583.html?find=AllocLinkID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
