.TH FIX.5.0SP2 "" "" "Tag #215"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
215 (tag215.html)
NoRoutingIDs (tag215.html)
NumInGroup
.PP
Number of repeating groups of RoutingID (217) and RoutingType (216)
values.
.PP
See Volume 3: "Pre-Trade Message Targeting/Routing"
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RoutingGrp (body_50485352.html?find=NoRoutingIDs)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
