.TH FIX.5.0SP2 "" "" "Tag #218"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
218 (tag218.html)
Spread (tag218.html)
\@Spread
PriceOffset
.PP
For Fixed Income. Either Swap Spread or Spread to Benchmark
depending upon the order type.
.PP
Spread to Benchmark: Basis points relative to a benchmark. To be
expressed as "count of basis points" (vs. an absolute value). E.g.
High Grade Corporate Bonds may express price as basis points
relative to benchmark (the BenchmarkCurveName (22) field). Note:
Basis points can be negative.
.PP
Swap Spread: Target spread for a swap.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SpreadOrBenchmarkCurveData (body_49484956.html?find=Spread)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
