.TH FIX.5.0SP2 "" "" "Tag #222"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
222 (tag222.html)
BenchmarkCurvePoint (tag222.html)
\@Point
String
.PP
Point on benchmark curve. Free form values: e.g. "Y", "7Y",
"INTERPOLATED".
.PP
Sample values:
.PP
M = combination of a number between 1-12 and a "M" for month
.PP
Y = combination of number between 1-100 and a "Y" for year}
.PP
10Y-OLD = see above, then add "-OLD" when appropriate
.PP
INTERPOLATED = the point is mathematically derived
.PP
2/2031 5 3/8 = the point is stated via a combination of maturity
month / year and coupon
.PP
See Fixed Income-specific documentation at
http://www.fixprotocol.org for additional values.
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SpreadOrBenchmarkCurveData (body_49484956.html?find=BenchmarkCurvePoint)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
