.TH FIX.5.0SP2 "" "" "Tag #23"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
23 (tag23.html)
IOIID (tag23.html)
\@IOIID
String
.PP
Unique identifier of IOI message.
.PP
(Prior to FIX 4.1 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=IOIID)]
[IOI (body_5554.html?find=IOIID)]
[MultilegOrderCancelReplace (body_54506567.html?find=IOIID)]
[NewOrderCross (body_5350115.html?find=IOIID)]
[NewOrderMultileg (body_54496566.html?find=IOIID)]
[NewOrderSingle (body_495268.html?find=IOIID)]
[QuoteResponse (body_54576574.html?find=IOIID)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=IOIID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
