.TH FIX.5.0SP2 "" "" "Tag #246"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
246 (tag246.html)
UnderlyingFactor (tag246.html)
\@Fctr
float
.PP
Underlying security\[aq]s Factor.
.PP
See Factor (228) field for description
.PP
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingFactor)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
