.TH FIX.5.0SP2 "" "" "Tag #252"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
252 (tag252.html)
LegRepurchaseRate (tag252.html)
\@RepoRt
Percentage
.PP
Multileg instrument\[aq]s individual leg security\[aq]s
RepurchaseRate. See RepurchaseRate (227) field for description
(Note tag # was reserved in FIX 4.1, added in FIX 4.3)
FIX.4.4
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegRepurchaseRate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
