.TH FIX.5.0SP2 "" "" "Tag #261"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
261 (tag261.html)
Reserved/Allocated to the Fixed Income proposal (tag261.html)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
