.TH FIX.5.0SP2 "" "" "Tag #266"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
266 (tag266.html)
AggregatedBook (tag266.html)
\@AggBook
Boolean
.PP
Specifies whether or not book entries should be aggregated. (Not
specified) = broker option
Y
=
.PP
book entries to be aggregated
N
=
.PP
book entries should not be aggregated
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequest (body_505786.html?find=AggregatedBook)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
