.TH FIX.5.0SP2 "" "" "Tag #269"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
269 (tag269.html)
MDEntryType (tag269.html)
\@Typ
char
.PP
Type Market Data entry.
0
=
.PP
Bid
1
=
.PP
Offer
2
=
.PP
Trade
3
=
.PP
Index Value
4
=
.PP
Opening Price
5
=
.PP
Closing Price
6
=
.PP
Settlement Price
7
=
.PP
Trading Session High Price
8
=
.PP
Trading Session Low Price
9
=
.PP
Trading Session VWAP Price
A
=
.PP
Imbalance
B
=
.PP
Trade Volume
C
=
.PP
Open Interest
D
=
.PP
Composite Underlying Price
E
=
.PP
Simulated Sell Price
F
=
.PP
Simulated Buy Price
G
=
.PP
Margin Rate
H
=
.PP
Mid Price
J
=
.PP
Empty Book
K
=
.PP
Settle High Price
L
=
.PP
Settle Low Price
M
=
.PP
Prior Settle Price
N
=
.PP
Session High Bid
O
=
.PP
Session Low Offer
P
=
.PP
Early Prices
Q
=
.PP
Auction Clearing Price
S
=
.PP
Swap Value Factor (SVP) for swaps cleared through a central
counterparty (CCP)
R
=
.PP
Daily value adjustment for long positions
T
=
.PP
Cumulative Value Adjustment for long positions
U
=
.PP
Daily Value Adjustment for Short Positions
V
=
.PP
Cumulative Value Adjustment for Short Positions
W
=
.PP
Fixing Price
X
=
.PP
Cash Rate
Y
=
.PP
Recovery Rate
Z
=
.PP
Recovery Rate for Long
a
=
.PP
Recovery Rate for Short
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=MDEntryType)]
[MDIncGrp (body_50485150.html?find=MDEntryType)]
[MDReqGrp (body_50485151.html?find=MDEntryType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
