.TH FIX.5.0SP2 "" "" "Tag #274"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
274 (tag274.html)
TickDirection (tag274.html)
\@TickDirctn
char
.PP
Direction of the "tick".
0
=
.PP
Plus Tick
1
=
.PP
Zero-Plus Tick
2
=
.PP
Minus Tick
3
=
.PP
Zero-Minus Tick
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=TickDirection)]
[MDIncGrp (body_50485150.html?find=TickDirection)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
