.TH FIX.5.0SP2 "" "" "Tag #276"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
276 (tag276.html)
QuoteCondition (tag276.html)
\@QCond
MultipleStringValue
.PP
Space-delimited list of conditions describing a quote.
A
=
.PP
Open/Active
B
=
.PP
Closed/Inactive
C
=
.PP
Exchange Best
D
=
.PP
Consolidated Best
E
=
.PP
Locked
F
=
.PP
Crossed
G
=
.PP
Depth
H
=
.PP
Fast Trading
I
=
.PP
Non-Firm
L
=
.PP
Manual/Slow Quote
J
=
.PP
Outright Price
K
=
.PP
Implied Price
M
=
.PP
Depth on Offer
N
=
.PP
Depth on Bid
O
=
.PP
Closing
P
=
.PP
News Dissemination
Q
=
.PP
Trading Range
R
=
.PP
Order Influx
S
=
.PP
Due to Related
T
=
.PP
News Pending
U
=
.PP
Additional Info
V
=
.PP
Additional Info due to related
W
=
.PP
Resume
X
=
.PP
View of Common
Y
=
.PP
Volume Alert
Z
=
.PP
Order Imbalance
a
=
.PP
Equipment Changeover
b
=
.PP
No Open / No Resume
c
=
.PP
Regular ETH
d
=
.PP
Automatic Execution
e
=
.PP
Automatic Execution ETH
f
=
.PP
Fast Market ETH
g
=
.PP
Inactive ETH
h
=
.PP
Rotation
i
=
.PP
Rotation ETH
j
=
.PP
Halt
k
=
.PP
Halt ETH
l
=
.PP
Due to News Dissemination
m
=
.PP
Due to News Pending
n
=
.PP
Trading Resume
o
=
.PP
Out of Sequence
p
=
.PP
Bid Specialist
q
=
.PP
Offer Specialist
r
=
.PP
Bid Offer Specialist
s
=
.PP
End of Day SAM
t
=
.PP
Forbidden SAM
u
=
.PP
Frozen SAM
v
=
.PP
PreOpening SAM
w
=
.PP
Opening SAM
x
=
.PP
Open SAM
y
=
.PP
Surveillance SAM
z
=
.PP
Suspended SAM
0
=
.PP
Reserved SAM
1
=
.PP
No Active SAM
2
=
.PP
Restricted
3
=
.PP
Rest of Book VWAP
4
=
.PP
Better Prices in Conditional Orders
5
=
.PP
Median Price
6
=
.PP
Full Curve
7
=
.PP
Flat Curve
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=QuoteCondition)]
[MDIncGrp (body_50485150.html?find=QuoteCondition)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
