.TH FIX.5.0SP2 "" "" "Tag #298"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
298 (tag298.html)
QuoteCancelType (tag298.html)
\@CxlTyp
int
.PP
Identifies the type of quote cancel.
1
=
.PP
Cancel for one or more securities
2
=
.PP
Cancel for Security Type(s)
3
=
.PP
Cancel for underlying security
4
=
.PP
Cancel All Quotes
5
=
.PP
Cancel quote specified in QuoteID
6
=
.PP
Cancel by QuoteType(537)
7
=
.PP
Cancel for Security Issuer
8
=
.PP
Cancel for Issuer of Underlying Security
.PP
   *   *   *   *   *
Used in messages:
[MassQuoteAcknowledgement (body_515398.html?find=QuoteCancelType)]
[QuoteCancel (body_515190.html?find=QuoteCancelType)]
[QuoteStatusReport (body_54566573.html?find=QuoteCancelType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
