.TH FIX.5.0SP2 "" "" "Tag #302"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
302 (tag302.html)
QuoteSetID (tag302.html)
\@SetID
String
.PP
Unique id for the Quote Set.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[QuotSetAckGrp (body_50485256.html?find=QuoteSetID)]
[QuotSetGrp (body_50485257.html?find=QuoteSetID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
