.TH FIX.5.0SP2 "" "" "Tag #303"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
303 (tag303.html)
QuoteRequestType (tag303.html)
\@ReqTyp
int
.PP
Indicates the type of Quote Request being generated
1
=
.PP
Manual
2
=
.PP
Automatic
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[QuotReqGrp (body_50485253.html?find=QuoteRequestType)]
[QuotReqRjctGrp (body_50485255.html?find=QuoteRequestType)]
[RFQReqGrp (body_50485349.html?find=QuoteRequestType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
