.TH FIX.5.0SP2 "" "" "Tag #315"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
315 (tag315.html)
UnderlyingPutOrCall (tag315.html)
\@PutCall
int
.PP
Put or call indicator of the underlying security.
.PP
See PutOrCall(201).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingPutOrCall)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
