.TH FIX.5.0SP2 "" "" "Tag #320"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
320 (tag320.html)
SecurityReqID (tag320.html)
\@ReqID
String
.PP
Unique ID of a Security Definition Request.
.PP
   *   *   *   *   *
Used in messages:
[DerivativeSecurityList (body_54486565.html?find=SecurityReqID)]
[DerivativeSecurityListRequest (body_5357122.html?find=SecurityReqID)]
[DerivativeSecurityListUpdateReport (body_4948516682.html?find=SecurityReqID)]
[SecurityDefinition (body_5155100.html?find=SecurityReqID)]
[SecurityDefinitionRequest (body_515499.html?find=SecurityReqID)]
[SecurityDefinitionUpdateReport (body_57536680.html?find=SecurityReqID)]
[SecurityList (body_5356121.html?find=SecurityReqID)]
[SecurityListRequest (body_5355120.html?find=SecurityReqID)]
[SecurityListUpdateReport (body_57546675.html?find=SecurityReqID)]
[SecurityTypeRequest (body_5353118.html?find=SecurityReqID)]
[SecurityTypes (body_5354119.html?find=SecurityReqID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
