.TH FIX.5.0SP2 "" "" "Tag #321"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
321 (tag321.html)
SecurityRequestType (tag321.html)
\@ReqTyp
int
.PP
Type of Security Definition Request.
0
=
.PP
Request Security identity and specifications
1
=
.PP
Request Security identity for the specifications provided (name of
the security is not supplied)
2
=
.PP
Request List Security Types
3
=
.PP
Request List Securities (can be qualified with Symbol,
SecurityType, TradingSessionID, SecurityExchange. If provided then
only list Securities for the specific type.)
4
=
.PP
Symbol
5
=
.PP
SecurityType and or CFICode
6
=
.PP
Product
7
=
.PP
TradingSessionID
8
=
.PP
All Securities
9
=
.PP
MarketID or MarketID + MarketSegmentID
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinitionRequest (body_515499.html?find=SecurityRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
