.TH FIX.5.0SP2 "" "" "Tag #323"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
323 (tag323.html)
SecurityResponseType (tag323.html)
\@RspTyp
int
.PP
Type of Security Definition message response.
1
=
.PP
Accept security proposal as-is
2
=
.PP
Accept security proposal with revisions as indicated in the message
3
=
.PP
List of security types returned per request
4
=
.PP
List of securities returned per request
5
=
.PP
Reject security proposal
6
=
.PP
Cannot match selection criteria
.PP
   *   *   *   *   *
Used in messages:
[SecurityDefinition (body_5155100.html?find=SecurityResponseType)]
[SecurityDefinitionUpdateReport (body_57536680.html?find=SecurityResponseType)]
[SecurityTypes (body_5354119.html?find=SecurityResponseType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
