.TH FIX.5.0SP2 "" "" "Tag #326"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
326 (tag326.html)
SecurityTradingStatus (tag326.html)
\@TrdgStat
int
.PP
Identifies the trading status applicable to the transaction.
1
=
.PP
Opening delay
2
=
.PP
Trading halt
3
=
.PP
Resume
4
=
.PP
No Open / No Resume
5
=
.PP
Price indication
6
=
.PP
Trading Range Indication
7
=
.PP
Market Imbalance Buy
8
=
.PP
Market Imbalance Sell
9
=
.PP
Market on Close Imbalance Buy
10
=
.PP
Market on Close Imbalance Sell
11
=
.PP
(not assigned)
12
=
.PP
No Market Imbalance
13
=
.PP
No Market on Close Imbalance
14
=
.PP
ITS Pre-opening
15
=
.PP
New Price Indication
16
=
.PP
Trade Dissemination Time
17
=
.PP
Ready to trade (start of session)
18
=
.PP
Not available for trading (end of session)
19
=
.PP
Not traded on this market
20
=
.PP
Unknown or Invalid
21
=
.PP
Pre-open
22
=
.PP
Opening Rotation
23
=
.PP
Fast Market
24
=
.PP
Pre-Cross - system is in a pre-cross state allowing market to
respond to either side of cross
25
=
.PP
Cross - system has crossed a percentage of the orders and allows
market to respond prior to crossing remaining portion
26
=
.PP
Post-close
.PP
   *   *   *   *   *
Used in messages:
[SecurityStatus (body_5157102.html?find=SecurityTradingStatus)]
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=SecurityTradingStatus)]
[MDIncGrp (body_50485150.html?find=SecurityTradingStatus)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
