.TH FIX.5.0SP2 "" "" "Tag #335"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
335 (tag335.html)
TradSesReqID (tag335.html)
\@ReqID
String
.PP
Unique ID of a Trading Session Status message.
.PP
   *   *   *   *   *
Used in messages:
[TradingSessionList (body_4948486674.html?find=TradSesReqID)]
[TradingSessionListRequest (body_4948496673.html?find=TradSesReqID)]
[TradingSessionListUpdateReport (body_4948526683.html?find=TradSesReqID)]
[TradingSessionStatus (body_5249104.html?find=TradSesReqID)]
[TradingSessionStatusRequest (body_5248103.html?find=TradSesReqID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
