.TH FIX.5.0SP2 "" "" "Tag #340"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
340 (tag340.html)
TradSesStatus (tag340.html)
\@Stat
int
.PP
State of the trading session.
0
=
.PP
Unknown
1
=
.PP
Halted
2
=
.PP
Open
3
=
.PP
Closed
4
=
.PP
Pre-Open
5
=
.PP
Pre-Close
6
=
.PP
Request Rejected
.PP
   *   *   *   *   *
Used in messages:
[TradingSessionStatus (body_5249104.html?find=TradSesStatus)]
.PP
   *   *   *   *   *
Used in components:
[TrdSessLstGrp (body_50485757.html?find=TradSesStatus)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
