.TH FIX.5.0SP2 "" "" "Tag #344"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
344 (tag344.html)
TradSesCloseTime (tag344.html)
\@ClsTm
UTCTimestamp
.PP
Closing time of the trading session
.PP
   *   *   *   *   *
Used in messages:
[TradingSessionStatus (body_5249104.html?find=TradSesCloseTime)]
.PP
   *   *   *   *   *
Used in components:
[TrdSessLstGrp (body_50485757.html?find=TradSesCloseTime)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
