.TH FIX.5.0SP2 "" "" "Tag #357"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
357 (tag357.html)
EncodedSubject (tag357.html)
\@EncSubject
data
.PP
Encoded (non-ASCII characters) representation of the Subject (147)
field in the encoded format specified via the MessageEncoding (347)
field. If used, the ASCII (English) representation should also be
specified in the Subject field.
.PP
   *   *   *   *   *
Used in messages:
[Email (body_495167.html?find=EncodedSubject)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
