.TH FIX.5.0SP2 "" "" "Tag #366"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
366 (tag366.html)
AllocPrice (tag366.html)
\@Px
Price
.PP
Executed price for an AllocAccount (79) entry used when using
"executed price" vs. "average price" allocations (e.g. Japan).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AllocAckGrp (body_50484850.html?find=AllocPrice)]
[AllocGrp (body_50484851.html?find=AllocPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
