.TH FIX.5.0SP2 "" "" "Tag #368"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
368 (tag368.html)
QuoteEntryRejectReason (tag368.html)
\@EntryRejRsn
int
.PP
Reason Quote Entry was rejected:
1
=
.PP
Unknown Symbol (security)
2
=
.PP
Exchange (Security) closed
3
=
.PP
Quote Request exceeds limit
4
=
.PP
Too late to enter
5
=
.PP
Unknown Quote
6
=
.PP
Duplicate Quote
7
=
.PP
Invalid bid/ask spread
8
=
.PP
Invalid price
9
=
.PP
Not authorized to quote security
10
=
.PP
Price exceeds current price band
11
=
.PP
Quote Locked - Unable to Update/Cancel
12
=
.PP
Invalid or unknown Security Issuer
13
=
.PP
Invalid or unknown Issuer of Underlying Security
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=QuoteEntryRejectReason)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
