.TH FIX.5.0SP2 "" "" "Tag #369"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
369 (tag369.html)
LastMsgSeqNumProcessed (tag369.html)
SeqNum
.PP
The last MsgSeqNum (34) value received by the FIX engine and
processed by downstream application, such as trading engine or
order routing system. Can be specified on every message sent.
Useful for detecting a backlog with a counterparty.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=LastMsgSeqNumProcessed)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
