.TH FIX.5.0SP2 "" "" "Tag #372"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
372 (tag372.html)
RefMsgType (tag372.html)
\@RefMsgTyp
String
.PP
The MsgType (35) of the FIX message being referenced.
0
=
.PP
Heartbeat
1
=
.PP
TestRequest
2
=
.PP
ResendRequest
3
=
.PP
Reject
4
=
.PP
SequenceReset
5
=
.PP
Logout
6
=
.PP
IOI
7
=
.PP
Advertisement
8
=
.PP
ExecutionReport
9
=
.PP
OrderCancelReject
A
=
.PP
Logon
AA
=
.PP
DerivativeSecurityList
AB
=
.PP
NewOrderMultileg
AC
=
.PP
MultilegOrderCancelReplace
AD
=
.PP
TradeCaptureReportRequest
AE
=
.PP
TradeCaptureReport
AF
=
.PP
OrderMassStatusRequest
AG
=
.PP
QuoteRequestReject
AH
=
.PP
RFQRequest
AI
=
.PP
QuoteStatusReport
AJ
=
.PP
QuoteResponse
AK
=
.PP
Confirmation
AL
=
.PP
PositionMaintenanceRequest
AM
=
.PP
PositionMaintenanceReport
AN
=
.PP
RequestForPositions
AO
=
.PP
RequestForPositionsAck
AP
=
.PP
PositionReport
AQ
=
.PP
TradeCaptureReportRequestAck
AR
=
.PP
TradeCaptureReportAck
AS
=
.PP
AllocationReport
AT
=
.PP
AllocationReportAck
AU
=
.PP
Confirmation_Ack
AV
=
.PP
SettlementInstructionRequest
AW
=
.PP
AssignmentReport
AX
=
.PP
CollateralRequest
AY
=
.PP
CollateralAssignment
AZ
=
.PP
CollateralResponse
B
=
.PP
News
BA
=
.PP
CollateralReport
BB
=
.PP
CollateralInquiry
BC
=
.PP
NetworkCounterpartySystemStatusRequest
BD
=
.PP
NetworkCounterpartySystemStatusResponse
BE
=
.PP
UserRequest
BF
=
.PP
UserResponse
BG
=
.PP
CollateralInquiryAck
BH
=
.PP
ConfirmationRequest
BI
=
.PP
TradingSessionListRequest
BJ
=
.PP
TradingSessionList
BK
=
.PP
SecurityListUpdateReport
BL
=
.PP
AdjustedPositionReport
BM
=
.PP
AllocationInstructionAlert
BN
=
.PP
ExecutionAcknowledgement
BO
=
.PP
ContraryIntentionReport
BP
=
.PP
SecurityDefinitionUpdateReport
BQ
=
.PP
SettlementObligationReport
BR
=
.PP
DerivativeSecurityListUpdateReport
BS
=
.PP
TradingSessionListUpdateReport
BT
=
.PP
MarketDefinitionRequest
BU
=
.PP
MarketDefinition
BV
=
.PP
MarketDefinitionUpdateReport
BW
=
.PP
ApplicationMessageRequest
BX
=
.PP
ApplicationMessageRequestAck
BY
=
.PP
ApplicationMessageReport
BZ
=
.PP
OrderMassActionReport
C
=
.PP
Email
CA
=
.PP
OrderMassActionRequest
CB
=
.PP
UserNotification
CC
=
.PP
StreamAssignmentRequest
CD
=
.PP
StreamAssignmentReport
CE
=
.PP
StreamAssignmentReportACK
CF
=
.PP
PartyDetailsListRequest
CG
=
.PP
PartyDetailsListReport
D
=
.PP
NewOrderSingle
E
=
.PP
NewOrderList
F
=
.PP
OrderCancelRequest
G
=
.PP
OrderCancelReplaceRequest
H
=
.PP
OrderStatusRequest
J
=
.PP
AllocationInstruction
K
=
.PP
ListCancelRequest
L
=
.PP
ListExecute
M
=
.PP
ListStatusRequest
N
=
.PP
ListStatus
P
=
.PP
AllocationInstructionAck
Q
=
.PP
DontKnowTradeDK
R
=
.PP
QuoteRequest
S
=
.PP
Quote
T
=
.PP
SettlementInstructions
V
=
.PP
MarketDataRequest
W
=
.PP
MarketDataSnapshotFullRefresh
X
=
.PP
MarketDataIncrementalRefresh
Y
=
.PP
MarketDataRequestReject
Z
=
.PP
QuoteCancel
a
=
.PP
QuoteStatusRequest
b
=
.PP
MassQuoteAcknowledgement
c
=
.PP
SecurityDefinitionRequest
d
=
.PP
SecurityDefinition
e
=
.PP
SecurityStatusRequest
f
=
.PP
SecurityStatus
g
=
.PP
TradingSessionStatusRequest
h
=
.PP
TradingSessionStatus
i
=
.PP
MassQuote
j
=
.PP
BusinessMessageReject
k
=
.PP
BidRequest
l
=
.PP
BidResponse
m
=
.PP
ListStrikePrice
n
=
.PP
XML_non_FIX
o
=
.PP
RegistrationInstructions
p
=
.PP
RegistrationInstructionsResponse
q
=
.PP
OrderMassCancelRequest
r
=
.PP
OrderMassCancelReport
s
=
.PP
NewOrderCross
t
=
.PP
CrossOrderCancelReplaceRequest
u
=
.PP
CrossOrderCancelRequest
v
=
.PP
SecurityTypeRequest
w
=
.PP
SecurityTypes
x
=
.PP
SecurityListRequest
y
=
.PP
SecurityList
z
=
.PP
DerivativeSecurityListRequest
.PP
   *   *   *   *   *
Used in messages:
[BusinessMessageReject (body_5251106.html?find=RefMsgType)]
[Reject (body_5251.html?find=RefMsgType)]
.PP
   *   *   *   *   *
Used in components:
[MsgTypeGrp (body_50485756.html?find=RefMsgType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
