.TH FIX.5.0SP2 "" "" "Tag #376"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
376 (tag376.html)
ComplianceID (tag376.html)
\@ComplianceID
String
.PP
ID used to represent this transaction for compliance purposes (e.g.
OATS reporting).
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=ComplianceID)]
[ExecutionReport (body_5756.html?find=ComplianceID)]
[MultilegOrderCancelReplace (body_54506567.html?find=ComplianceID)]
[NewOrderCross (body_5350115.html?find=ComplianceID)]
[NewOrderMultileg (body_54496566.html?find=ComplianceID)]
[NewOrderSingle (body_495268.html?find=ComplianceID)]
[OrderCancelReplaceRequest (body_495571.html?find=ComplianceID)]
[OrderCancelRequest (body_495470.html?find=ComplianceID)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=ComplianceID)]
[SideCrossOrdCxlGrp (body_50485356.html?find=ComplianceID)]
[TrdCapRptAckSideGrp (body_50485752.html?find=ComplianceID)]
[TrdCapRptSideGrp (body_50485449.html?find=ComplianceID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
