.TH FIX.5.0SP2 "" "" "Tag #381"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
381 (tag381.html)
GrossTradeAmt (tag381.html)
\@GrossTrdAmt
Amt
.PP
Total amount traded (i.e. quantity * price) expressed in units of
currency. For FX Futures this is used to express the notional value
of a fill when quantity fields are expressed in terms of contract
size (i.e. quantity * price * contract size).
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=GrossTradeAmt)]
[AllocationInstructionAlert (body_57566677.html?find=GrossTradeAmt)]
[AllocationReport (body_55566583.html?find=GrossTradeAmt)]
[Confirmation (body_55486575.html?find=GrossTradeAmt)]
[ExecutionReport (body_5756.html?find=GrossTradeAmt)]
[TradeCaptureReport (body_54526569.html?find=GrossTradeAmt)]
[TradeCaptureReportAck (body_55556582.html?find=GrossTradeAmt)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
