.TH FIX.5.0SP2 "" "" "Tag #384"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
384 (tag384.html)
NoMsgTypes (tag384.html)
NumInGroup
.PP
Number of MsgTypes (35) in repeating group.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[MsgTypeGrp (body_50485756.html?find=NoMsgTypes)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
