.TH FIX.5.0SP2 "" "" "Tag #386"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
386 (tag386.html)
NoTradingSessions (tag386.html)
NumInGroup
.PP
Number of TradingSessionIDs (336) in repeating group.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdSessLstGrp (body_50485757.html?find=NoTradingSessions)]
[TrdgSesGrp (body_50485452.html?find=NoTradingSessions)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
