.TH FIX.5.0SP2 "" "" "Tag #390"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
390 (tag390.html)
BidID (tag390.html)
\@BidID
String
.PP
Unique identifier for Bid Response as assigned by sell-side
(broker, exchange, ECN). Uniqueness must be guaranteed within a
single trading day.
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=BidID)]
[BidResponse (body_5253108.html?find=BidID)]
[ListExecute (body_504976.html?find=BidID)]
[NewOrderList (body_495369.html?find=BidID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
