.TH FIX.5.0SP2 "" "" "Tag #400"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
400 (tag400.html)
BidDescriptor (tag400.html)
\@BidDescptr
String
.PP
BidDescriptor value. Usage depends upon BidDescriptorTyp (399).
.PP
If BidDescriptorType = 1
.PP
Industrials etc - Free text
.PP
If BidDescriptorType = 2
.PP
"FR" etc - ISO Country Codes
.PP
If BidDescriptorType = 3
.PP
FT00, FT250, STOX - Free text
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[BidDescReqGrp (body_50484854.html?find=BidDescriptor)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
