.TH FIX.5.0SP2 "" "" "Tag #414"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
414 (tag414.html)
ProgRptReqs (tag414.html)
\@ProgRptReqs
int
.PP
Code to identify the desired frequency of progress reports.
1
=
.PP
Buy-side explicitly requests status using Statue Request (default),
the sell-side firm can, however, send a DONE status List STatus
Response in an unsolicited fashion
2
=
.PP
Sell-side periodically sends status using List Status. Period
optionally specified in ProgressPeriod.
3
=
.PP
Real-time execution reports (to be discourage)
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=ProgRptReqs)]
[NewOrderList (body_495369.html?find=ProgRptReqs)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
