.TH FIX.5.0SP2 "" "" "Tag #421"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
421 (tag421.html)
Country (tag421.html)
\@Ctry
Country
.PP
ISO Country Code in field
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[BidCompRspGrp (body_50484853.html?find=Country)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
