.TH FIX.5.0SP2 "" "" "Tag #437"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
437 (tag437.html)
ContraTradeQty (tag437.html)
\@CntraTrdQty
Qty
.PP
Quantity traded with the ContraBroker (375).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ContraGrp (body_50484950.html?find=ContraTradeQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
