.TH FIX.5.0SP2 "" "" "Tag #443"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
443 (tag443.html)
StrikeTime (tag443.html)
\@StrkTm
UTCTimestamp
.PP
The time at which current market prices are used to determine the
value of a basket.
.PP
   *   *   *   *   *
Used in messages:
[BidRequest (body_5252107.html?find=StrikeTime)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
