.TH FIX.5.0SP2 "" "" "Tag #459"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
459 (tag459.html)
UnderlyingSecurityAltIDSource (tag459.html)
\@AltIDSrc
String
.PP
Identifies class or source of the UnderlyingSecurityAltID (458)
value. Required if UnderlyingSecurityAltID is specified.
.PP
Valid values:
.PP
Same
1
=
.PP
CUSIP
2
=
.PP
SEDOL
3
=
.PP
QUIK
4
=
.PP
ISIN number
5
=
.PP
RIC code
6
=
.PP
ISO Currency Code
7
=
.PP
ISO Country Code
8
=
.PP
Exchange Symbol
9
=
.PP
Consolidated Tape Association (CTA) Symbol (SIAC CTS/CQS line
format)
A
=
.PP
Bloomberg Symbol
B
=
.PP
Wertpapier
C
=
.PP
Dutch
D
=
.PP
Valoren
E
=
.PP
Sicovam
F
=
.PP
Belgian
G
=
.PP
"Common" (Clearstream and Euroclear)
H
=
.PP
Clearing House / Clearing Organization
I
=
.PP
ISDA/FpML Product Specification (XML in EncodedSecurityDesc)
J
=
.PP
Option Price Reporting Authority
K
=
.PP
ISDA/FpML Product URL (URL in SecurityID)
L
=
.PP
Letter of Credit
M
=
.PP
Marketplace-assigned Identifier
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UndSecAltIDGrp (body_50485551.html?find=UnderlyingSecurityAltIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
