.TH FIX.5.0SP2 "" "" "Tag #464"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
464 (tag464.html)
TestMessageIndicator (tag464.html)
Boolean
.PP
Indicates whether or not this FIX Session is a "test" vs.
"production" connection. Useful for preventing "accidents".
N
=
.PP
Fales (Production)
Y
=
.PP
True (Test)
.PP
   *   *   *   *   *
Used in messages:
[Logon (body_494965.html?find=TestMessageIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
