.TH FIX.5.0SP2 "" "" "Tag #474"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
474 (tag474.html)
MailingDtls (tag474.html)
\@MailingDtls
String
.PP
Set of Correspondence address details, possibly including phone,
fax, etc.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RgstDtlsGrp (body_50485351.html?find=MailingDtls)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
