.TH FIX.5.0SP2 "" "" "Tag #477"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
477 (tag477.html)
DistribPaymentMethod (tag477.html)
\@DistribPmtMethod
int
.PP
A code identifying the payment method for a (fractional)
distribution.
.PP
13 through 998 are reserved for future use
.PP
Values above 1000 are available for use by private agreement among
counterparties
1
=
.PP
CREST
2
=
.PP
NSCC
3
=
.PP
Euroclear
4
=
.PP
Clearstream
5
=
.PP
Cheque
6
=
.PP
Telegraphic Transfer
7
=
.PP
Fed Wire
8
=
.PP
Direct Credit (BECS, BACS)
9
=
.PP
ACH Credit
10
=
.PP
BPAY
11
=
.PP
High Value Clearing System HVACS
12
=
.PP
Reinvest In Fund
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RgstDistInstGrp (body_50485350.html?find=DistribPaymentMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
