.TH FIX.5.0SP2 "" "" "Tag #48"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
48 (tag48.html)
SecurityID (tag48.html)
\@ID
String
.PP
Security identifier value of SecurityIDSource (22) type (e.g.
CUSIP, SEDOL, ISIN, etc). Requires SecurityIDSource.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=SecurityID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
