.TH FIX.5.0SP2 "" "" "Tag #489"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
489 (tag489.html)
CardNumber (tag489.html)
\@CardNum
String
.PP
The number of the payment card as specified on the card being used
for payment.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[SettlInstGrp (body_50485355.html?find=CardNumber)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
