.TH FIX.5.0SP2 "" "" "Tag #513"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
513 (tag513.html)
RegistID (tag513.html)
\@RegistID
String
.PP
Unique identifier of the registration details as assigned by
institution or intermediary.
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=RegistID)]
[ExecutionReport (body_5756.html?find=RegistID)]
[MultilegOrderCancelReplace (body_54506567.html?find=RegistID)]
[NewOrderCross (body_5350115.html?find=RegistID)]
[NewOrderList (body_495369.html?find=RegistID)]
[NewOrderMultileg (body_54496566.html?find=RegistID)]
[NewOrderSingle (body_495268.html?find=RegistID)]
[OrderCancelReplaceRequest (body_495571.html?find=RegistID)]
[RegistrationInstructions (body_5256111.html?find=RegistID)]
[RegistrationInstructionsResponse (body_5257112.html?find=RegistID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
