.TH FIX.5.0SP2 "" "" "Tag #515"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
515 (tag515.html)
ExecValuationPoint (tag515.html)
\@ExecValuationPoint
UTCTimestamp
.PP
For CIV - a date and time stamp to indicate the fund valuation
point with respect to which a order was priced by the fund manager.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ExecValuationPoint)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
