.TH FIX.5.0SP2 "" "" "Tag #516"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
516 (tag516.html)
OrderPercent (tag516.html)
\@Pct
Percentage
.PP
For CIV specifies the approximate order quantity desired. For a CIV
Sale it specifies percentage of investor\[aq]s total holding to be
sold. For a CIV switch/exchange it specifies percentage of
investor\[aq]s cash realised from sales to be re-invested. The
executing broker, intermediary or fund manager is responsible for
converting and calculating OrderQty (38) in shares/units for
subsequent messages.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[OrderQtyData (body_49484949.html?find=OrderPercent)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
