.TH FIX.5.0SP2 "" "" "Tag #517"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
517 (tag517.html)
OwnershipType (tag517.html)
\@OwnershipTyp
char
.PP
The relationship between Registration parties.
J
=
.PP
Joint Investors
T
=
.PP
Tenants in Common
2
=
.PP
Joint Trustees
.PP
   *   *   *   *   *
Used in messages:
[RegistrationInstructions (body_5256111.html?find=OwnershipType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
