.TH FIX.5.0SP2 "" "" "Tag #520"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
520 (tag520.html)
ContAmtValue (tag520.html)
\@ContAmtValu
float
.PP
Value of Contract Amount, e.g. a financial amount or percentage as
indicated by ContAmtType (519).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ContAmtGrp (body_50484949.html?find=ContAmtValue)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
