.TH FIX.5.0SP2 "" "" "Tag #522"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
522 (tag522.html)
OwnerType (tag522.html)
\@OwnerTyp
int
.PP
Identifies the type of owner.
1
=
.PP
Individual Investor
2
=
.PP
Public Company
3
=
.PP
Private Company
4
=
.PP
Individual Trustee
5
=
.PP
Company Trustee
6
=
.PP
Pension Plan
7
=
.PP
Custodian Under Gifts to Minors Act
8
=
.PP
Trusts
9
=
.PP
Fiduciaries
10
=
.PP
Networking Sub-account
11
=
.PP
Non-profit organization
12
=
.PP
Corporate Body
13
=
.PP
Nominee
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[RgstDtlsGrp (body_50485351.html?find=OwnerType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
