.TH FIX.5.0SP2 "" "" "Tag #534"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
534 (tag534.html)
NoAffectedOrders (tag534.html)
\@NoAffctdOrds
NumInGroup
.PP
Number of affected orders in the repeating group of order ids.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AffectedOrdGrp (body_50484849.html?find=NoAffectedOrders)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
