.TH FIX.5.0SP2 "" "" "Tag #559"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
559 (tag559.html)
SecurityListRequestType (tag559.html)
\@ListReqTyp
int
.PP
Identifies the type/criteria of Security List Request
0
=
.PP
Symbol
1
=
.PP
SecurityType and/or CFICode
2
=
.PP
Product
3
=
.PP
TradingSessionID
4
=
.PP
All Securities
5
=
.PP
MarketID or MarketID + MarketSegmentID
.PP
   *   *   *   *   *
Used in messages:
[DerivativeSecurityListRequest (body_5357122.html?find=SecurityListRequestType)]
[SecurityListRequest (body_5355120.html?find=SecurityListRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
