.TH FIX.5.0SP2 "" "" "Tag #560"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
560 (tag560.html)
SecurityRequestResult (tag560.html)
\@ReqRslt
int
.PP
The results returned to a Security Request message
0
=
.PP
Valid request
1
=
.PP
Invalid or unsupported request
2
=
.PP
No instruments found that match selection criteria
3
=
.PP
Not authorized to retrieve instrument data
4
=
.PP
Instrument data temporarily unavailable
5
=
.PP
Request for instrument data not supported
.PP
   *   *   *   *   *
Used in messages:
[DerivativeSecurityList (body_54486565.html?find=SecurityRequestResult)]
[DerivativeSecurityListUpdateReport (body_4948516682.html?find=SecurityRequestResult)]
[SecurityList (body_5356121.html?find=SecurityRequestResult)]
[SecurityListUpdateReport (body_57546675.html?find=SecurityRequestResult)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
