.TH FIX.5.0SP2 "" "" "Tag #568"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
568 (tag568.html)
TradeRequestID (tag568.html)
\@ReqID
String
.PP
Trade Capture Report Request ID
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TradeRequestID)]
[TradeCaptureReportRequest (body_54516568.html?find=TradeRequestID)]
[TradeCaptureReportRequestAck (body_55546581.html?find=TradeRequestID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
