.TH FIX.5.0SP2 "" "" "Tag #573"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
573 (tag573.html)
MatchStatus (tag573.html)
\@MtchStat
char
.PP
The status of this trade with respect to matching or comparison.
0
=
.PP
Compared, matched or affirmed
1
=
.PP
Uncompared, unmatched, or unaffirmed
2
=
.PP
Advisory or alert
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstructionAck (body_505280.html?find=MatchStatus)]
[AllocationReportAck (body_55576584.html?find=MatchStatus)]
[Confirmation_Ack (body_56486585.html?find=MatchStatus)]
[PositionReport (body_55536580.html?find=MatchStatus)]
[RequestForPositions (body_55516578.html?find=MatchStatus)]
[RequestForPositionsAck (body_55526579.html?find=MatchStatus)]
[TradeCaptureReport (body_54526569.html?find=MatchStatus)]
[TradeCaptureReportAck (body_55556582.html?find=MatchStatus)]
[TradeCaptureReportRequest (body_54516568.html?find=MatchStatus)]
.PP
   *   *   *   *   *
Used in components:
[AllocGrp (body_50484851.html?find=MatchStatus)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
