.TH FIX.5.0SP2 "" "" "Tag #577"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
577 (tag577.html)
ClearingInstruction (tag577.html)
\@ClrngInstrctn
int
.PP
Eligibility of this trade for clearing and central counterparty
processing
.PP
values above 4000 are reserved for agreement between parties
0
=
.PP
Process normally
1
=
.PP
Exclude from all netting
2
=
.PP
Bilateral netting only
3
=
.PP
Ex clearing
4
=
.PP
Special trade
5
=
.PP
Multilateral netting
6
=
.PP
Clear against central counterparty
7
=
.PP
Exclude from central counterparty
8
=
.PP
Manual mode (pre-posting and/or pre-giveup)
9
=
.PP
Automatic posting mode (trade posting to the position account
number specified)
10
=
.PP
Automatic give-up mode (trade give-up to the give-up destination
number specified)
11
=
.PP
Qualified Service Representative QSR
12
=
.PP
Customer trade
13
=
.PP
Self clearing
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[ClrInstGrp (body_50484855.html?find=ClearingInstruction)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
