.TH FIX.5.0SP2 "" "" "Tag #578"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
578 (tag578.html)
TradeInputSource (tag578.html)
\@InptSrc
String
.PP
Type of input device or system from which the trade was entered.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=TradeInputSource)]
[AllocationInstructionAlert (body_57566677.html?find=TradeInputSource)]
[AllocationReport (body_55566583.html?find=TradeInputSource)]
[TradeCaptureReportRequest (body_54516568.html?find=TradeInputSource)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=TradeInputSource)]
[TrdCapRptSideGrp (body_50485449.html?find=TradeInputSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
