.TH FIX.5.0SP2 "" "" "Tag #583"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
583 (tag583.html)
ClOrdLinkID (tag583.html)
\@ClOrdLinkID
String
.PP
Permits order originators to tie together groups of orders in which
trades resulting from orders are associated for a specific purpose,
for example the calculation of average execution price for a
customer or to associate lists submitted to a broker as waves of a
larger program trade.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=ClOrdLinkID)]
[MultilegOrderCancelReplace (body_54506567.html?find=ClOrdLinkID)]
[NewOrderMultileg (body_54496566.html?find=ClOrdLinkID)]
[NewOrderSingle (body_495268.html?find=ClOrdLinkID)]
[OrderCancelReject (body_494857.html?find=ClOrdLinkID)]
[OrderCancelReplaceRequest (body_495571.html?find=ClOrdLinkID)]
[OrderCancelRequest (body_495470.html?find=ClOrdLinkID)]
[OrderStatusRequest (body_495672.html?find=ClOrdLinkID)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=ClOrdLinkID)]
[SideCrossOrdCxlGrp (body_50485356.html?find=ClOrdLinkID)]
[SideCrossOrdModGrp (body_50485357.html?find=ClOrdLinkID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
