.TH FIX.5.0SP2 "" "" "Tag #585"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
585 (tag585.html)
MassStatusReqType (tag585.html)
\@MassStatReqTyp
int
.PP
Mass Status Request Type
1
=
.PP
Status for orders for a Security
2
=
.PP
Status for orders for an Underlying Security
3
=
.PP
Status for orders for a Product
4
=
.PP
Status for orders for a CFICode
5
=
.PP
Status for orders for a SecurityType
6
=
.PP
Status for orders for a trading session
7
=
.PP
Status for all orders
8
=
.PP
Status for orders for a PartyID
9
=
.PP
Status for Security Issuer
10
=
.PP
Status for Issuer of Underlying Security
.PP
   *   *   *   *   *
Used in messages:
[OrderMassStatusRequest (body_54536570.html?find=MassStatusReqType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
