.TH FIX.5.0SP2 "" "" "Tag #588"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
588 (tag588.html)
LegSettlDate (tag588.html)
\@SettlDt
LocalMktDate
.PP
Refer to description for SettlDate[64]
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegSettlDate)]
[LegOrdGrp (body_50485053.html?find=LegSettlDate)]
[LegQuotGrp (body_50485055.html?find=LegSettlDate)]
[LegQuotStatGrp (body_50485056.html?find=LegSettlDate)]
[QuotReqLegsGrp (body_50485254.html?find=LegSettlDate)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegSettlDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
