.TH FIX.5.0SP2 "" "" "Tag #591"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
591 (tag591.html)
PreallocMethod (tag591.html)
\@PreallocMeth
char
.PP
Indicates the method of preallocation.
0
=
.PP
Pro-rata
1
=
.PP
Do not pro-rata - discuss first
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=PreallocMethod)]
[MultilegOrderCancelReplace (body_54506567.html?find=PreallocMethod)]
[NewOrderMultileg (body_54496566.html?find=PreallocMethod)]
[NewOrderSingle (body_495268.html?find=PreallocMethod)]
[OrderCancelReplaceRequest (body_495571.html?find=PreallocMethod)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=PreallocMethod)]
[SideCrossOrdModGrp (body_50485357.html?find=PreallocMethod)]
[TrdCapRptAckSideGrp (body_50485752.html?find=PreallocMethod)]
[TrdCapRptSideGrp (body_50485449.html?find=PreallocMethod)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
