.TH FIX.5.0SP2 "" "" "Tag #601"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
601 (tag601.html)
LegSymbolSfx (tag601.html)
\@Sfx
String
.PP
Multileg instrument\[aq]s individual security\[aq]s SymbolSfx.
.PP
See SymbolSfx (65) field for description
—\ For Fixed Income\ —
CD
=
.PP
EUCP with lump-sum interest rather than discount price
WI
=
.PP
"When Issued" for a security to be reissued under an old CUSIP or
ISIN
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegSymbolSfx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
