.TH FIX.5.0SP2 "" "" "Tag #602"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
602 (tag602.html)
LegSecurityID (tag602.html)
\@ID
String
.PP
Multileg instrument\[aq]s individual security\[aq]s SecurityID.
.PP
See SecurityID (48) field for description
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegSecurityID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
