.TH FIX.5.0SP2 "" "" "Tag #609"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
609 (tag609.html)
LegSecurityType (tag609.html)
\@SecTyp
String
.PP
Refer to definition of SecurityType(167)
UST
=
.PP
US Treasury Note (Deprecated Value Use TNOTE)
USTB
=
.PP
US Treasury Bill (Deprecated Value Use TBILL)
—\ Agency\ —
EUSUPRA
=
.PP
Euro Supranational Coupons *
FAC
=
.PP
Federal Agency Coupon
FADN
=
.PP
Federal Agency Discount Note
PEF
=
.PP
Private Export Funding *
SUPRA
=
.PP
USD Supranational Coupons *
—\ Corporate\ —
CORP
=
.PP
Corporate Bond
CPP
=
.PP
Corporate Private Placement
CB
=
.PP
Convertible Bond
DUAL
=
.PP
Dual Currency
EUCORP
=
.PP
Euro Corporate Bond
EUFRN
=
.PP
Euro Corporate Floating Rate Notes
FRN
=
.PP
US Corporate Floating Rate Notes
XLINKD
=
.PP
Indexed Linked
STRUCT
=
.PP
Structured Notes
YANK
=
.PP
Yankee Corporate Bond
—\ Currency\ —
FOR
=
.PP
Foreign Exchange Contract
FXNDF
=
.PP
Non-deliverable forward
FXSPOT
=
.PP
FX Spot
FXFWD
=
.PP
FX Forward
FXSWAP
=
.PP
FX Swap
—\ Derivatives\ —
CDS
=
.PP
Credit Default Swap
FUT
=
.PP
Future
OPT
=
.PP
Option
OOF
=
.PP
Options on Futures
OOP
=
.PP
Options on Physical - use not recommended
IRS
=
.PP
Interest Rate Swap
OOC
=
.PP
Options on Combo
—\ Equity\ —
CS
=
.PP
Common Stock
PS
=
.PP
Preferred Stock
—\ Financing\ —
REPO
=
.PP
Repurchase
FORWARD
=
.PP
Forward
BUYSELL
=
.PP
Buy Sellback
SECLOAN
=
.PP
Securities Loan
SECPLEDGE
=
.PP
Securities Pledge
—\ Government\ —
BRADY
=
.PP
Brady Bond
CAN
=
.PP
Canadian Treasury Notes
CTB
=
.PP
Canadian Treasury Bills
EUSOV
=
.PP
Euro Sovereigns *
PROV
=
.PP
Canadian Provincial Bonds
TB
=
.PP
Treasury Bill - non US
TBOND
=
.PP
US Treasury Bond
TINT
=
.PP
Interest Strip From Any Bond Or Note
TBILL
=
.PP
US Treasury Bill
TIPS
=
.PP
Treasury Inflation Protected Securities
TCAL
=
.PP
Principal Strip Of A Callable Bond Or Note
TPRN
=
.PP
Principal Strip From A Non-Callable Bond Or Note
TNOTE
=
.PP
US Treasury Note
—\ Loan\ —
TERM
=
.PP
Term Loan
RVLV
=
.PP
Revolver Loan
RVLVTRM
=
.PP
Revolver/Term Loan
BRIDGE
=
.PP
Bridge Loan
LOFC
=
.PP
Letter Of Credit
SWING
=
.PP
Swing Line Facility
DINP
=
.PP
Debtor In Possession
DEFLTED
=
.PP
Defaulted
WITHDRN
=
.PP
Withdrawn
REPLACD
=
.PP
Replaced
MATURED
=
.PP
Matured
AMENDED
=
.PP
Amended & Restated
RETIRED
=
.PP
Retired
—\ Money Market\ —
BA
=
.PP
Bankers Acceptance
BDN
=
.PP
Bank Depository Note
BN
=
.PP
Bank Notes
BOX
=
.PP
Bill Of Exchanges
CAMM
=
.PP
Canadian Money Markets
CD
=
.PP
Certificate Of Deposit
CL
=
.PP
Call Loans
CP
=
.PP
Commercial Paper
DN
=
.PP
Deposit Notes
EUCD
=
.PP
Euro Certificate Of Deposit
EUCP
=
.PP
Euro Commercial Paper
LQN
=
.PP
Liquidity Note
MTN
=
.PP
Medium Term Notes
ONITE
=
.PP
Overnight
PN
=
.PP
Promissory Note
STN
=
.PP
Short Term Loan Note
PZFJ
=
.PP
Plazos Fijos
SLQN
=
.PP
Secured Liquidity Note
TD
=
.PP
Time Deposit
TLQN
=
.PP
Term Liquidity Note
XCN
=
.PP
Extended Comm Note
YCD
=
.PP
Yankee Certificate Of Deposit
—\ Mortgage\ —
ABS
=
.PP
Asset-backed Securities
CMB
=
.PP
Canadian Mortgage Bonds
CMBS
=
.PP
Corp. Mortgage-backed Securities
CMO
=
.PP
Collateralized Mortgage Obligation
IET
=
.PP
IOETTE Mortgage
MBS
=
.PP
Mortgage-backed Securities
MIO
=
.PP
Mortgage Interest Only
MPO
=
.PP
Mortgage Principal Only
MPP
=
.PP
Mortgage Private Placement
MPT
=
.PP
Miscellaneous Pass-through
PFAND
=
.PP
Pfandbriefe *
TBA
=
.PP
To Be Announced
—\ Municipal\ —
AN
=
.PP
Other Anticipation Notes (BAN, GAN, etc.)
COFO
=
.PP
Certificate Of Obligation
COFP
=
.PP
Certificate Of Participation
GO
=
.PP
General Obligation Bonds
MT
=
.PP
Mandatory Tender
RAN
=
.PP
Revenue Anticipation Note
REV
=
.PP
Revenue Bonds
SPCLA
=
.PP
Special Assessment
SPCLO
=
.PP
Special Obligation
SPCLT
=
.PP
Special Tax
TAN
=
.PP
Tax Anticipation Note
TAXA
=
.PP
Tax Allocation
TECP
=
.PP
Tax Exempt Commercial Paper
TMCP
=
.PP
Taxable Municipal CP
TRAN
=
.PP
Tax Revenue Anticipation Note
VRDN
=
.PP
Variable Rate Demand Note
WAR
=
.PP
Warrant
—\ Other\ —
MF
=
.PP
Mutual Fund
MLEG
=
.PP
Multileg Instrument
NONE
=
.PP
No Security Type
?
=
.PP
Wildcard entry for use on Security Definition Request
CASH
=
.PP
Cash
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentLeg (body_49484853.html?find=LegSecurityType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
