.TH FIX.5.0SP2 "" "" "Tag #634"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
634 (tag634.html)
OfferYield (tag634.html)
\@OfrYld
Percentage
.PP
Offer yield
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=OfferYield)]
[QuoteResponse (body_54576574.html?find=OfferYield)]
[QuoteStatusReport (body_54566573.html?find=OfferYield)]
.PP
   *   *   *   *   *
Used in components:
[QuotEntryAckGrp (body_50485250.html?find=OfferYield)]
[QuotEntryGrp (body_50485251.html?find=OfferYield)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
