.TH FIX.5.0SP2 "" "" "Tag #637"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
637 (tag637.html)
LegLastPx (tag637.html)
\@LastPx
Price
.PP
Execution price assigned to a leg of a multileg instrument.
.PP
See LastPx (31) field for description and values
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegLastPx)]
[TrdInstrmtLegGrp (body_50485451.html?find=LegLastPx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
