.TH FIX.5.0SP2 "" "" "Tag #64"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
64 (tag64.html)
SettlDate (tag64.html)
\@SettlDt
LocalMktDate
.PP
Specific date of trade settlement (SettlementDate) in YYYYMMDD
format.
.PP
If present, this field overrides SettlType (63). This field is
required if the value of SettlType (63) is 6 (Future) or 8 (Sellers
Option). This field must be omitted if the value of SettlType (63)
is 7 (When and If Issued)
.PP
(expressed in local time at place of settlement)
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=SettlDate)]
[AllocationInstructionAlert (body_57566677.html?find=SettlDate)]
[AllocationReport (body_55566583.html?find=SettlDate)]
[CollateralAssignment (body_56526589.html?find=SettlDate)]
[CollateralInquiry (body_56556666.html?find=SettlDate)]
[CollateralInquiryAck (body_57506671.html?find=SettlDate)]
[CollateralReport (body_56546665.html?find=SettlDate)]
[CollateralRequest (body_56516588.html?find=SettlDate)]
[CollateralResponse (body_56536590.html?find=SettlDate)]
[Confirmation (body_55486575.html?find=SettlDate)]
[CrossOrderCancelReplaceRequest (body_5351116.html?find=SettlDate)]
[ExecutionReport (body_5756.html?find=SettlDate)]
[MultilegOrderCancelReplace (body_54506567.html?find=SettlDate)]
[NewOrderCross (body_5350115.html?find=SettlDate)]
[NewOrderMultileg (body_54496566.html?find=SettlDate)]
[NewOrderSingle (body_495268.html?find=SettlDate)]
[OrderCancelReplaceRequest (body_495571.html?find=SettlDate)]
[Quote (body_505583.html?find=SettlDate)]
[QuoteResponse (body_54576574.html?find=SettlDate)]
[QuoteStatusReport (body_54566573.html?find=SettlDate)]
[TradeCaptureReport (body_54526569.html?find=SettlDate)]
[TradeCaptureReportAck (body_55556582.html?find=SettlDate)]
.PP
   *   *   *   *   *
Used in components:
[BidCompReqGrp (body_50484852.html?find=SettlDate)]
[BidCompRspGrp (body_50484853.html?find=SettlDate)]
[InstrmtMDReqGrp (body_50485050.html?find=SettlDate)]
[ListOrdGrp (body_50485148.html?find=SettlDate)]
[MDFullGrp (body_50485149.html?find=SettlDate)]
[MDIncGrp (body_50485150.html?find=SettlDate)]
[QuotEntryAckGrp (body_50485250.html?find=SettlDate)]
[QuotEntryGrp (body_50485251.html?find=SettlDate)]
[QuotReqGrp (body_50485253.html?find=SettlDate)]
[QuotReqRjctGrp (body_50485255.html?find=SettlDate)]
[SettlObligationInstructions (body_50494849.html?find=SettlDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
