.TH FIX.5.0SP2 "" "" "Tag #646"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
646 (tag646.html)
MktOfferPx (tag646.html)
\@MktOfrPx
Price
.PP
Used to indicate the best offer in a market
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=MktOfferPx)]
[QuoteResponse (body_54576574.html?find=MktOfferPx)]
[QuoteStatusReport (body_54566573.html?find=MktOfferPx)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
