.TH FIX.5.0SP2 "" "" "Tag #648"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
648 (tag648.html)
MinOfferSize (tag648.html)
\@MinOfrSz
Qty
.PP
Used to indicate a minimum quantity for an offer. If this field is
used the OfferSize (135) field is interpreted as the maximum offer
size.
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=MinOfferSize)]
[QuoteResponse (body_54576574.html?find=MinOfferSize)]
[QuoteStatusReport (body_54566573.html?find=MinOfferSize)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
