.TH FIX.5.0SP2 "" "" "Tag #660"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
660 (tag660.html)
AcctIDSource (tag660.html)
\@AcctIDSrc
int
.PP
Used to identify the source of the Account (1) code. This is
especially useful if the account is a new account that the
Respondent may not have setup yet in their system.
1
=
.PP
BIC
2
=
.PP
SID Code
3
=
.PP
TFM (GSPTA)
4
=
.PP
OMGEO (Alert ID)
5
=
.PP
DTCC Code
99
=
.PP
Other (custom or proprietary)
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=AcctIDSource)]
[MassQuote (body_5250105.html?find=AcctIDSource)]
[MassQuoteAcknowledgement (body_515398.html?find=AcctIDSource)]
[MultilegOrderCancelReplace (body_54506567.html?find=AcctIDSource)]
[NewOrderMultileg (body_54496566.html?find=AcctIDSource)]
[NewOrderSingle (body_495268.html?find=AcctIDSource)]
[OrderCancelReject (body_494857.html?find=AcctIDSource)]
[OrderCancelReplaceRequest (body_495571.html?find=AcctIDSource)]
[OrderCancelRequest (body_495470.html?find=AcctIDSource)]
[OrderMassStatusRequest (body_54536570.html?find=AcctIDSource)]
[OrderStatusRequest (body_495672.html?find=AcctIDSource)]
[PositionMaintenanceReport (body_55506577.html?find=AcctIDSource)]
[PositionMaintenanceRequest (body_55496576.html?find=AcctIDSource)]
[PositionReport (body_55536580.html?find=AcctIDSource)]
[Quote (body_505583.html?find=AcctIDSource)]
[QuoteCancel (body_515190.html?find=AcctIDSource)]
[QuoteResponse (body_54576574.html?find=AcctIDSource)]
[QuoteStatusReport (body_54566573.html?find=AcctIDSource)]
[QuoteStatusRequest (body_515297.html?find=AcctIDSource)]
[RegistrationInstructions (body_5256111.html?find=AcctIDSource)]
[RegistrationInstructionsResponse (body_5257112.html?find=AcctIDSource)]
[RequestForPositions (body_55516578.html?find=AcctIDSource)]
[RequestForPositionsAck (body_55526579.html?find=AcctIDSource)]
.PP
   *   *   *   *   *
Used in components:
[BidCompReqGrp (body_50484852.html?find=AcctIDSource)]
[ListOrdGrp (body_50485148.html?find=AcctIDSource)]
[QuotReqGrp (body_50485253.html?find=AcctIDSource)]
[QuotReqRjctGrp (body_50485255.html?find=AcctIDSource)]
[SideCrossOrdModGrp (body_50485357.html?find=AcctIDSource)]
[TrdCapRptAckSideGrp (body_50485752.html?find=AcctIDSource)]
[TrdCapRptSideGrp (body_50485449.html?find=AcctIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
