.TH FIX.5.0SP2 "" "" "Tag #661"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
661 (tag661.html)
AllocAcctIDSource (tag661.html)
\@ActIDSrc
int
.PP
Used to identify the source of the AllocAccount (79) code.
.PP
See AcctIDSource (660) for
1
=
.PP
BIC
2
=
.PP
SID Code
3
=
.PP
TFM (GSPTA)
4
=
.PP
OMGEO (Alert ID)
5
=
.PP
DTCC Code
99
=
.PP
Other (custom or proprietary)
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=AllocAcctIDSource)]
[ConfirmationRequest (body_57516672.html?find=AllocAcctIDSource)]
[SettlementInstructionRequest (body_56496586.html?find=AllocAcctIDSource)]
.PP
   *   *   *   *   *
Used in components:
[AllocAckGrp (body_50484850.html?find=AllocAcctIDSource)]
[AllocGrp (body_50484851.html?find=AllocAcctIDSource)]
[PreAllocGrp (body_50485157.html?find=AllocAcctIDSource)]
[PreAllocMlegGrp (body_50485248.html?find=AllocAcctIDSource)]
[TrdAllocGrp (body_50485448.html?find=AllocAcctIDSource)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
