.TH FIX.5.0SP2 "" "" "Tag #668"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
668 (tag668.html)
DeliveryForm (tag668.html)
\@DlvryForm
int
.PP
Identifies the form of delivery.
1
=
.PP
Book Entry (default)
2
=
.PP
Bearer
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrumentExtension (body_49484852.html?find=DeliveryForm)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
