.TH FIX.5.0SP2 "" "" "Tag #677"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
677 (tag677.html)
LegBenchmarkCurveName (tag677.html)
\@Name
String
.PP
Name of the Leg Benchmark Curve.
.PP
See BenchmarkCurveName (22) for description and
EONIA
=
.PP
EONIA
EUREPO
=
.PP
EUREPO
Euribor
=
.PP
Euribor
FutureSWAP
=
.PP
FutureSWAP
LIBID
=
.PP
LIBID
LIBOR
=
.PP
LIBOR (London Inter-Bank Offer)
MuniAAA
=
.PP
MuniAAA
OTHER
=
.PP
OTHER
Pfandbriefe
=
.PP
Pfandbriefe
SONIA
=
.PP
SONIA
SWAP
=
.PP
SWAP
Treasury
=
.PP
Treasury
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[LegBenchmarkCurveData (body_49484854.html?find=LegBenchmarkCurveName)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
