.TH FIX.5.0SP2 "" "" "Tag #678"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
678 (tag678.html)
LegBenchmarkCurvePoint (tag678.html)
\@Point
String
.PP
Identifies the point on the Leg Benchmark Curve.
.PP
See BenchmarkCurvePoint (222) for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[LegBenchmarkCurveData (body_49484854.html?find=LegBenchmarkCurvePoint)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
