.TH FIX.5.0SP2 "" "" "Tag #683"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
683 (tag683.html)
NoLegStipulations (tag683.html)
NumInGroup
.PP
Number of leg stipulation entries
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[LegStipulations (body_49484855.html?find=NoLegStipulations)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
