.TH FIX.5.0SP2 "" "" "Tag #685"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
685 (tag685.html)
LegOrderQty (tag685.html)
\@OrdQty
Qty
.PP
Quantity ordered of this leg.
.PP
See OrderQty (38) for description and
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[InstrmtLegExecGrp (body_50484956.html?find=LegOrderQty)]
[LegOrdGrp (body_50485053.html?find=LegOrderQty)]
[LegQuotGrp (body_50485055.html?find=LegOrderQty)]
[LegQuotStatGrp (body_50485056.html?find=LegOrderQty)]
[QuotReqLegsGrp (body_50485254.html?find=LegOrderQty)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
