.TH FIX.5.0SP2 "" "" "Tag #697"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
697 (tag697.html)
YieldRedemptionPrice (tag697.html)
\@RedPx
Price
.PP
Price to which the yield has been calculated.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[YieldData (body_49485050.html?find=YieldRedemptionPrice)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
