.TH FIX.5.0SP2 "" "" "Tag #698"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
698 (tag698.html)
YieldRedemptionPriceType (tag698.html)
\@RedPxTyp
int
.PP
The price type of the YieldRedemptionPrice (697)
.PP
See PriceType (423) for description and
1
=
.PP
Percentage (i.e. percent of par) (often called "dollar price" for
fixed income)
2
=
.PP
Per unit (i.e. per share or contract)
3
=
.PP
Fixed amount (absolute value)
4
=
.PP
Discount - percentage points below par
5
=
.PP
Premium - percentage points over par
6
=
.PP
Spread (basis points spread)
7
=
.PP
TED Price
8
=
.PP
TED Yield
9
=
.PP
Yield
10
=
.PP
Fixed cabinet trade price (primarily for listed futures and
options)
11
=
.PP
Variable cabinet trade price (primarily for listed futures and
options)
13
=
.PP
Product ticks in halfs
14
=
.PP
Product ticks in fourths
15
=
.PP
Product ticks in eights
16
=
.PP
Product ticks in sixteenths
17
=
.PP
Product ticks in thirty-seconds
18
=
.PP
Product ticks in sixty-forths
19
=
.PP
Product ticks in one-twenty-eights
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[YieldData (body_49485050.html?find=YieldRedemptionPriceType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
