.TH FIX.5.0SP2 "" "" "Tag #70"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
70 (tag70.html)
AllocID (tag70.html)
\@AllocID
String
.PP
Unique identifier for allocation message.
.PP
(Prior to FIX 4.1 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=AllocID)]
[AllocationInstructionAck (body_505280.html?find=AllocID)]
[AllocationInstructionAlert (body_57566677.html?find=AllocID)]
[AllocationReport (body_55566583.html?find=AllocID)]
[AllocationReportAck (body_55576584.html?find=AllocID)]
[Confirmation (body_55486575.html?find=AllocID)]
[ConfirmationRequest (body_57516672.html?find=AllocID)]
[ExecutionReport (body_5756.html?find=AllocID)]
[MultilegOrderCancelReplace (body_54506567.html?find=AllocID)]
[NewOrderMultileg (body_54496566.html?find=AllocID)]
[NewOrderSingle (body_495268.html?find=AllocID)]
[OrderCancelReplaceRequest (body_495571.html?find=AllocID)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=AllocID)]
[SideCrossOrdModGrp (body_50485357.html?find=AllocID)]
[TrdCapRptAckSideGrp (body_50485752.html?find=AllocID)]
[TrdCapRptSideGrp (body_50485449.html?find=AllocID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
