.TH FIX.5.0SP2 "" "" "Tag #701"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
701 (tag701.html)
YieldCalcDate (tag701.html)
\@CalcDt
LocalMktDate
.PP
Include as needed to clarify yield irregularities associated with
date, e.g. when it falls on a non-business day.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[YieldData (body_49485050.html?find=YieldCalcDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
