.TH FIX.5.0SP2 "" "" "Tag #71"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
71 (tag71.html)
AllocTransType (tag71.html)
\@TransTyp
char
.PP
Identifies allocation transaction type *** SOME VALUES HAVE BEEN
REPLACED - See "Replaced Features and Supported Approach" ***
0
=
.PP
New
1
=
.PP
Replace
2
=
.PP
Cancel
3
=
.PP
Preliminary (without MiscFees and NetMoney) (Removed/Replaced)
4
=
.PP
Calculated (includes MiscFees and NetMoney) (Removed/Replaced)
5
=
.PP
Calculated without Preliminary (sent unsolicited by broker,
includes MiscFees and NetMoney) (Removed/Replaced)
6
=
.PP
Reversal
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=AllocTransType)]
[AllocationInstructionAlert (body_57566677.html?find=AllocTransType)]
[AllocationReport (body_55566583.html?find=AllocTransType)]
[AllocationReportAck (body_55576584.html?find=AllocTransType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
