.TH FIX.5.0SP2 "" "" "Tag #711"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
711 (tag711.html)
NoUnderlyings (tag711.html)
NumInGroup
.PP
Number of underlying legs that make up the security.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PosUndInstrmtGrp (body_50485156.html?find=NoUnderlyings)]
[UndInstrmtCollGrp (body_50485453.html?find=NoUnderlyings)]
[UndInstrmtGrp (body_50485454.html?find=NoUnderlyings)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
