.TH FIX.5.0SP2 "" "" "Tag #718"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
718 (tag718.html)
AdjustmentType (tag718.html)
\@AdjTyp
int
.PP
Type of adjustment to be applied, used for PCS and PAJ
0
=
.PP
Process Request As Margin Disposition
1
=
.PP
Delta Plus
2
=
.PP
Delta Minus
3
=
.PP
Final
.PP
   *   *   *   *   *
Used in messages:
[PositionMaintenanceReport (body_55506577.html?find=AdjustmentType)]
[PositionMaintenanceRequest (body_55496576.html?find=AdjustmentType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
