.TH FIX.5.0SP2 "" "" "Tag #721"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
721 (tag721.html)
PosMaintRptID (tag721.html)
\@RptID
String
.PP
Unique identifier for this position report
.PP
   *   *   *   *   *
Used in messages:
[AdjustedPositionReport (body_57556676.html?find=PosMaintRptID)]
[PositionMaintenanceReport (body_55506577.html?find=PosMaintRptID)]
[PositionReport (body_55536580.html?find=PosMaintRptID)]
[RequestForPositionsAck (body_55526579.html?find=PosMaintRptID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
