.TH FIX.5.0SP2 "" "" "Tag #724"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
724 (tag724.html)
PosReqType (tag724.html)
\@ReqTyp
int
.PP
Used to specify the type of position request being made.
0
=
.PP
Positions
1
=
.PP
Trades
2
=
.PP
Exercises
3
=
.PP
Assignments
4
=
.PP
Settlement Activity
5
=
.PP
Backout Message
6
=
.PP
Delta Positions
.PP
   *   *   *   *   *
Used in messages:
[AdjustedPositionReport (body_57556676.html?find=PosReqType)]
[PositionReport (body_55536580.html?find=PosReqType)]
[RequestForPositions (body_55516578.html?find=PosReqType)]
[RequestForPositionsAck (body_55526579.html?find=PosReqType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
