.TH FIX.5.0SP2 "" "" "Tag #730"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
730 (tag730.html)
SettlPrice (tag730.html)
\@SetPx
Price
.PP
Settlement price
.PP
   *   *   *   *   *
Used in messages:
[AdjustedPositionReport (body_57556676.html?find=SettlPrice)]
[AssignmentReport (body_56506587.html?find=SettlPrice)]
[PositionReport (body_55536580.html?find=SettlPrice)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
