.TH FIX.5.0SP2 "" "" "Tag #746"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
746 (tag746.html)
OpenInterest (tag746.html)
\@OpenInt
Amt
.PP
Open interest that was eligible for assignment.
.PP
   *   *   *   *   *
Used in messages:
[AssignmentReport (body_56506587.html?find=OpenInterest)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
