.TH FIX.5.0SP2 "" "" "Tag #749"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
749 (tag749.html)
TradeRequestResult (tag749.html)
\@ReqRslt
int
.PP
Result of Trade Request
0
=
.PP
Successful (default)
1
=
.PP
Invalid or unknown instrument
2
=
.PP
Invalid type of trade requested
3
=
.PP
Invalid parties
4
=
.PP
Invalid transport type requested
5
=
.PP
Invalid destination requested
8
=
.PP
TradeRequestType not supported
9
=
.PP
Not authorized
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReportRequestAck (body_55546581.html?find=TradeRequestResult)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
