.TH FIX.5.0SP2 "" "" "Tag #75"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
75 (tag75.html)
TradeDate (tag75.html)
\@TrdDt
LocalMktDate
.PP
Indicates date of trade referenced in this message in YYYYMMDD
format. Absence of this field indicates current day (expressed in
local time at place of trade).
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=TradeDate)]
[AllocationInstruction (body_495774.html?find=TradeDate)]
[AllocationInstructionAck (body_505280.html?find=TradeDate)]
[AllocationInstructionAlert (body_57566677.html?find=TradeDate)]
[AllocationReport (body_55566583.html?find=TradeDate)]
[AllocationReportAck (body_55576584.html?find=TradeDate)]
[BidRequest (body_5252107.html?find=TradeDate)]
[Confirmation (body_55486575.html?find=TradeDate)]
[Confirmation_Ack (body_56486585.html?find=TradeDate)]
[ExecutionReport (body_5756.html?find=TradeDate)]
[ListCancelRequest (body_504875.html?find=TradeDate)]
[MarketDataIncrementalRefresh (body_514988.html?find=TradeDate)]
[MarketDataSnapshotFullRefresh (body_514887.html?find=TradeDate)]
[MultilegOrderCancelReplace (body_54506567.html?find=TradeDate)]
[NewOrderMultileg (body_54496566.html?find=TradeDate)]
[NewOrderSingle (body_495268.html?find=TradeDate)]
[OrderCancelReject (body_494857.html?find=TradeDate)]
[OrderCancelReplaceRequest (body_495571.html?find=TradeDate)]
[TradeCaptureReport (body_54526569.html?find=TradeDate)]
[TradeCaptureReportAck (body_55556582.html?find=TradeDate)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=TradeDate)]
[SideCrossOrdCxlGrp (body_50485356.html?find=TradeDate)]
[SideCrossOrdModGrp (body_50485357.html?find=TradeDate)]
[TrdCapDtGrp (body_50485457.html?find=TradeDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
