.TH FIX.5.0SP2 "" "" "Tag #750"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
750 (tag750.html)
TradeRequestStatus (tag750.html)
\@ReqStat
int
.PP
Status of Trade Request.
0
=
.PP
Accepted
1
=
.PP
Completed
2
=
.PP
Rejected
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReportRequestAck (body_55546581.html?find=TradeRequestStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
