.TH FIX.5.0SP2 "" "" "Tag #766"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
766 (tag766.html)
AllowableOneSidednessValue (tag766.html)
\@AOSValu
Amt
.PP
The maximum amount that execution of one side of a program trade
can exceed execution of the other.
.PP
   *   *   *   *   *
Used in messages:
[NewOrderList (body_495369.html?find=AllowableOneSidednessValue)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
