.TH FIX.5.0SP2 "" "" "Tag #769"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
769 (tag769.html)
TrdRegTimestamp (tag769.html)
\@TS
UTCTimestamp
.PP
Traded / Regulatory timestamp value. Use to store time information
required by government regulators or self regulatory organizations
(such as an exchange or clearing house).
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdRegTimestamps (body_49485048.html?find=TrdRegTimestamp)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
