.TH FIX.5.0SP2 "" "" "Tag #773"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
773 (tag773.html)
ConfirmType (tag773.html)
\@CnfmTyp
int
.PP
Identifies the type of Confirmation message being sent.
1
=
.PP
Status
2
=
.PP
Confirmation
3
=
.PP
Confirmation Request Rejected (reason can be stated in Text (58)
field)
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=ConfirmType)]
[ConfirmationRequest (body_57516672.html?find=ConfirmType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
