.TH FIX.5.0SP2 "" "" "Tag #789"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
789 (tag789.html)
NextExpectedMsgSeqNum (tag789.html)
SeqNum
.PP
Next expected MsgSeqNum value to be received.
.PP
   *   *   *   *   *
Used in messages:
[Logon (body_494965.html?find=NextExpectedMsgSeqNum)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
