.TH FIX.5.0SP2 "" "" "Tag #792"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
792 (tag792.html)
SettlInstReqRejCode (tag792.html)
\@SettlInstReqRejCode
int
.PP
Identifies reason for rejection (of a settlement instruction
request message).
0
=
.PP
Unable to process request
1
=
.PP
Unknown account
2
=
.PP
No matching settlement instructions found
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[SettlementInstructions (body_505684.html?find=SettlInstReqRejCode)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
