.TH FIX.5.0SP2 "" "" "Tag #797"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
797 (tag797.html)
CopyMsgIndicator (tag797.html)
\@CopyMsgInd
Boolean
.PP
Indicates whether or not this message is a drop copy of another
message.
.PP
   *   *   *   *   *
Used in messages:
[Confirmation (body_55486575.html?find=CopyMsgIndicator)]
[ExecutionReport (body_5756.html?find=CopyMsgIndicator)]
[TradeCaptureReport (body_54526569.html?find=CopyMsgIndicator)]
[TradeCaptureReportAck (body_55556582.html?find=CopyMsgIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
