.TH FIX.5.0SP2 "" "" "Tag #805"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
805 (tag805.html)
NestedPartySubIDType (tag805.html)
\@Typ
int
.PP
Type of NestedPartySubID (545) value.
.PP
Same values as PartySubIDType (803)
1
=
.PP
Firm
2
=
.PP
Person
3
=
.PP
System
4
=
.PP
Application
5
=
.PP
Full legal name of firm
6
=
.PP
Postal address
7
=
.PP
Phone number
8
=
.PP
Email address
9
=
.PP
Contact name
10
=
.PP
Securities account number (for settlement instructions)
11
=
.PP
Registration number (for settlement instructions and confirmations)
12
=
.PP
Registered address (for confirmation purposes)
13
=
.PP
Regulatory status (for confirmation purposes)
14
=
.PP
Registration name (for settlement instructions)
15
=
.PP
Cash account number (for settlement instructions)
16
=
.PP
BIC
17
=
.PP
CSD participant member code
18
=
.PP
Registered address
19
=
.PP
Fund account name
20
=
.PP
Telex number
21
=
.PP
Fax number
22
=
.PP
Securities account name
23
=
.PP
Cash account name
24
=
.PP
Department
25
=
.PP
Location desk
26
=
.PP
Position account type
27
=
.PP
Security locate ID
28
=
.PP
Market maker
29
=
.PP
Eligible counterparty
30
=
.PP
Professional client
31
=
.PP
Location
32
=
.PP
Execution venue
33
=
.PP
Currency delivery identifier
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NstdPtysSubGrp (body_50485556.html?find=NestedPartySubIDType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
