.TH FIX.5.0SP2 "" "" "Tag #811"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
811 (tag811.html)
PriceDelta (tag811.html)
\@PxDelta
float
.PP
The rate of change in the price of a derivative with respect to the
movement in the price of the underlying instrument(s) upon which
the derivative instrument price is based.
.PP
This value is normally between -1.0 and 1.0.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=PriceDelta)]
[PositionReport (body_55536580.html?find=PriceDelta)]
.PP
   *   *   *   *   *
Used in components:
[MDFullGrp (body_50485149.html?find=PriceDelta)]
[MDIncGrp (body_50485150.html?find=PriceDelta)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
