.TH FIX.5.0SP2 "" "" "Tag #812"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
812 (tag812.html)
ApplQueueMax (tag812.html)
\@ApplQuMax
int
.PP
Used to specify the maximum number of application messages that can
be queued bedore a corrective action needs to take place to resolve
the queuing issue.
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequest (body_505786.html?find=ApplQueueMax)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
