.TH FIX.5.0SP2 "" "" "Tag #815"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
815 (tag815.html)
ApplQueueAction (tag815.html)
\@ApplQuActn
int
.PP
Action to take to resolve an application message queue (backlog).
0
=
.PP
No Action Taken
1
=
.PP
Queue Flushed
2
=
.PP
Overlay Last
3
=
.PP
End Session
.PP
   *   *   *   *   *
Used in messages:
[MarketDataRequest (body_505786.html?find=ApplQueueAction)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
