.TH FIX.5.0SP2 "" "" "Tag #819"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
819 (tag819.html)
AvgPxIndicator (tag819.html)
\@AvgPxInd
int
.PP
Average Pricing Indicator
0
=
.PP
No Average Pricing
1
=
.PP
Trade is part of an average price group identified by the
TradeLinkID (820)
2
=
.PP
Last trade is the average price group identified by the TradeLinkID
(820)
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=AvgPxIndicator)]
[AllocationInstructionAlert (body_57566677.html?find=AvgPxIndicator)]
[AllocationReport (body_55566583.html?find=AvgPxIndicator)]
[AllocationReportAck (body_55576584.html?find=AvgPxIndicator)]
[TradeCaptureReport (body_54526569.html?find=AvgPxIndicator)]
[TradeCaptureReportAck (body_55556582.html?find=AvgPxIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
