.TH FIX.5.0SP2 "" "" "Tag #820"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
820 (tag820.html)
TradeLinkID (tag820.html)
\@LinkID
String
.PP
Used to link a group of trades together. Useful for linking a group
of trades together for average price calculations.
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=TradeLinkID)]
[TradeCaptureReportAck (body_55556582.html?find=TradeLinkID)]
[TradeCaptureReportRequest (body_54516568.html?find=TradeLinkID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
