.TH FIX.5.0SP2 "" "" "Tag #825"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
825 (tag825.html)
ExchangeRule (tag825.html)
\@ExchRule
String
.PP
Used to report any exchange rules that apply to this trade.
.PP
Primarily intended for US futures markets. Certain trading
practices are permitted by the CFTC, such as large lot trading,
block trading, all or none trades. If the rules are used, the
exchanges are required to indicate these rules on the trade.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=ExchangeRule)]
[TrdCapRptSideGrp (body_50485449.html?find=ExchangeRule)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
