.TH FIX.5.0SP2 "" "" "Tag #835"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
835 (tag835.html)
PegMoveType (tag835.html)
\@MoveTyp
int
.PP
Describes whether peg is static or floats
0
=
.PP
Floating (default)
1
=
.PP
Fixed
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[PegInstructions (body_49484951.html?find=PegMoveType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
