.TH FIX.5.0SP2 "" "" "Tag #841"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
841 (tag841.html)
DiscretionMoveType (tag841.html)
\@MoveTyp
int
.PP
Describes whether discretionay price is static or floats
0
=
.PP
Floating (default)
1
=
.PP
Fixed
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DiscretionInstructions (body_49484849.html?find=DiscretionMoveType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
