.TH FIX.5.0SP2 "" "" "Tag #842"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
842 (tag842.html)
DiscretionOffsetType (tag842.html)
\@OfstTyp
int
.PP
Type of Discretion Offset value
0
=
.PP
Price (default)
1
=
.PP
Basis Points
2
=
.PP
Ticks
3
=
.PP
Price Tier / Level
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DiscretionInstructions (body_49484849.html?find=DiscretionOffsetType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
