.TH FIX.5.0SP2 "" "" "Tag #844"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
844 (tag844.html)
DiscretionRoundDirection (tag844.html)
\@RndDir
int
.PP
If the calculated discretionary price is not a valid tick price,
specifies whether to round the price to be more or less aggressive
1
=
.PP
More aggressive - on a buy order round the price up to the nearest
tick; on a sell round down to the nearest tick
2
=
.PP
More passive - on a buy order round down to the nearest tick; on a
sell order round up to the nearest tick
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[DiscretionInstructions (body_49484849.html?find=DiscretionRoundDirection)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
