.TH FIX.5.0SP2 "" "" "Tag #848"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
848 (tag848.html)
TargetStrategyParameters (tag848.html)
\@TgtStrategyParameters
String
.PP
Field to allow further specification of the TargetStrategy - usage
to be agreed between counterparties
FIX.5.0
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=TargetStrategyParameters)]
[ExecutionReport (body_5756.html?find=TargetStrategyParameters)]
[MultilegOrderCancelReplace (body_54506567.html?find=TargetStrategyParameters)]
[NewOrderCross (body_5350115.html?find=TargetStrategyParameters)]
[NewOrderMultileg (body_54496566.html?find=TargetStrategyParameters)]
[NewOrderSingle (body_495268.html?find=TargetStrategyParameters)]
[OrderCancelReplaceRequest (body_495571.html?find=TargetStrategyParameters)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=TargetStrategyParameters)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
