.TH FIX.5.0SP2 "" "" "Tag #853"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
853 (tag853.html)
ShortSaleReason (tag853.html)
\@ShrtSaleRsn
int
.PP
Reason for short sale.
0
=
.PP
Dealer Sold Short
1
=
.PP
Dealer Sold Short Exempt
2
=
.PP
Selling Customer Sold Short
3
=
.PP
Selling Customer Sold Short Exempt
4
=
.PP
Qualified Service Representative (QSR) or Automatic Give-up (AGU)
Contra Side Sold Short
5
=
.PP
QSR or AGU Contra Side Sold Short Exempt
.PP
   *   *   *   *   *
Used in messages:
[TradeCaptureReport (body_54526569.html?find=ShortSaleReason)]
[TradeCaptureReportAck (body_55556582.html?find=ShortSaleReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
