.TH FIX.5.0SP2 "" "" "Tag #854"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
854 (tag854.html)
QtyType (tag854.html)
\@QtyTyp
int
.PP
Type of quantity specified in a quantity field:
0
=
.PP
Units (shares, par, currency)
1
=
.PP
Contracts (if used - must specify ContractMultiplier (tag 231))
2
=
.PP
Units of Measure per Time Unit (if used - must specify
UnitofMeasure (tag 996) and TimeUnit (tag 997))
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=QtyType)]
[AllocationInstruction (body_495774.html?find=QtyType)]
[AllocationInstructionAlert (body_57566677.html?find=QtyType)]
[AllocationReport (body_55566583.html?find=QtyType)]
[CollateralAssignment (body_56526589.html?find=QtyType)]
[CollateralInquiry (body_56556666.html?find=QtyType)]
[CollateralInquiryAck (body_57506671.html?find=QtyType)]
[CollateralReport (body_56546665.html?find=QtyType)]
[CollateralRequest (body_56516588.html?find=QtyType)]
[CollateralResponse (body_56536590.html?find=QtyType)]
[Confirmation (body_55486575.html?find=QtyType)]
[ExecutionReport (body_5756.html?find=QtyType)]
[IOI (body_5554.html?find=QtyType)]
[MultilegOrderCancelReplace (body_54506567.html?find=QtyType)]
[NewOrderMultileg (body_54496566.html?find=QtyType)]
[NewOrderSingle (body_495268.html?find=QtyType)]
[OrderCancelReplaceRequest (body_495571.html?find=QtyType)]
[TradeCaptureReport (body_54526569.html?find=QtyType)]
[TradeCaptureReportAck (body_55556582.html?find=QtyType)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=QtyType)]
[QuotReqGrp (body_50485253.html?find=QtyType)]
[QuotReqRjctGrp (body_50485255.html?find=QtyType)]
[SideCrossOrdModGrp (body_50485357.html?find=QtyType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
