.TH FIX.5.0SP2 "" "" "Tag #864"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
864 (tag864.html)
NoEvents (tag864.html)
NumInGroup
.PP
Number of repeating EventType entries.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[EvntGrp (body_50485548.html?find=NoEvents)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
