.TH FIX.5.0SP2 "" "" "Tag #873"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
873 (tag873.html)
DatedDate (tag873.html)
\@Dated
LocalMktDate
.PP
The effective date of a new securities issue determined by its
underwriters. Often but not always the same as the Issue Date and
the Interest Accrual Date
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[Instrument (body_49484851.html?find=DatedDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
