.TH FIX.5.0SP2 "" "" "Tag #877"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
877 (tag877.html)
UnderlyingCPProgram (tag877.html)
\@CPPgm
String
.PP
The program under which the underlying commercial paper is issued
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingCPProgram)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
