.TH FIX.5.0SP2 "" "" "Tag #88"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
88 (tag88.html)
AllocRejCode (tag88.html)
\@RejCode
int
.PP
Identifies reason for rejection.
0
=
.PP
Unknown account(s)
1
=
.PP
Incorrect quantity
2
=
.PP
Incorrect averageg price
3
=
.PP
Unknown executing broker mnemonic
4
=
.PP
Commission difference
5
=
.PP
Unknown OrderID (37)
6
=
.PP
Unknown ListID (66)
7
=
.PP
Other (further in Text (58))
8
=
.PP
Incorrect allocated quantity
9
=
.PP
Calculation difference
10
=
.PP
Unknown or stale ExecID
11
=
.PP
Mismatched data
12
=
.PP
Unknown ClOrdID
13
=
.PP
Warehouse request rejected
99
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstructionAck (body_505280.html?find=AllocRejCode)]
[AllocationReport (body_55566583.html?find=AllocRejCode)]
[AllocationReportAck (body_55576584.html?find=AllocRejCode)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
