.TH FIX.5.0SP2 "" "" "Tag #880"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
880 (tag880.html)
TrdMatchID (tag880.html)
\@MtchID
String
.PP
Identifier assigned to a trade by a matching system.
.PP
   *   *   *   *   *
Used in messages:
[ExecutionReport (body_5756.html?find=TrdMatchID)]
[TradeCaptureReport (body_54526569.html?find=TrdMatchID)]
[TradeCaptureReportAck (body_55556582.html?find=TrdMatchID)]
[TradeCaptureReportRequest (body_54516568.html?find=TrdMatchID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
