.TH FIX.5.0SP2 "" "" "Tag #893"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
893 (tag893.html)
LastFragment (tag893.html)
\@LastFragment
Boolean
.PP
Indicates whether this message is the last in a sequence of
messages for those messages that support fragmentation, such as
Allocation Instruction, Mass Quote, Security List, Derivative
Security List
N
=
.PP
Not Last Message
Y
=
.PP
Last Message
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=LastFragment)]
[AllocationInstructionAlert (body_57566677.html?find=LastFragment)]
[AllocationReport (body_55566583.html?find=LastFragment)]
[DerivativeSecurityList (body_54486565.html?find=LastFragment)]
[DerivativeSecurityListUpdateReport (body_4948516682.html?find=LastFragment)]
[ExecutionReport (body_5756.html?find=LastFragment)]
[ListStatus (body_505178.html?find=LastFragment)]
[ListStrikePrice (body_5254109.html?find=LastFragment)]
[NewOrderList (body_495369.html?find=LastFragment)]
[PartyDetailsListReport (body_4949566771.html?find=LastFragment)]
[SecurityList (body_5356121.html?find=LastFragment)]
[SecurityListUpdateReport (body_57546675.html?find=LastFragment)]
[SecurityTypes (body_5354119.html?find=LastFragment)]
.PP
   *   *   *   *   *
Used in components:
[QuotSetAckGrp (body_50485256.html?find=LastFragment)]
[QuotSetGrp (body_50485257.html?find=LastFragment)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
