.TH FIX.5.0SP2 "" "" "Tag #894"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
894 (tag894.html)
CollReqID (tag894.html)
\@ReqID
String
.PP
Collateral Request Identifier
.PP
   *   *   *   *   *
Used in messages:
[CollateralAssignment (body_56526589.html?find=CollReqID)]
[CollateralRequest (body_56516588.html?find=CollReqID)]
[CollateralResponse (body_56536590.html?find=CollReqID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
