.TH FIX.5.0SP2 "" "" "Tag #895"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
895 (tag895.html)
CollAsgnReason (tag895.html)
\@AsgnRsn
int
.PP
Reason for Collateral Assignment
0
=
.PP
Initial
1
=
.PP
Scheduled
2
=
.PP
Time Warning
3
=
.PP
Margin Deficiency
4
=
.PP
Margin Excess
5
=
.PP
Forward Collateral Demand
6
=
.PP
Event of default
7
=
.PP
Adverse tax event
.PP
   *   *   *   *   *
Used in messages:
[CollateralAssignment (body_56526589.html?find=CollAsgnReason)]
[CollateralRequest (body_56516588.html?find=CollAsgnReason)]
[CollateralResponse (body_56536590.html?find=CollAsgnReason)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
