.TH FIX.5.0SP2 "" "" "Tag #896"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
896 (tag896.html)
CollInquiryQualifier (tag896.html)
\@Qual
int
.PP
Collateral inquiry qualifiers:
0
=
.PP
Trade Date
1
=
.PP
GC Instrument
2
=
.PP
Collateral Instrument
3
=
.PP
Substitution Eligible
4
=
.PP
Not Assigned
5
=
.PP
Partially Assigned
6
=
.PP
Fully Assigned
7
=
.PP
Outstanding Trades (Today < end date)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CollInqQualGrp (body_50484856.html?find=CollInquiryQualifier)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
