.TH FIX.5.0SP2 "" "" "Tag #9"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
9 (tag9.html)
BodyLength (tag9.html)
Length
.PP
Message length, in bytes, forward to the CheckSum field. ALWAYS
SECOND FIELD IN MESSAGE. (Always unencrypted)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[StandardHeader (body_49485052.html?find=BodyLength)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
