.TH FIX.5.0SP2 "" "" "Tag #909"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
909 (tag909.html)
CollInquiryID (tag909.html)
\@ID
String
.PP
Collateral Inquiry Identifier
.PP
   *   *   *   *   *
Used in messages:
[CollateralInquiry (body_56556666.html?find=CollInquiryID)]
[CollateralInquiryAck (body_57506671.html?find=CollInquiryID)]
[CollateralReport (body_56546665.html?find=CollInquiryID)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
