.TH FIX.5.0SP2 "" "" "Tag #910"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
910 (tag910.html)
CollStatus (tag910.html)
\@Stat
int
.PP
Collateral Status
0
=
.PP
Unassigned
1
=
.PP
Partially Assigned
2
=
.PP
Assignment Proposed
3
=
.PP
Assigned (Accepted)
4
=
.PP
Challenged
.PP
   *   *   *   *   *
Used in messages:
[CollateralReport (body_56546665.html?find=CollStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
