.TH FIX.5.0SP2 "" "" "Tag #914"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
914 (tag914.html)
AgreementID (tag914.html)
\@AgmtID
String
.PP
A common reference to the applicable standing agreement between the
counterparties to a financing transaction.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[FinancingDetails (body_49484850.html?find=AgreementID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
