.TH FIX.5.0SP2 "" "" "Tag #916"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
916 (tag916.html)
StartDate (tag916.html)
\@StartDt
LocalMktDate
.PP
Start date of a financing deal, i.e. the date the buyer pays the
seller cash and takes control of the collateral
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[FinancingDetails (body_49484850.html?find=StartDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
