.TH FIX.5.0SP2 "" "" "Tag #917"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
917 (tag917.html)
EndDate (tag917.html)
\@EndDt
LocalMktDate
.PP
End date of a financing deal, i.e. the date the seller reimburses
the buyer and takes back control of the collateral
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[FinancingDetails (body_49484850.html?find=EndDate)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
