.TH FIX.5.0SP2 "" "" "Tag #92"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
92 (tag92.html)
BrokerOfCredit (tag92.html)
String
.PP
Broker to receive trade credit.
FIX.4.2
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
