.TH FIX.5.0SP2 "" "" "Tag #921"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
921 (tag921.html)
StartCash (tag921.html)
\@StartCsh
Amt
.PP
Starting dirty cash consideration of a financing deal, i.e. paid to
the seller on the Start Date.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=StartCash)]
[AllocationInstructionAlert (body_57566677.html?find=StartCash)]
[AllocationReport (body_55566583.html?find=StartCash)]
[CollateralAssignment (body_56526589.html?find=StartCash)]
[CollateralInquiry (body_56556666.html?find=StartCash)]
[CollateralReport (body_56546665.html?find=StartCash)]
[CollateralRequest (body_56516588.html?find=StartCash)]
[CollateralResponse (body_56536590.html?find=StartCash)]
[Confirmation (body_55486575.html?find=StartCash)]
[ExecutionReport (body_5756.html?find=StartCash)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=StartCash)]
[TrdCapRptSideGrp (body_50485449.html?find=StartCash)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
