.TH FIX.5.0SP2 "" "" "Tag #922"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
922 (tag922.html)
EndCash (tag922.html)
\@EndCsh
Amt
.PP
Ending dirty cash consideration of a financing deal. i.e.
reimbursed to the buyer on the End Date.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=EndCash)]
[AllocationInstructionAlert (body_57566677.html?find=EndCash)]
[AllocationReport (body_55566583.html?find=EndCash)]
[CollateralAssignment (body_56526589.html?find=EndCash)]
[CollateralInquiry (body_56556666.html?find=EndCash)]
[CollateralReport (body_56546665.html?find=EndCash)]
[CollateralRequest (body_56516588.html?find=EndCash)]
[CollateralResponse (body_56536590.html?find=EndCash)]
[Confirmation (body_55486575.html?find=EndCash)]
[ExecutionReport (body_5756.html?find=EndCash)]
.PP
   *   *   *   *   *
Used in components:
[TrdCapRptAckSideGrp (body_50485752.html?find=EndCash)]
[TrdCapRptSideGrp (body_50485449.html?find=EndCash)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
