.TH FIX.5.0SP2 "" "" "Tag #931"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
931 (tag931.html)
RefSubID (tag931.html)
\@RefSubID
String
.PP
Assigned value used to identify specific elements within a firm.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CompIDReqGrp (body_50484857.html?find=RefSubID)]
[CompIDStatGrp (body_50484948.html?find=RefSubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
