.TH FIX.5.0SP2 "" "" "Tag #935"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
935 (tag935.html)
NetworkRequestType (tag935.html)
\@NtwkReqTyp
int
.PP
Indicates the type and level of details required for a Network
Status Request Message
.PP
Boolean logic applies EG If you want to subscribe for changes to
certain id\[aq]s then UserRequestType =0 (8+2), Snapshot for
certain ID\[aq]s = 9 (8+1)
1
=
.PP
Snapshot
2
=
.PP
Subscribe
4
=
.PP
Stop Subscribing
8
=
.PP
Level of Detail, then NoCompID\[aq]s becomes required
.PP
   *   *   *   *   *
Used in messages:
[NetworkCounterpartySystemStatusRequest (body_56566667.html?find=NetworkRequestType)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
