.TH FIX.5.0SP2 "" "" "Tag #938"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
938 (tag938.html)
NoCollInquiryQualifier (tag938.html)
NumInGroup
.PP
Number of CollInquiryQualifier entries in a repeating group.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[CollInqQualGrp (body_50484856.html?find=NoCollInquiryQualifier)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
