.TH FIX.5.0SP2 "" "" "Tag #941"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
941 (tag941.html)
UnderlyingStrikeCurrency (tag941.html)
\@StrkCcy
Currency
.PP
Currency in which the strike price of an underlying instrument is
denominated
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingStrikeCurrency)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
