.TH FIX.5.0SP2 "" "" "Tag #944"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
944 (tag944.html)
CollAction (tag944.html)
\@Actn
int
.PP
Action proposed for an Underlying Instrument instance.
0
=
.PP
Retain
1
=
.PP
Add
2
=
.PP
Remove
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UndInstrmtCollGrp (body_50485453.html?find=CollAction)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
