.TH FIX.5.0SP2 "" "" "Tag #945"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
945 (tag945.html)
CollInquiryStatus (tag945.html)
\@Stat
int
.PP
Status of Collateral Inquiry
0
=
.PP
Accepted
1
=
.PP
Accepted With Warnings
2
=
.PP
Completed
3
=
.PP
Completed With Warnings
4
=
.PP
Rejected
.PP
   *   *   *   *   *
Used in messages:
[CollateralInquiryAck (body_57506671.html?find=CollInquiryStatus)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
