.TH FIX.5.0SP2 "" "" "Tag #953"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
953 (tag953.html)
Nested3PartySubID (tag953.html)
\@ID
String
.PP
PartySubID value within a "third instance" Nested repeating group.
.PP
Same values as PartySubID (523)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[NstdPtys3SubGrp (body_50485648.html?find=Nested3PartySubID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
