.TH FIX.5.0SP2 "" "" "Tag #974"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
974 (tag974.html)
UnderlyingCashType (tag974.html)
\@CashTyp
String
.PP
Used for derivatives that deliver into cash underlying.
FIXED
=
.PP
FIXED
DIFF
=
.PP
DIFF
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingCashType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
