.TH FIX.5.0SP2 "" "" "Tag #975"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
975 (tag975.html)
UnderlyingSettlementType (tag975.html)
\@SettlTyp
int
.PP
Indicates order settlement period for the underlying instrument.
2
=
.PP
T+1
4
=
.PP
T+3
5
=
.PP
T+4
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[UnderlyingInstrument (body_49485049.html?find=UnderlyingSettlementType)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
