.TH FIX.5.0SP2 "" "" "Tag #978"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
978 (tag978.html)
LateIndicator (tag978.html)
\@LateInd
Boolean
.PP
Indicates if the contrary intention was received after the exchange
imposed cutoff time
.PP
   *   *   *   *   *
Used in messages:
[ContraryIntentionReport (body_57526679.html?find=LateIndicator)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
