.TH FIX.5.0SP2 "" "" "Tag #99"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
99 (tag99.html)
StopPx (tag99.html)
\@StopPx
Price
.PP
Price per unit of quantity (e.g. per share)
.PP
   *   *   *   *   *
Used in messages:
[CrossOrderCancelReplaceRequest (body_5351116.html?find=StopPx)]
[ExecutionReport (body_5756.html?find=StopPx)]
[MultilegOrderCancelReplace (body_54506567.html?find=StopPx)]
[NewOrderCross (body_5350115.html?find=StopPx)]
[NewOrderMultileg (body_54496566.html?find=StopPx)]
[NewOrderSingle (body_495268.html?find=StopPx)]
[OrderCancelReplaceRequest (body_495571.html?find=StopPx)]
.PP
   *   *   *   *   *
Used in components:
[ListOrdGrp (body_50485148.html?find=StopPx)]
[TradeReportOrderDetail (body_50495251.html?find=StopPx)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
