.TH FIX.5.0SP2 "" "" "Tag #990"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
990 (tag990.html)
LegReportID (tag990.html)
\@RptID
String
.PP
Additional attribute to store the Trade ID of the Leg.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[TrdInstrmtLegGrp (body_50485451.html?find=LegReportID)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
