.TH FIX.5.0SP2 "" "" "Tag #991"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
991 (tag991.html)
RndPx (tag991.html)
\@RndPx
Price
.PP
Specifies average price rounded to quoted precision.
.PP
   *   *   *   *   *
Used in messages:
[AllocationInstruction (body_495774.html?find=RndPx)]
[AllocationInstructionAlert (body_57566677.html?find=RndPx)]
[AllocationReport (body_55566583.html?find=RndPx)]
[TradeCaptureReport (body_54526569.html?find=RndPx)]
[TradeCaptureReportAck (body_55556582.html?find=RndPx)]
.PP
   *   *   *   *   *
Used in components:

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
