.TH FIX.5.0SP2 "" "" "Tag #993"
Tag
Field Name
XML Name
Data Type
Description
Depr.
Valid values
993 (tag993.html)
AllocCustomerCapacity (tag993.html)
\@CustCpcty
String
.PP
Capacity of customer in the allocation block.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
Used in components:
[AllocAckGrp (body_50484850.html?find=AllocCustomerCapacity)]
[AllocGrp (body_50484851.html?find=AllocCustomerCapacity)]
[TrdAllocGrp (body_50485448.html?find=AllocCustomerCapacity)]

.PD 0
.P
.PD

.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
