.TH FIX.4.1 "" "" "Tag #117"
Tag
Field Name
Data Type
Description
Depr.
Valid values
117 (tag117.html)
QuoteID (tag117.html)
char
.PP
Unique identifier for quote
.PP
   *   *   *   *   *
Used in messages:
[Order - Single (body_495268.html?find=QuoteID)]
[Quote (body_505583.html?find=QuoteID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
