.TH FIX.4.1 "" "" "Tag #131"
Tag
Field Name
Data Type
Description
Depr.
Valid values
131 (tag131.html)
QuoteReqID (tag131.html)
char
.PP
Unique identifier for quote request
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=QuoteReqID)]
[Quote Request (body_505482.html?find=QuoteReqID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
