.TH FIX.4.1 "" "" "Tag #139"
Tag
Field Name
Data Type
Description
Depr.
Valid values
139 (tag139.html)
MiscFeeType (tag139.html)
char
.PP
Indicates type of miscellaneous fee.
1
=
.PP
Regulatory (e.g. SEC)
2
=
.PP
Tax
3
=
.PP
Local Commission
4
=
.PP
Exchange Fees
5
=
.PP
Stamp
6
=
.PP
Levy
7
=
.PP
Other
8
=
.PP
Markup
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=MiscFeeType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
