.TH FIX.4.1 "" "" "Tag #153"
Tag
Field Name
Data Type
Description
Depr.
Valid values
153 (tag153.html)
AllocAvgPx (tag153.html)
float
.PP
AvgPx for a specific AllocAccount
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AllocAvgPx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
