.TH FIX.4.1 "" "" "Tag #157"
Tag
Field Name
Data Type
Description
Depr.
Valid values
157 (tag157.html)
NumDaysInterest (tag157.html)
int
.PP
Number of Days of Interest for convertible bonds and fixed income
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=NumDaysInterest)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
