.TH FIX.4.1 "" "" "Tag #158"
Tag
Field Name
Data Type
Description
Depr.
Valid values
158 (tag158.html)
AccruedInterestRate (tag158.html)
float
.PP
Accrued Interest Rate for convertible bonds and fixed income
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AccruedInterestRate)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
