.TH FIX.4.1 "" "" "Tag #191"
Tag
Field Name
Data Type
Description
Depr.
Valid values
191 (tag191.html)
OfferForwardPoints (tag191.html)
float
.PP
Offer F/X forward points added to spot rate. May be a negative
value.
.PP
   *   *   *   *   *
Used in messages:
[Quote (body_505583.html?find=OfferForwardPoints)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
