.TH FIX.4.1 "" "" "Tag #2"
Tag
Field Name
Data Type
Description
Depr.
Valid values
2 (tag2.html)
AdvId (tag2.html)
char
.PP
Unique identifier of advertisement message.
.PP
(Prior to FIX 4.1 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=AdvId)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
