.TH FIX.4.1 "" "" "Tag #45"
Tag
Field Name
Data Type
Description
Depr.
Valid values
45 (tag45.html)
RefSeqNum (tag45.html)
int
.PP
Reference message sequence number
.PP
   *   *   *   *   *
Used in messages:
[Reject (body_5251.html?find=RefSeqNum)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
