.TH FIX.4.1 "" "" "Tag #48"
Tag
Field Name
Data Type
Description
Depr.
Valid values
48 (tag48.html)
SecurityID (tag48.html)
char
.PP
CUSIP or other alternate security identifier
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=SecurityID)]
[Allocation (body_495774.html?find=SecurityID)]
[Don’t Know Trade (DK) (body_505381.html?find=SecurityID)]
[Email (body_495167.html?find=SecurityID)]
[Execution Report (body_5756.html?find=SecurityID)]
[Indication of Interest (body_5554.html?find=SecurityID)]
[News (body_495066.html?find=SecurityID)]
[Order - List (body_495369.html?find=SecurityID)]
[Order - Single (body_495268.html?find=SecurityID)]
[Order Cancel Request (body_495470.html?find=SecurityID)]
[Order Cancel/Replace Request (body_495571.html?find=SecurityID)]
[Order Status Request (body_495672.html?find=SecurityID)]
[Quote (body_505583.html?find=SecurityID)]
[Quote Request (body_505482.html?find=SecurityID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
