.TH FIX.4.1 "" "" "Tag #57"
Tag
Field Name
Data Type
Description
Depr.
Valid values
57 (tag57.html)
TargetSubID (tag57.html)
char
.PP
Assigned value used to identify specific individual or unit
intended to receive message. “ADMIN” reserved for administrative
messages not intended for a specific user.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
