.TH FIX.4.1 "" "" "Tag #71"
Tag
Field Name
Data Type
Description
Depr.
Valid values
71 (tag71.html)
AllocTransType (tag71.html)
char
.PP
Identifies allocation transaction type
0
=
.PP
New
1
=
.PP
Replace
2
=
.PP
Cancel
3
=
.PP
Preliminary (without MiscFees and NetMoney)
4
=
.PP
Calculated (includes MiscFees and NetMoney)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AllocTransType)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
