.TH FIX.4.1 "" "" "Tag #110"
Tag
Field Name
Data Type
Description
Depr.
Valid values
110 (tag110.html)
MinQty (tag110.html)
int
.PP
Minimum quantity of an order to be executed.
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=MinQty)]
[Order - Single (body_495268.html?find=MinQty)]
[Order Cancel/Replace Request (body_495571.html?find=MinQty)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
