.TH FIX.4.1 "" "" "Tag #113"
Tag
Field Name
Data Type
Description
Depr.
Valid values
113 (tag113.html)
ReportToExch (tag113.html)
char
.PP
Identifies party of trade responsible for exchange reporting.
N
=
.PP
Indicates that party sending message will report trade
Y
=
.PP
Indicates that party receiving message must report trade
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=ReportToExch)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
