.TH FIX.4.1 "" "" "Tag #12"
Tag
Field Name
Data Type
Description
Depr.
Valid values
12 (tag12.html)
Commission (tag12.html)
float
.PP
Commission. Note if CommType is percentage, Commission of 5% should
be represented as .05.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=Commission)]
[Execution Report (body_5756.html?find=Commission)]
[Order - List (body_495369.html?find=Commission)]
[Order - Single (body_495268.html?find=Commission)]
[Order Cancel/Replace Request (body_495571.html?find=Commission)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
