.TH FIX.4.1 "" "" "Tag #125"
Tag
Field Name
Data Type
Description
Depr.
Valid values
125 (tag125.html)
CxlType(no longer used) (tag125.html)
char
.PP
No longer used. Included here for reference to prior versions.
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
