.TH FIX.4.1 "" "" "Tag #127"
Tag
Field Name
Data Type
Description
Depr.
Valid values
127 (tag127.html)
DKReason (tag127.html)
char
.PP
Reason for execution rejection.
A
=
.PP
Unknown symbol
B
=
.PP
Wrong side
C
=
.PP
Quantity exceeds order
D
=
.PP
No matching order
E
=
.PP
Price exceeds limit
Z
=
.PP
Other
.PP
   *   *   *   *   *
Used in messages:
[Don’t Know Trade (DK) (body_505381.html?find=DKReason)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
