.TH FIX.4.1 "" "" "Tag #142"
Tag
Field Name
Data Type
Description
Depr.
Valid values
142 (tag142.html)
SenderLocationID (tag142.html)
char
.PP
Assigned value used to identify specific message originator’s
location (i.e. geographic location and/or desk, trader)
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
