.TH FIX.4.1 "" "" "Tag #160"
Tag
Field Name
Data Type
Description
Depr.
Valid values
160 (tag160.html)
SettlInstMode (tag160.html)
char
.PP
Indicates mode used for Settlement Instructions
0
=
.PP
Default
1
=
.PP
Standing Instructions Provided
2
=
.PP
Specific Allocation Account Overriding
3
=
.PP
Specific Allocation Account Standing
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=SettlInstMode)]
[Settlement Instructions (body_505684.html?find=SettlInstMode)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
