.TH FIX.4.1 "" "" "Tag #164"
Tag
Field Name
Data Type
Description
Depr.
Valid values
164 (tag164.html)
EmailThreadID (tag164.html)
char
.PP
Unique identifier for an email thread (new and chain of replies)
.PP
   *   *   *   *   *
Used in messages:
[Email (body_495167.html?find=EmailThreadID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
