.TH FIX.4.1 "" "" "Tag #168"
Tag
Field Name
Data Type
Description
Depr.
Valid values
168 (tag168.html)
EffectiveTime (tag168.html)
time
.PP
Time the details within the message should take effect (always
expressed in GMT)
.PP
   *   *   *   *   *
Used in messages:
[Settlement Instructions (body_505684.html?find=EffectiveTime)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
