.TH FIX.4.1 "" "" "Tag #195"
Tag
Field Name
Data Type
Description
Depr.
Valid values
195 (tag195.html)
LastForwardPoints (tag195.html)
float
.PP
F/X forward points added to LastSpotRate. May be a negative value.
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=LastForwardPoints)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
