.TH FIX.4.1 "" "" "Tag #204"
Tag
Field Name
Data Type
Description
Depr.
Valid values
204 (tag204.html)
CustomerOrFirm (tag204.html)
int
.PP
Used for options when delivering the order to an execution
system/exchange to specify if the order is for a customer or the
firm placing the order itself.
0
=
.PP
Customer
1
=
.PP
Firm
.PP
   *   *   *   *   *
Used in messages:
[Order - List (body_495369.html?find=CustomerOrFirm)]
[Order - Single (body_495268.html?find=CustomerOrFirm)]
[Order Cancel/Replace Request (body_495571.html?find=CustomerOrFirm)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
