.TH FIX.4.1 "" "" "Tag #205"
Tag
Field Name
Data Type
Description
Depr.
Valid values
205 (tag205.html)
MaturityDay (tag205.html)
day-of-month
.PP
Day of month used in conjunction with MaturityMonthYear to specify
the maturity date for SecurityType=FUT or SecurityType=OPT.
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=MaturityDay)]
[Allocation (body_495774.html?find=MaturityDay)]
[Don’t Know Trade (DK) (body_505381.html?find=MaturityDay)]
[Email (body_495167.html?find=MaturityDay)]
[Execution Report (body_5756.html?find=MaturityDay)]
[Indication of Interest (body_5554.html?find=MaturityDay)]
[News (body_495066.html?find=MaturityDay)]
[Order - List (body_495369.html?find=MaturityDay)]
[Order - Single (body_495268.html?find=MaturityDay)]
[Order Cancel Request (body_495470.html?find=MaturityDay)]
[Order Cancel/Replace Request (body_495571.html?find=MaturityDay)]
[Order Status Request (body_495672.html?find=MaturityDay)]
[Quote (body_505583.html?find=MaturityDay)]
[Quote Request (body_505482.html?find=MaturityDay)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
