.TH FIX.4.1 "" "" "Tag #206"
Tag
Field Name
Data Type
Description
Depr.
Valid values
206 (tag206.html)
OptAttribute (tag206.html)
char
.PP
Can be used for SecurityType=OPT to identify a particular security.
0-9
=
.PP
single digit version number assigned by exchange following capital
adjustments (0=current, 1=prior, 2=prior to 1, etc).
L
=
.PP
Long (a.k.a. American)
S
=
.PP
Short (a.k.a. European)
.PP
   *   *   *   *   *
Used in messages:
[Advertisement (body_5655.html?find=OptAttribute)]
[Allocation (body_495774.html?find=OptAttribute)]
[Don’t Know Trade (DK) (body_505381.html?find=OptAttribute)]
[Email (body_495167.html?find=OptAttribute)]
[Execution Report (body_5756.html?find=OptAttribute)]
[Indication of Interest (body_5554.html?find=OptAttribute)]
[News (body_495066.html?find=OptAttribute)]
[Order - List (body_495369.html?find=OptAttribute)]
[Order - Single (body_495268.html?find=OptAttribute)]
[Order Cancel Request (body_495470.html?find=OptAttribute)]
[Order Cancel/Replace Request (body_495571.html?find=OptAttribute)]
[Order Status Request (body_495672.html?find=OptAttribute)]
[Quote (body_505583.html?find=OptAttribute)]
[Quote Request (body_505482.html?find=OptAttribute)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
