.TH FIX.4.1 "" "" "Tag #24"
Tag
Field Name
Data Type
Description
Depr.
Valid values
24 (tag24.html)
IOIOthSvc (tag24.html)
char
.PP
Indicates if, and on which other services, the indication has been
advertised. Each character represents an additional service (e.g.
if on Bridge and Autex, field = BA, if only on Autex, field = A)
A
=
.PP
Autex
B
=
.PP
Bridge
.PP
   *   *   *   *   *
Used in messages:
[Indication of Interest (body_5554.html?find=IOIOthSvc)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
