.TH FIX.4.1 "" "" "Tag #29"
Tag
Field Name
Data Type
Description
Depr.
Valid values
29 (tag29.html)
LastCapacity (tag29.html)
char
.PP
Broker capacity in order execution
1
=
.PP
Agent
2
=
.PP
Cross as agent
3
=
.PP
Cross as principal
4
=
.PP
Principal
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=LastCapacity)]
[Execution Report (body_5756.html?find=LastCapacity)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
