.TH FIX.4.1 "" "" "Tag #35"
Tag
Field Name
Data Type
Description
Depr.
Valid values
35 (tag35.html)
MsgType (tag35.html)
char
.PP
Defines message type. ALWAYS THIRD FIELD IN MESSAGE. (Always
unencrypted)
.PP
Note: A "U" as the first character in the MsgType field (i.e. U1,
U2, etc) indicates that the message format is privately defined
between the sender and receiver.
0
=
.PP
Heartbeat
1
=
.PP
Test Request
2
=
.PP
Resend Request
3
=
.PP
Reject
4
=
.PP
Sequence Reset
5
=
.PP
Logout
6
=
.PP
Indication of Interest
7
=
.PP
Advertisement
8
=
.PP
Execution Report
9
=
.PP
Order Cancel Reject
A
=
.PP
Logon
B
=
.PP
News
C
=
.PP
Email
D
=
.PP
Order - Single
E
=
.PP
Order - List
F
=
.PP
Order Cancel Request
G
=
.PP
Order Cancel/Replace Request
H
=
.PP
Order Status Request
J
=
.PP
Allocation
K
=
.PP
List Cancel Request
L
=
.PP
List Execute
M
=
.PP
List Status Request
N
=
.PP
List Status
P
=
.PP
Allocation ACK
Q
=
.PP
Dont Know Trade (DK)
R
=
.PP
Quote Request
S
=
.PP
Quote
T
=
.PP
Settlement Instructions
.PP
   *   *   *   *   *
Used in messages:
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
