.TH FIX.4.1 "" "" "Tag #7"
Tag
Field Name
Data Type
Description
Depr.
Valid values
7 (tag7.html)
BeginSeqNo (tag7.html)
int
.PP
Message sequence number of first record in range to be resent
.PP
   *   *   *   *   *
Used in messages:
[Resend Request (body_5150.html?find=BeginSeqNo)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
