.TH FIX.4.1 "" "" "Tag #70"
Tag
Field Name
Data Type
Description
Depr.
Valid values
70 (tag70.html)
AllocID (tag70.html)
char
.PP
Unique identifier for allocation record.
.PP
(Prior to FIX 4.1 this field was of type int)
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AllocID)]
[Allocation ACK (body_505280.html?find=AllocID)]
[Settlement Instructions (body_505684.html?find=AllocID)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
