.TH FIX.4.1 "" "" "Tag #74"
Tag
Field Name
Data Type
Description
Depr.
Valid values
74 (tag74.html)
AvgPrxPrecision (tag74.html)
int
.PP
Indicates number of decimal places to be used for average pricing.
Absence of this field indicates that default precision arranged by
the broker/institution is to be used.
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=AvgPrxPrecision)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
