.TH FIX.4.1 "" "" "Tag #77"
Tag
Field Name
Data Type
Description
Depr.
Valid values
77 (tag77.html)
OpenClose (tag77.html)
char
.PP
For options only.
C
=
.PP
Close
O
=
.PP
Open
.PP
   *   *   *   *   *
Used in messages:
[Allocation (body_495774.html?find=OpenClose)]
[Order - List (body_495369.html?find=OpenClose)]
[Order - Single (body_495268.html?find=OpenClose)]
[Order Cancel/Replace Request (body_495571.html?find=OpenClose)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
