.TH FIX.4.1 "" "" "Tag #99"
Tag
Field Name
Data Type
Description
Depr.
Valid values
99 (tag99.html)
StopPx (tag99.html)
float
.PP
Price per share
.PP
   *   *   *   *   *
Used in messages:
[Execution Report (body_5756.html?find=StopPx)]
[Order - List (body_495369.html?find=StopPx)]
[Order - Single (body_495268.html?find=StopPx)]
[Order Cancel/Replace Request (body_495571.html?find=StopPx)]
.PP
   *   *   *   *   *
.PP
.PP
.IP \[bu] 2
© 2007 FIX Protocol Limited
.IP \[bu] 2
Contact us (http://www.fixprotocol.org/contact.shtml)
.IP \[bu] 2
Copyright and Acceptable Use policy (http://www.fixprotocol.org/copyright.shtml)
.IP \[bu] 2
Privacy policy (http://www.fixprotocol.org/privacy.shtml)
